# Vestibular Schwannoma Data Processing Pipeline
- Inventory extracted imaging files and align accession identifiers with clinical timeline metadata.
- Organize imaging assets into patient- and timepoint-specific folders, copying source files to a normalized workspace.
- Select high-resolution reference scans, derive brain-extracted masks, and run ANTs-based registration across intra- and inter-timepoint studies.
- Generate coregistered outputs, propagate accompanying segmentations, and log failures for later inspection.

In [ ]:
from pathlib import Path
import pandas as pd
import os
# load the meta file that allows for exploration of each subfolder
# dest folder with month-stamped name
root_dir = Path("/standard/gam_ai_group/ExtractedData-08-13-2025")

# read batch CSVs and tag batch_id
dfs = [
    pd.read_csv(root_dir / f"VS_batch{i}" / "Original" / "original_meta.csv").assign(batch_id=i)
    for i in range(1, 6)
]
meta_df = pd.concat(dfs, ignore_index=True)

# concise cleaner: normalize backslashes and strip leading spaces per path segment
col = "Downloaded Original Series Path"
if col not in meta_df.columns:
    raise ValueError(f"Column '{col}' not found")

meta_df[col] = meta_df[col].apply(
    lambda v: v if pd.isna(v) else "/".join(part.lstrip() for part in str(v).replace("\\", "/").split("/"))
)
# save cleaned metadata
meta_df.to_csv("meta_df.csv", index=False)
from pathlib import Path
import pandas as pd

# --- your existing setup code above this remains the same ---

# Column we are cleaning
col = "Downloaded Original Series Path"
if col not in meta_df.columns:
    raise ValueError(f"Column '{col}' not found")

def clean_relpath(v, trim_both=False):
    """Normalize slashes and remove leading spaces for each segment.
    Set trim_both=True to remove both leading & trailing spaces per segment."""
    if pd.isna(v):
        return v
    s = str(v).replace("\\", "/")
    # Choose lstrip (leading only) or strip (both ends)
    strip_fn = (str.strip if trim_both else str.lstrip)
    parts = [strip_fn(seg) for seg in s.split("/") if seg != ""]
    return "/".join(parts)

# Clean the relative path column (leading spaces per level removed)
meta_df[col] = meta_df[col].map(lambda v: clean_relpath(v, trim_both=False))

# --- build abs_path from root_dir / VS_batch{batch_id} / Original / <cleaned relative path> ---
def _build_abs_path(row):
    v = row[col]
    if pd.isna(v) or not str(v).strip():
        return pd.NA
    # ensure treated as relative under "Original"
    rel = str(v).lstrip("/")  # guard against accidental leading slash
    p = root_dir / f"VS_batch{int(row['batch_id'])}" / rel
    return p.as_posix()

meta_df["abs_path"] = meta_df.apply(_build_abs_path, axis=1)

# (Optional) quick validation: no segment should start with a space
# bad_segments = (
#     meta_df[col].astype("string")
#     .str.split("/")
#     .explode()
#     .str.match(r"^\s")
# )
# print("Any segments still starting with a space? ->", bool(bad_segments.fillna(False).any()))

# Save
meta_df.to_csv("meta_df.csv", index=False)

In [2]:
#final.csv has the datapoints and the paths of the files
#[ ] needs image path, segmentation path, Patient_MRI_Days Tracker, segmentation column
#[ ] identify the nifti final of use in the segmentation and image

In [3]:
from pathlib import Path
import pandas as pd

meta_df = pd.read_csv('safe_final_cleaned.csv')

# Create abs_path with proper NaN/None handling
meta_df['abs_path'] = meta_df['Downloaded Original Series Path'].apply(
    lambda x: str(Path(x).resolve()) if pd.notna(x) and isinstance(x, str) else None
)

In [4]:
from pathlib import Path
import pandas as pd
import difflib
import os

def clean_path_components(path_str):
    """Remove leading/trailing spaces from each directory level AND clean path endings."""
    if pd.isna(path_str) or not isinstance(path_str, str):
        return None
    
    # First, strip trailing spaces and periods from the entire path string
    path_str = path_str.rstrip(' .\t')
    
    if not path_str:
        return None
    
    # Split the path into components
    path = Path(path_str)
    parts = list(path.parts)
    
    # Strip leading/trailing whitespace from each component
    cleaned_parts = [part.strip() for part in parts]
    
    # Also strip trailing periods from each component
    cleaned_parts = [part.rstrip('.') for part in cleaned_parts]
    
    # Remove any empty parts
    cleaned_parts = [p for p in cleaned_parts if p]
    
    if len(cleaned_parts) == 0:
        return None
    
    # Handle absolute vs relative paths
    if path.is_absolute():
        cleaned_path = Path(cleaned_parts[0]).joinpath(*cleaned_parts[1:])
    else:
        cleaned_path = Path(*cleaned_parts)
    
    return str(cleaned_path)

def attempt_path_recovery(bad_path_str, similarity_cutoff=0.6):
    """
    Tries to heal a broken path by traversing it from the root.
    If a component doesn't exist, it looks for the closest match in the current directory.
    """
    if not bad_path_str:
        return None

    original_path = Path(bad_path_str)
    parts = list(original_path.parts)
    
    # Start building the path from the first component (drive or root)
    current_path = Path(parts[0])
    
    # If the root itself doesn't exist (e.g. wrong drive letter), we can't do much
    if not current_path.exists():
        return None

    # Iterate through the rest of the components
    for i, part in enumerate(parts[1:], start=1):
        test_path = current_path / part
        
        if test_path.exists():
            # If it exists, keep going
            current_path = test_path
        else:
            # The path broke here. Look inside 'current_path' for a fuzzy match.
            try:
                # List all real items in the current directory
                candidates = [x.name for x in current_path.iterdir()]
                
                # specific check: sometimes case sensitivity is the only issue
                lower_map = {c.lower(): c for c in candidates}
                if part.lower() in lower_map:
                    best_match = lower_map[part.lower()]
                else:
                    # Use difflib to find closest string match
                    matches = difflib.get_close_matches(part, candidates, n=1, cutoff=similarity_cutoff)
                    best_match = matches[0] if matches else None
                
                if best_match:
                    # We found a fix! Update current path with the REAL name
                    current_path = current_path / best_match
                else:
                    # No match found, recovery failed
                    return None
            except (PermissionError, OSError):
                # Can't read directory, stop here
                return None

    return str(current_path)

def process_paths(df, path_col='abs_path', error_csv='errored_paths.csv'):
    """
    1. Checks existence.
    2. Tries to recover missing paths via fuzzy matching.
    3. Returns cleaned DF and final error DF.
    """
    if path_col not in df.columns:
        raise KeyError(f"Column '{path_col}' not found in DataFrame")
    
    # 1. Initial Check
    print("🔍 Performing initial existence check...")
    df['exists'] = df[path_col].apply(lambda p: Path(p).exists() if pd.notna(p) and p else False)
    
    valid_mask = df['exists']
    clean_df = df[valid_mask].copy()
    error_df = df[~valid_mask].copy()
    
    print(f"   Initial Pass: {len(clean_df)} valid, {len(error_df)} missing.")

    # 2. Recovery Phase
    if not error_df.empty:
        print("\n🚑 Attempting to recover broken paths (this may take a moment)...")
        
        # Define a wrapper to print progress or handle errors
        def recover_wrapper(p):
            if pd.isna(p): return None
            return attempt_path_recovery(p)

        # Apply recovery
        error_df['recovered_path'] = error_df[path_col].apply(recover_wrapper)
        
        # Check which ones were successfully recovered
        recovered_mask = error_df['recovered_path'].notna()
        recovered_df = error_df[recovered_mask].copy()
        
        # Update the main path column with the recovered version
        recovered_df[path_col] = recovered_df['recovered_path']
        
        # Drop helper columns
        clean_df = clean_df.drop(columns=['exists'])
        recovered_df = recovered_df.drop(columns=['exists', 'recovered_path'])
        
        # Add recovered rows back to clean_df
        clean_df = pd.concat([clean_df, recovered_df], ignore_index=True)
        
        # Update error_df to only include those that failed recovery
        final_error_df = error_df[~recovered_mask].drop(columns=['exists', 'recovered_path'])
        
        print(f"   ✅ Recovered {len(recovered_df)} paths via fuzzy matching!")
    else:
        final_error_df = pd.DataFrame(columns=df.columns)

    # Save final errors
    if not final_error_df.empty:
        final_error_df.to_csv(error_csv, index=False)
        print(f"⚠️  {len(final_error_df)} paths are unrecoverable - saved to '{error_csv}'")
    
    return clean_df, final_error_df

# --- Main Execution ---

# 1. Load Data
meta_df = pd.read_csv('safe_final_cleaned.csv')

# 2. Basic String Cleaning
print("🧹 Cleaning path strings...")
meta_df['abs_path'] = meta_df['Downloaded Original Series Path'].apply(clean_path_components)

# 3. Process (Check & Recover)
clean_meta_df, error_df = process_paths(meta_df)

# 4. Save
#clean_meta_df.to_csv('cleaned_valid_paths.csv', index=False)
print(f"\n💾 Saved {len(clean_meta_df)} rows with verified paths to 'cleaned_valid_paths.csv'")

# 5. Debugging Output
if not error_df.empty:
    print("\n🔍 Examples of unrecoverable paths:")
    for path in error_df['abs_path'].head(3):
        if pd.notna(path):
            print(f"  Failed: {path}")
            # Show deepest existing parent for debugging
            try:
                p = Path(path)
                while not p.exists() and len(p.parts) > 1:
                    p = p.parent
                print(f"    -> Deepest existing match: {p}")
            except:
                pass

🧹 Cleaning path strings...
🔍 Performing initial existence check...
   Initial Pass: 8560 valid, 23 missing.

🚑 Attempting to recover broken paths (this may take a moment)...
   ✅ Recovered 23 paths via fuzzy matching!

💾 Saved 8583 rows with verified paths to 'cleaned_valid_paths.csv'

In [5]:
from datetime import datetime

timestamp = datetime.now().strftime('%Y%m%d')
error_df.to_csv(f'missing_paths_{timestamp}.csv')
# Results in: missing_paths_20260117_143022.csv

In [6]:
# --- Load timeline metadata from the Carina spreadsheet and normalize identifiers ---
# Import the information from deidentified Carina to timeline from database
df_excel = pd.read_excel("VS AI Database, Draft 12.01 Jack Veda reconciled.xlsx")
# Keep only the fields needed to align folder structure with patient/timepoint info
df_time = df_excel[['Carina Accession Number', 'Patient_MRI_Days Tracker']].replace('.', None).dropna(subset=['Patient_MRI_Days Tracker'])
# Retain whitespace/full string for accession number to preserve join key
df_time['Carina Accession Number'] = df_time['Carina Accession Number']
# Split tracker strings into patient ID, scan order, and inter-scan spacing
df_time[['Patient_ID', 'Scan Order', 'Days between scans']] = df_time['Patient_MRI_Days Tracker'].str.split('_', expand=True)
# Ensure scans are in chronological order before merging back to filesystem inventory
df_time = df_time.sort_values(by=['Patient_ID', 'Scan Order'])

In [7]:
meta_db_df = pd.merge(
    df_time,
    clean_meta_df,
    left_on="Carina Accession Number",
    right_on="Accession Number",
    how="inner"
)

# Calculate number of unique patients matched
num_patients_matched = meta_db_df['Patient_ID'].nunique()
print(f"Number of unique patients matched: {num_patients_matched}")

# Find unmatched records from clean_meta_df
unmatched_df = clean_meta_df[
    ~clean_meta_df['Accession Number'].isin(meta_db_df['Accession Number'])
]

# Export unmatched to CSV
#unmatched_df.to_csv('unmatched.csv', index=False)
print(f"Number of unmatched records: {len(unmatched_df)}")
print(f"Unmatched records exported to 'unmatched.csv'")

Number of unique patients matched: 257
Number of unmatched records: 10
Unmatched records exported to 'unmatched.csv'

In [8]:
meta_db_df = meta_db_df.rename(columns={'Labels': 'Series Labels'})

In [9]:
#filter the patients to t2_thin and t1+_thin
print(meta_db_df['Series Labels'].value_counts())

#meta_db_df=meta_db_df[meta_db_df ['Series Labels'].isin(['t2_thin','t1+_thin'])]
meta_db_df=meta_db_df[meta_db_df ['Series Labels'].isin(['t2_thin','t1+_thin','t1+_thick_cor','t1+_thick_ax','t2_thick'])]
print('Filtered Data')
print(meta_db_df['Series Labels'].value_counts())

Series Labels
t2_thin          549
t1+_thick_cor    410
t1+_thick_ax     404
t1+_thin         292
t2_thick         155
t1_pre            67
flair             10
Name: count, dtype: int64
Filtered Data
Series Labels
t2_thin          549
t1+_thick_cor    410
t1+_thick_ax     404
t1+_thin         292
t2_thick         155
Name: count, dtype: int64

In [10]:
import pandas as pd
import os
import shutil
from pathlib import Path
import re
from tqdm import tqdm

def find_nifti_files(abs_path):
    """
    Find NIfTI files in the directory.
    Returns: (image_path, seg_path, multiple_segs_flag, all_seg_files)
    """
    if not os.path.exists(abs_path):
        return None, None, False, []
    
    # Get all .nii.gz files
    nii_files = [f for f in os.listdir(abs_path) if f.endswith('.nii.gz')]
    
    # Find image file (no 'uvauser' in name)
    image_files = [f for f in nii_files if 'uvauser' not in f.lower()]
    image_files = [f for f in nii_files if 'image' in f.lower()]
    image_path = os.path.join(abs_path, image_files[0]) if image_files else None
    
    # Find segmentation files (with 'uvauser' in name)
    seg_files = [f for f in nii_files if 'uvauser' in f.lower()]
    
    # Check for multiple segmentations
    multiple_segs = len(seg_files) > 1
    
    # Select segmentation: prefer one with 'copy' if multiple exist
    seg_path = None
    if seg_files:
        if multiple_segs:
            # Try to find one with 'copy' in the name
            copy_segs = [f for f in seg_files if 'copy' in f.lower()]
            seg_path = os.path.join(abs_path, copy_segs[0]) if copy_segs else os.path.join(abs_path, seg_files[0])
        else:
            seg_path = os.path.join(abs_path, seg_files[0])
    
    return image_path, seg_path, multiple_segs, seg_files

def copy_to_organized_folder(src_path, base_output_dir, series_label, patient_mri_days):
    """
    Copy file to organized folder structure with prefixed filename.
    Prefix format: Patient_MRI_Days_Tracker_SeriesLabels_original_filename
    Returns the new path
    """
    if not src_path or not os.path.exists(src_path):
        return None
    
    # Create destination directory
    dest_dir = os.path.join(base_output_dir, str(series_label), str(patient_mri_days))
    os.makedirs(dest_dir, exist_ok=True)
    
    # Get original filename
    original_filename = os.path.basename(src_path)
    
    # Create prefixed filename: Patient_MRI_Days_Tracker_SeriesLabels_original_filename
    prefixed_filename = f"{patient_mri_days}_{series_label}_{original_filename}"
    
    # Create destination path with prefixed filename
    dest_path = os.path.join(dest_dir, prefixed_filename)
    
    # Copy file
    shutil.copy2(src_path, dest_path)
    
    return dest_path

def process_meta_db(meta_db_df, base_output_dir):
    """
    Process the meta database dataframe to find and organize NIfTI files.
    
    Parameters:
    - meta_db_df: DataFrame with metadata
    - base_output_dir: Base directory for organized output
    
    Returns:
    - Updated DataFrame with new columns
    """
    # Create new columns
    meta_db_df['original_image_path'] = None
    meta_db_df['original_seg_path'] = None
    meta_db_df['multiple_segs_flag'] = False
    meta_db_df['all_seg_filenames'] = None  # New column for all seg filenames
    meta_db_df['modality_image_path'] = None
    meta_db_df['modality_seg_path'] = None
    
    # Track multiple segmentations
    multiple_seg_rows = []
    
    # Iterate through each row with progress bar
    for idx, row in tqdm(meta_db_df.iterrows(), total=len(meta_db_df), desc="Processing NIfTI files"):
        abs_path = row['abs_path']
        series_label = row['Series Labels']
        patient_mri_days = row['Patient_MRI_Days Tracker']
        
        # Find NIfTI files
        image_path, seg_path, multiple_segs, all_seg_files = find_nifti_files(abs_path)
        
        # Update original paths
        meta_db_df.at[idx, 'original_image_path'] = image_path
        meta_db_df.at[idx, 'original_seg_path'] = seg_path
        meta_db_df.at[idx, 'multiple_segs_flag'] = multiple_segs
        
        # Store all segmentation filenames as a list (only if there are multiple)
        if multiple_segs:
            meta_db_df.at[idx, 'all_seg_filenames'] = all_seg_files
        
        # Copy files to organized structure with prefixed filenames
        if image_path:
            new_image_path = copy_to_organized_folder(
                image_path, base_output_dir, series_label, patient_mri_days
            )
            meta_db_df.at[idx, 'modality_image_path'] = new_image_path
        
        if seg_path:
            new_seg_path = copy_to_organized_folder(
                seg_path, base_output_dir, series_label, patient_mri_days
            )
            meta_db_df.at[idx, 'modality_seg_path'] = new_seg_path
        
        if multiple_segs:
            multiple_seg_rows.append(idx)
    
    # Print summary of multiple segmentations
    if multiple_seg_rows:
        print(f"\n⚠️  Found {len(multiple_seg_rows)} rows with multiple segmentations:")
        print(f"   Row indices: {multiple_seg_rows}")
        print("\n   Details:")
        for idx in multiple_seg_rows:
            seg_list = meta_db_df.at[idx, 'all_seg_filenames']
            print(f"   Row {idx}: {len(seg_list)} segmentations - {seg_list}")
    
    return meta_db_df

# Usage in Jupyter Notebook:
# Uncomment and run the following lines after loading your dataframe

# Set base output directory
base_output_dir = './raw_studies'

# Process the dataframe
updated_meta_db_df = process_meta_db(meta_db_df, base_output_dir)

# Save the updated dataframe
#updated_meta_db_df.to_csv('updated_metadata.csv', index=False)

# Display results
updated_meta_db_df[['Patient_MRI_Days Tracker', 'Series Labels', 'original_image_path', 
                      'original_seg_path', 'multiple_segs_flag', 'all_seg_filenames',
                      'modality_image_path', 'modality_seg_path']].head()

Processing NIfTI files: 100%|██████████| 1810/1810 [09:10<00:00,  3.29it/s]

⚠️  Found 307 rows with multiple segmentations:
   Row indices: [82, 87, 116, 129, 141, 180, 182, 202, 207, 211, 233, 257, 283, 287, 318, 342, 358, 359, 374, 404, 424, 426, 429, 452, 461, 467, 478, 545, 551, 557, 605, 638, 652, 654, 656, 660, 673, 695, 706, 708, 814, 818, 819, 842, 865, 867, 870, 872, 899, 914, 934, 955, 1026, 1048, 1057, 1083, 1089, 1095, 1243, 1257, 1318, 1320, 1330, 1332, 1350, 1364, 1631, 1652, 1658, 1666, 1706, 1708, 1715, 1719, 1720, 1891, 1907, 1928, 1936, 1942, 2030, 2044, 2056, 2152, 2182, 2343, 2353, 2383, 2397, 2448, 2453, 2454, 2497, 2500, 2502, 2512, 2514, 2519, 2570, 2576, 2605, 2630, 2633, 2749, 2795, 2962, 2982, 3175, 3178, 3180, 3184, 3212, 3233, 3245, 3250, 3255, 3259, 3263, 3330, 3335, 3415, 3418, 3421, 3422, 3426, 3488, 3506, 3507, 3509, 3583, 3602, 3626, 3698, 3699, 3700, 3749, 3752, 3753, 3761, 3762, 3766, 3786, 3800, 3802, 3808, 3919, 3932, 3957, 3959, 3960, 3964, 3965, 3976, 4044, 4092, 4153, 4189, 4190, 4196, 4199, 4202, 4220, 4237, 4453, 4479, 4483, 4612, 4658, 4685, 4690, 4718, 4767, 4769, 4773, 4779, 4781, 4782, 4797, 4810, 4884, 4907, 4960, 4969, 4970, 4972, 4973, 4974, 4993, 5093, 5102, 5103, 5105, 5110, 5167, 5219, 5351, 5352, 5363, 5366, 5368, 5400, 5484, 5489, 5492, 5521, 5556, 5575, 5576, 5577, 5590, 5606, 5642, 5666, 5668, 5670, 5707, 5715, 5723, 5724, 5730, 5739, 5748, 5758, 5759, 5823, 5839, 5847, 5848, 5849, 5864, 5871, 5877, 5910, 5913, 5914, 5943, 5978, 5995, 6014, 6028, 6030, 6035, 6044, 6066, 6068, 6069, 6074, 6130, 6131, 6151, 6155, 6191, 6299, 6316, 6336, 6343, 6356, 6397, 6403, 6409, 6421, 6432, 6451, 6452, 6473, 6478, 6480, 6516, 6517, 6519, 6523, 6533, 6584, 6587, 6716, 6720, 6784, 6787, 6791, 6822, 7106, 7107, 7123, 7137, 7379, 7386, 7390, 7396, 7405, 7589, 7751, 7806, 7825, 7876, 8019, 8020, 8026, 8068, 8081, 8106, 8117, 8137, 8147, 8463, 8544, 8558, 8562]

   Details:
   Row 82: 2 segmentations - ['VS_uvauser1.nii.gz', 'VS_uvauser1-copy.nii.gz']
   Row 87: 2 segmentations - ['RVS _uvauser2-copy.nii.gz', 'RVS _uvauser2.nii.gz']
   Row 116: 2 segmentations - ['CO_tumorcore _uvauser3.nii.gz', 'AX_tumorcore _uvauser3.nii.gz']
   Row 129: 4 segmentations - ['AX_VS_uvauser1.nii.gz', 'AX_VS_uvauser1-copy.nii.gz', 'CO_VS_uvauser1.nii.gz', 'T2_VS_uvauser1.nii.gz']
   Row 141: 2 segmentations - ['tumorcore T2S _uvauser3.nii.gz', 'tumorcore T2S _uvauser3-copy.nii.gz']
   Row 180: 3 segmentations - ['AS1_uvauser4.nii.gz', '1_uvauser4.nii.gz', 'AS1_uvauser4-copy.nii.gz']
   Row 182: 2 segmentations - ['AS_uvauser4.nii.gz', 'AS_uvauser4-copy.nii.gz']
   Row 202: 2 segmentations - ['1_uvauser4-copy.nii.gz', '1_uvauser4.nii.gz']
   Row 207: 3 segmentations - ['AS1_uvauser4.nii.gz', '1_uvauser4.nii.gz', 'AS1_uvauser4-copy.nii.gz']
   Row 211: 2 segmentations - ['VS_uvauser1.nii.gz', 'VS_uvauser1-copy.nii.gz']
   Row 233: 2 segmentations - ['Tumorcore _uvauser3-copy.nii.gz', 'Tumorcore _uvauser3.nii.gz']
   Row 257: 3 segmentations - ['T2Final_VS_uvauser5.nii.gz', 'CO_VS_uvauser5.nii.gz', 'AX_VS_uvauser5.nii.gz']
   Row 283: 3 segmentations - ['LVS _uvauser2-copy.nii.gz', '1_uvauser4.nii.gz', 'LVS _uvauser2.nii.gz']
   Row 287: 2 segmentations - ['1_uvauser4.nii.gz', 'LVS _uvauser2.nii.gz']
   Row 318: 2 segmentations - ['LVS _uvauser2-copy.nii.gz', 'LVS _uvauser2.nii.gz']
   Row 342: 2 segmentations - ['RVS _uvauser2-copy.nii.gz', 'RVS _uvauser2.nii.gz']
   Row 358: 2 segmentations - ['VST1thin_uvauser6.nii.gz', 'RVS _uvauser2.nii.gz']
   Row 359: 2 segmentations - ['VST2thin_uvauser6.nii.gz', 'RVS _uvauser2.nii.gz']
   Row 374: 3 segmentations - ['AX_VS_uvauser1.nii.gz', 'CO_VS_uvauser1.nii.gz', 'T2_VS_uvauser1.nii.gz']
   Row 404: 2 segmentations - ['LVS _uvauser2-copy.nii.gz', 'LVS _uvauser2.nii.gz']
   Row 424: 2 segmentations - ['LVS _uvauser2-copy.nii.gz', 'LVS _uvauser2.nii.gz']
   Row 426: 2 segmentations - ['LVS _uvauser2-copy.nii.gz', 'LVS _uvauser2.nii.gz']
   Row 429: 2 segmentations - ['LVS _uvauser2-copy.nii.gz', 'LVS _uvauser2.nii.gz']
   Row 452: 2 segmentations - ['tumorcore _uvauser3.nii.gz', 'LVS _uvauser2.nii.gz']
   Row 461: 2 segmentations - ['manual_10_uvauser10.nii.gz', 'tumorcore _uvauser3.nii.gz']
   Row 467: 2 segmentations - ['CO_tumorcore _uvauser3.nii.gz', 'AX_tumorcore _uvauser3.nii.gz']
   Row 478: 3 segmentations - ['AX_VS_uvauser1.nii.gz', 'CO_VS_uvauser1.nii.gz', 'T2_VS_uvauser1.nii.gz']
   Row 545: 2 segmentations - ['VS_uvauser1.nii.gz', 'LVS _uvauser2.nii.gz']
   Row 551: 4 segmentations - ['AX_VS_uvauser1.nii.gz', 'CO_VS_uvauser1.nii.gz', 'T2_VS_uvauser1.nii.gz', 'LVS _uvauser2.nii.gz']
   Row 557: 4 segmentations - ['T2Final_VS_uvauser5.nii.gz', 'T2Final_VS_uvauser5-copy.nii.gz', 'CO_VS_uvauser5.nii.gz', 'AX_VS_uvauser5.nii.gz']
   Row 605: 2 segmentations - ['AS_uvauser4.nii.gz', 'VST1ax_uvauser6.nii.gz']
   Row 638: 2 segmentations - ['VS_uvauser1.nii.gz', 'VS_uvauser1-copy.nii.gz']
   Row 652: 2 segmentations - ['VS2_uvauser1.nii.gz', 'RVS _uvauser2.nii.gz']
   Row 654: 2 segmentations - ['VS2_uvauser1.nii.gz', 'RVS _uvauser2.nii.gz']
   Row 656: 2 segmentations - ['1_uvauser4.nii.gz', 'RVS _uvauser2.nii.gz']
   Row 660: 3 segmentations - ['T2Final_VS_uvauser5.nii.gz', 'CO_VS_uvauser5.nii.gz', 'AX_VS_uvauser5.nii.gz']
   Row 673: 3 segmentations - ['AX_VS_uvauser1.nii.gz', 'CO_VS_uvauser1.nii.gz', 'T2_VS_uvauser1.nii.gz']
   Row 695: 2 segmentations - ['CO_VS_uvauser5.nii.gz', 'AX_VS_uvauser5.nii.gz']
   Row 706: 2 segmentations - ['VS_uvauser1.nii.gz', 'LVS _uvauser2.nii.gz']
   Row 708: 2 segmentations - ['VS_uvauser1.nii.gz', 'LVS _uvauser2.nii.gz']
   Row 814: 2 segmentations - ['AS_uvauser4.nii.gz', 'LVS _uvauser2.nii.gz']
   Row 818: 2 segmentations - ['AS_uvauser4.nii.gz', 'LVS _uvauser2.nii.gz']
   Row 819: 2 segmentations - ['AS_uvauser4.nii.gz', 'LVS _uvauser2.nii.gz']
   Row 842: 3 segmentations - ['T2Final_VS_uvauser5.nii.gz', 'CO_VS_uvauser5.nii.gz', 'AX_VS_uvauser5.nii.gz']
   Row 865: 4 segmentations - ['T2_VS_uvauser1-copy.nii.gz', 'AX_VS_uvauser1.nii.gz', 'CO_VS_uvauser1.nii.gz', 'T2_VS_uvauser1.nii.gz']
   Row 867: 6 segmentations - ['AX_VS_uvauser1.nii.gz', 'CO_AS_uvauser4.nii.gz', 'AS_uvauser4.nii.gz', 'CO_VS_uvauser1.nii.gz', 'AX_AS_uvauser4.nii.gz', 'T2_VS_uvauser1.nii.gz']
   Row 870: 2 segmentations - ['AS_uvauser4.nii.gz', 'VS_uvauser1.nii.gz']
   Row 872: 2 segmentations - ['AS_uvauser4.nii.gz', 'VS_uvauser1.nii.gz']
   Row 899: 2 segmentations - ['2_uvauser4-copy.nii.gz', '2_uvauser4.nii.gz']
   Row 914: 3 segmentations - ['AX_Tumorcore _uvauser3.nii.gz', 'CO_tumorcore _uvauser3.nii.gz', 'Tumorcore _uvauser3.nii.gz']
   Row 934: 2 segmentations - ['tumorcore _uvauser3-copy.nii.gz', 'tumorcore _uvauser3.nii.gz']
   Row 955: 2 segmentations - ['1_uvauser4-copy.nii.gz', '1_uvauser4.nii.gz']
   Row 1026: 2 segmentations - ['LVS _uvauser2-copy.nii.gz', 'LVS _uvauser2.nii.gz']
   Row 1048: 3 segmentations - ['T2Final_VS_uvauser5.nii.gz', 'CO_VS_uvauser5.nii.gz', 'AX_VS_uvauser5.nii.gz']
   Row 1057: 3 segmentations - ['T2Final_VS_uvauser5.nii.gz', 'CO_VS_uvauser5.nii.gz', 'AX_VS_uvauser5.nii.gz']
   Row 1083: 3 segmentations - ['T2Final_VS_uvauser5.nii.gz', 'CO_VS_uvauser5.nii.gz', 'AX_VS_uvauser5.nii.gz']
   Row 1089: 3 segmentations - ['AX_VS_uvauser1.nii.gz', 'CO_VS_uvauser1.nii.gz', 'T2_VS_uvauser1.nii.gz']
   Row 1095: 2 segmentations - ['AS_uvauser4.nii.gz', 'Tumorcore _uvauser3.nii.gz']
   Row 1243: 2 segmentations - ['VS_uvauser1.nii.gz', 'VS_uvauser1-copy.nii.gz']
   Row 1257: 3 segmentations - ['AX_Tumorcore _uvauser3.nii.gz', 'CO_Tumorcore _uvauser3.nii.gz', 'Tumorcore _uvauser3.nii.gz']
   Row 1318: 2 segmentations - ['RVS _uvauser2.nii.gz', 'VST1ax_uvauser6.nii.gz']
   Row 1320: 2 segmentations - ['RVS _uvauser2.nii.gz', 'VST2_uvauser6.nii.gz']
   Row 1330: 2 segmentations - ['VST1cor_uvauser6.nii.gz', 'RVS _uvauser2.nii.gz']
   Row 1332: 2 segmentations - ['VS_uvauser5.nii.gz', 'tumorcore _uvauser3.nii.gz']
   Row 1350: 2 segmentations - ['AS_uvauser4.nii.gz', 'T2Final_VS_uvauser5.nii.gz']
   Row 1364: 2 segmentations - ['T2Final_VS_uvauser5.nii.gz', 'AX_VS_uvauser5.nii.gz']
   Row 1631: 2 segmentations - ['VST2_uvauser6-copy.nii.gz', 'VST2_uvauser6.nii.gz']
   Row 1652: 3 segmentations - ['T2Final_VS_uvauser5.nii.gz', 'CO_VS_uvauser5.nii.gz', 'AX_VS_uvauser5.nii.gz']
   Row 1658: 2 segmentations - ['tumorcore _uvauser3.nii.gz', 'VST1ax_uvauser6.nii.gz']
   Row 1666: 3 segmentations - ['AX_VS_uvauser1.nii.gz', 'CO_VS_uvauser1.nii.gz', 'T2_VS_uvauser1.nii.gz']
   Row 1706: 3 segmentations - ['AX_VS_uvauser1.nii.gz', 'CO_VS_uvauser1.nii.gz', 'T2_VS_uvauser1.nii.gz']
   Row 1708: 2 segmentations - ['AS_uvauser4.nii.gz', 'tumorcore _uvauser3.nii.gz']
   Row 1715: 3 segmentations - ['AS_uvauser4.nii.gz', 'AS_uvauser4-copy.nii.gz', 'tumorcore _uvauser3.nii.gz']
   Row 1719: 2 segmentations - ['VST1ax_uvauser6.nii.gz', 'LVS _uvauser2.nii.gz']
   Row 1720: 2 segmentations - ['VST1cor_uvauser6.nii.gz', 'LVS _uvauser2.nii.gz']
   Row 1891: 2 segmentations - ['RVS _uvauser2-copy.nii.gz', 'RVS _uvauser2.nii.gz']
   Row 1907: 2 segmentations - ['RVS _uvauser2-copy.nii.gz', 'RVS _uvauser2.nii.gz']
   Row 1928: 2 segmentations - ['AS_uvauser4.nii.gz', 'RVS _uvauser2.nii.gz']
   Row 1936: 2 segmentations - ['AS1_uvauser4.nii.gz', 'RVS _uvauser2.nii.gz']
   Row 1942: 2 segmentations - ['AS_uvauser4.nii.gz', 'RVS _uvauser2.nii.gz']
   Row 2030: 2 segmentations - ['VST2_uvauser6-copy.nii.gz', 'VST2_uvauser6.nii.gz']
   Row 2044: 2 segmentations - ['RVS _uvauser2-copy.nii.gz', 'RVS _uvauser2.nii.gz']
   Row 2056: 2 segmentations - ['RVS _uvauser2-copy.nii.gz', 'RVS _uvauser2.nii.gz']
   Row 2152: 2 segmentations - ['tumorcore _uvauser3-copy.nii.gz', 'tumorcore _uvauser3.nii.gz']
   Row 2182: 3 segmentations - ['AX_Tumorcore _uvauser3.nii.gz', 'CO_Tumorcore _uvauser3.nii.gz', 'Tumorcore _uvauser3.nii.gz']
   Row 2343: 4 segmentations - ['AX_VS_uvauser1.nii.gz', 'T2Final_VS_uvauser5.nii.gz', 'CO_VS_uvauser1.nii.gz', 'T2_VS_uvauser1.nii.gz']
   Row 2353: 5 segmentations - ['AX_VS_uvauser1.nii.gz', 'T2Final_VS_uvauser5.nii.gz', 'CO_VS_uvauser1.nii.gz', 'T2Final_VS_uvauser5-copy.nii.gz', 'T2_VS_uvauser1.nii.gz']
   Row 2383: 3 segmentations - ['AX_Tumorcore _uvauser3.nii.gz', 'CO_Tumorcore _uvauser3.nii.gz', 'Tumorcore _uvauser3.nii.gz']
   Row 2397: 3 segmentations - ['AX_Tumorcore _uvauser3.nii.gz', 'CO_Tumorcore _uvauser3.nii.gz', 'Tumorcore _uvauser3.nii.gz']
   Row 2448: 2 segmentations - ['AS_uvauser4.nii.gz', 'VS_uvauser5.nii.gz']
   Row 2453: 6 segmentations - ['CO_AS_uvauser4.nii.gz', 'AS_uvauser4.nii.gz', 'T2Final_VS_uvauser5.nii.gz', 'CO_VS_uvauser5.nii.gz', 'AX_AS_uvauser4.nii.gz', 'AX_VS_uvauser5.nii.gz']
   Row 2454: 2 segmentations - ['AS_uvauser4.nii.gz', 'VS_uvauser5.nii.gz']
   Row 2497: 2 segmentations - ['VS_uvauser1.nii.gz', 'LVS _uvauser2.nii.gz']
   Row 2500: 2 segmentations - ['VS_uvauser1.nii.gz', 'LVS _uvauser2.nii.gz']
   Row 2502: 4 segmentations - ['AX_VS_uvauser1.nii.gz', 'CO_VS_uvauser1.nii.gz', 'T2_VS_uvauser1.nii.gz', 'LVS _uvauser2.nii.gz']
   Row 2512: 4 segmentations - ['T2Final_VS_uvauser5.nii.gz', 'CO_VS_uvauser5.nii.gz', 'AX_VS_uvauser5.nii.gz', 'LVS _uvauser2.nii.gz']
   Row 2514: 2 segmentations - ['VS_uvauser5.nii.gz', 'LVS _uvauser2.nii.gz']
   Row 2519: 2 segmentations - ['VS_uvauser5.nii.gz', 'LVS _uvauser2.nii.gz']
   Row 2570: 3 segmentations - ['AX_Tumorcore _uvauser3.nii.gz', 'CO_Tumorcore _uvauser3.nii.gz', 'Tumorcore _uvauser3.nii.gz']
   Row 2576: 2 segmentations - ['1_uvauser4-copy.nii.gz', '1_uvauser4.nii.gz']
   Row 2605: 2 segmentations - ['VST2_uvauser6-copy.nii.gz', 'VST2_uvauser6.nii.gz']
   Row 2630: 3 segmentations - ['T2Final_VS_uvauser5.nii.gz', 'CO_VS_uvauser5.nii.gz', 'AX_VS_uvauser5.nii.gz']
   Row 2633: 3 segmentations - ['T2_VS_uvauser1.nii.gz', 'CO_CO_VS_uvauser1.nii.gz', 'AX_AX_VS_uvauser1.nii.gz']
   Row 2749: 2 segmentations - ['AX_tumorcore _uvauser3.nii.gz', 'AX_tumorcore _uvauser3-copy.nii.gz']
   Row 2795: 2 segmentations - ['manual_uvauser12_uvauser12.nii.gz', 'user9-uva-seg-T1post-left_uvauser9.nii.gz']
   Row 2962: 2 segmentations - ['AS_uvauser4.nii.gz', 'AS_uvauser4-copy.nii.gz']
   Row 2982: 2 segmentations - ['AS_uvauser4.nii.gz', 'VST1_uvauser6.nii.gz']
   Row 3175: 2 segmentations - ['VST1cor_uvauser6.nii.gz', 'RVS _uvauser2.nii.gz']
   Row 3178: 2 segmentations - ['RVS _uvauser2.nii.gz', 'VST2_uvauser6.nii.gz']
   Row 3180: 2 segmentations - ['manual_0_uvauser1.nii.gz', 'manual_0_uvauser13.nii.gz']
   Row 3184: 2 segmentations - ['manual_0_uvauser1.nii.gz', 'manual_0_uvauser13.nii.gz']
   Row 3212: 2 segmentations - ['tumorcore _uvauser3-copy.nii.gz', 'tumorcore _uvauser3.nii.gz']
   Row 3233: 2 segmentations - ['VST2_uvauser6-copy.nii.gz', 'VST2_uvauser6.nii.gz']
   Row 3245: 2 segmentations - ['tumorcore _uvauser3.nii.gz', 'RVS _uvauser2.nii.gz']
   Row 3250: 4 segmentations - ['RVS _uvauser2-copy.nii.gz', 'tumorcore _uvauser3.nii.gz', 'RVS _uvauser2.nii.gz', 'AX_tumorcore _uvauser3.nii.gz']
   Row 3255: 2 segmentations - ['tumorcore _uvauser3.nii.gz', 'manual_0_uvauser1.nii.gz']
   Row 3259: 2 segmentations - ['tumorcore _uvauser3.nii.gz', 'AX_tumorcore _uvauser3.nii.gz']
   Row 3263: 2 segmentations - ['RVS _uvauser2-copy.nii.gz', 'RVS _uvauser2.nii.gz']
   Row 3330: 3 segmentations - ['AX_VS_uvauser1.nii.gz', 'CO_VS_uvauser1.nii.gz', 'T2_VS_uvauser1.nii.gz']
   Row 3335: 2 segmentations - ['AS_uvauser4.nii.gz', 'tumorcore _uvauser3.nii.gz']
   Row 3415: 2 segmentations - ['AX_VS_uvauser1.nii.gz', 'VS_uvauser1.nii.gz']
   Row 3418: 2 segmentations - ['Manual_0_uvauser11.nii.gz', 'VS_uvauser1.nii.gz']
   Row 3421: 3 segmentations - ['AS_uvauser4.nii.gz', 'tumorcore _uvauser3.nii.gz', 'RVS _uvauser2.nii.gz']
   Row 3422: 2 segmentations - ['AS_uvauser4.nii.gz', 'RVS _uvauser2.nii.gz']
   Row 3426: 3 segmentations - ['AS_uvauser4.nii.gz', 'tumorcore _uvauser3.nii.gz', 'RVS _uvauser2.nii.gz']
   Row 3488: 2 segmentations - ['VS_uvauser1.nii.gz', 'VS_uvauser1-copy.nii.gz']
   Row 3506: 4 segmentations - ['AX_VS_uvauser1.nii.gz', 'CO_VS_uvauser1.nii.gz', 'T2_VS_uvauser1.nii.gz', 'VST2_uvauser6.nii.gz']
   Row 3507: 2 segmentations - ['VS_uvauser1.nii.gz', 'VST1AX_uvauser6.nii.gz']
   Row 3509: 2 segmentations - ['VST1COR_uvauser6.nii.gz', 'VS_uvauser1.nii.gz']
   Row 3583: 2 segmentations - ['T2Final_VS_uvauser5.nii.gz', 'RVS _uvauser2.nii.gz']
   Row 3602: 3 segmentations - ['T2Final_VS_uvauser5.nii.gz', 'CO_VS_uvauser5.nii.gz', 'AX_VS_uvauser5.nii.gz']
   Row 3626: 2 segmentations - ['VST2_uvauser6-copy.nii.gz', 'VST2_uvauser6.nii.gz']
   Row 3698: 2 segmentations - ['RVS _uvauser2.nii.gz', 'VST1AX_uvauser6.nii.gz']
   Row 3699: 2 segmentations - ['VST1COR_uvauser6.nii.gz', 'RVS _uvauser2.nii.gz']
   Row 3700: 2 segmentations - ['RVS _uvauser2.nii.gz', 'VST2_uvauser6.nii.gz']
   Row 3749: 2 segmentations - ['VS_uvauser1.nii.gz', 'VS_uvauser1-copy.nii.gz']
   Row 3752: 2 segmentations - ['VS_uvauser1.nii.gz', 'VS_uvauser1-copy.nii.gz']
   Row 3753: 4 segmentations - ['AX_VS_uvauser1.nii.gz', 'T2Final_VS_uvauser5.nii.gz', 'CO_VS_uvauser1.nii.gz', 'T2_VS_uvauser1.nii.gz']
   Row 3761: 2 segmentations - ['AS_uvauser4.nii.gz', 'VS_uvauser1.nii.gz']
   Row 3762: 2 segmentations - ['AS_uvauser4.nii.gz', 'VS_uvauser1.nii.gz']
   Row 3766: 6 segmentations - ['AX_VS_uvauser1.nii.gz', 'CO_AS_uvauser4.nii.gz', 'AS_uvauser4.nii.gz', 'CO_VS_uvauser1.nii.gz', 'AX_AS_uvauser4.nii.gz', 'T2_VS_uvauser1.nii.gz']
   Row 3786: 2 segmentations - ['manual_0_uvauser8.nii.gz', 'manual_0_uvauser13.nii.gz']
   Row 3800: 3 segmentations - ['AX_VS_uvauser1.nii.gz', 'CO_VS_uvauser1.nii.gz', 'T2_VS_uvauser1.nii.gz']
   Row 3802: 2 segmentations - ['AX_tumorcore _uvauser3.nii.gz', 'VST2_uvauser6.nii.gz']
   Row 3808: 2 segmentations - ['tumorcore _uvauser3.nii.gz', 'VST1AX_uvauser6.nii.gz']
   Row 3919: 2 segmentations - ['AS2_uvauser4-copy.nii.gz', 'AS2_uvauser4.nii.gz']
   Row 3932: 2 segmentations - ['AS2_uvauser4-copy.nii.gz', 'AS2_uvauser4.nii.gz']
   Row 3957: 3 segmentations - ['AS_uvauser4.nii.gz', 'AS_uvauser4-copy.nii.gz', 'tumorcore _uvauser3.nii.gz']
   Row 3959: 2 segmentations - ['AS_uvauser4.nii.gz', 'tumorcore _uvauser3.nii.gz']
   Row 3960: 2 segmentations - ['AS_uvauser4.nii.gz', 'tumorcore _uvauser3.nii.gz']
   Row 3964: 2 segmentations - ['AS_uvauser4.nii.gz', 'tumorcore _uvauser3.nii.gz']
   Row 3965: 2 segmentations - ['AS_uvauser4.nii.gz', 'tumorcore _uvauser3.nii.gz']
   Row 3976: 3 segmentations - ['T2Final_VS_uvauser5.nii.gz', 'CO_VS_uvauser5.nii.gz', 'AX_VS_uvauser5.nii.gz']
   Row 4044: 2 segmentations - ['LVS _uvauser2-copy.nii.gz', 'LVS _uvauser2.nii.gz']
   Row 4092: 3 segmentations - ['tumorcore _uvauser3.nii.gz', 'VS_uvauser1.nii.gz', 'RVS _uvauser2.nii.gz']
   Row 4153: 2 segmentations - ['VS_uvauser1.nii.gz', 'VS_uvauser1-copy.nii.gz']
   Row 4189: 2 segmentations - ['AS1_uvauser4.nii.gz', 'VS_uvauser1.nii.gz']
   Row 4190: 2 segmentations - ['VS1_uvauser1.nii.gz', 'AS2_uvauser4.nii.gz']
   Row 4196: 3 segmentations - ['AS_uvauser4.nii.gz', 'VS_uvauser5.nii.gz', 'VS_uvauser1.nii.gz']
   Row 4199: 3 segmentations - ['AS_uvauser4.nii.gz', 'VS_uvauser5.nii.gz', 'VS_uvauser1.nii.gz']
   Row 4202: 9 segmentations - ['AX_VS_uvauser1.nii.gz', 'CO_AS_uvauser4.nii.gz', 'AS_uvauser4.nii.gz', 'T2Final_VS_uvauser5.nii.gz', 'CO_VS_uvauser1.nii.gz', 'CO_VS_uvauser5.nii.gz', 'AX_AS_uvauser4.nii.gz', 'T2_VS_uvauser1.nii.gz', 'AX_VS_uvauser5.nii.gz']
   Row 4220: 3 segmentations - ['T2Final_VS_uvauser5.nii.gz', 'CO_VS_uvauser5.nii.gz', 'AX_VS_uvauser5.nii.gz']
   Row 4237: 2 segmentations - ['manual_0_uvauser8.nii.gz', 'manual_0_uvauser8-copy.nii.gz']
   Row 4453: 3 segmentations - ['AS_uvauser4.nii.gz', 'VST1_uvauser6.nii.gz', 'VS_uvauser1.nii.gz']
   Row 4479: 2 segmentations - ['AS_uvauser4.nii.gz', 'RVS _uvauser2.nii.gz']
   Row 4483: 2 segmentations - ['RVS _uvauser2-copy.nii.gz', 'RVS _uvauser2.nii.gz']
   Row 4612: 2 segmentations - ['tumorcore _uvauser3-copy.nii.gz', 'tumorcore _uvauser3.nii.gz']
   Row 4658: 2 segmentations - ['tumorcore _uvauser3.nii.gz', 'LVS _uvauser2.nii.gz']
   Row 4685: 2 segmentations - ['AS_uvauser4.nii.gz', 'VS_uvauser5.nii.gz']
   Row 4690: 2 segmentations - ['AS_uvauser4.nii.gz', 'VS_uvauser5.nii.gz']
   Row 4718: 2 segmentations - ['CO_tumorcore _uvauser3.nii.gz', 'AX_tumorcore _uvauser3.nii.gz']
   Row 4767: 2 segmentations - ['AS_uvauser4.nii.gz', 'VS_uvauser1.nii.gz']
   Row 4769: 2 segmentations - ['AS_uvauser4.nii.gz', 'VS_uvauser1.nii.gz']
   Row 4773: 6 segmentations - ['AX_VS_uvauser1.nii.gz', 'CO_AS_uvauser4.nii.gz', 'AS_uvauser4.nii.gz', 'CO_VS_uvauser1.nii.gz', 'VS_T2_uvauser1.nii.gz', 'AX_AS_uvauser4.nii.gz']
   Row 4779: 2 segmentations - ['T1COR_uvauser6.nii.gz', 'VS_uvauser1.nii.gz']
   Row 4781: 2 segmentations - ['T1AX_uvauser6.nii.gz', 'VS_uvauser1.nii.gz']
   Row 4782: 4 segmentations - ['AX_VS_uvauser1.nii.gz', 'T2CISS_uvauser6.nii.gz', 'CO_VS_uvauser1.nii.gz', 'VS_T2_uvauser1.nii.gz']
   Row 4797: 3 segmentations - ['manual_10_uvauser10.nii.gz', 'T2Final_VS_uvauser5.nii.gz', 'CO_VS_uvauser5.nii.gz']
   Row 4810: 2 segmentations - ['T1_uvauser6.nii.gz', 'AS_uvauser4.nii.gz']
   Row 4884: 2 segmentations - ['RVS _uvauser2-copy.nii.gz', 'RVS _uvauser2.nii.gz']
   Row 4907: 2 segmentations - ['RVS _uvauser2-copy.nii.gz', 'RVS _uvauser2.nii.gz']
   Row 4960: 2 segmentations - ['RVS _uvauser2-copy.nii.gz', 'RVS _uvauser2.nii.gz']
   Row 4969: 2 segmentations - ['AS_uvauser4.nii.gz', 'RVS _uvauser2.nii.gz']
   Row 4970: 2 segmentations - ['AS_uvauser4.nii.gz', 'RVS _uvauser2.nii.gz']
   Row 4972: 2 segmentations - ['AS_uvauser4.nii.gz', 'RVS _uvauser2.nii.gz']
   Row 4973: 2 segmentations - ['manual_10_uvauser10.nii.gz', 'tumorcore _uvauser3.nii.gz']
   Row 4974: 2 segmentations - ['CO_tumorcore _uvauser3.nii.gz', 'AX_tumorcore _uvauser3.nii.gz']
   Row 4993: 2 segmentations - ['T1Final_VS_uvauser5.nii.gz', 'VS_uvauser1.nii.gz']
   Row 5093: 2 segmentations - ['CO_tumorcore _uvauser3.nii.gz', 'AX_tumorcore _uvauser3.nii.gz']

,Patient_MRI_Days Tracker,Series Labels,original_image_path,original_seg_path,multiple_segs_flag,all_seg_filenames,modality_image_path,modality_seg_path
39,116_1_290,t2_thick,Original/VS_batch4_0183 VS_batch4_0183/MRI BRA...,None,False,None,./raw_studies/t2_thick/116_1_290/116_1_290_t2_...,None
63,126_0_0,t2_thick,Original/VS_batch2_0001 VS_batch2_0001/MR NO R...,Original/VS_batch2_0001 VS_batch2_0001/MR NO R...,False,None,./raw_studies/t2_thick/126_0_0/126_0_0_t2_thic...,./raw_studies/t2_thick/126_0_0/126_0_0_t2_thic...
66,126_0_0,t1+_thick_cor,Original/VS_batch2_0001 VS_batch2_0001/MR NO R...,Original/VS_batch2_0001 VS_batch2_0001/MR NO R...,False,None,./raw_studies/t1+_thick_cor/126_0_0/126_0_0_t1...,./raw_studies/t1+_thick_cor/126_0_0/126_0_0_t1...
70,126_0_0,t1+_thick_ax,Original/VS_batch2_0001 VS_batch2_0001/MR NO R...,Original/VS_batch2_0001 VS_batch2_0001/MR NO R...,False,None,./raw_studies/t1+_thick_ax/126_0_0/126_0_0_t1+...,./raw_studies/t1+_thick_ax/126_0_0/126_0_0_t1+...
77,126_1_312,t1+_thick_ax,Original/VS_batch1_0001 VS_batch1_0001/MRI TEM...,Original/VS_batch1_0001 VS_batch1_0001/MRI TEM...,False,None,./raw_studies/t1+_thick_ax/126_1_312/126_1_312...,./raw_studies/t1+_thick_ax/126_1_312/126_1_312...

In [11]:
updated_meta_db_df

,Carina Accession Number,Patient_MRI_Days Tracker,Patient_ID,Scan Order,Days between scans,Patient ID,Patient Name,Patient Birth Date,Study Date,Accession Number,...,Series Labels,Notes,Study_Labels,abs_path,original_image_path,original_seg_path,multiple_segs_flag,all_seg_filenames,modality_image_path,modality_seg_path
39,VS_batch4_0183_002,116_1_290,116,1,290,VS_batch4_0183,VS_batch4_0183,11/23/1949,11/19/2017,VS_batch4_0183_002,...,t2_thick,NaN,non_contrast,Original/VS_batch4_0183 VS_batch4_0183/MRI BRA...,Original/VS_batch4_0183 VS_batch4_0183/MRI BRA...,None,False,None,./raw_studies/t2_thick/116_1_290/116_1_290_t2_...,None
63,VS_batch2_0001_001,126_0_0,126,0,0,VS_batch2_0001,VS_batch2_0001,5/19/1976,10/12/2001,VS_batch2_0001_001,...,t2_thick,NaN,qc1,Original/VS_batch2_0001 VS_batch2_0001/MR NO R...,Original/VS_batch2_0001 VS_batch2_0001/MR NO R...,Original/VS_batch2_0001 VS_batch2_0001/MR NO R...,False,None,./raw_studies/t2_thick/126_0_0/126_0_0_t2_thic...,./raw_studies/t2_thick/126_0_0/126_0_0_t2_thic...
66,VS_batch2_0001_001,126_0_0,126,0,0,VS_batch2_0001,VS_batch2_0001,5/19/1976,10/12/2001,VS_batch2_0001_001,...,t1+_thick_cor,NaN,qc1,Original/VS_batch2_0001 VS_batch2_0001/MR NO R...,Original/VS_batch2_0001 VS_batch2_0001/MR NO R...,Original/VS_batch2_0001 VS_batch2_0001/MR NO R...,False,None,./raw_studies/t1+_thick_cor/126_0_0/126_0_0_t1...,./raw_studies/t1+_thick_cor/126_0_0/126_0_0_t1...
70,VS_batch2_0001_001,126_0_0,126,0,0,VS_batch2_0001,VS_batch2_0001,5/19/1976,10/12/2001,VS_batch2_0001_001,...,t1+_thick_ax,NaN,qc1,Original/VS_batch2_0001 VS_batch2_0001/MR NO R...,Original/VS_batch2_0001 VS_batch2_0001/MR NO R...,Original/VS_batch2_0001 VS_batch2_0001/MR NO R...,False,None,./raw_studies/t1+_thick_ax/126_0_0/126_0_0_t1+...,./raw_studies/t1+_thick_ax/126_0_0/126_0_0_t1+...
77,VS_batch1_0001_001,126_1_312,126,1,312,VS_batch1_0001,VS_batch1_0001,4/14/1983,7/15/2009,VS_batch1_0001_001,...,t1+_thick_ax,NaN,qc1,Original/VS_batch1_0001 VS_batch1_0001/MRI TEM...,Original/VS_batch1_0001 VS_batch1_0001/MRI TEM...,Original/VS_batch1_0001 VS_batch1_0001/MRI TEM...,False,None,./raw_studies/t1+_thick_ax/126_1_312/126_1_312...,./raw_studies/t1+_thick_ax/126_1_312/126_1_312...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8552,VS_batch1_0089_002,95_1_182,95,1,182,VS_batch1_0089,VS_batch1_0089,4/20/1930,1/21/1982,VS_batch1_0089_002,...,t1+_thick_ax,NaN,qc1,Original/VS_batch1_0089 VS_batch1_0089/BRAIN W...,Original/VS_batch1_0089 VS_batch1_0089/BRAIN W...,Original/VS_batch1_0089 VS_batch1_0089/BRAIN W...,False,None,./raw_studies/t1+_thick_ax/95_1_182/95_1_182_t...,./raw_studies/t1+_thick_ax/95_1_182/95_1_182_t...
8558,VS_batch1_0089_002,95_1_182,95,1,182,VS_batch1_0089,VS_batch1_0089,4/20/1930,1/21/1982,VS_batch1_0089_002,...,t2_thin,NaN,qc1,Original/VS_batch1_0089 VS_batch1_0089/BRAIN W...,Original/VS_batch1_0089 VS_batch1_0089/BRAIN W...,Original/VS_batch1_0089 VS_batch1_0089/BRAIN W...,True,"[RVS _uvauser2-copy.nii.gz, RVS _uvauser2.nii.gz]",./raw_studies/t2_thin/95_1_182/95_1_182_t2_thi...,./raw_studies/t2_thin/95_1_182/95_1_182_t2_thi...
8562,VS_batch1_0089_003,95_2_574,95,2,574,VS_batch1_0089,VS_batch1_0089,4/20/1930,2/17/1983,VS_batch1_0089_003,...,t2_thin,NaN,qc1,Original/VS_batch1_0089 VS_batch1_0089/MR NO R...,Original/VS_batch1_0089 VS_batch1_0089/MR NO R...,Original/VS_batch1_0089 VS_batch1_0089/MR NO R...,True,"[RVS _uvauser2-copy.nii.gz, RVS _uvauser2.nii.gz]",./raw_studies/t2_thin/95_2_574/95_2_574_t2_thi...,./raw_studies/t2_thin/95_2_574/95_2_574_t2_thi...
8569,VS_batch1_0089_003,95_2_574,95,2,574,VS_batch1_0089,VS_batch1_0089,4/20/1930,2/17/1983,VS_batch1_0089_003,...,t1+_thick_cor,NaN,qc1,Original/VS_batch1_0089 VS_batch1_0089/MR NO R...,Original/VS_batch1_0089 VS_batch1_0089/MR NO R...,Original/VS_batch1_0089 VS_batch1_0089/MR NO R...,False,None,./raw_studies/t1+_thick_cor/95_2_574/95_2_574_...,./raw_studies/t1+_thick_cor/95_2_574/95_2_574_...
8571,VS_batch1_0089_003,95_2_574,95,2,574,VS_batch1_0089,VS_batch1_0089,4/20/1930,2/17/1983,VS_batch1_0089_003,...,t1+_thick_ax,NaN,qc1,Original/VS_batch1_0089 VS_batch1_0089/MR NO R...,Original/VS_batch1_0089 VS_batch1_0089/MR NO R...,Original/VS_batch1_0089 VS_batch1_0089/MR NO R...,False,None,./raw_studies/t1+_thick_ax/95_2_574/95_2_574_t...,./raw_studies/t1+_thick_ax/95_2_574/95_2_574_t...

In [12]:
updated_meta_db_df= updated_meta_db_df.drop(['Patient Name',
       'Patient Birth Date', 'Study Date', 'Accession Number',
       'Downloaded Original Series Path','Notes',],axis=1)

In [13]:
updated_meta_db_df = updated_meta_db_df.rename(columns={
    "Series Labels": "Study Type",
    "modality_image_path":"image path",
    "modality_seg_path": "segmentation path"

})
print(updated_meta_db_df.Study_Labels.unique())

['non_contrast' 'qc1' 'check' 'no_thins']

In [14]:
#check if there is anything of concern in the study labels
updated_meta_db_df=updated_meta_db_df[~updated_meta_db_df['Study_Labels'].isin(['not_vs','non_contrast'])]

In [15]:
from datetime import datetime

# Generate filename with current date
date_str = datetime.now().strftime("%Y-%m-%d")
filename = f"meta_df_{date_str}.csv"

# Save DataFrame to CSV
updated_meta_db_df.to_csv(filename, index=False)

print(f"DataFrame saved to {filename}")

DataFrame saved to meta_df_2026-02-10.csv

In [16]:
# ------------------------------------------------------------
# 1) Configuration & imports
# ------------------------------------------------------------
# Set a reproducible seed (used later if randomness added) and number of threads for ITK/ANTs operations.
# Increase THREADS to leverage more CPU cores for registration & preprocessing.
SEED = 42
THREADS = 16

import os
# Set ITK thread limit so ANTs/SimpleITK honors the chosen concurrency.
os.environ["ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS"] = str(THREADS)
print(f"Set ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS to {THREADS}.")

import gc
import shutil
import subprocess
import shlex
from pathlib import Path
from datetime import datetime
import pandas as pd
from IPython.display import display
from tqdm.auto import tqdm
import nibabel as nib
import tifffile
import SimpleITK as sitk
import ants
from pathlib import Path
import numpy as np

# Load the metadata CSV then remove undesired study types and rows missing image paths.
# The regex excludes 'T1 pre' and 'T2 Thick' variants (case-insensitive).

meta_df = pd.read_csv(filename)
meta_df = meta_df[~meta_df['Study Type'].str.contains(r'T1 pre|T2 Thick', case=False, na=False)].dropna(subset = 'image path')
# List of candidate T2 thin images (example subset potentially targeted for HD-BET).
images = meta_df[meta_df['Study Type']=='t2_thin']['image path'].dropna() 
print(len(images))

Set ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS to 16.
542

In [17]:
meta_df

,Carina Accession Number,Patient_MRI_Days Tracker,Patient_ID,Scan Order,Days between scans,Patient ID,Series Instance UID,Series Index,Series Description,Study Type,Study_Labels,abs_path,original_image_path,original_seg_path,multiple_segs_flag,all_seg_filenames,image path,segmentation path
0,VS_batch2_0001_001,126_0_0,126,0,0,VS_batch2_0001,1.2.826.0.1.3680043.8.498.11849212733585833999...,1,t2_propeller_ax,t2_thick,qc1,Original/VS_batch2_0001 VS_batch2_0001/MR NO R...,Original/VS_batch2_0001 VS_batch2_0001/MR NO R...,Original/VS_batch2_0001 VS_batch2_0001/MR NO R...,False,NaN,./raw_studies/t2_thick/126_0_0/126_0_0_t2_thic...,./raw_studies/t2_thick/126_0_0/126_0_0_t2_thic...
1,VS_batch2_0001_001,126_0_0,126,0,0,VS_batch2_0001,1.2.826.0.1.3680043.8.498.93570814980014534584...,4,t1_pg_cor,t1+_thick_cor,qc1,Original/VS_batch2_0001 VS_batch2_0001/MR NO R...,Original/VS_batch2_0001 VS_batch2_0001/MR NO R...,Original/VS_batch2_0001 VS_batch2_0001/MR NO R...,False,NaN,./raw_studies/t1+_thick_cor/126_0_0/126_0_0_t1...,./raw_studies/t1+_thick_cor/126_0_0/126_0_0_t1...
2,VS_batch2_0001_001,126_0_0,126,0,0,VS_batch2_0001,1.2.826.0.1.3680043.8.498.37810492909716881335...,8,t1_pg_ax,t1+_thick_ax,qc1,Original/VS_batch2_0001 VS_batch2_0001/MR NO R...,Original/VS_batch2_0001 VS_batch2_0001/MR NO R...,Original/VS_batch2_0001 VS_batch2_0001/MR NO R...,False,NaN,./raw_studies/t1+_thick_ax/126_0_0/126_0_0_t1+...,./raw_studies/t1+_thick_ax/126_0_0/126_0_0_t1+...
3,VS_batch1_0001_001,126_1_312,126,1,312,VS_batch1_0001,1.2.826.0.1.3680043.8.498.28817049015689088667...,7,NaN,t1+_thick_ax,qc1,Original/VS_batch1_0001 VS_batch1_0001/MRI TEM...,Original/VS_batch1_0001 VS_batch1_0001/MRI TEM...,Original/VS_batch1_0001 VS_batch1_0001/MRI TEM...,False,NaN,./raw_studies/t1+_thick_ax/126_1_312/126_1_312...,./raw_studies/t1+_thick_ax/126_1_312/126_1_312...
4,VS_batch1_0001_001,126_1_312,126,1,312,VS_batch1_0001,1.2.826.0.1.3680043.8.498.13013546638123012911...,8,NaN,t1+_thick_cor,qc1,Original/VS_batch1_0001 VS_batch1_0001/MRI TEM...,Original/VS_batch1_0001 VS_batch1_0001/MRI TEM...,Original/VS_batch1_0001 VS_batch1_0001/MRI TEM...,False,NaN,./raw_studies/t1+_thick_cor/126_1_312/126_1_31...,./raw_studies/t1+_thick_cor/126_1_312/126_1_31...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1801,VS_batch1_0089_002,95_1_182,95,1,182,VS_batch1_0089,1.2.826.0.1.3680043.8.498.10208435538285008774...,5,NaN,t1+_thick_ax,qc1,Original/VS_batch1_0089 VS_batch1_0089/BRAIN W...,Original/VS_batch1_0089 VS_batch1_0089/BRAIN W...,Original/VS_batch1_0089 VS_batch1_0089/BRAIN W...,False,NaN,./raw_studies/t1+_thick_ax/95_1_182/95_1_182_t...,./raw_studies/t1+_thick_ax/95_1_182/95_1_182_t...
1802,VS_batch1_0089_002,95_1_182,95,1,182,VS_batch1_0089,1.2.826.0.1.3680043.8.498.14209899306722623411...,11,NaN,t2_thin,qc1,Original/VS_batch1_0089 VS_batch1_0089/BRAIN W...,Original/VS_batch1_0089 VS_batch1_0089/BRAIN W...,Original/VS_batch1_0089 VS_batch1_0089/BRAIN W...,True,"['RVS _uvauser2-copy.nii.gz', 'RVS _uvauser2.n...",./raw_studies/t2_thin/95_1_182/95_1_182_t2_thi...,./raw_studies/t2_thin/95_1_182/95_1_182_t2_thi...
1803,VS_batch1_0089_003,95_2_574,95,2,574,VS_batch1_0089,1.2.826.0.1.3680043.8.498.57214864933569825812...,1,NaN,t2_thin,qc1,Original/VS_batch1_0089 VS_batch1_0089/MR NO R...,Original/VS_batch1_0089 VS_batch1_0089/MR NO R...,Original/VS_batch1_0089 VS_batch1_0089/MR NO R...,True,"['RVS _uvauser2-copy.nii.gz', 'RVS _uvauser2.n...",./raw_studies/t2_thin/95_2_574/95_2_574_t2_thi...,./raw_studies/t2_thin/95_2_574/95_2_574_t2_thi...
1804,VS_batch1_0089_003,95_2_574,95,2,574,VS_batch1_0089,1.2.826.0.1.3680043.8.498.80100859856888426958...,8,NaN,t1+_thick_cor,qc1,Original/VS_batch1_0089 VS_batch1_0089/MR NO R...,Original/VS_batch1_0089 VS_batch1_0089/MR NO R...,Original/VS_batch1_0089 VS_batch1_0089/MR NO R...,False,NaN,./raw_studies/t1+_thick_cor/95_2_574/95_2_574_...,./raw_studies/t1+_thick_cor/95_2_574/95_2_574_...
1805,VS_batch1_0089_003,95_2_574,95,2,574,VS_batch1_0089,1.2.826.0.1.3680043.8.498.38606280617406530650...,10,NaN,t1+_thick_ax,qc1,Original/VS_batch1_0089 VS_batch1_0089/MR NO R...,Original/VS_batch1_0089 VS_batch1_0089/MR NO R...,Original/VS_batch1_0089 VS_batch1_0089/MR NO R...,False,NaN,./raw_studies/t1+_thick_ax/95_2_574/95_2_574_t...,./raw_studies/t1+_thick_ax/95_2_574/95_2_574_t...

In [18]:
# === HD-BET processing pipeline ===
# Builds a working dataframe of candidate images, stages unprocessed ones into hd_input,
# executes HD-BET (batch or per-file fallback), collects outputs, writes manifests, then cleans temp inputs.
# Assumptions: meta_df has columns 'image path' and 'Study Type'.


# --------------------------
# Config (edit as needed)
# --------------------------
cwd = os.getcwd()  # or set to a specific working directory path string
raw_path = os.path.join(cwd, 'hd_input')   # input folder for HD-BET
bet_path = os.path.join(cwd, 'hd_output')  # output folder for HD-BET

# Filter which rows to include from meta_df
FILTER_STUDY_TYPE = None  # set to None to use all rows

# meta_df columns
PATH_COLUMN = "image path"      # path to .nii or .nii.gz
STUDY_COL   = "Study Type"

# HD-BET binary path (uses this if it exists; else falls back to PATH)
hd_bet_path = '/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet'

# HD-BET flags
DEVICE = "cuda"
DISABLE_TTA = True                   # if your build doesn't support it, change to: ["--tta", "0"]
SAVE_ONLY_MASK = True                # True -> --save_bet_mask --no_bet_image

# What counts as "already processed" in hd_output:
KNOWN_OUTPUT_SUFFIXES = ['_bet', '_bet_mask', '_mask']

# Whether to wipe hd_input before copying (recommended for clean runs)
CLEAN_HD_INPUT_FIRST = True

# --------------------------
# Helpers
# --------------------------
def _strip_nii_ext(fn: str) -> str:
    """Return filename without the .nii or .nii.gz extension."""
    if fn.endswith('.nii.gz'):
        return fn[:-7]
    if fn.endswith('.nii'):
        return fn[:-4]
    return fn

def _expected_outputs(basename_noext: str, suffixes=None):
    """Build set of possible HD-BET output names (with .nii.gz) given a base."""
    suffixes = suffixes or ['_bet', '_bet_mask', '_mask']
    return {f"{basename_noext}{s}.nii.gz" for s in suffixes}

# --------------------------
# 1) Build df from meta_df
# --------------------------
if FILTER_STUDY_TYPE is None:
    sel = meta_df.copy()
else:
    if STUDY_COL not in meta_df.columns:
        raise KeyError(f"'{STUDY_COL}' not found in meta_df.")
    sel = meta_df[meta_df[STUDY_COL] == FILTER_STUDY_TYPE].copy()

if PATH_COLUMN not in sel.columns:
    raise KeyError(f"'{PATH_COLUMN}' not found in meta_df.")

# Drop rows with missing paths, and create (Image_Path, Image)
sel = sel[sel[PATH_COLUMN].notna()].copy()
sel["Image_Path"] = sel[PATH_COLUMN].astype(str)
sel["Image"] = sel["Image_Path"].apply(os.path.basename)

# Keep only what we need for processing, but retain Study Type for context
keep_cols = [c for c in ["Image", "Image_Path", STUDY_COL] if c in sel.columns]
df = sel[keep_cols].copy()

print(f"[INFO] Candidate rows from meta_df: {len(df)}" + (f" | Study Type == '{FILTER_STUDY_TYPE}'" if FILTER_STUDY_TYPE else ""))

# ------------------------------------------
# 2) Prepare HD-BET input/output folders
# ------------------------------------------
os.makedirs(raw_path, exist_ok=True)
os.makedirs(bet_path, exist_ok=True)

# If desired, clear hd_input so this run is fresh
if CLEAN_HD_INPUT_FIRST:
    for p in Path(raw_path).glob("*"):
        if p.is_file():
            p.unlink()

# List of existing outputs (if hd_output already exists)
existing_files = set(os.listdir(bet_path)) if os.path.exists(bet_path) else set()

[INFO] Candidate rows from meta_df: 1793

In [19]:
# ----------------------------------------------------
# 3) Decide: TODO vs SKIPPED; copy only unprocessed
# ----------------------------------------------------
rows_todo = []
rows_skipped = []

print(f"\n=== Processing {len(df)} total files ===")
print(f"Found {len(existing_files)} existing output files in {bet_path}")

for idx, row in df.iterrows():
    img_name = str(row["Image"])
    img_path = str(row["Image_Path"])
    
    # NIfTI guard
    if not (img_name.endswith(".nii") or img_name.endswith(".nii.gz")):
        rs = row.to_dict()
        rs["Reason"] = "unsupported_extension"
        rows_skipped.append(rs)
        print(f"❌ Skipped {img_name}: unsupported extension")
        continue
    
    # Already processed?
    base_noext = _strip_nii_ext(img_name)
    expected = _expected_outputs(base_noext, KNOWN_OUTPUT_SUFFIXES)
    matches = expected & existing_files
    
    if matches:
        rs = row.to_dict()
        rs["Reason"] = "already_processed"
        rs["ExistingOutputsMatched"] = ";".join(sorted(matches))
        rows_skipped.append(rs)
        print(f"⏭️  Skipped {img_name}: already processed (found {len(matches)} outputs)")
        continue
    
    # Missing file?
    if not img_path or not os.path.exists(img_path):
        rs = row.to_dict()
        rs["Reason"] = "missing_file"
        rows_skipped.append(rs)
        print(f"❌ Skipped {img_name}: file not found at {img_path}")
        continue
    
    # Copy to hd_input
    dest = os.path.join(raw_path, img_name)
    shutil.copy(img_path, dest)
    rt = row.to_dict()
    rt["CopiedTo"] = dest
    rows_todo.append(rt)
    print(f"✅ Copied {img_name} to hd_input")

todo_df = pd.DataFrame(rows_todo)
skipped_df = pd.DataFrame(rows_skipped)

print(f"\n=== Summary ===")
print(f"To process: {len(todo_df)}")
print(f"Skipped: {len(skipped_df)}")
if len(skipped_df) > 0:
    print(f"\nSkip reasons:")
    print(skipped_df["Reason"].value_counts())

=== Processing 1793 total files ===
Found 1645 existing output files in /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_output
⏭️  Skipped 126_0_0_t2_thick_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 126_0_0_t1+_thick_cor_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 126_0_0_t1+_thick_ax_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 126_1_312_t1+_thick_ax_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 126_1_312_t1+_thick_cor_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 126_1_312_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 126_1_312_t1+_thick_cor_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 126_2_582_t1+_thick_cor_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 126_2_582_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 126_2_582_t1+_thick_ax_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 126_3_921_t1+_thick_ax_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 126_3_921_t1+_thick_cor_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 126_3_921_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 126_4_1231_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 126_4_1231_t1+_thick_ax_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 126_4_1231_t1+_thick_cor_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 126_5_1607_t1+_thick_ax_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 126_5_1607_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 126_5_1607_t1+_thick_cor_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 131_0_0_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 131_0_0_t1+_thick_ax_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 131_0_0_t1+_thick_cor_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 131_1_196_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 131_1_196_t1+_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 131_2_258_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 131_2_258_t1+_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 132_0_0_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 132_0_0_t1+_thick_cor_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 132_0_0_t1+_thick_ax_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 132_1_148_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 132_1_148_t1+_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 132_2_232_t1+_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 132_2_232_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 137_0_0_t1+_thick_cor_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 137_0_0_t1+_thick_ax_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 137_0_0_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 137_1_571_t1+_thick_cor_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 137_1_571_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 137_1_571_t1+_thick_ax_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 137_2_2111_t1+_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 137_2_2111_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 140_0_0_t1+_thick_cor_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 140_0_0_t1+_thick_ax_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 140_0_0_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 140_1_327_t2_thick_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 140_1_327_t1+_thick_ax_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 140_1_327_t1+_thick_cor_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 140_2_780_t1+_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 140_2_780_t1+_thick_cor_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 140_2_780_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 146_0_0_t1+_thick_ax_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 146_0_0_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 146_0_0_t1+_thick_cor_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 146_1_538_t1+_thick_cor_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 146_1_538_t2_thick_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 146_1_538_t1+_thick_ax_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 146_2_941_t1+_thick_ax_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 146_2_941_t1+_thick_cor_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 146_2_941_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 147_0_0_t1+_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 147_0_0_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 147_0_0_t1+_thick_cor_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 147_1_104_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 147_1_104_t1+_thick_cor_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 147_1_104_t1+_thick_ax_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 147_1_104_t1+_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 148_0_0_t1+_thick_cor_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 148_0_0_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 148_0_0_t1+_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 148_1_182_t1+_thick_cor_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 148_1_182_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 148_1_182_t1+_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 148_2_253_t1+_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 148_2_253_t1+_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 148_2_253_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 152_0_0_t1+_thick_ax_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 152_0_0_t1+_thick_cor_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 152_0_0_t2_thick_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 152_1_95_t2_thick_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 152_1_95_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 152_1_95_t1+_thick_ax_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 152_1_95_t2_thick_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 152_1_95_t1+_thick_cor_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 152_2_461_t1+_thick_ax_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 152_2_461_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 152_2_461_t1+_thick_cor_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 152_3_905_t1+_thick_ax_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 152_3_905_t1+_thick_cor_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 152_3_905_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 152_4_1291_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 152_4_1291_t1+_thick_ax_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 152_4_1291_t1+_thick_cor_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 152_5_1683_t1+_thick_ax_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 152_5_1683_t1+_thick_cor_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 152_5_1683_t2_thin_image.nii.gz: already processed (found 1 outputs)
✅ Copied 16_1_1850_t2_thick_image.nii.gz to hd_input
⏭️  Skipped 169_0_0_t1+_thick_cor_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 169_0_0_t1+_thick_ax_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 169_0_0_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 169_1_184_t1+_thick_cor_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 169_1_184_t2_thick_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 169_1_184_t1+_thick_ax_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 169_1_184_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 169_1_184_t1+_thick_ax_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 169_2_722_t1+_thick_cor_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 169_2_722_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 169_2_722_t1+_thick_ax_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 169_3_835_t1+_thick_ax_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 169_3_835_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 169_3_835_t1+_thick_cor_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 170_0_0_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 170_0_0_t1+_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 170_1_176_t1+_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 170_1_176_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 170_2_382_t1+_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 170_2_382_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 170_3_732_t1+_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 170_3_732_t2_thin_image.nii.gz: already processed (found 1 outputs)
✅ Copied 175_0_0_t2_thick_image.nii.gz to hd_input
✅ Copied 175_0_0_t1+_thin_image.nii.gz to hd_input
⏭️  Skipped 178_0_0_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 178_0_0_t1+_thick_cor_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 178_0_0_t1+_thick_ax_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 178_1_138_t1+_thick_cor_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 178_1_138_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 178_1_138_t1+_thick_ax_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 178_2_282_t2_thick_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 178_2_282_t1+_thick_cor_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 178_2_282_t1+_thick_ax_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 178_3_765_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 178_3_765_t1+_thick_cor_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 178_3_765_t1+_thick_ax_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 178_4_2203_t1+_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 178_4_2203_t1+_thick_ax_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 178_4_2203_t1+_thick_cor_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 178_5_2486_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 178_5_2486_t1+_thick_ax_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 178_5_2486_t1+_thick_cor_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 181_0_0_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 181_0_0_t1+_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 181_1_61_t1+_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 181_2_194_t1+_thick_ax_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 181_2_194_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 182_0_0_t1+_thick_ax_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 182_0_0_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 182_0_0_t2_thick_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 185_0_0_t1+_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 185_0_0_t1+_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 185_0_0_t2_thick_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 185_1_277_t1+_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 185_1_277_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 185_2_325_t2_thin_image.nii.gz: already processed (found 1 outputs)
✅ Copied 185_2_325_t1+_thin_image_uint8.nii.gz to hd_input
⏭️  Skipped 188_0_0_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 188_0_0_t1+_thick_cor_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 188_0_0_t1+_thick_ax_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 188_1_263_t1+_thick_cor_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 188_1_263_t1+_thick_ax_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 188_1_263_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 188_2_645_t1+_thick_ax_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 188_2_645_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 188_2_645_t1+_thick_cor_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 188_3_1033_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 188_3_1033_t1+_thick_cor_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 188_3_1033_t1+_thick_ax_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 188_4_1434_t1+_thick_ax_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 188_4_1434_t1+_thick_cor_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 188_4_1434_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 188_5_2399_t1+_thick_ax_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 188_5_2399_t1+_thick_cor_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 188_5_2399_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 190_0_0_t1+_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 190_0_0_t2_thick_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 190_0_0_t1+_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 190_1_150_t1+_thick_ax_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 190_1_150_t1+_thick_cor_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 190_1_150_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 190_2_1367_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 190_2_1367_t1+_thick_ax_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 190_2_1367_t1+_thick_cor_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 190_3_2717_t2_thick_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 190_4_2800_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 193_0_0_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 193_0_0_t1+_thick_ax_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 193_0_0_t1+_thick_cor_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 193_1_175_t1+_thick_ax_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 193_1_175_t1+_thick_cor_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 193_1_175_t2_thin_image.nii.gz: already processed (found 1 outputs)
✅ Copied 193_2_314_t2_thin_image.nii.gz to hd_input
⏭️  Skipped 193_2_314_t1+_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 199_0_0_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 199_0_0_t1+_thick_ax_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 199_0_0_t1+_thick_cor_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 199_1_183_t1+_thick_ax_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 199_1_183_t1+_thick_cor_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 199_1_183_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 199_2_292_t1+_thin_image.nii.gz: already processed (found 1 outputs)
✅ Copied 199_2_292_t2_thin_image_uint8.nii.gz to hd_input
⏭️  Skipped 200_0_0_t1+_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 200_0_0_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 200_1_45_t1+_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 200_1_45_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 202_0_0_t1+_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 202_0_0_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 202_1_667_t2_thick_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 202_2_826_t1+_thick_ax_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 202_2_826_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 202_2_826_t1+_thick_cor_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 206_0_0_t1+_thick_cor_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 206_0_0_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 206_0_0_t1+_thick_ax_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 206_1_356_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 206_1_356_t1+_thick_ax_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 206_1_356_t1+_thick_cor_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 207_0_0_t1+_thick_cor_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 207_0_0_t1+_thick_ax_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 207_0_0_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 207_1_291_t1+_thick_ax_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 207_1_291_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 207_1_291_t1+_thick_cor_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 207_2_651_t1+_thick_cor_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 207_2_651_t1+_thick_ax_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 207_2_651_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 207_3_1194_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 207_3_1194_t1+_thick_ax_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 207_3_1194_t1+_thick_cor_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 207_4_1986_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 207_4_1986_t1+_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 208_1_36_t2_thick_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 208_1_36_t1+_thick_cor_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 208_1_36_t1+_thick_ax_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 210_0_0_t1+_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 210_0_0_t1+_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 210_0_0_t2_thick_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 210_1_162_t1+_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 210_1_162_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 210_2_231_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 210_2_231_t1+_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 210_2_231_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 215_0_0_t2_thin_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 215_0_0_t1+_thick_ax_image.nii.gz: already processed (found 1 outputs)
⏭️  Skipped 215_0_0_t1+_thick_cor_image.nii.gz: already processed (found 1 outputs)

In [20]:
# ----------------------------------------
# 4) Write CSV manifests (todo & skipped)
# ----------------------------------------
timestamp = datetime.now().strftime("%Y%m")
todo_csv = os.path.join(cwd, f"hd_bet_todo_{timestamp}.csv")
skipped_csv = os.path.join(cwd, f"hd_bet_skipped_{timestamp}.csv")

todo_df.to_csv(todo_csv, index=False)
skipped_df.to_csv(skipped_csv, index=False)
print(f"[INFO] Wrote: {todo_csv}")
print(f"[INFO] Wrote: {skipped_csv}")

[INFO] Wrote: /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_bet_todo_202602.csv
[INFO] Wrote: /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_bet_skipped_202602.csv

In [21]:

# ----------------------------------------
# 5) Run HD-BET (if anything to process)
# ----------------------------------------
if todo_df.empty:
    print("[INFO] Nothing to run. All images are either processed, missing, or unsupported.")
    print(f"[SUMMARY] skipped={len(skipped_df)}, todo=0")
else:
    # Resolve hd-bet command
    if hd_bet_path and Path(hd_bet_path).exists():
        hd_bet_cmd = hd_bet_path
    else:
        # fallback to PATH lookup
        hd_bet_cmd = shutil.which("hd-bet")
        if not hd_bet_cmd:
            raise FileNotFoundError(
                "hd-bet command not found. Set hd_bet_path to the full path or ensure it's on PATH."
            )

    args = [
        shlex.quote(hd_bet_cmd),
        "-i", shlex.quote(raw_path),
        "-o", shlex.quote(bet_path),
        "-device", shlex.quote(DEVICE),
    ]
    if DISABLE_TTA:
        # If your build doesn't support this flag, replace with: args.extend(["--tta", "0"])
        args.append("--disable_tta")
    if SAVE_ONLY_MASK:
        args.extend(["--save_bet_mask", "--no_bet_image"])

    command = " ".join(args)
    print(f"[INFO] Running HD-BET on {len(todo_df)} files (batch):\n{command}")

    # Use subprocess for better error reporting. On batch failure, retry per-file with explicit output path.
    try:
        subprocess.run(command, shell=True, check=True)
    except subprocess.CalledProcessError as e:
        print(f"[ERROR] HD-BET batch run failed with return code {e.returncode}. Falling back to per-file runs.")
        per_file_failures = []
        # iterate over files actually copied into raw_path (use todo_df to preserve original ordering/info)
        for rt in rows_todo:
            input_fp = rt["CopiedTo"]
            if not os.path.exists(input_fp):
                print(f"[WARN] Input missing for per-file retry: {input_fp}")
                per_file_failures.append((input_fp, "missing_input"))
                continue

            base_noext = _strip_nii_ext(os.path.basename(input_fp))
            # direct full output file path ending in .nii.gz inside hd_output
            out_fp = os.path.join(bet_path, f"{base_noext}.nii.gz")

            per_args = [
                shlex.quote(hd_bet_cmd),
                "-i", shlex.quote(input_fp),
                "-o", shlex.quote(out_fp),
                "-device", shlex.quote(DEVICE),
            ]
            if DISABLE_TTA:
                per_args.append("--disable_tta")
            if SAVE_ONLY_MASK:
                per_args.extend(["--save_bet_mask", "--no_bet_image"])

            per_command = " ".join(per_args)
            print(f"[INFO] Running HD-BET for single file:\n{per_command}")
            try:
                subprocess.run(per_command, shell=True, check=True)
            except subprocess.CalledProcessError as e2:
                print(f"[ERROR] HD-BET failed for {input_fp} with return code {e2.returncode}")
                per_file_failures.append((input_fp, e2.returncode))
            except Exception as ex:
                print(f"[ERROR] Unexpected error for {input_fp}: {ex}")
                per_file_failures.append((input_fp, str(ex)))
        if per_file_failures:
            print(f"[WARN] Per-file retries had {len(per_file_failures)} failures. See logs above.")
    finally:
        # Clean up input folder and free memory
        try:
            shutil.rmtree(raw_path)
            print(f"[INFO] Removed temp folder: {raw_path}")
        except Exception as e:
            print(f"[WARN] Could not remove {raw_path}: {e}")
        gc.collect()

    print(f"[SUMMARY] processed={len(todo_df)}, skipped={len(skipped_df)}")
try:
    shutil.rmtree(raw_path)
    print(f"[INFO] Removed temp folder: {raw_path}")
except Exception as e:
    print(f"[WARN] Could not remove {raw_path}: {e}")
gc.collect()

[INFO] Running HD-BET on 57 files (batch):
/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet -i '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input' -o '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_output' -device cuda --disable_tta --save_bet_mask --no_bet_image

########################
If you are using hd-bet, please cite the following papers:

Isensee F, Schell M, Tursunova I, Brugnara G, Bonekamp D, Neuberger U, Wick A, Schlemmer HP, Heiland S, Wick W, Bendszus M, Maier-Hein KH, Kickingereder P. Automated brain extraction of multi-sequence MRI using artificial neural networks. arXiv preprint arXiv:1901.11341, 2019.

Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
########################

There are 55 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 55 cases that I would like to predict

Process SpawnProcess-11:
Traceback (most recent call last):
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 58, in preprocess_fromfiles_save_to_queue
    raise e
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 31, in preprocess_fromfiles_save_to_queue
    data, seg, data_properties = preprocessor.run_case(list_of_lists[idx],
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/preprocessing/preprocessors/default_preprocessor.py", line 146, in run_case
    data, seg, data_properties = self.run_case_npy(data, seg, data_properties, plans_manager, configuration_manager,
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/preprocessing/preprocessors/default_preprocessor.py", line 83, in run_case_npy
    data = self._normalize(data, seg, configuration_manager,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/preprocessing/preprocessors/default_preprocessor.py", line 231, in _normalize
    scheme = configuration_manager.normalization_schemes[c]
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/entry_point.py", line 53, in main
    hdbet_predict(args.input,args.output, predictor, keep_brain_mask=args.save_bet_mask,
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/hd_bet_prediction.py", line 69, in hdbet_predict
    predictor.predict_from_files(
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 268, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 361, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in preprocessing_iterator_fromfiles
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in <listcomp>
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
     ^^^^^^^^^^^^^^
RuntimeError: No CUDA GPUs are available

[ERROR] HD-BET batch run failed with return code 1. Falling back to per-file runs.
[INFO] Running HD-BET for single file:
/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet -i '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/16_1_1850_t2_thick_image.nii.gz' -o '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_output/16_1_1850_t2_thick_image.nii.gz' -device cuda --disable_tta --save_bet_mask --no_bet_image

########################
If you are using hd-bet, please cite the following papers:

Isensee F, Schell M, Tursunova I, Brugnara G, Bonekamp D, Neuberger U, Wick A, Schlemmer HP, Heiland S, Wick W, Bendszus M, Maier-Hein KH, Kickingereder P. Automated brain extraction of multi-sequence MRI using artificial neural networks. arXiv preprint arXiv:1901.11341, 2019.

Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
########################

There are 1 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1 cases that I would like to predict

Traceback (most recent call last):
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/entry_point.py", line 53, in main
    hdbet_predict(args.input,args.output, predictor, keep_brain_mask=args.save_bet_mask,
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/hd_bet_prediction.py", line 69, in hdbet_predict
    predictor.predict_from_files(
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 268, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 361, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in preprocessing_iterator_fromfiles
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in <listcomp>
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
     ^^^^^^^^^^^^^^
RuntimeError: No CUDA GPUs are available

[ERROR] HD-BET failed for /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/16_1_1850_t2_thick_image.nii.gz with return code 1
[INFO] Running HD-BET for single file:
/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet -i '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/175_0_0_t2_thick_image.nii.gz' -o '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_output/175_0_0_t2_thick_image.nii.gz' -device cuda --disable_tta --save_bet_mask --no_bet_image

########################
If you are using hd-bet, please cite the following papers:

Isensee F, Schell M, Tursunova I, Brugnara G, Bonekamp D, Neuberger U, Wick A, Schlemmer HP, Heiland S, Wick W, Bendszus M, Maier-Hein KH, Kickingereder P. Automated brain extraction of multi-sequence MRI using artificial neural networks. arXiv preprint arXiv:1901.11341, 2019.

Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
########################

There are 1 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1 cases that I would like to predict

Traceback (most recent call last):
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/entry_point.py", line 53, in main
    hdbet_predict(args.input,args.output, predictor, keep_brain_mask=args.save_bet_mask,
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/hd_bet_prediction.py", line 69, in hdbet_predict
    predictor.predict_from_files(
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 268, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 361, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in preprocessing_iterator_fromfiles
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in <listcomp>
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
     ^^^^^^^^^^^^^^
RuntimeError: No CUDA GPUs are available

[ERROR] HD-BET failed for /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/175_0_0_t2_thick_image.nii.gz with return code 1
[INFO] Running HD-BET for single file:
/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet -i '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/175_0_0_t1+_thin_image.nii.gz' -o '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_output/175_0_0_t1+_thin_image.nii.gz' -device cuda --disable_tta --save_bet_mask --no_bet_image

########################
If you are using hd-bet, please cite the following papers:

Isensee F, Schell M, Tursunova I, Brugnara G, Bonekamp D, Neuberger U, Wick A, Schlemmer HP, Heiland S, Wick W, Bendszus M, Maier-Hein KH, Kickingereder P. Automated brain extraction of multi-sequence MRI using artificial neural networks. arXiv preprint arXiv:1901.11341, 2019.

Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
########################

There are 1 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1 cases that I would like to predict

Traceback (most recent call last):
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/entry_point.py", line 53, in main
    hdbet_predict(args.input,args.output, predictor, keep_brain_mask=args.save_bet_mask,
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/hd_bet_prediction.py", line 69, in hdbet_predict
    predictor.predict_from_files(
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 268, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 361, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in preprocessing_iterator_fromfiles
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in <listcomp>
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
     ^^^^^^^^^^^^^^
RuntimeError: No CUDA GPUs are available

[ERROR] HD-BET failed for /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/175_0_0_t1+_thin_image.nii.gz with return code 1
[INFO] Running HD-BET for single file:
/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet -i '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/185_2_325_t1+_thin_image_uint8.nii.gz' -o '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_output/185_2_325_t1+_thin_image_uint8.nii.gz' -device cuda --disable_tta --save_bet_mask --no_bet_image

########################
If you are using hd-bet, please cite the following papers:

Isensee F, Schell M, Tursunova I, Brugnara G, Bonekamp D, Neuberger U, Wick A, Schlemmer HP, Heiland S, Wick W, Bendszus M, Maier-Hein KH, Kickingereder P. Automated brain extraction of multi-sequence MRI using artificial neural networks. arXiv preprint arXiv:1901.11341, 2019.

Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
########################

There are 1 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1 cases that I would like to predict

Traceback (most recent call last):
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/entry_point.py", line 53, in main
    hdbet_predict(args.input,args.output, predictor, keep_brain_mask=args.save_bet_mask,
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/hd_bet_prediction.py", line 69, in hdbet_predict
    predictor.predict_from_files(
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 268, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 361, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in preprocessing_iterator_fromfiles
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in <listcomp>
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
     ^^^^^^^^^^^^^^
RuntimeError: No CUDA GPUs are available

[ERROR] HD-BET failed for /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/185_2_325_t1+_thin_image_uint8.nii.gz with return code 1
[INFO] Running HD-BET for single file:
/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet -i '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/193_2_314_t2_thin_image.nii.gz' -o '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_output/193_2_314_t2_thin_image.nii.gz' -device cuda --disable_tta --save_bet_mask --no_bet_image

########################
If you are using hd-bet, please cite the following papers:

Isensee F, Schell M, Tursunova I, Brugnara G, Bonekamp D, Neuberger U, Wick A, Schlemmer HP, Heiland S, Wick W, Bendszus M, Maier-Hein KH, Kickingereder P. Automated brain extraction of multi-sequence MRI using artificial neural networks. arXiv preprint arXiv:1901.11341, 2019.

Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
########################

There are 1 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1 cases that I would like to predict

Process SpawnProcess-11:
Traceback (most recent call last):
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 58, in preprocess_fromfiles_save_to_queue
    raise e
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 31, in preprocess_fromfiles_save_to_queue
    data, seg, data_properties = preprocessor.run_case(list_of_lists[idx],
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/preprocessing/preprocessors/default_preprocessor.py", line 146, in run_case
    data, seg, data_properties = self.run_case_npy(data, seg, data_properties, plans_manager, configuration_manager,
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/preprocessing/preprocessors/default_preprocessor.py", line 83, in run_case_npy
    data = self._normalize(data, seg, configuration_manager,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/preprocessing/preprocessors/default_preprocessor.py", line 231, in _normalize
    scheme = configuration_manager.normalization_schemes[c]
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/entry_point.py", line 53, in main
    hdbet_predict(args.input,args.output, predictor, keep_brain_mask=args.save_bet_mask,
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/hd_bet_prediction.py", line 69, in hdbet_predict
    predictor.predict_from_files(
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 268, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 361, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 111, in preprocessing_iterator_fromfiles
    raise RuntimeError('Background workers died. Look for the error message further up! If there is '
RuntimeError: Background workers died. Look for the error message further up! If there is none then your RAM was full and the worker was killed by the OS. Use fewer workers or get more RAM in that case!

[ERROR] HD-BET failed for /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/193_2_314_t2_thin_image.nii.gz with return code 1
[INFO] Running HD-BET for single file:
/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet -i '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/199_2_292_t2_thin_image_uint8.nii.gz' -o '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_output/199_2_292_t2_thin_image_uint8.nii.gz' -device cuda --disable_tta --save_bet_mask --no_bet_image

########################
If you are using hd-bet, please cite the following papers:

Isensee F, Schell M, Tursunova I, Brugnara G, Bonekamp D, Neuberger U, Wick A, Schlemmer HP, Heiland S, Wick W, Bendszus M, Maier-Hein KH, Kickingereder P. Automated brain extraction of multi-sequence MRI using artificial neural networks. arXiv preprint arXiv:1901.11341, 2019.

Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
########################

There are 1 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1 cases that I would like to predict

Traceback (most recent call last):
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/entry_point.py", line 53, in main
    hdbet_predict(args.input,args.output, predictor, keep_brain_mask=args.save_bet_mask,
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/hd_bet_prediction.py", line 69, in hdbet_predict
    predictor.predict_from_files(
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 268, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 361, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in preprocessing_iterator_fromfiles
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in <listcomp>
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
     ^^^^^^^^^^^^^^
RuntimeError: No CUDA GPUs are available

[ERROR] HD-BET failed for /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/199_2_292_t2_thin_image_uint8.nii.gz with return code 1
[INFO] Running HD-BET for single file:
/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet -i '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/237_2_503_t2_thick_image.nii.gz' -o '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_output/237_2_503_t2_thick_image.nii.gz' -device cuda --disable_tta --save_bet_mask --no_bet_image

########################
If you are using hd-bet, please cite the following papers:

Isensee F, Schell M, Tursunova I, Brugnara G, Bonekamp D, Neuberger U, Wick A, Schlemmer HP, Heiland S, Wick W, Bendszus M, Maier-Hein KH, Kickingereder P. Automated brain extraction of multi-sequence MRI using artificial neural networks. arXiv preprint arXiv:1901.11341, 2019.

Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
########################

There are 1 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1 cases that I would like to predict

Traceback (most recent call last):
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/entry_point.py", line 53, in main
    hdbet_predict(args.input,args.output, predictor, keep_brain_mask=args.save_bet_mask,
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/hd_bet_prediction.py", line 69, in hdbet_predict
    predictor.predict_from_files(
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 268, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 361, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in preprocessing_iterator_fromfiles
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in <listcomp>
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
     ^^^^^^^^^^^^^^
RuntimeError: No CUDA GPUs are available

[ERROR] HD-BET failed for /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/237_2_503_t2_thick_image.nii.gz with return code 1
[INFO] Running HD-BET for single file:
/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet -i '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/237_2_503_t1+_thick_ax_image.nii.gz' -o '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_output/237_2_503_t1+_thick_ax_image.nii.gz' -device cuda --disable_tta --save_bet_mask --no_bet_image

########################
If you are using hd-bet, please cite the following papers:

Isensee F, Schell M, Tursunova I, Brugnara G, Bonekamp D, Neuberger U, Wick A, Schlemmer HP, Heiland S, Wick W, Bendszus M, Maier-Hein KH, Kickingereder P. Automated brain extraction of multi-sequence MRI using artificial neural networks. arXiv preprint arXiv:1901.11341, 2019.

Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
########################

There are 1 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1 cases that I would like to predict

Traceback (most recent call last):
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/entry_point.py", line 53, in main
    hdbet_predict(args.input,args.output, predictor, keep_brain_mask=args.save_bet_mask,
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/hd_bet_prediction.py", line 69, in hdbet_predict
    predictor.predict_from_files(
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 268, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 361, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in preprocessing_iterator_fromfiles
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in <listcomp>
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
     ^^^^^^^^^^^^^^
RuntimeError: No CUDA GPUs are available

[ERROR] HD-BET failed for /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/237_2_503_t1+_thick_ax_image.nii.gz with return code 1
[INFO] Running HD-BET for single file:
/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet -i '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/299_1_637_t1+_thin_image.nii.gz' -o '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_output/299_1_637_t1+_thin_image.nii.gz' -device cuda --disable_tta --save_bet_mask --no_bet_image

########################
If you are using hd-bet, please cite the following papers:

Isensee F, Schell M, Tursunova I, Brugnara G, Bonekamp D, Neuberger U, Wick A, Schlemmer HP, Heiland S, Wick W, Bendszus M, Maier-Hein KH, Kickingereder P. Automated brain extraction of multi-sequence MRI using artificial neural networks. arXiv preprint arXiv:1901.11341, 2019.

Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
########################

There are 1 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1 cases that I would like to predict

Traceback (most recent call last):
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/entry_point.py", line 53, in main
    hdbet_predict(args.input,args.output, predictor, keep_brain_mask=args.save_bet_mask,
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/hd_bet_prediction.py", line 69, in hdbet_predict
    predictor.predict_from_files(
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 268, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 361, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in preprocessing_iterator_fromfiles
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in <listcomp>
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
     ^^^^^^^^^^^^^^
RuntimeError: No CUDA GPUs are available

[ERROR] HD-BET failed for /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/299_1_637_t1+_thin_image.nii.gz with return code 1
[INFO] Running HD-BET for single file:
/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet -i '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/315_1_2738_t1+_thick_ax_image.nii.gz' -o '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_output/315_1_2738_t1+_thick_ax_image.nii.gz' -device cuda --disable_tta --save_bet_mask --no_bet_image

########################
If you are using hd-bet, please cite the following papers:

Isensee F, Schell M, Tursunova I, Brugnara G, Bonekamp D, Neuberger U, Wick A, Schlemmer HP, Heiland S, Wick W, Bendszus M, Maier-Hein KH, Kickingereder P. Automated brain extraction of multi-sequence MRI using artificial neural networks. arXiv preprint arXiv:1901.11341, 2019.

Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
########################

There are 1 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1 cases that I would like to predict

Traceback (most recent call last):
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/entry_point.py", line 53, in main
    hdbet_predict(args.input,args.output, predictor, keep_brain_mask=args.save_bet_mask,
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/hd_bet_prediction.py", line 69, in hdbet_predict
    predictor.predict_from_files(
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 268, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 361, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in preprocessing_iterator_fromfiles
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in <listcomp>
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
     ^^^^^^^^^^^^^^
RuntimeError: No CUDA GPUs are available

[ERROR] HD-BET failed for /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/315_1_2738_t1+_thick_ax_image.nii.gz with return code 1
[INFO] Running HD-BET for single file:
/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet -i '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/315_1_2738_t1+_thick_cor_image.nii.gz' -o '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_output/315_1_2738_t1+_thick_cor_image.nii.gz' -device cuda --disable_tta --save_bet_mask --no_bet_image

########################
If you are using hd-bet, please cite the following papers:

Isensee F, Schell M, Tursunova I, Brugnara G, Bonekamp D, Neuberger U, Wick A, Schlemmer HP, Heiland S, Wick W, Bendszus M, Maier-Hein KH, Kickingereder P. Automated brain extraction of multi-sequence MRI using artificial neural networks. arXiv preprint arXiv:1901.11341, 2019.

Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
########################

There are 1 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1 cases that I would like to predict

Traceback (most recent call last):
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/entry_point.py", line 53, in main
    hdbet_predict(args.input,args.output, predictor, keep_brain_mask=args.save_bet_mask,
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/hd_bet_prediction.py", line 69, in hdbet_predict
    predictor.predict_from_files(
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 268, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 361, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in preprocessing_iterator_fromfiles
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in <listcomp>
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
     ^^^^^^^^^^^^^^
RuntimeError: No CUDA GPUs are available

[ERROR] HD-BET failed for /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/315_1_2738_t1+_thick_cor_image.nii.gz with return code 1
[INFO] Running HD-BET for single file:
/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet -i '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/315_1_2738_t2_thick_image.nii.gz' -o '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_output/315_1_2738_t2_thick_image.nii.gz' -device cuda --disable_tta --save_bet_mask --no_bet_image

########################
If you are using hd-bet, please cite the following papers:

Isensee F, Schell M, Tursunova I, Brugnara G, Bonekamp D, Neuberger U, Wick A, Schlemmer HP, Heiland S, Wick W, Bendszus M, Maier-Hein KH, Kickingereder P. Automated brain extraction of multi-sequence MRI using artificial neural networks. arXiv preprint arXiv:1901.11341, 2019.

Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
########################

There are 1 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1 cases that I would like to predict

Traceback (most recent call last):
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/entry_point.py", line 53, in main
    hdbet_predict(args.input,args.output, predictor, keep_brain_mask=args.save_bet_mask,
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/hd_bet_prediction.py", line 69, in hdbet_predict
    predictor.predict_from_files(
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 268, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 361, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in preprocessing_iterator_fromfiles
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in <listcomp>
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
     ^^^^^^^^^^^^^^
RuntimeError: No CUDA GPUs are available

[ERROR] HD-BET failed for /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/315_1_2738_t2_thick_image.nii.gz with return code 1
[INFO] Running HD-BET for single file:
/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet -i '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/338_6_3807_t2_thin_image.nii.gz' -o '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_output/338_6_3807_t2_thin_image.nii.gz' -device cuda --disable_tta --save_bet_mask --no_bet_image

########################
If you are using hd-bet, please cite the following papers:

Isensee F, Schell M, Tursunova I, Brugnara G, Bonekamp D, Neuberger U, Wick A, Schlemmer HP, Heiland S, Wick W, Bendszus M, Maier-Hein KH, Kickingereder P. Automated brain extraction of multi-sequence MRI using artificial neural networks. arXiv preprint arXiv:1901.11341, 2019.

Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
########################

There are 1 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1 cases that I would like to predict

Traceback (most recent call last):
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/entry_point.py", line 53, in main
    hdbet_predict(args.input,args.output, predictor, keep_brain_mask=args.save_bet_mask,
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/hd_bet_prediction.py", line 69, in hdbet_predict
    predictor.predict_from_files(
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 268, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 361, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in preprocessing_iterator_fromfiles
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in <listcomp>
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
     ^^^^^^^^^^^^^^
RuntimeError: No CUDA GPUs are available

[ERROR] HD-BET failed for /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/338_6_3807_t2_thin_image.nii.gz with return code 1
[INFO] Running HD-BET for single file:
/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet -i '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/338_6_3807_t1+_thick_ax_image.nii.gz' -o '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_output/338_6_3807_t1+_thick_ax_image.nii.gz' -device cuda --disable_tta --save_bet_mask --no_bet_image

########################
If you are using hd-bet, please cite the following papers:

Isensee F, Schell M, Tursunova I, Brugnara G, Bonekamp D, Neuberger U, Wick A, Schlemmer HP, Heiland S, Wick W, Bendszus M, Maier-Hein KH, Kickingereder P. Automated brain extraction of multi-sequence MRI using artificial neural networks. arXiv preprint arXiv:1901.11341, 2019.

Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
########################

There are 1 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1 cases that I would like to predict

Traceback (most recent call last):
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/entry_point.py", line 53, in main
    hdbet_predict(args.input,args.output, predictor, keep_brain_mask=args.save_bet_mask,
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/hd_bet_prediction.py", line 69, in hdbet_predict
    predictor.predict_from_files(
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 268, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 361, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in preprocessing_iterator_fromfiles
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in <listcomp>
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
     ^^^^^^^^^^^^^^
RuntimeError: No CUDA GPUs are available

[ERROR] HD-BET failed for /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/338_6_3807_t1+_thick_ax_image.nii.gz with return code 1
[INFO] Running HD-BET for single file:
/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet -i '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/350_0_0_t1+_thin_image.nii.gz' -o '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_output/350_0_0_t1+_thin_image.nii.gz' -device cuda --disable_tta --save_bet_mask --no_bet_image

########################
If you are using hd-bet, please cite the following papers:

Isensee F, Schell M, Tursunova I, Brugnara G, Bonekamp D, Neuberger U, Wick A, Schlemmer HP, Heiland S, Wick W, Bendszus M, Maier-Hein KH, Kickingereder P. Automated brain extraction of multi-sequence MRI using artificial neural networks. arXiv preprint arXiv:1901.11341, 2019.

Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
########################

There are 1 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1 cases that I would like to predict

Traceback (most recent call last):
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/entry_point.py", line 53, in main
    hdbet_predict(args.input,args.output, predictor, keep_brain_mask=args.save_bet_mask,
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/hd_bet_prediction.py", line 69, in hdbet_predict
    predictor.predict_from_files(
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 268, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 361, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in preprocessing_iterator_fromfiles
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in <listcomp>
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
     ^^^^^^^^^^^^^^
RuntimeError: No CUDA GPUs are available

[ERROR] HD-BET failed for /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/350_0_0_t1+_thin_image.nii.gz with return code 1
[INFO] Running HD-BET for single file:
/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet -i '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/351_0_0_t2_thick_image.nii.gz' -o '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_output/351_0_0_t2_thick_image.nii.gz' -device cuda --disable_tta --save_bet_mask --no_bet_image

########################
If you are using hd-bet, please cite the following papers:

Isensee F, Schell M, Tursunova I, Brugnara G, Bonekamp D, Neuberger U, Wick A, Schlemmer HP, Heiland S, Wick W, Bendszus M, Maier-Hein KH, Kickingereder P. Automated brain extraction of multi-sequence MRI using artificial neural networks. arXiv preprint arXiv:1901.11341, 2019.

Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
########################

There are 1 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1 cases that I would like to predict

Traceback (most recent call last):
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/entry_point.py", line 53, in main
    hdbet_predict(args.input,args.output, predictor, keep_brain_mask=args.save_bet_mask,
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/hd_bet_prediction.py", line 69, in hdbet_predict
    predictor.predict_from_files(
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 268, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 361, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in preprocessing_iterator_fromfiles
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in <listcomp>
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
     ^^^^^^^^^^^^^^
RuntimeError: No CUDA GPUs are available

[ERROR] HD-BET failed for /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/351_0_0_t2_thick_image.nii.gz with return code 1
[INFO] Running HD-BET for single file:
/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet -i '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/364_0_0_t1+_thick_ax_image.nii.gz' -o '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_output/364_0_0_t1+_thick_ax_image.nii.gz' -device cuda --disable_tta --save_bet_mask --no_bet_image

########################
If you are using hd-bet, please cite the following papers:

Isensee F, Schell M, Tursunova I, Brugnara G, Bonekamp D, Neuberger U, Wick A, Schlemmer HP, Heiland S, Wick W, Bendszus M, Maier-Hein KH, Kickingereder P. Automated brain extraction of multi-sequence MRI using artificial neural networks. arXiv preprint arXiv:1901.11341, 2019.

Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
########################

There are 1 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1 cases that I would like to predict

Traceback (most recent call last):
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/entry_point.py", line 53, in main
    hdbet_predict(args.input,args.output, predictor, keep_brain_mask=args.save_bet_mask,
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/hd_bet_prediction.py", line 69, in hdbet_predict
    predictor.predict_from_files(
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 268, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 361, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in preprocessing_iterator_fromfiles
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in <listcomp>
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
     ^^^^^^^^^^^^^^
RuntimeError: No CUDA GPUs are available

[ERROR] HD-BET failed for /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/364_0_0_t1+_thick_ax_image.nii.gz with return code 1
[INFO] Running HD-BET for single file:
/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet -i '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/403_2_392_t1+_thin_image.nii.gz' -o '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_output/403_2_392_t1+_thin_image.nii.gz' -device cuda --disable_tta --save_bet_mask --no_bet_image

########################
If you are using hd-bet, please cite the following papers:

Isensee F, Schell M, Tursunova I, Brugnara G, Bonekamp D, Neuberger U, Wick A, Schlemmer HP, Heiland S, Wick W, Bendszus M, Maier-Hein KH, Kickingereder P. Automated brain extraction of multi-sequence MRI using artificial neural networks. arXiv preprint arXiv:1901.11341, 2019.

Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
########################

There are 1 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1 cases that I would like to predict

Traceback (most recent call last):
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/entry_point.py", line 53, in main
    hdbet_predict(args.input,args.output, predictor, keep_brain_mask=args.save_bet_mask,
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/hd_bet_prediction.py", line 69, in hdbet_predict
    predictor.predict_from_files(
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 268, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 361, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in preprocessing_iterator_fromfiles
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in <listcomp>
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
     ^^^^^^^^^^^^^^
RuntimeError: No CUDA GPUs are available

[ERROR] HD-BET failed for /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/403_2_392_t1+_thin_image.nii.gz with return code 1
[INFO] Running HD-BET for single file:
/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet -i '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/403_4_938_t2_thick_image.nii.gz' -o '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_output/403_4_938_t2_thick_image.nii.gz' -device cuda --disable_tta --save_bet_mask --no_bet_image

########################
If you are using hd-bet, please cite the following papers:

Isensee F, Schell M, Tursunova I, Brugnara G, Bonekamp D, Neuberger U, Wick A, Schlemmer HP, Heiland S, Wick W, Bendszus M, Maier-Hein KH, Kickingereder P. Automated brain extraction of multi-sequence MRI using artificial neural networks. arXiv preprint arXiv:1901.11341, 2019.

Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
########################

There are 1 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1 cases that I would like to predict

Traceback (most recent call last):
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/entry_point.py", line 53, in main
    hdbet_predict(args.input,args.output, predictor, keep_brain_mask=args.save_bet_mask,
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/hd_bet_prediction.py", line 69, in hdbet_predict
    predictor.predict_from_files(
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 268, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 361, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in preprocessing_iterator_fromfiles
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in <listcomp>
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
     ^^^^^^^^^^^^^^
RuntimeError: No CUDA GPUs are available

[ERROR] HD-BET failed for /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/403_4_938_t2_thick_image.nii.gz with return code 1
[INFO] Running HD-BET for single file:
/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet -i '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/412_1_371_t1+_thick_ax_image.nii.gz' -o '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_output/412_1_371_t1+_thick_ax_image.nii.gz' -device cuda --disable_tta --save_bet_mask --no_bet_image

########################
If you are using hd-bet, please cite the following papers:

Isensee F, Schell M, Tursunova I, Brugnara G, Bonekamp D, Neuberger U, Wick A, Schlemmer HP, Heiland S, Wick W, Bendszus M, Maier-Hein KH, Kickingereder P. Automated brain extraction of multi-sequence MRI using artificial neural networks. arXiv preprint arXiv:1901.11341, 2019.

Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
########################

There are 1 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1 cases that I would like to predict

Traceback (most recent call last):
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/entry_point.py", line 53, in main
    hdbet_predict(args.input,args.output, predictor, keep_brain_mask=args.save_bet_mask,
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/hd_bet_prediction.py", line 69, in hdbet_predict
    predictor.predict_from_files(
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 268, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 361, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in preprocessing_iterator_fromfiles
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in <listcomp>
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
     ^^^^^^^^^^^^^^
RuntimeError: No CUDA GPUs are available

[ERROR] HD-BET failed for /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/412_1_371_t1+_thick_ax_image.nii.gz with return code 1
[INFO] Running HD-BET for single file:
/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet -i '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/412_1_371_t2_thin_image.nii.gz' -o '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_output/412_1_371_t2_thin_image.nii.gz' -device cuda --disable_tta --save_bet_mask --no_bet_image

########################
If you are using hd-bet, please cite the following papers:

Isensee F, Schell M, Tursunova I, Brugnara G, Bonekamp D, Neuberger U, Wick A, Schlemmer HP, Heiland S, Wick W, Bendszus M, Maier-Hein KH, Kickingereder P. Automated brain extraction of multi-sequence MRI using artificial neural networks. arXiv preprint arXiv:1901.11341, 2019.

Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
########################

There are 1 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1 cases that I would like to predict

Traceback (most recent call last):
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/entry_point.py", line 53, in main
    hdbet_predict(args.input,args.output, predictor, keep_brain_mask=args.save_bet_mask,
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/hd_bet_prediction.py", line 69, in hdbet_predict
    predictor.predict_from_files(
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 268, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 361, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in preprocessing_iterator_fromfiles
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in <listcomp>
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
     ^^^^^^^^^^^^^^
RuntimeError: No CUDA GPUs are available

[ERROR] HD-BET failed for /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/412_1_371_t2_thin_image.nii.gz with return code 1
[INFO] Running HD-BET for single file:
/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet -i '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/412_1_371_t1+_thick_cor_image.nii.gz' -o '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_output/412_1_371_t1+_thick_cor_image.nii.gz' -device cuda --disable_tta --save_bet_mask --no_bet_image

########################
If you are using hd-bet, please cite the following papers:

Isensee F, Schell M, Tursunova I, Brugnara G, Bonekamp D, Neuberger U, Wick A, Schlemmer HP, Heiland S, Wick W, Bendszus M, Maier-Hein KH, Kickingereder P. Automated brain extraction of multi-sequence MRI using artificial neural networks. arXiv preprint arXiv:1901.11341, 2019.

Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
########################

There are 1 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1 cases that I would like to predict

Traceback (most recent call last):
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/entry_point.py", line 53, in main
    hdbet_predict(args.input,args.output, predictor, keep_brain_mask=args.save_bet_mask,
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/hd_bet_prediction.py", line 69, in hdbet_predict
    predictor.predict_from_files(
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 268, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 361, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in preprocessing_iterator_fromfiles
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in <listcomp>
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
     ^^^^^^^^^^^^^^
RuntimeError: No CUDA GPUs are available

[ERROR] HD-BET failed for /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/412_1_371_t1+_thick_cor_image.nii.gz with return code 1
[INFO] Running HD-BET for single file:
/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet -i '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/417_0_0_t2_thick_image.nii.gz' -o '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_output/417_0_0_t2_thick_image.nii.gz' -device cuda --disable_tta --save_bet_mask --no_bet_image

########################
If you are using hd-bet, please cite the following papers:

Isensee F, Schell M, Tursunova I, Brugnara G, Bonekamp D, Neuberger U, Wick A, Schlemmer HP, Heiland S, Wick W, Bendszus M, Maier-Hein KH, Kickingereder P. Automated brain extraction of multi-sequence MRI using artificial neural networks. arXiv preprint arXiv:1901.11341, 2019.

Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
########################

There are 1 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1 cases that I would like to predict

Traceback (most recent call last):
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/entry_point.py", line 53, in main
    hdbet_predict(args.input,args.output, predictor, keep_brain_mask=args.save_bet_mask,
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/hd_bet_prediction.py", line 69, in hdbet_predict
    predictor.predict_from_files(
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 268, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 361, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in preprocessing_iterator_fromfiles
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in <listcomp>
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
     ^^^^^^^^^^^^^^
RuntimeError: No CUDA GPUs are available

[ERROR] HD-BET failed for /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/417_0_0_t2_thick_image.nii.gz with return code 1
[INFO] Running HD-BET for single file:
/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet -i '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/417_0_0_t1+_thick_ax_image.nii.gz' -o '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_output/417_0_0_t1+_thick_ax_image.nii.gz' -device cuda --disable_tta --save_bet_mask --no_bet_image

########################
If you are using hd-bet, please cite the following papers:

Isensee F, Schell M, Tursunova I, Brugnara G, Bonekamp D, Neuberger U, Wick A, Schlemmer HP, Heiland S, Wick W, Bendszus M, Maier-Hein KH, Kickingereder P. Automated brain extraction of multi-sequence MRI using artificial neural networks. arXiv preprint arXiv:1901.11341, 2019.

Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
########################

There are 1 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1 cases that I would like to predict

Traceback (most recent call last):
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/entry_point.py", line 53, in main
    hdbet_predict(args.input,args.output, predictor, keep_brain_mask=args.save_bet_mask,
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/hd_bet_prediction.py", line 69, in hdbet_predict
    predictor.predict_from_files(
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 268, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 361, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in preprocessing_iterator_fromfiles
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in <listcomp>
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
     ^^^^^^^^^^^^^^
RuntimeError: No CUDA GPUs are available

[ERROR] HD-BET failed for /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/417_0_0_t1+_thick_ax_image.nii.gz with return code 1
[INFO] Running HD-BET for single file:
/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet -i '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/424_6_4194_t2_thin_image_uint8.nii.gz' -o '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_output/424_6_4194_t2_thin_image_uint8.nii.gz' -device cuda --disable_tta --save_bet_mask --no_bet_image

########################
If you are using hd-bet, please cite the following papers:

Isensee F, Schell M, Tursunova I, Brugnara G, Bonekamp D, Neuberger U, Wick A, Schlemmer HP, Heiland S, Wick W, Bendszus M, Maier-Hein KH, Kickingereder P. Automated brain extraction of multi-sequence MRI using artificial neural networks. arXiv preprint arXiv:1901.11341, 2019.

Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
########################

There are 1 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1 cases that I would like to predict

Traceback (most recent call last):
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/entry_point.py", line 53, in main
    hdbet_predict(args.input,args.output, predictor, keep_brain_mask=args.save_bet_mask,
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/hd_bet_prediction.py", line 69, in hdbet_predict
    predictor.predict_from_files(
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 268, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 361, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in preprocessing_iterator_fromfiles
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in <listcomp>
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
     ^^^^^^^^^^^^^^
RuntimeError: No CUDA GPUs are available

[ERROR] HD-BET failed for /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/424_6_4194_t2_thin_image_uint8.nii.gz with return code 1
[INFO] Running HD-BET for single file:
/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet -i '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/426_0_0_t1+_thick_cor_image.nii.gz' -o '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_output/426_0_0_t1+_thick_cor_image.nii.gz' -device cuda --disable_tta --save_bet_mask --no_bet_image

########################
If you are using hd-bet, please cite the following papers:

Isensee F, Schell M, Tursunova I, Brugnara G, Bonekamp D, Neuberger U, Wick A, Schlemmer HP, Heiland S, Wick W, Bendszus M, Maier-Hein KH, Kickingereder P. Automated brain extraction of multi-sequence MRI using artificial neural networks. arXiv preprint arXiv:1901.11341, 2019.

Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
########################

There are 1 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1 cases that I would like to predict

Traceback (most recent call last):
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/entry_point.py", line 53, in main
    hdbet_predict(args.input,args.output, predictor, keep_brain_mask=args.save_bet_mask,
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/hd_bet_prediction.py", line 69, in hdbet_predict
    predictor.predict_from_files(
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 268, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 361, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in preprocessing_iterator_fromfiles
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in <listcomp>
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
     ^^^^^^^^^^^^^^
RuntimeError: No CUDA GPUs are available

[ERROR] HD-BET failed for /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/426_0_0_t1+_thick_cor_image.nii.gz with return code 1
[INFO] Running HD-BET for single file:
/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet -i '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/426_0_0_t2_thin_image.nii.gz' -o '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_output/426_0_0_t2_thin_image.nii.gz' -device cuda --disable_tta --save_bet_mask --no_bet_image

########################
If you are using hd-bet, please cite the following papers:

Isensee F, Schell M, Tursunova I, Brugnara G, Bonekamp D, Neuberger U, Wick A, Schlemmer HP, Heiland S, Wick W, Bendszus M, Maier-Hein KH, Kickingereder P. Automated brain extraction of multi-sequence MRI using artificial neural networks. arXiv preprint arXiv:1901.11341, 2019.

Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
########################

There are 1 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1 cases that I would like to predict

Traceback (most recent call last):
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/entry_point.py", line 53, in main
    hdbet_predict(args.input,args.output, predictor, keep_brain_mask=args.save_bet_mask,
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/hd_bet_prediction.py", line 69, in hdbet_predict
    predictor.predict_from_files(
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 268, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 361, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in preprocessing_iterator_fromfiles
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in <listcomp>
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
     ^^^^^^^^^^^^^^
RuntimeError: No CUDA GPUs are available

[ERROR] HD-BET failed for /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/426_0_0_t2_thin_image.nii.gz with return code 1
[INFO] Running HD-BET for single file:
/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet -i '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/426_0_0_t1+_thick_ax_image.nii.gz' -o '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_output/426_0_0_t1+_thick_ax_image.nii.gz' -device cuda --disable_tta --save_bet_mask --no_bet_image

########################
If you are using hd-bet, please cite the following papers:

Isensee F, Schell M, Tursunova I, Brugnara G, Bonekamp D, Neuberger U, Wick A, Schlemmer HP, Heiland S, Wick W, Bendszus M, Maier-Hein KH, Kickingereder P. Automated brain extraction of multi-sequence MRI using artificial neural networks. arXiv preprint arXiv:1901.11341, 2019.

Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
########################

There are 1 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1 cases that I would like to predict

Traceback (most recent call last):
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/entry_point.py", line 53, in main
    hdbet_predict(args.input,args.output, predictor, keep_brain_mask=args.save_bet_mask,
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/hd_bet_prediction.py", line 69, in hdbet_predict
    predictor.predict_from_files(
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 268, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 361, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in preprocessing_iterator_fromfiles
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in <listcomp>
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
     ^^^^^^^^^^^^^^
RuntimeError: No CUDA GPUs are available

[ERROR] HD-BET failed for /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/426_0_0_t1+_thick_ax_image.nii.gz with return code 1
[INFO] Running HD-BET for single file:
/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet -i '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/45_4_4326_t1+_thin_image.nii.gz' -o '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_output/45_4_4326_t1+_thin_image.nii.gz' -device cuda --disable_tta --save_bet_mask --no_bet_image

########################
If you are using hd-bet, please cite the following papers:

Isensee F, Schell M, Tursunova I, Brugnara G, Bonekamp D, Neuberger U, Wick A, Schlemmer HP, Heiland S, Wick W, Bendszus M, Maier-Hein KH, Kickingereder P. Automated brain extraction of multi-sequence MRI using artificial neural networks. arXiv preprint arXiv:1901.11341, 2019.

Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
########################

There are 1 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1 cases that I would like to predict

Traceback (most recent call last):
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/entry_point.py", line 53, in main
    hdbet_predict(args.input,args.output, predictor, keep_brain_mask=args.save_bet_mask,
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/hd_bet_prediction.py", line 69, in hdbet_predict
    predictor.predict_from_files(
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 268, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 361, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in preprocessing_iterator_fromfiles
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in <listcomp>
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
     ^^^^^^^^^^^^^^
RuntimeError: No CUDA GPUs are available

[ERROR] HD-BET failed for /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/45_4_4326_t1+_thin_image.nii.gz with return code 1
[INFO] Running HD-BET for single file:
/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet -i '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/45_5_5953_t1+_thin_image.nii.gz' -o '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_output/45_5_5953_t1+_thin_image.nii.gz' -device cuda --disable_tta --save_bet_mask --no_bet_image

########################
If you are using hd-bet, please cite the following papers:

Isensee F, Schell M, Tursunova I, Brugnara G, Bonekamp D, Neuberger U, Wick A, Schlemmer HP, Heiland S, Wick W, Bendszus M, Maier-Hein KH, Kickingereder P. Automated brain extraction of multi-sequence MRI using artificial neural networks. arXiv preprint arXiv:1901.11341, 2019.

Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
########################

There are 1 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1 cases that I would like to predict

Traceback (most recent call last):
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/entry_point.py", line 53, in main
    hdbet_predict(args.input,args.output, predictor, keep_brain_mask=args.save_bet_mask,
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/hd_bet_prediction.py", line 69, in hdbet_predict
    predictor.predict_from_files(
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 268, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 361, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in preprocessing_iterator_fromfiles
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in <listcomp>
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
     ^^^^^^^^^^^^^^
RuntimeError: No CUDA GPUs are available

[ERROR] HD-BET failed for /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/45_5_5953_t1+_thin_image.nii.gz with return code 1
[INFO] Running HD-BET for single file:
/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet -i '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/459_3_493_t1+_thin_image.nii.gz' -o '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_output/459_3_493_t1+_thin_image.nii.gz' -device cuda --disable_tta --save_bet_mask --no_bet_image

########################
If you are using hd-bet, please cite the following papers:

Isensee F, Schell M, Tursunova I, Brugnara G, Bonekamp D, Neuberger U, Wick A, Schlemmer HP, Heiland S, Wick W, Bendszus M, Maier-Hein KH, Kickingereder P. Automated brain extraction of multi-sequence MRI using artificial neural networks. arXiv preprint arXiv:1901.11341, 2019.

Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
########################

There are 1 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1 cases that I would like to predict

Traceback (most recent call last):
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/entry_point.py", line 53, in main
    hdbet_predict(args.input,args.output, predictor, keep_brain_mask=args.save_bet_mask,
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/hd_bet_prediction.py", line 69, in hdbet_predict
    predictor.predict_from_files(
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 268, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 361, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in preprocessing_iterator_fromfiles
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in <listcomp>
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
     ^^^^^^^^^^^^^^
RuntimeError: No CUDA GPUs are available

[ERROR] HD-BET failed for /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/459_3_493_t1+_thin_image.nii.gz with return code 1
[INFO] Running HD-BET for single file:
/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet -i '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/459_3_493_t2_thin_image.nii.gz' -o '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_output/459_3_493_t2_thin_image.nii.gz' -device cuda --disable_tta --save_bet_mask --no_bet_image

########################
If you are using hd-bet, please cite the following papers:

Isensee F, Schell M, Tursunova I, Brugnara G, Bonekamp D, Neuberger U, Wick A, Schlemmer HP, Heiland S, Wick W, Bendszus M, Maier-Hein KH, Kickingereder P. Automated brain extraction of multi-sequence MRI using artificial neural networks. arXiv preprint arXiv:1901.11341, 2019.

Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
########################

There are 1 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1 cases that I would like to predict

Traceback (most recent call last):
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/entry_point.py", line 53, in main
    hdbet_predict(args.input,args.output, predictor, keep_brain_mask=args.save_bet_mask,
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/hd_bet_prediction.py", line 69, in hdbet_predict
    predictor.predict_from_files(
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 268, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 361, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in preprocessing_iterator_fromfiles
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in <listcomp>
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
     ^^^^^^^^^^^^^^
RuntimeError: No CUDA GPUs are available

[ERROR] HD-BET failed for /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/459_3_493_t2_thin_image.nii.gz with return code 1
[INFO] Running HD-BET for single file:
/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet -i '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/483_3_1995_t2_thin_image_uint8.nii.gz' -o '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_output/483_3_1995_t2_thin_image_uint8.nii.gz' -device cuda --disable_tta --save_bet_mask --no_bet_image

########################
If you are using hd-bet, please cite the following papers:

Isensee F, Schell M, Tursunova I, Brugnara G, Bonekamp D, Neuberger U, Wick A, Schlemmer HP, Heiland S, Wick W, Bendszus M, Maier-Hein KH, Kickingereder P. Automated brain extraction of multi-sequence MRI using artificial neural networks. arXiv preprint arXiv:1901.11341, 2019.

Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
########################

There are 1 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1 cases that I would like to predict

Traceback (most recent call last):
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/entry_point.py", line 53, in main
    hdbet_predict(args.input,args.output, predictor, keep_brain_mask=args.save_bet_mask,
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/hd_bet_prediction.py", line 69, in hdbet_predict
    predictor.predict_from_files(
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 268, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 361, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in preprocessing_iterator_fromfiles
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in <listcomp>
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
     ^^^^^^^^^^^^^^
RuntimeError: No CUDA GPUs are available

[ERROR] HD-BET failed for /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/483_3_1995_t2_thin_image_uint8.nii.gz with return code 1
[INFO] Running HD-BET for single file:
/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet -i '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/486_2_631_t1+_thin_image.nii.gz' -o '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_output/486_2_631_t1+_thin_image.nii.gz' -device cuda --disable_tta --save_bet_mask --no_bet_image

########################
If you are using hd-bet, please cite the following papers:

Isensee F, Schell M, Tursunova I, Brugnara G, Bonekamp D, Neuberger U, Wick A, Schlemmer HP, Heiland S, Wick W, Bendszus M, Maier-Hein KH, Kickingereder P. Automated brain extraction of multi-sequence MRI using artificial neural networks. arXiv preprint arXiv:1901.11341, 2019.

Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
########################

There are 1 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1 cases that I would like to predict

Traceback (most recent call last):
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/entry_point.py", line 53, in main
    hdbet_predict(args.input,args.output, predictor, keep_brain_mask=args.save_bet_mask,
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/hd_bet_prediction.py", line 69, in hdbet_predict
    predictor.predict_from_files(
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 268, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 361, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in preprocessing_iterator_fromfiles
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in <listcomp>
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
     ^^^^^^^^^^^^^^
RuntimeError: No CUDA GPUs are available

[ERROR] HD-BET failed for /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/486_2_631_t1+_thin_image.nii.gz with return code 1
[INFO] Running HD-BET for single file:
/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet -i '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/50_3_283_t1+_thick_cor_image.nii.gz' -o '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_output/50_3_283_t1+_thick_cor_image.nii.gz' -device cuda --disable_tta --save_bet_mask --no_bet_image

########################
If you are using hd-bet, please cite the following papers:

Isensee F, Schell M, Tursunova I, Brugnara G, Bonekamp D, Neuberger U, Wick A, Schlemmer HP, Heiland S, Wick W, Bendszus M, Maier-Hein KH, Kickingereder P. Automated brain extraction of multi-sequence MRI using artificial neural networks. arXiv preprint arXiv:1901.11341, 2019.

Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
########################

There are 1 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1 cases that I would like to predict

Traceback (most recent call last):
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/entry_point.py", line 53, in main
    hdbet_predict(args.input,args.output, predictor, keep_brain_mask=args.save_bet_mask,
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/hd_bet_prediction.py", line 69, in hdbet_predict
    predictor.predict_from_files(
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 268, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 361, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in preprocessing_iterator_fromfiles
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in <listcomp>
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
     ^^^^^^^^^^^^^^
RuntimeError: No CUDA GPUs are available

[ERROR] HD-BET failed for /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/50_3_283_t1+_thick_cor_image.nii.gz with return code 1
[INFO] Running HD-BET for single file:
/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet -i '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/50_3_283_t2_thin_image.nii.gz' -o '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_output/50_3_283_t2_thin_image.nii.gz' -device cuda --disable_tta --save_bet_mask --no_bet_image

########################
If you are using hd-bet, please cite the following papers:

Isensee F, Schell M, Tursunova I, Brugnara G, Bonekamp D, Neuberger U, Wick A, Schlemmer HP, Heiland S, Wick W, Bendszus M, Maier-Hein KH, Kickingereder P. Automated brain extraction of multi-sequence MRI using artificial neural networks. arXiv preprint arXiv:1901.11341, 2019.

Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
########################

There are 1 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1 cases that I would like to predict

Traceback (most recent call last):
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/entry_point.py", line 53, in main
    hdbet_predict(args.input,args.output, predictor, keep_brain_mask=args.save_bet_mask,
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/hd_bet_prediction.py", line 69, in hdbet_predict
    predictor.predict_from_files(
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 268, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 361, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in preprocessing_iterator_fromfiles
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in <listcomp>
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
     ^^^^^^^^^^^^^^
RuntimeError: No CUDA GPUs are available

[ERROR] HD-BET failed for /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/50_3_283_t2_thin_image.nii.gz with return code 1
[INFO] Running HD-BET for single file:
/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet -i '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/50_3_283_t2_thin_image.nii.gz' -o '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_output/50_3_283_t2_thin_image.nii.gz' -device cuda --disable_tta --save_bet_mask --no_bet_image

########################
If you are using hd-bet, please cite the following papers:

Isensee F, Schell M, Tursunova I, Brugnara G, Bonekamp D, Neuberger U, Wick A, Schlemmer HP, Heiland S, Wick W, Bendszus M, Maier-Hein KH, Kickingereder P. Automated brain extraction of multi-sequence MRI using artificial neural networks. arXiv preprint arXiv:1901.11341, 2019.

Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
########################

There are 1 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1 cases that I would like to predict

Traceback (most recent call last):
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/entry_point.py", line 53, in main
    hdbet_predict(args.input,args.output, predictor, keep_brain_mask=args.save_bet_mask,
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/hd_bet_prediction.py", line 69, in hdbet_predict
    predictor.predict_from_files(
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 268, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 361, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in preprocessing_iterator_fromfiles
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in <listcomp>
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
     ^^^^^^^^^^^^^^
RuntimeError: No CUDA GPUs are available

[ERROR] HD-BET failed for /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/50_3_283_t2_thin_image.nii.gz with return code 1
[INFO] Running HD-BET for single file:
/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet -i '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/50_3_283_t2_thick_image.nii.gz' -o '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_output/50_3_283_t2_thick_image.nii.gz' -device cuda --disable_tta --save_bet_mask --no_bet_image

########################
If you are using hd-bet, please cite the following papers:

Isensee F, Schell M, Tursunova I, Brugnara G, Bonekamp D, Neuberger U, Wick A, Schlemmer HP, Heiland S, Wick W, Bendszus M, Maier-Hein KH, Kickingereder P. Automated brain extraction of multi-sequence MRI using artificial neural networks. arXiv preprint arXiv:1901.11341, 2019.

Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
########################

There are 1 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1 cases that I would like to predict

Traceback (most recent call last):
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/entry_point.py", line 53, in main
    hdbet_predict(args.input,args.output, predictor, keep_brain_mask=args.save_bet_mask,
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/hd_bet_prediction.py", line 69, in hdbet_predict
    predictor.predict_from_files(
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 268, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 361, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in preprocessing_iterator_fromfiles
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in <listcomp>
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
     ^^^^^^^^^^^^^^
RuntimeError: No CUDA GPUs are available

[ERROR] HD-BET failed for /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/50_3_283_t2_thick_image.nii.gz with return code 1
[INFO] Running HD-BET for single file:
/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet -i '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/50_3_283_t2_thin_image_uint8.nii.gz' -o '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_output/50_3_283_t2_thin_image_uint8.nii.gz' -device cuda --disable_tta --save_bet_mask --no_bet_image

########################
If you are using hd-bet, please cite the following papers:

Isensee F, Schell M, Tursunova I, Brugnara G, Bonekamp D, Neuberger U, Wick A, Schlemmer HP, Heiland S, Wick W, Bendszus M, Maier-Hein KH, Kickingereder P. Automated brain extraction of multi-sequence MRI using artificial neural networks. arXiv preprint arXiv:1901.11341, 2019.

Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
########################

There are 1 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1 cases that I would like to predict

Traceback (most recent call last):
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/entry_point.py", line 53, in main
    hdbet_predict(args.input,args.output, predictor, keep_brain_mask=args.save_bet_mask,
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/hd_bet_prediction.py", line 69, in hdbet_predict
    predictor.predict_from_files(
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 268, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 361, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in preprocessing_iterator_fromfiles
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in <listcomp>
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
     ^^^^^^^^^^^^^^
RuntimeError: No CUDA GPUs are available

[ERROR] HD-BET failed for /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/50_3_283_t2_thin_image_uint8.nii.gz with return code 1
[INFO] Running HD-BET for single file:
/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet -i '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/50_3_283_t1+_thick_ax_image.nii.gz' -o '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_output/50_3_283_t1+_thick_ax_image.nii.gz' -device cuda --disable_tta --save_bet_mask --no_bet_image

########################
If you are using hd-bet, please cite the following papers:

Isensee F, Schell M, Tursunova I, Brugnara G, Bonekamp D, Neuberger U, Wick A, Schlemmer HP, Heiland S, Wick W, Bendszus M, Maier-Hein KH, Kickingereder P. Automated brain extraction of multi-sequence MRI using artificial neural networks. arXiv preprint arXiv:1901.11341, 2019.

Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
########################

There are 1 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1 cases that I would like to predict

Traceback (most recent call last):
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/entry_point.py", line 53, in main
    hdbet_predict(args.input,args.output, predictor, keep_brain_mask=args.save_bet_mask,
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/hd_bet_prediction.py", line 69, in hdbet_predict
    predictor.predict_from_files(
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 268, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 361, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in preprocessing_iterator_fromfiles
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in <listcomp>
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
     ^^^^^^^^^^^^^^
RuntimeError: No CUDA GPUs are available

[ERROR] HD-BET failed for /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/50_3_283_t1+_thick_ax_image.nii.gz with return code 1
[INFO] Running HD-BET for single file:
/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet -i '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/50_3_283_t2_thick_image.nii.gz' -o '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_output/50_3_283_t2_thick_image.nii.gz' -device cuda --disable_tta --save_bet_mask --no_bet_image

########################
If you are using hd-bet, please cite the following papers:

Isensee F, Schell M, Tursunova I, Brugnara G, Bonekamp D, Neuberger U, Wick A, Schlemmer HP, Heiland S, Wick W, Bendszus M, Maier-Hein KH, Kickingereder P. Automated brain extraction of multi-sequence MRI using artificial neural networks. arXiv preprint arXiv:1901.11341, 2019.

Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
########################

There are 1 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1 cases that I would like to predict

Traceback (most recent call last):
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/entry_point.py", line 53, in main
    hdbet_predict(args.input,args.output, predictor, keep_brain_mask=args.save_bet_mask,
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/hd_bet_prediction.py", line 69, in hdbet_predict
    predictor.predict_from_files(
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 268, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 361, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in preprocessing_iterator_fromfiles
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in <listcomp>
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
     ^^^^^^^^^^^^^^
RuntimeError: No CUDA GPUs are available

[ERROR] HD-BET failed for /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/50_3_283_t2_thick_image.nii.gz with return code 1
[INFO] Running HD-BET for single file:
/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet -i '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/508_1_260_t1+_thin_image_uint8.nii.gz' -o '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_output/508_1_260_t1+_thin_image_uint8.nii.gz' -device cuda --disable_tta --save_bet_mask --no_bet_image

########################
If you are using hd-bet, please cite the following papers:

Isensee F, Schell M, Tursunova I, Brugnara G, Bonekamp D, Neuberger U, Wick A, Schlemmer HP, Heiland S, Wick W, Bendszus M, Maier-Hein KH, Kickingereder P. Automated brain extraction of multi-sequence MRI using artificial neural networks. arXiv preprint arXiv:1901.11341, 2019.

Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
########################

There are 1 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1 cases that I would like to predict

Traceback (most recent call last):
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/entry_point.py", line 53, in main
    hdbet_predict(args.input,args.output, predictor, keep_brain_mask=args.save_bet_mask,
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/hd_bet_prediction.py", line 69, in hdbet_predict
    predictor.predict_from_files(
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 268, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 361, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in preprocessing_iterator_fromfiles
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in <listcomp>
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
     ^^^^^^^^^^^^^^
RuntimeError: No CUDA GPUs are available

[ERROR] HD-BET failed for /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/508_1_260_t1+_thin_image_uint8.nii.gz with return code 1
[INFO] Running HD-BET for single file:
/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet -i '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/558_5_1775_t1+_thin_image_uint8.nii.gz' -o '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_output/558_5_1775_t1+_thin_image_uint8.nii.gz' -device cuda --disable_tta --save_bet_mask --no_bet_image

########################
If you are using hd-bet, please cite the following papers:

Isensee F, Schell M, Tursunova I, Brugnara G, Bonekamp D, Neuberger U, Wick A, Schlemmer HP, Heiland S, Wick W, Bendszus M, Maier-Hein KH, Kickingereder P. Automated brain extraction of multi-sequence MRI using artificial neural networks. arXiv preprint arXiv:1901.11341, 2019.

Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
########################

There are 1 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1 cases that I would like to predict

Traceback (most recent call last):
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/entry_point.py", line 53, in main
    hdbet_predict(args.input,args.output, predictor, keep_brain_mask=args.save_bet_mask,
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/hd_bet_prediction.py", line 69, in hdbet_predict
    predictor.predict_from_files(
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 268, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 361, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in preprocessing_iterator_fromfiles
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in <listcomp>
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
     ^^^^^^^^^^^^^^
RuntimeError: No CUDA GPUs are available

[ERROR] HD-BET failed for /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/558_5_1775_t1+_thin_image_uint8.nii.gz with return code 1
[INFO] Running HD-BET for single file:
/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet -i '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/562_2_550_t2_thick_image.nii.gz' -o '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_output/562_2_550_t2_thick_image.nii.gz' -device cuda --disable_tta --save_bet_mask --no_bet_image

########################
If you are using hd-bet, please cite the following papers:

Isensee F, Schell M, Tursunova I, Brugnara G, Bonekamp D, Neuberger U, Wick A, Schlemmer HP, Heiland S, Wick W, Bendszus M, Maier-Hein KH, Kickingereder P. Automated brain extraction of multi-sequence MRI using artificial neural networks. arXiv preprint arXiv:1901.11341, 2019.

Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
########################

There are 1 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1 cases that I would like to predict

Traceback (most recent call last):
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/entry_point.py", line 53, in main
    hdbet_predict(args.input,args.output, predictor, keep_brain_mask=args.save_bet_mask,
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/hd_bet_prediction.py", line 69, in hdbet_predict
    predictor.predict_from_files(
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 268, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 361, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in preprocessing_iterator_fromfiles
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in <listcomp>
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
     ^^^^^^^^^^^^^^
RuntimeError: No CUDA GPUs are available

[ERROR] HD-BET failed for /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/562_2_550_t2_thick_image.nii.gz with return code 1
[INFO] Running HD-BET for single file:
/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet -i '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/58_2_532_t2_thin_image.nii.gz' -o '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_output/58_2_532_t2_thin_image.nii.gz' -device cuda --disable_tta --save_bet_mask --no_bet_image

########################
If you are using hd-bet, please cite the following papers:

Isensee F, Schell M, Tursunova I, Brugnara G, Bonekamp D, Neuberger U, Wick A, Schlemmer HP, Heiland S, Wick W, Bendszus M, Maier-Hein KH, Kickingereder P. Automated brain extraction of multi-sequence MRI using artificial neural networks. arXiv preprint arXiv:1901.11341, 2019.

Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
########################

There are 1 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1 cases that I would like to predict

Process SpawnProcess-11:
Traceback (most recent call last):
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 58, in preprocess_fromfiles_save_to_queue
    raise e
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 31, in preprocess_fromfiles_save_to_queue
    data, seg, data_properties = preprocessor.run_case(list_of_lists[idx],
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/preprocessing/preprocessors/default_preprocessor.py", line 146, in run_case
    data, seg, data_properties = self.run_case_npy(data, seg, data_properties, plans_manager, configuration_manager,
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/preprocessing/preprocessors/default_preprocessor.py", line 83, in run_case_npy
    data = self._normalize(data, seg, configuration_manager,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/preprocessing/preprocessors/default_preprocessor.py", line 231, in _normalize
    scheme = configuration_manager.normalization_schemes[c]
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/entry_point.py", line 53, in main
    hdbet_predict(args.input,args.output, predictor, keep_brain_mask=args.save_bet_mask,
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/hd_bet_prediction.py", line 69, in hdbet_predict
    predictor.predict_from_files(
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 268, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 361, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 111, in preprocessing_iterator_fromfiles
    raise RuntimeError('Background workers died. Look for the error message further up! If there is '
RuntimeError: Background workers died. Look for the error message further up! If there is none then your RAM was full and the worker was killed by the OS. Use fewer workers or get more RAM in that case!

[ERROR] HD-BET failed for /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/58_2_532_t2_thin_image.nii.gz with return code 1
[INFO] Running HD-BET for single file:
/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet -i '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/603_2_1141_t2_thin_image_uint8.nii.gz' -o '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_output/603_2_1141_t2_thin_image_uint8.nii.gz' -device cuda --disable_tta --save_bet_mask --no_bet_image

########################
If you are using hd-bet, please cite the following papers:

Isensee F, Schell M, Tursunova I, Brugnara G, Bonekamp D, Neuberger U, Wick A, Schlemmer HP, Heiland S, Wick W, Bendszus M, Maier-Hein KH, Kickingereder P. Automated brain extraction of multi-sequence MRI using artificial neural networks. arXiv preprint arXiv:1901.11341, 2019.

Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
########################

There are 1 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1 cases that I would like to predict

Traceback (most recent call last):
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/entry_point.py", line 53, in main
    hdbet_predict(args.input,args.output, predictor, keep_brain_mask=args.save_bet_mask,
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/hd_bet_prediction.py", line 69, in hdbet_predict
    predictor.predict_from_files(
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 268, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 361, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in preprocessing_iterator_fromfiles
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in <listcomp>
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
     ^^^^^^^^^^^^^^
RuntimeError: No CUDA GPUs are available

[ERROR] HD-BET failed for /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/603_2_1141_t2_thin_image_uint8.nii.gz with return code 1
[INFO] Running HD-BET for single file:
/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet -i '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/651_1_1351_t1+_thin_image_uint8.nii.gz' -o '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_output/651_1_1351_t1+_thin_image_uint8.nii.gz' -device cuda --disable_tta --save_bet_mask --no_bet_image

########################
If you are using hd-bet, please cite the following papers:

Isensee F, Schell M, Tursunova I, Brugnara G, Bonekamp D, Neuberger U, Wick A, Schlemmer HP, Heiland S, Wick W, Bendszus M, Maier-Hein KH, Kickingereder P. Automated brain extraction of multi-sequence MRI using artificial neural networks. arXiv preprint arXiv:1901.11341, 2019.

Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
########################

There are 1 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1 cases that I would like to predict

Traceback (most recent call last):
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/entry_point.py", line 53, in main
    hdbet_predict(args.input,args.output, predictor, keep_brain_mask=args.save_bet_mask,
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/hd_bet_prediction.py", line 69, in hdbet_predict
    predictor.predict_from_files(
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 268, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 361, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in preprocessing_iterator_fromfiles
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in <listcomp>
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
     ^^^^^^^^^^^^^^
RuntimeError: No CUDA GPUs are available

[ERROR] HD-BET failed for /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/651_1_1351_t1+_thin_image_uint8.nii.gz with return code 1
[INFO] Running HD-BET for single file:
/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet -i '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/651_3_1653_t2_thin_image_uint8.nii.gz' -o '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_output/651_3_1653_t2_thin_image_uint8.nii.gz' -device cuda --disable_tta --save_bet_mask --no_bet_image

########################
If you are using hd-bet, please cite the following papers:

Isensee F, Schell M, Tursunova I, Brugnara G, Bonekamp D, Neuberger U, Wick A, Schlemmer HP, Heiland S, Wick W, Bendszus M, Maier-Hein KH, Kickingereder P. Automated brain extraction of multi-sequence MRI using artificial neural networks. arXiv preprint arXiv:1901.11341, 2019.

Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
########################

There are 1 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1 cases that I would like to predict

Traceback (most recent call last):
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/entry_point.py", line 53, in main
    hdbet_predict(args.input,args.output, predictor, keep_brain_mask=args.save_bet_mask,
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/hd_bet_prediction.py", line 69, in hdbet_predict
    predictor.predict_from_files(
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 268, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 361, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in preprocessing_iterator_fromfiles
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in <listcomp>
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
     ^^^^^^^^^^^^^^
RuntimeError: No CUDA GPUs are available

[ERROR] HD-BET failed for /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/651_3_1653_t2_thin_image_uint8.nii.gz with return code 1
[INFO] Running HD-BET for single file:
/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet -i '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/701_1_184_t1+_thin_image.nii.gz' -o '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_output/701_1_184_t1+_thin_image.nii.gz' -device cuda --disable_tta --save_bet_mask --no_bet_image

########################
If you are using hd-bet, please cite the following papers:

Isensee F, Schell M, Tursunova I, Brugnara G, Bonekamp D, Neuberger U, Wick A, Schlemmer HP, Heiland S, Wick W, Bendszus M, Maier-Hein KH, Kickingereder P. Automated brain extraction of multi-sequence MRI using artificial neural networks. arXiv preprint arXiv:1901.11341, 2019.

Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
########################

There are 1 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1 cases that I would like to predict

Traceback (most recent call last):
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/entry_point.py", line 53, in main
    hdbet_predict(args.input,args.output, predictor, keep_brain_mask=args.save_bet_mask,
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/hd_bet_prediction.py", line 69, in hdbet_predict
    predictor.predict_from_files(
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 268, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 361, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in preprocessing_iterator_fromfiles
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in <listcomp>
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
     ^^^^^^^^^^^^^^
RuntimeError: No CUDA GPUs are available

[ERROR] HD-BET failed for /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/701_1_184_t1+_thin_image.nii.gz with return code 1
[INFO] Running HD-BET for single file:
/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet -i '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/701_1_184_t2_thin_image.nii.gz' -o '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_output/701_1_184_t2_thin_image.nii.gz' -device cuda --disable_tta --save_bet_mask --no_bet_image

########################
If you are using hd-bet, please cite the following papers:

Isensee F, Schell M, Tursunova I, Brugnara G, Bonekamp D, Neuberger U, Wick A, Schlemmer HP, Heiland S, Wick W, Bendszus M, Maier-Hein KH, Kickingereder P. Automated brain extraction of multi-sequence MRI using artificial neural networks. arXiv preprint arXiv:1901.11341, 2019.

Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
########################

There are 1 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1 cases that I would like to predict

Traceback (most recent call last):
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/entry_point.py", line 53, in main
    hdbet_predict(args.input,args.output, predictor, keep_brain_mask=args.save_bet_mask,
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/hd_bet_prediction.py", line 69, in hdbet_predict
    predictor.predict_from_files(
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 268, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 361, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in preprocessing_iterator_fromfiles
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in <listcomp>
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
     ^^^^^^^^^^^^^^
RuntimeError: No CUDA GPUs are available

[ERROR] HD-BET failed for /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/701_1_184_t2_thin_image.nii.gz with return code 1
[INFO] Running HD-BET for single file:
/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet -i '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/701_2_240_t2_thin_image_uint8.nii.gz' -o '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_output/701_2_240_t2_thin_image_uint8.nii.gz' -device cuda --disable_tta --save_bet_mask --no_bet_image

########################
If you are using hd-bet, please cite the following papers:

Isensee F, Schell M, Tursunova I, Brugnara G, Bonekamp D, Neuberger U, Wick A, Schlemmer HP, Heiland S, Wick W, Bendszus M, Maier-Hein KH, Kickingereder P. Automated brain extraction of multi-sequence MRI using artificial neural networks. arXiv preprint arXiv:1901.11341, 2019.

Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
########################

There are 1 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1 cases that I would like to predict

Traceback (most recent call last):
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/entry_point.py", line 53, in main
    hdbet_predict(args.input,args.output, predictor, keep_brain_mask=args.save_bet_mask,
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/hd_bet_prediction.py", line 69, in hdbet_predict
    predictor.predict_from_files(
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 268, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 361, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in preprocessing_iterator_fromfiles
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in <listcomp>
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
     ^^^^^^^^^^^^^^
RuntimeError: No CUDA GPUs are available

[ERROR] HD-BET failed for /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/701_2_240_t2_thin_image_uint8.nii.gz with return code 1
[INFO] Running HD-BET for single file:
/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet -i '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/735_1_357_t2_thin_image_uint8.nii.gz' -o '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_output/735_1_357_t2_thin_image_uint8.nii.gz' -device cuda --disable_tta --save_bet_mask --no_bet_image

########################
If you are using hd-bet, please cite the following papers:

Isensee F, Schell M, Tursunova I, Brugnara G, Bonekamp D, Neuberger U, Wick A, Schlemmer HP, Heiland S, Wick W, Bendszus M, Maier-Hein KH, Kickingereder P. Automated brain extraction of multi-sequence MRI using artificial neural networks. arXiv preprint arXiv:1901.11341, 2019.

Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
########################

There are 1 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1 cases that I would like to predict

Traceback (most recent call last):
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/entry_point.py", line 53, in main
    hdbet_predict(args.input,args.output, predictor, keep_brain_mask=args.save_bet_mask,
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/hd_bet_prediction.py", line 69, in hdbet_predict
    predictor.predict_from_files(
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 268, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 361, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in preprocessing_iterator_fromfiles
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in <listcomp>
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
     ^^^^^^^^^^^^^^
RuntimeError: No CUDA GPUs are available

[ERROR] HD-BET failed for /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/735_1_357_t2_thin_image_uint8.nii.gz with return code 1
[INFO] Running HD-BET for single file:
/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet -i '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/735_2_721_t2_thin_image_uint8.nii.gz' -o '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_output/735_2_721_t2_thin_image_uint8.nii.gz' -device cuda --disable_tta --save_bet_mask --no_bet_image

########################
If you are using hd-bet, please cite the following papers:

Isensee F, Schell M, Tursunova I, Brugnara G, Bonekamp D, Neuberger U, Wick A, Schlemmer HP, Heiland S, Wick W, Bendszus M, Maier-Hein KH, Kickingereder P. Automated brain extraction of multi-sequence MRI using artificial neural networks. arXiv preprint arXiv:1901.11341, 2019.

Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
########################

There are 1 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1 cases that I would like to predict

Traceback (most recent call last):
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/entry_point.py", line 53, in main
    hdbet_predict(args.input,args.output, predictor, keep_brain_mask=args.save_bet_mask,
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/hd_bet_prediction.py", line 69, in hdbet_predict
    predictor.predict_from_files(
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 268, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 361, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in preprocessing_iterator_fromfiles
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in <listcomp>
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
     ^^^^^^^^^^^^^^
RuntimeError: No CUDA GPUs are available

[ERROR] HD-BET failed for /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/735_2_721_t2_thin_image_uint8.nii.gz with return code 1
[INFO] Running HD-BET for single file:
/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet -i '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/741_1_221_t2_thin_image_uint8.nii.gz' -o '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_output/741_1_221_t2_thin_image_uint8.nii.gz' -device cuda --disable_tta --save_bet_mask --no_bet_image

########################
If you are using hd-bet, please cite the following papers:

Isensee F, Schell M, Tursunova I, Brugnara G, Bonekamp D, Neuberger U, Wick A, Schlemmer HP, Heiland S, Wick W, Bendszus M, Maier-Hein KH, Kickingereder P. Automated brain extraction of multi-sequence MRI using artificial neural networks. arXiv preprint arXiv:1901.11341, 2019.

Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
########################

There are 1 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1 cases that I would like to predict

Traceback (most recent call last):
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/entry_point.py", line 53, in main
    hdbet_predict(args.input,args.output, predictor, keep_brain_mask=args.save_bet_mask,
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/hd_bet_prediction.py", line 69, in hdbet_predict
    predictor.predict_from_files(
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 268, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 361, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in preprocessing_iterator_fromfiles
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in <listcomp>
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
     ^^^^^^^^^^^^^^
RuntimeError: No CUDA GPUs are available

[ERROR] HD-BET failed for /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/741_1_221_t2_thin_image_uint8.nii.gz with return code 1
[INFO] Running HD-BET for single file:
/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet -i '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/747_3_565_t2_thin_image_uint8.nii.gz' -o '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_output/747_3_565_t2_thin_image_uint8.nii.gz' -device cuda --disable_tta --save_bet_mask --no_bet_image

########################
If you are using hd-bet, please cite the following papers:

Isensee F, Schell M, Tursunova I, Brugnara G, Bonekamp D, Neuberger U, Wick A, Schlemmer HP, Heiland S, Wick W, Bendszus M, Maier-Hein KH, Kickingereder P. Automated brain extraction of multi-sequence MRI using artificial neural networks. arXiv preprint arXiv:1901.11341, 2019.

Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
########################

There are 1 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1 cases that I would like to predict

Traceback (most recent call last):
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/entry_point.py", line 53, in main
    hdbet_predict(args.input,args.output, predictor, keep_brain_mask=args.save_bet_mask,
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/hd_bet_prediction.py", line 69, in hdbet_predict
    predictor.predict_from_files(
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 268, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 361, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in preprocessing_iterator_fromfiles
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in <listcomp>
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
     ^^^^^^^^^^^^^^
RuntimeError: No CUDA GPUs are available

[ERROR] HD-BET failed for /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/747_3_565_t2_thin_image_uint8.nii.gz with return code 1
[INFO] Running HD-BET for single file:
/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet -i '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/788_0_0_t2_thick_image.nii.gz' -o '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_output/788_0_0_t2_thick_image.nii.gz' -device cuda --disable_tta --save_bet_mask --no_bet_image

########################
If you are using hd-bet, please cite the following papers:

Isensee F, Schell M, Tursunova I, Brugnara G, Bonekamp D, Neuberger U, Wick A, Schlemmer HP, Heiland S, Wick W, Bendszus M, Maier-Hein KH, Kickingereder P. Automated brain extraction of multi-sequence MRI using artificial neural networks. arXiv preprint arXiv:1901.11341, 2019.

Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
########################

There are 1 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1 cases that I would like to predict

Traceback (most recent call last):
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/entry_point.py", line 53, in main
    hdbet_predict(args.input,args.output, predictor, keep_brain_mask=args.save_bet_mask,
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/hd_bet_prediction.py", line 69, in hdbet_predict
    predictor.predict_from_files(
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 268, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 361, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in preprocessing_iterator_fromfiles
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in <listcomp>
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
     ^^^^^^^^^^^^^^
RuntimeError: No CUDA GPUs are available

[ERROR] HD-BET failed for /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/788_0_0_t2_thick_image.nii.gz with return code 1
[INFO] Running HD-BET for single file:
/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet -i '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/84_1_851_t2_thin_image.nii.gz' -o '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_output/84_1_851_t2_thin_image.nii.gz' -device cuda --disable_tta --save_bet_mask --no_bet_image

########################
If you are using hd-bet, please cite the following papers:

Isensee F, Schell M, Tursunova I, Brugnara G, Bonekamp D, Neuberger U, Wick A, Schlemmer HP, Heiland S, Wick W, Bendszus M, Maier-Hein KH, Kickingereder P. Automated brain extraction of multi-sequence MRI using artificial neural networks. arXiv preprint arXiv:1901.11341, 2019.

Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
########################

There are 1 cases in the source folder
I am processing 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1 cases that I would like to predict

Traceback (most recent call last):
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/bin/hd-bet", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/entry_point.py", line 53, in main
    hdbet_predict(args.input,args.output, predictor, keep_brain_mask=args.save_bet_mask,
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/HD_BET/hd_bet_prediction.py", line 69, in hdbet_predict
    predictor.predict_from_files(
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 268, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 361, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in preprocessing_iterator_fromfiles
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
  File "/home/mnn7bx/.conda/envs/nguyen_ants_env/lib/python3.11/site-packages/nnunetv2/inference/data_iterators.py", line 117, in <listcomp>
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
     ^^^^^^^^^^^^^^
RuntimeError: No CUDA GPUs are available

[ERROR] HD-BET failed for /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input/84_1_851_t2_thin_image.nii.gz with return code 1
[WARN] Per-file retries had 57 failures. See logs above.
[INFO] Removed temp folder: /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input
[SUMMARY] processed=57, skipped=1736
[WARN] Could not remove /sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input: [Errno 2] No such file or directory: '/sfs/ceph/standard/gam_ai_group/600 qc1 scans/studies_20260130105647718474/hd_input'

0

In [22]:
# === Entropy, voxel volume, file size, and segmentation volume computation ===
# For every row in meta_df, derive voxel dimensions (from row columns or file headers) and compute:
#   - voxel_volume = product of (dx, dy, dz) when available
#   - voxel_unit = unit of measure for voxel dimensions (e.g., 'mm', 'um', 'pixels')
#   - volume_unit = unit of measure for volumes (e.g., 'mm³', 'um³', 'pixels³')
#   - entropy (Shannon, base 2) over intensities using histogram (approximate if large).
#   - file_size_mb = file size in megabytes
#   - coregistered_image = path to coregistered image (replaces 'raw_studies' with COREGISTERED_FOLDER)
#   - coregistered_segmentation = path to coregistered segmentation (replaces 'raw_studies' with COREGISTERED_FOLDER)
#   - segmentation_volume = volume of segmentation (non-zero voxels * voxel_volume) in cubic units
#   - antspy_spacing = spacing tuple extracted directly from ANTsPy image
# Results added to meta_df and cached in meta_df.csv for reuse.

# Optional runtime toggles: set to False if you want exact (but slower) entropy
APPROXIMATE_ENTROPY = True
MAX_ENTROPY_SAMPLES = int(1_000_000)  # max number of voxels to use for histogram when approximating
BINS = 256  # histogram bins for entropy calculation
CSV_PATH = 'meta_df_entropy.csv'
COREGISTERED_FOLDER = 'df_coregistered_02_09_2026_V6.6/raw_studies'  # Folder name to replace 'raw_studies' with
from tqdm import tqdm
tqdm.pandas()

# Try to import ANTsPy
try:
    import ants
    ANTS_AVAILABLE = True
except ImportError:
    ANTS_AVAILABLE = False
    print("Warning: ANTsPy not available. antspy_spacing column will contain NaN values.")

def _get_voxel_dims_from_row(row):
    """
    Extract voxel dimensions and unit from row.
    Returns: (dims_tuple, unit_string) or (None, None)
    """
    key_sets = [
        ('voxel_x','voxel_y','voxel_z'),
        ('spacing_x','spacing_y','spacing_z'),
        ('vx','vy','vz'),
        ('voxel_size_x','voxel_size_y','voxel_size_z'),
        ('voxel_size',),
        ('spacing',),
        ('voxel_dims',),
        ('pixel_size',),
    ]
    
    # Try to find unit information
    unit = None
    for unit_col in ['voxel_unit', 'spacing_unit', 'unit', 'voxel_units', 'spacing_units']:
        if unit_col in row.index and pd.notna(row[unit_col]):
            unit = str(row[unit_col]).strip()
            break
    
    for keys in key_sets:
        if all(k in row.index for k in keys):
            vals = row[list(keys)]
            if len(keys) == 1:
                v = vals.iloc[0]
                if v is None:
                    continue
                if hasattr(v, '__iter__') and not isinstance(v, str):
                    arr = np.asarray(v, dtype=float)
                    if arr.size >= 3:
                        return tuple(arr[:3].astype(float)), unit
                    elif arr.size == 2:
                        return (float(arr[0]), float(arr[1]), 1.0), unit
                    else:
                        continue
            else:
                try:
                    return tuple(map(float, vals.values[:3])), unit
                except Exception:
                    continue
    return None, None

def _get_voxel_dims_from_file(path):
    """
    Extract voxel dimensions and unit from file headers.
    Returns: (dims_tuple, unit_string) or (None, None)
    """
    ext = os.path.splitext(path)[1].lower()
    if ext in ('.nii', '.nii.gz') and nib is not None:
        try:
            img = nib.load(path)
            zooms = img.header.get_zooms()
            # Try to get unit from NIfTI header
            unit = 'mm'  # Default for NIfTI
            try:
                # NIfTI xyzt_units field
                xyzt_units = img.header.get_xyzt_units()
                if xyzt_units[0]:
                    unit = xyzt_units[0]
            except Exception:
                pass
            
            if len(zooms) >= 3:
                return tuple(map(float, zooms[:3])), unit
            elif len(zooms) == 2:
                return (float(zooms[0]), float(zooms[1]), 1.0), unit
        except Exception:
            pass
    if tifffile is not None and ext in ('.tif', '.tiff'):
        try:
            with tifffile.TiffFile(path) as tif:
                unit = 'pixels'  # Default for TIFF
                ij_metadata = tif.imagej_metadata
                if ij_metadata:
                    # Try to get unit from ImageJ metadata
                    if 'unit' in ij_metadata:
                        unit = str(ij_metadata['unit'])
                    spacing = ij_metadata.get('spacing')
                    if spacing:
                        try:
                            sp = float(spacing)
                            return (1.0, 1.0, sp), unit
                        except Exception:
                            pass
                for page in tif.pages:
                    tags = page.tags
                    if 'XResolution' in tags and 'YResolution' in tags:
                        try:
                            xr = tags['XResolution'].value
                            yr = tags['YResolution'].value
                            def rational_to_float(r):
                                if isinstance(r, tuple) and len(r) == 2:
                                    return r[0] / r[1] if r[1] != 0 else 1.0
                                return float(r)
                            # Check for ResolutionUnit tag
                            if 'ResolutionUnit' in tags:
                                res_unit = tags['ResolutionUnit'].value
                                # 1 = None, 2 = inches, 3 = centimeters
                                if res_unit == 2:
                                    unit = 'inches'
                                elif res_unit == 3:
                                    unit = 'cm'
                            return (rational_to_float(xr), rational_to_float(yr), 1.0), unit
                        except Exception:
                            pass
        except Exception:
            pass
    if sitk is not None:
        try:
            img = sitk.ReadImage(path)
            spacing = img.GetSpacing()
            unit = 'mm'  # Default for medical images
            if len(spacing) >= 3:
                return tuple(map(float, spacing[:3])), unit
            elif len(spacing) == 2:
                return (float(spacing[0]), float(spacing[1]), 1.0), unit
        except Exception:
            pass
    return None, None

def _get_antspy_spacing(path):
    """
    Extract spacing from image using ANTsPy.
    Returns: tuple of spacing values or None if error/not available
    """
    if not ANTS_AVAILABLE:
        return None
    
    if not isinstance(path, str) or not os.path.exists(path):
        return None
    
    try:
        # Read image with ANTsPy
        img = ants.image_read(path)
        # Get spacing - returns tuple
        spacing = img.spacing
        return tuple(float(s) for s in spacing)
    except Exception:
        return None

def _compute_entropy_from_array(arr, bins=BINS, approximate=APPROXIMATE_ENTROPY, max_samples=MAX_ENTROPY_SAMPLES):
    try:
        flat = arr.ravel()
        n = flat.size
        if n == 0:
            return 0.0
        # Subsample deterministically to avoid large memory/cpu cost
        if approximate and n > max_samples:
            step = int(np.ceil(n / max_samples))
            sample = flat[::step]
        else:
            sample = flat
        # handle NaNs by masking
        if np.issubdtype(sample.dtype, np.floating):
            # ignore NaNs in float data
            mask = ~np.isnan(sample)
            if not np.any(mask):
                return 0.0
            sample = sample[mask]
            mn = float(np.min(sample))
            mx = float(np.max(sample))
            if np.isclose(mx, mn):
                return 0.0
            counts, _ = np.histogram(sample, bins=bins, range=(mn, mx))
        else:
            try:
                mn = int(sample.min())
                mx = int(sample.max())
            except Exception:
                mn = int(np.nanmin(sample))
                mx = int(np.nanmax(sample))
            if np.isclose(mx, mn):
                return 0.0
            if mx - mn + 1 <= bins:
                counts, _ = np.histogram(sample, bins=(mx - mn + 1), range=(mn - 0.5, mx + 0.5))
            else:
                counts, _ = np.histogram(sample, bins=bins, range=(mn, mx))
        probs = counts.astype(np.float64)
        s = probs.sum()
        if s == 0:
            return 0.0
        probs /= s
        nz = probs > 0
        entropy = -np.sum(probs[nz] * np.log2(probs[nz]))
        return float(entropy)
    except Exception:
        return float('nan')

def _read_array(path):
    ext = os.path.splitext(path)[1].lower()
    if tifffile is not None and ext in ('.tif', '.tiff'):
        try:
            with tifffile.TiffFile(path) as tif:
                return tif.asarray(memmap=True)
        except Exception:
            try:
                return tifffile.imread(path)
            except Exception:
                pass
    if nib is not None and ext in ('.nii', '.nii.gz'):
        try:
            img = nib.load(path)
            return img.get_fdata(dtype=np.float32)
        except Exception:
            pass
    if sitk is not None:
        try:
            img = sitk.ReadImage(path)
            arr = sitk.GetArrayFromImage(img)
            return arr
        except Exception:
            pass
    if ext == '.npy':
        return np.load(path, mmap_mode='r')
    raise RuntimeError(f"Could not read image {path}; unsupported format or missing libraries.")

def _get_file_size_mb(path):
    """Get file size in megabytes"""
    try:
        if os.path.exists(path):
            size_bytes = os.path.getsize(path)
            return size_bytes / (1024 * 1024)  # Convert to MB
        return np.nan
    except Exception:
        return np.nan

def _get_volume_unit(voxel_unit):
    """
    Convert linear unit to cubic unit.
    E.g., 'mm' -> 'mm³', 'um' -> 'um³', 'pixels' -> 'pixels³'
    """
    if not voxel_unit or pd.isna(voxel_unit):
        return None
    
    unit_str = str(voxel_unit).strip()
    
    # Handle common variations
    unit_map = {
        'mm': 'mm³',
        'millimeter': 'mm³',
        'millimeters': 'mm³',
        'um': 'um³',
        'μm': 'μm³',
        'micrometer': 'um³',
        'micrometers': 'um³',
        'nm': 'nm³',
        'nanometer': 'nm³',
        'nanometers': 'nm³',
        'cm': 'cm³',
        'centimeter': 'cm³',
        'centimeters': 'cm³',
        'm': 'm³',
        'meter': 'm³',
        'meters': 'm³',
        'pixel': 'pixels³',
        'pixels': 'pixels³',
        'px': 'px³',
        'inch': 'in³',
        'inches': 'in³',
        'in': 'in³',
    }
    
    # Check if unit is in our map
    unit_lower = unit_str.lower()
    if unit_lower in unit_map:
        return unit_map[unit_lower]
    
    # If not in map, just add ³ to the end
    return f"{unit_str}³"

def _compute_segmentation_volume(seg_path, voxel_volume):
    """
    Compute the volume of a segmentation by counting non-zero voxels
    and multiplying by voxel_volume.
    
    Args:
        seg_path: Path to segmentation file
        voxel_volume: Volume of a single voxel (product of spacing dimensions)
        
    Returns:
        Volume in cubic units (same as voxel_volume units), or NaN if error
    """
    try:
        if not isinstance(seg_path, str) or not os.path.exists(seg_path):
            return np.nan
        
        if np.isnan(voxel_volume):
            return np.nan
            
        # Read the segmentation array
        seg_array = _read_array(seg_path)
        
        # Count non-zero voxels
        non_zero_count = np.count_nonzero(seg_array)
        
        # Calculate volume
        volume = non_zero_count * voxel_volume
        
        return float(volume)
        
    except Exception as e:
        return np.nan

def _find_coregistered_files(row, coregistered_folder='df_coregistered2_05_2026_V6.4.1/raw_studies'):
    """
    Finds coregistered files by replacing 'raw_studies' in the image_path and segmentation_path
    with the specified coregistered folder name.
    Returns (coregistered_image_path, coregistered_segmentation_path) tuple.
    
    Args:
        row: DataFrame row containing 'image path' and 'segmentation path' columns
        coregistered_folder: Folder name to replace 'raw_studies' with
    """
    try:
        coreg_image = np.nan
        coreg_seg = np.nan
        
        # Get image path from row
        for col in ['image path', 'Image Path', 'image_path']:
            if col in row.index and pd.notna(row[col]):
                img_path = str(row[col])
                print(f"Original image path: {img_path}")
                
                # Replace 'raw_studies' with coregistered folder name (case-insensitive)
                if 'raw_studies' in img_path.lower():
                    # Find the actual case-sensitive occurrence
                    idx = img_path.lower().find('raw_studies')
                    coreg_image = img_path[:idx] + coregistered_folder + img_path[idx+len('raw_studies'):]
                    coreg_image = coreg_image.replace('.nii.gz','_coregistered.nii.gz')
                    print(f"Checking coregistered image path: {coreg_image}")
                    
                    # Check if file exists
                    if not os.path.exists(coreg_image):
                        print(f"  → File NOT found")
                        coreg_image = np.nan
                    else:
                        print(f"  → File FOUND")
                        pass  # FIXED: Changed 'break' to 'pass'
                break
        
        # Get segmentation path from row
        for col in ['segmentation path', 'Segmentation Path', 'segmentation_path']:
            if col in row.index and pd.notna(row[col]):
                seg_path = str(row[col])
                print(f"Original segmentation path: {seg_path}")
                
                # Replace 'raw_studies' with coregistered folder name (case-insensitive)
                if 'raw_studies' in seg_path.lower():
                    # Find the actual case-sensitive occurrence
                    idx = seg_path.lower().find('raw_studies')
                    coreg_seg = seg_path[:idx] + coregistered_folder + seg_path[idx+len('raw_studies'):]
                    coreg_seg = coreg_seg.replace('.nii.gz','_coregistered.nii.gz')
                    #print(f"Checking coregistered segmentation path: {coreg_seg}")
                    
                    # Check if file exists
                    if not os.path.exists(coreg_seg):
                        #print(f"  → File NOT found")
                        coreg_seg = np.nan
                    else:
                        #print(f"  → File FOUND")
                        pass  # This was already correct
                    break  # FIXED: Moved 'break' to correct indentation level
        
        print(f"Returning: ({coreg_image}, {coreg_seg})\n")
        return coreg_image, coreg_seg
        
    except Exception as e:
        print(f"Exception occurred: {e}\n")
        return np.nan, np.nan

def _process_path(path, row):
    if not isinstance(path, str) or not os.path.exists(path):
        return pd.Series({
            'entropy': np.nan, 
            'voxel_volume': np.nan,
            'voxel_unit': None,
            'volume_unit': None,
            'file_size_mb': np.nan,
            'coregistered_image': np.nan,
            'coregistered_segmentation': np.nan,
            'segmentation_volume': np.nan,
            'antspy_spacing': None
        })
    
    # Get file size
    file_size_mb = _get_file_size_mb(path)
    
    # Find coregistered files (both image and segmentation)
    coreg_image, coreg_seg = _find_coregistered_files(row, COREGISTERED_FOLDER)
    
    # Get ANTsPy spacing
    antspy_spacing = _get_antspy_spacing(path)
    
    # Get voxel dimensions and unit
    dims, voxel_unit = _get_voxel_dims_from_row(row)
    if dims is None:
        dims, voxel_unit = _get_voxel_dims_from_file(path)
    
    voxel_volume = np.nan
    volume_unit = None
    
    if dims is not None:
        try:
            voxel_volume = float(np.prod(dims))
            volume_unit = _get_volume_unit(voxel_unit)
        except Exception:
            voxel_volume = np.nan
    
    # Compute entropy for the image
    try:
        arr = _read_array(path)
        entropy = _compute_entropy_from_array(arr)
    except Exception:
        entropy = float('nan')
    
    # Compute segmentation volume using the existing 'segmentation path' column
    segmentation_volume = np.nan
    for seg_col in ['segmentation path', 'Segmentation Path', 'segmentation_path']:
        if seg_col in row.index and pd.notna(row[seg_col]):
            seg_path = row[seg_col]
            segmentation_volume = _compute_segmentation_volume(seg_path, voxel_volume)
            break
    
    return pd.Series({
        'entropy': entropy, 
        'voxel_volume': voxel_volume,
        'voxel_unit': voxel_unit,
        'volume_unit': volume_unit,
        'file_size_mb': file_size_mb,
        'coregistered_image': coreg_image,
        'coregistered_segmentation': coreg_seg,
        'segmentation_volume': segmentation_volume,
        'antspy_spacing': antspy_spacing
    })

def _run_compute_and_save(meta):
    _meta = meta.copy()
    results = _meta.progress_apply(lambda r: _process_path(r['image path'], r), axis=1)
    _meta[['entropy', 'voxel_volume', 'voxel_unit', 'volume_unit', 'file_size_mb', 'coregistered_image', 'coregistered_segmentation', 'segmentation_volume', 'antspy_spacing']] = results
    _meta.to_csv(CSV_PATH, index=False)
    print(f"Saved results to {CSV_PATH}")
    return _meta

# If meta_df_entropy.csv exists, load it and skip computation. Otherwise compute and save.
if os.path.exists(CSV_PATH):
    try:
        meta_df = pd.read_csv(CSV_PATH)
        print(f"Loaded existing {CSV_PATH}; skipping computation.")
    except Exception as e:
        if 'meta_df' not in globals():
            raise RuntimeError(f"Failed to read {CSV_PATH}: {e}\nNo in-memory meta_df available.")
        print(f"Error reading {CSV_PATH}: {e}. Computing from in-memory meta_df...")
        meta_df = _run_compute_and_save(meta_df)
else:
    if 'meta_df' not in globals():
        raise RuntimeError("meta_df not found in notebook and no meta_df_entropy.csv present.")
    print(f"Computing metrics for {len(meta_df)} rows...")
    meta_df = _run_compute_and_save(meta_df)

Computing metrics for 1793 rows...

  0%|          | 0/1793 [00:00<?, ?it/s]

Original image path: ./raw_studies/t2_thick/126_0_0/126_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/126_0_0/126_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/126_0_0/126_0_0_t2_thick_RVS _uvauser2.nii.gz
Returning: (nan, nan)

  0%|          | 2/1793 [00:00<09:51,  3.03it/s]

Original image path: ./raw_studies/t1+_thick_cor/126_0_0/126_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/126_0_0/126_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/126_0_0/126_0_0_t1+_thick_cor_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/126_0_0/126_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/126_0_0/126_0_0_t1+_thick_cor_RVS _uvauser2_coregistered.nii.gz)

  0%|          | 3/1793 [00:00<09:37,  3.10it/s]

Original image path: ./raw_studies/t1+_thick_ax/126_0_0/126_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/126_0_0/126_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/126_0_0/126_0_0_t1+_thick_ax_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/126_0_0/126_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/126_0_0/126_0_0_t1+_thick_ax_RVS _uvauser2_coregistered.nii.gz)

  0%|          | 4/1793 [00:01<09:07,  3.26it/s]

Original image path: ./raw_studies/t1+_thick_ax/126_1_312/126_1_312_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/126_1_312/126_1_312_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/126_1_312/126_1_312_t1+_thick_ax_VS2_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/126_1_312/126_1_312_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/126_1_312/126_1_312_t1+_thick_ax_VS2_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/126_1_312/126_1_312_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/126_1_312/126_1_312_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/126_1_312/126_1_312_t1+_thick_cor_VS2_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/126_1_312/126_1_312_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/126_1_312/126_1_312_t1+_thick_cor_VS2_uvauser1_coregistered.nii.gz)

  0%|          | 6/1793 [00:01<06:35,  4.52it/s]

Original image path: ./raw_studies/t2_thin/126_1_312/126_1_312_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/126_1_312/126_1_312_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/126_1_312/126_1_312_t2_thin_VS_uvauser1-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/126_1_312/126_1_312_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/126_1_312/126_1_312_t2_thin_VS_uvauser1-copy_coregistered.nii.gz)

  0%|          | 8/1793 [00:03<12:45,  2.33it/s]

Original image path: ./raw_studies/t1+_thick_cor/126_1_312/126_1_312_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/126_1_312/126_1_312_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/126_1_312/126_1_312_t1+_thick_cor_VS2_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/126_1_312/126_1_312_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/126_1_312/126_1_312_t1+_thick_cor_VS2_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/126_2_582/126_2_582_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/126_2_582/126_2_582_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/126_2_582/126_2_582_t1+_thick_cor_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/126_2_582/126_2_582_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/126_2_582/126_2_582_t1+_thick_cor_RVS _uvauser2_coregistered.nii.gz)

  1%|          | 9/1793 [00:03<10:24,  2.86it/s]

Original image path: ./raw_studies/t2_thin/126_2_582/126_2_582_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/126_2_582/126_2_582_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/126_2_582/126_2_582_t2_thin_RVS _uvauser2-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/126_2_582/126_2_582_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/126_2_582/126_2_582_t2_thin_RVS _uvauser2-copy_coregistered.nii.gz)

  1%|          | 11/1793 [00:04<13:10,  2.25it/s]

Original image path: ./raw_studies/t1+_thick_ax/126_2_582/126_2_582_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/126_2_582/126_2_582_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/126_2_582/126_2_582_t1+_thick_ax_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/126_2_582/126_2_582_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/126_2_582/126_2_582_t1+_thick_ax_RVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/126_3_921/126_3_921_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/126_3_921/126_3_921_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/126_3_921/126_3_921_t1+_thick_ax_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/126_3_921/126_3_921_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/126_3_921/126_3_921_t1+_thick_ax_RVS _uvauser2_coregistered.nii.gz)

  1%|          | 13/1793 [00:04<08:09,  3.64it/s]

Original image path: ./raw_studies/t1+_thick_cor/126_3_921/126_3_921_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/126_3_921/126_3_921_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/126_3_921/126_3_921_t1+_thick_cor_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/126_3_921/126_3_921_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/126_3_921/126_3_921_t1+_thick_cor_RVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/126_3_921/126_3_921_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/126_3_921/126_3_921_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/126_3_921/126_3_921_t2_thin_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/126_3_921/126_3_921_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/126_3_921/126_3_921_t2_thin_RVS _uvauser2_coregistered.nii.gz)

  1%|          | 14/1793 [00:05<13:57,  2.12it/s]

Original image path: ./raw_studies/t2_thin/126_4_1231/126_4_1231_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/126_4_1231/126_4_1231_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/126_4_1231/126_4_1231_t2_thin_CO_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/126_4_1231/126_4_1231_t2_thin_image_coregistered.nii.gz, nan)

  1%|          | 16/1793 [00:07<16:53,  1.75it/s]

Original image path: ./raw_studies/t1+_thick_ax/126_4_1231/126_4_1231_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/126_4_1231/126_4_1231_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/126_4_1231/126_4_1231_t1+_thick_ax_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/126_4_1231/126_4_1231_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/126_4_1231/126_4_1231_t1+_thick_ax_tumorcore _uvauser3_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/126_4_1231/126_4_1231_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/126_4_1231/126_4_1231_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/126_4_1231/126_4_1231_t1+_thick_cor_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/126_4_1231/126_4_1231_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/126_4_1231/126_4_1231_t1+_thick_cor_tumorcore _uvauser3_coregistered.nii.gz)

  1%|          | 18/1793 [00:07<10:52,  2.72it/s]

Original image path: ./raw_studies/t1+_thick_ax/126_5_1607/126_5_1607_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/126_5_1607/126_5_1607_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/126_5_1607/126_5_1607_t1+_thick_ax_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/126_5_1607/126_5_1607_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/126_5_1607/126_5_1607_t1+_thick_ax_VS_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/126_5_1607/126_5_1607_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/126_5_1607/126_5_1607_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/126_5_1607/126_5_1607_t2_thin_AX_VS_uvauser1-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/126_5_1607/126_5_1607_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/126_5_1607/126_5_1607_t2_thin_AX_VS_uvauser1-copy_coregistered.nii.gz)

  1%|          | 20/1793 [00:08<13:21,  2.21it/s]

Original image path: ./raw_studies/t1+_thick_cor/126_5_1607/126_5_1607_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/126_5_1607/126_5_1607_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/126_5_1607/126_5_1607_t1+_thick_cor_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/126_5_1607/126_5_1607_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/126_5_1607/126_5_1607_t1+_thick_cor_VS_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/131_0_0/131_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/131_0_0/131_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/131_0_0/131_0_0_t2_thin_tumorcore T2S _uvauser3-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/131_0_0/131_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/131_0_0/131_0_0_t2_thin_tumorcore T2S _uvauser3-copy_coregistered.nii.gz)

  1%|          | 22/1793 [00:09<09:26,  3.12it/s]

Original image path: ./raw_studies/t1+_thick_ax/131_0_0/131_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/131_0_0/131_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/131_0_0/131_0_0_t1+_thick_ax_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/131_0_0/131_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/131_0_0/131_0_0_t1+_thick_ax_tumorcore _uvauser3_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/131_0_0/131_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/131_0_0/131_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/131_0_0/131_0_0_t1+_thick_cor_image_coregistered.nii.gz, nan)

  1%|▏         | 23/1793 [00:09<08:37,  3.42it/s]

Original image path: ./raw_studies/t2_thin/131_1_196/131_1_196_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/131_1_196/131_1_196_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/131_1_196/131_1_196_t2_thin_AS1_uvauser4-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/131_1_196/131_1_196_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/131_1_196/131_1_196_t2_thin_AS1_uvauser4-copy_coregistered.nii.gz)

  1%|▏         | 24/1793 [00:10<14:57,  1.97it/s]

Original image path: ./raw_studies/t1+_thin/131_1_196/131_1_196_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/131_1_196/131_1_196_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/131_1_196/131_1_196_t1+_thin_AS_uvauser4-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/131_1_196/131_1_196_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/131_1_196/131_1_196_t1+_thin_AS_uvauser4-copy_coregistered.nii.gz)

  1%|▏         | 25/1793 [00:12<25:01,  1.18it/s]

Original image path: ./raw_studies/t2_thin/131_2_258/131_2_258_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/131_2_258/131_2_258_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/131_2_258/131_2_258_t2_thin_1_uvauser4-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/131_2_258/131_2_258_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/131_2_258/131_2_258_t2_thin_1_uvauser4-copy_coregistered.nii.gz)

  1%|▏         | 26/1793 [00:13<27:46,  1.06it/s]

Original image path: ./raw_studies/t1+_thin/131_2_258/131_2_258_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/131_2_258/131_2_258_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/131_2_258/131_2_258_t1+_thin_AS1_uvauser4-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/131_2_258/131_2_258_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/131_2_258/131_2_258_t1+_thin_AS1_uvauser4-copy_coregistered.nii.gz)

  2%|▏         | 27/1793 [00:15<34:56,  1.19s/it]

Original image path: ./raw_studies/t2_thin/132_0_0/132_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/132_0_0/132_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/132_0_0/132_0_0_t2_thin_VS_uvauser1-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/132_0_0/132_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/132_0_0/132_0_0_t2_thin_VS_uvauser1-copy_coregistered.nii.gz)

  2%|▏         | 29/1793 [00:15<21:49,  1.35it/s]

Original image path: ./raw_studies/t1+_thick_cor/132_0_0/132_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/132_0_0/132_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/132_0_0/132_0_0_t1+_thick_cor_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/132_0_0/132_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/132_0_0/132_0_0_t1+_thick_cor_VS_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/132_0_0/132_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/132_0_0/132_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/132_0_0/132_0_0_t1+_thick_ax_image_coregistered.nii.gz, nan)

  2%|▏         | 30/1793 [00:15<16:26,  1.79it/s]

Original image path: ./raw_studies/t2_thin/132_1_148/132_1_148_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/132_1_148/132_1_148_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/132_1_148/132_1_148_t2_thin_image_coregistered.nii.gz, nan)

  2%|▏         | 31/1793 [00:16<16:15,  1.81it/s]

Original image path: ./raw_studies/t1+_thin/132_1_148/132_1_148_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/132_1_148/132_1_148_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/132_1_148/132_1_148_t1+_thin_Tumorcore _uvauser3-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/132_1_148/132_1_148_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/132_1_148/132_1_148_t1+_thin_Tumorcore _uvauser3-copy_coregistered.nii.gz)

  2%|▏         | 32/1793 [00:16<15:01,  1.95it/s]

Original image path: ./raw_studies/t1+_thin/132_2_232/132_2_232_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/132_2_232/132_2_232_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/132_2_232/132_2_232_t1+_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/132_2_232/132_2_232_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/132_2_232/132_2_232_t1+_thin_VS_uvauser1_coregistered.nii.gz)

  2%|▏         | 33/1793 [00:17<14:27,  2.03it/s]

Original image path: ./raw_studies/t2_thin/132_2_232/132_2_232_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/132_2_232/132_2_232_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/132_2_232/132_2_232_t2_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/132_2_232/132_2_232_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/132_2_232/132_2_232_t2_thin_VS_uvauser1_coregistered.nii.gz)

  2%|▏         | 34/1793 [00:17<16:10,  1.81it/s]

Original image path: ./raw_studies/t1+_thick_cor/137_0_0/137_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/137_0_0/137_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/137_0_0/137_0_0_t1+_thick_cor_VST1cor_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/137_0_0/137_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/137_0_0/137_0_0_t1+_thick_cor_VST1cor_uvauser6_coregistered.nii.gz)

  2%|▏         | 35/1793 [00:18<13:10,  2.22it/s]

Original image path: ./raw_studies/t1+_thick_ax/137_0_0/137_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/137_0_0/137_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/137_0_0/137_0_0_t1+_thick_ax_VST1AX_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/137_0_0/137_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/137_0_0/137_0_0_t1+_thick_ax_VST1AX_uvauser6_coregistered.nii.gz)

  2%|▏         | 36/1793 [00:18<11:04,  2.65it/s]

Original image path: ./raw_studies/t2_thin/137_0_0/137_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/137_0_0/137_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/137_0_0/137_0_0_t2_thin_VST2SPACE_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/137_0_0/137_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/137_0_0/137_0_0_t2_thin_VST2SPACE_uvauser6_coregistered.nii.gz)

  2%|▏         | 38/1793 [00:20<15:55,  1.84it/s]

Original image path: ./raw_studies/t1+_thick_cor/137_1_571/137_1_571_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/137_1_571/137_1_571_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/137_1_571/137_1_571_t1+_thick_cor_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/137_1_571/137_1_571_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/137_1_571/137_1_571_t1+_thick_cor_VS_uvauser5_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/137_1_571/137_1_571_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/137_1_571/137_1_571_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/137_1_571/137_1_571_t2_thin_T2Final_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/137_1_571/137_1_571_t2_thin_image_coregistered.nii.gz, nan)

  2%|▏         | 40/1793 [00:21<18:02,  1.62it/s]

Original image path: ./raw_studies/t1+_thick_ax/137_1_571/137_1_571_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/137_1_571/137_1_571_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/137_1_571/137_1_571_t1+_thick_ax_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/137_1_571/137_1_571_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/137_1_571/137_1_571_t1+_thick_ax_VS_uvauser5_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thin/137_2_2111/137_2_2111_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/137_2_2111/137_2_2111_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/137_2_2111/137_2_2111_t1+_thin_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/137_2_2111/137_2_2111_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/137_2_2111/137_2_2111_t1+_thin_VS_uvauser5_coregistered.nii.gz)

  2%|▏         | 41/1793 [00:22<16:23,  1.78it/s]

Original image path: ./raw_studies/t2_thin/137_2_2111/137_2_2111_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/137_2_2111/137_2_2111_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/137_2_2111/137_2_2111_t2_thin_image_coregistered.nii.gz, nan)

  2%|▏         | 42/1793 [00:23<19:54,  1.47it/s]

Original image path: ./raw_studies/t1+_thick_cor/140_0_0/140_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/140_0_0/140_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/140_0_0/140_0_0_t1+_thick_cor_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/140_0_0/140_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/140_0_0/140_0_0_t1+_thick_cor_LVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/140_0_0/140_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/140_0_0/140_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/140_0_0/140_0_0_t1+_thick_ax_LVS _uvauser2-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/140_0_0/140_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/140_0_0/140_0_0_t1+_thick_ax_LVS _uvauser2-copy_coregistered.nii.gz)

  2%|▏         | 44/1793 [00:23<12:26,  2.34it/s]

Original image path: ./raw_studies/t2_thin/140_0_0/140_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/140_0_0/140_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/140_0_0/140_0_0_t2_thin_1_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/140_0_0/140_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/140_0_0/140_0_0_t2_thin_1_uvauser4_coregistered.nii.gz)

  3%|▎         | 45/1793 [00:24<16:12,  1.80it/s]

Original image path: ./raw_studies/t2_thick/140_1_327/140_1_327_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/140_1_327/140_1_327_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/140_1_327/140_1_327_t2_thick_LVS _uvauser2.nii.gz
Returning: (nan, nan)

  3%|▎         | 46/1793 [00:25<20:08,  1.45it/s]

Original image path: ./raw_studies/t1+_thick_ax/140_1_327/140_1_327_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/140_1_327/140_1_327_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/140_1_327/140_1_327_t1+_thick_ax_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/140_1_327/140_1_327_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/140_1_327/140_1_327_t1+_thick_ax_LVS _uvauser2_coregistered.nii.gz)

  3%|▎         | 48/1793 [00:25<13:23,  2.17it/s]

Original image path: ./raw_studies/t1+_thick_cor/140_1_327/140_1_327_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/140_1_327/140_1_327_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/140_1_327/140_1_327_t1+_thick_cor_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/140_1_327/140_1_327_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/140_1_327/140_1_327_t1+_thick_cor_LVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thin/140_2_780/140_2_780_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/140_2_780/140_2_780_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/140_2_780/140_2_780_t1+_thin_LVS _uvauser2-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/140_2_780/140_2_780_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/140_2_780/140_2_780_t1+_thin_LVS _uvauser2-copy_coregistered.nii.gz)

  3%|▎         | 50/1793 [00:27<19:31,  1.49it/s]

Original image path: ./raw_studies/t1+_thick_cor/140_2_780/140_2_780_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/140_2_780/140_2_780_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/140_2_780/140_2_780_t1+_thick_cor_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/140_2_780/140_2_780_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/140_2_780/140_2_780_t1+_thick_cor_LVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/140_2_780/140_2_780_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/140_2_780/140_2_780_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/140_2_780/140_2_780_t2_thin_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/140_2_780/140_2_780_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/140_2_780/140_2_780_t2_thin_LVS _uvauser2_coregistered.nii.gz)

  3%|▎         | 52/1793 [00:29<17:41,  1.64it/s]

Original image path: ./raw_studies/t1+_thick_ax/146_0_0/146_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/146_0_0/146_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/146_0_0/146_0_0_t1+_thick_ax_RVS  _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/146_0_0/146_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/146_0_0/146_0_0_t1+_thick_ax_RVS  _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/146_0_0/146_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/146_0_0/146_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/146_0_0/146_0_0_t2_thin_RVS _uvauser2-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/146_0_0/146_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/146_0_0/146_0_0_t2_thin_RVS _uvauser2-copy_coregistered.nii.gz)

  3%|▎         | 54/1793 [00:29<12:37,  2.30it/s]

Original image path: ./raw_studies/t1+_thick_cor/146_0_0/146_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/146_0_0/146_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/146_0_0/146_0_0_t1+_thick_cor_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/146_0_0/146_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/146_0_0/146_0_0_t1+_thick_cor_RVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/146_1_538/146_1_538_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/146_1_538/146_1_538_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/146_1_538/146_1_538_t1+_thick_cor_VST1COR_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/146_1_538/146_1_538_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/146_1_538/146_1_538_t1+_thick_cor_VST1COR_uvauser6_coregistered.nii.gz)

  3%|▎         | 55/1793 [00:29<10:07,  2.86it/s]

Original image path: ./raw_studies/t2_thick/146_1_538/146_1_538_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/146_1_538/146_1_538_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/146_1_538/146_1_538_t2_thick_VST2THICK_uvauser6.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thick_ax/146_1_538/146_1_538_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/146_1_538/146_1_538_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/146_1_538/146_1_538_t1+_thick_ax_VST1AX_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/146_1_538/146_1_538_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/146_1_538/146_1_538_t1+_thick_ax_VST1AX_uvauser6_coregistered.nii.gz)

  3%|▎         | 58/1793 [00:30<06:23,  4.52it/s]

Original image path: ./raw_studies/t1+_thick_ax/146_2_941/146_2_941_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/146_2_941/146_2_941_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/146_2_941/146_2_941_t1+_thick_ax_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/146_2_941/146_2_941_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/146_2_941/146_2_941_t1+_thick_ax_RVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/146_2_941/146_2_941_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/146_2_941/146_2_941_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/146_2_941/146_2_941_t1+_thick_cor_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/146_2_941/146_2_941_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/146_2_941/146_2_941_t1+_thick_cor_RVS _uvauser2_coregistered.nii.gz)

  3%|▎         | 59/1793 [00:30<05:47,  4.99it/s]

Original image path: ./raw_studies/t2_thin/146_2_941/146_2_941_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/146_2_941/146_2_941_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/146_2_941/146_2_941_t2_thin_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/146_2_941/146_2_941_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/146_2_941/146_2_941_t2_thin_RVS _uvauser2_coregistered.nii.gz)

  3%|▎         | 60/1793 [00:30<06:08,  4.70it/s]

Original image path: ./raw_studies/t1+_thin/147_0_0/147_0_0_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/147_0_0/147_0_0_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/147_0_0/147_0_0_t1+_thin_VST1thin_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/147_0_0/147_0_0_t1+_thin_image_coregistered.nii.gz, nan)

  3%|▎         | 61/1793 [00:31<13:49,  2.09it/s]

Original image path: ./raw_studies/t2_thin/147_0_0/147_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/147_0_0/147_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/147_0_0/147_0_0_t2_thin_VST2thin_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/147_0_0/147_0_0_t2_thin_image_coregistered.nii.gz, nan)

  4%|▎         | 63/1793 [00:32<12:03,  2.39it/s]

Original image path: ./raw_studies/t1+_thick_cor/147_0_0/147_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/147_0_0/147_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/147_0_0/147_0_0_t1+_thick_cor_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/147_0_0/147_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/147_0_0/147_0_0_t1+_thick_cor_RVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/147_1_104/147_1_104_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/147_1_104/147_1_104_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/147_1_104/147_1_104_t2_thin_AX_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/147_1_104/147_1_104_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/147_1_104/147_1_104_t2_thin_AX_VS_uvauser1_coregistered.nii.gz)

  4%|▎         | 66/1793 [00:33<07:51,  3.66it/s]

Original image path: ./raw_studies/t1+_thick_cor/147_1_104/147_1_104_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/147_1_104/147_1_104_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/147_1_104/147_1_104_t1+_thick_cor_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/147_1_104/147_1_104_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/147_1_104/147_1_104_t1+_thick_cor_VS_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/147_1_104/147_1_104_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/147_1_104/147_1_104_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/147_1_104/147_1_104_t1+_thick_ax_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/147_1_104/147_1_104_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/147_1_104/147_1_104_t1+_thick_ax_VS_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thin/147_1_104/147_1_104_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/147_1_104/147_1_104_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/147_1_104/147_1_104_t1+_thin_image_coregistered.nii.gz, nan)

  4%|▍         | 68/1793 [00:33<07:17,  3.94it/s]

Original image path: ./raw_studies/t1+_thick_cor/148_0_0/148_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/148_0_0/148_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/148_0_0/148_0_0_t1+_thick_cor_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/148_0_0/148_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/148_0_0/148_0_0_t1+_thick_cor_LVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/148_0_0/148_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/148_0_0/148_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/148_0_0/148_0_0_t2_thin_LVS _uvauser2-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/148_0_0/148_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/148_0_0/148_0_0_t2_thin_LVS _uvauser2-copy_coregistered.nii.gz)

  4%|▍         | 69/1793 [00:34<14:09,  2.03it/s]

Original image path: ./raw_studies/t1+_thin/148_0_0/148_0_0_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/148_0_0/148_0_0_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/148_0_0/148_0_0_t1+_thin_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/148_0_0/148_0_0_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/148_0_0/148_0_0_t1+_thin_LVS _uvauser2_coregistered.nii.gz)

  4%|▍         | 71/1793 [00:36<19:59,  1.44it/s]

Original image path: ./raw_studies/t1+_thick_cor/148_1_182/148_1_182_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/148_1_182/148_1_182_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/148_1_182/148_1_182_t1+_thick_cor_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/148_1_182/148_1_182_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/148_1_182/148_1_182_t1+_thick_cor_LVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/148_1_182/148_1_182_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/148_1_182/148_1_182_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/148_1_182/148_1_182_t2_thin_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/148_1_182/148_1_182_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/148_1_182/148_1_182_t2_thin_LVS _uvauser2_coregistered.nii.gz)

  4%|▍         | 72/1793 [00:38<23:21,  1.23it/s]

Original image path: ./raw_studies/t1+_thin/148_1_182/148_1_182_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/148_1_182/148_1_182_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/148_1_182/148_1_182_t1+_thin_LVS _uvauser2-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/148_1_182/148_1_182_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/148_1_182/148_1_182_t1+_thin_LVS _uvauser2-copy_coregistered.nii.gz)

  4%|▍         | 73/1793 [00:38<19:49,  1.45it/s]

Original image path: ./raw_studies/t1+_thin/148_2_253/148_2_253_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/148_2_253/148_2_253_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/148_2_253/148_2_253_t1+_thin_LVS _uvauser2-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/148_2_253/148_2_253_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/148_2_253/148_2_253_t1+_thin_LVS _uvauser2-copy_coregistered.nii.gz)

  4%|▍         | 74/1793 [00:39<24:25,  1.17it/s]

Original image path: ./raw_studies/t1+_thin/148_2_253/148_2_253_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/148_2_253/148_2_253_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/148_2_253/148_2_253_t1+_thin_LVS _uvauser2-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/148_2_253/148_2_253_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/148_2_253/148_2_253_t1+_thin_LVS _uvauser2-copy_coregistered.nii.gz)

  4%|▍         | 75/1793 [00:40<27:39,  1.04it/s]

Original image path: ./raw_studies/t2_thin/148_2_253/148_2_253_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/148_2_253/148_2_253_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/148_2_253/148_2_253_t2_thin_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/148_2_253/148_2_253_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/148_2_253/148_2_253_t2_thin_LVS _uvauser2_coregistered.nii.gz)

  4%|▍         | 76/1793 [00:43<40:58,  1.43s/it]

Original image path: ./raw_studies/t1+_thick_ax/152_0_0/152_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/152_0_0/152_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/152_0_0/152_0_0_t1+_thick_ax_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/152_0_0/152_0_0_t1+_thick_ax_image_coregistered.nii.gz, nan)

  4%|▍         | 77/1793 [00:43<31:23,  1.10s/it]

Original image path: ./raw_studies/t1+_thick_cor/152_0_0/152_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/152_0_0/152_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/152_0_0/152_0_0_t1+_thick_cor_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/152_0_0/152_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/152_0_0/152_0_0_t1+_thick_cor_LVS _uvauser2_coregistered.nii.gz)

  4%|▍         | 79/1793 [00:44<18:12,  1.57it/s]

Original image path: ./raw_studies/t2_thick/152_0_0/152_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/152_0_0/152_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/152_0_0/152_0_0_t2_thick_LVS _uvauser2.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t2_thick/152_1_95/152_1_95_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/152_1_95/152_1_95_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

  4%|▍         | 80/1793 [00:44<14:16,  2.00it/s]

Original image path: ./raw_studies/t2_thin/152_1_95/152_1_95_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/152_1_95/152_1_95_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/152_1_95/152_1_95_t2_thin_AX_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/152_1_95/152_1_95_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/152_1_95/152_1_95_t2_thin_AX_tumorcore _uvauser3_coregistered.nii.gz)

  5%|▍         | 82/1793 [00:44<10:47,  2.64it/s]

Original image path: ./raw_studies/t1+_thick_ax/152_1_95/152_1_95_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/152_1_95/152_1_95_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/152_1_95/152_1_95_t1+_thick_ax_manual_10_uvauser10.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/152_1_95/152_1_95_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/152_1_95/152_1_95_t1+_thick_ax_manual_10_uvauser10_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thick/152_1_95/152_1_95_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/152_1_95/152_1_95_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

  5%|▍         | 84/1793 [00:45<07:33,  3.77it/s]

Original image path: ./raw_studies/t1+_thick_cor/152_1_95/152_1_95_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/152_1_95/152_1_95_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/152_1_95/152_1_95_t1+_thick_cor_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thick_ax/152_2_461/152_2_461_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/152_2_461/152_2_461_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/152_2_461/152_2_461_t1+_thick_ax_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/152_2_461/152_2_461_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/152_2_461/152_2_461_t1+_thick_ax_tumorcore _uvauser3_coregistered.nii.gz)

  5%|▍         | 85/1793 [00:45<06:44,  4.22it/s]

Original image path: ./raw_studies/t2_thin/152_2_461/152_2_461_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/152_2_461/152_2_461_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/152_2_461/152_2_461_t2_thin_CO_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/152_2_461/152_2_461_t2_thin_image_coregistered.nii.gz, nan)

  5%|▍         | 87/1793 [00:45<06:26,  4.41it/s]

Original image path: ./raw_studies/t1+_thick_cor/152_2_461/152_2_461_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/152_2_461/152_2_461_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/152_2_461/152_2_461_t1+_thick_cor_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/152_2_461/152_2_461_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/152_2_461/152_2_461_t1+_thick_cor_tumorcore _uvauser3_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/152_3_905/152_3_905_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/152_3_905/152_3_905_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/152_3_905/152_3_905_t1+_thick_ax_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/152_3_905/152_3_905_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/152_3_905/152_3_905_t1+_thick_ax_VS_uvauser1_coregistered.nii.gz)

  5%|▍         | 89/1793 [00:46<05:18,  5.35it/s]

Original image path: ./raw_studies/t1+_thick_cor/152_3_905/152_3_905_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/152_3_905/152_3_905_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/152_3_905/152_3_905_t1+_thick_cor_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/152_3_905/152_3_905_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/152_3_905/152_3_905_t1+_thick_cor_VS_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/152_3_905/152_3_905_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/152_3_905/152_3_905_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/152_3_905/152_3_905_t2_thin_AX_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/152_3_905/152_3_905_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/152_3_905/152_3_905_t2_thin_AX_VS_uvauser1_coregistered.nii.gz)

  5%|▌         | 90/1793 [00:46<07:01,  4.04it/s]

Original image path: ./raw_studies/t2_thin/152_4_1291/152_4_1291_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/152_4_1291/152_4_1291_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/152_4_1291/152_4_1291_t2_thin_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/152_4_1291/152_4_1291_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/152_4_1291/152_4_1291_t2_thin_LVS _uvauser2_coregistered.nii.gz)

  5%|▌         | 92/1793 [00:47<10:46,  2.63it/s]

Original image path: ./raw_studies/t1+_thick_ax/152_4_1291/152_4_1291_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/152_4_1291/152_4_1291_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/152_4_1291/152_4_1291_t1+_thick_ax_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/152_4_1291/152_4_1291_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/152_4_1291/152_4_1291_t1+_thick_ax_LVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/152_4_1291/152_4_1291_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/152_4_1291/152_4_1291_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/152_4_1291/152_4_1291_t1+_thick_cor_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/152_4_1291/152_4_1291_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/152_4_1291/152_4_1291_t1+_thick_cor_LVS _uvauser2_coregistered.nii.gz)

  5%|▌         | 94/1793 [00:48<07:23,  3.83it/s]

Original image path: ./raw_studies/t1+_thick_ax/152_5_1683/152_5_1683_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/152_5_1683/152_5_1683_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/152_5_1683/152_5_1683_t1+_thick_ax_VST1ax_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/152_5_1683/152_5_1683_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/152_5_1683/152_5_1683_t1+_thick_ax_VST1ax_uvauser6_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/152_5_1683/152_5_1683_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/152_5_1683/152_5_1683_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/152_5_1683/152_5_1683_t1+_thick_cor_VST1cor_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/152_5_1683/152_5_1683_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/152_5_1683/152_5_1683_t1+_thick_cor_VST1cor_uvauser6_coregistered.nii.gz)

  5%|▌         | 95/1793 [00:48<06:25,  4.40it/s]

Original image path: ./raw_studies/t2_thin/152_5_1683/152_5_1683_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/152_5_1683/152_5_1683_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/152_5_1683/152_5_1683_t2_thin_VST2ax_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/152_5_1683/152_5_1683_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/152_5_1683/152_5_1683_t2_thin_VST2ax_uvauser6_coregistered.nii.gz)

  5%|▌         | 97/1793 [00:48<07:42,  3.67it/s]

Original image path: ./raw_studies/t2_thick/16_1_1850/16_1_1850_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/16_1_1850/16_1_1850_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thick_cor/169_0_0/169_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/169_0_0/169_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/169_0_0/169_0_0_t1+_thick_cor_VST1ax_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/169_0_0/169_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/169_0_0/169_0_0_t1+_thick_cor_VST1ax_uvauser6_coregistered.nii.gz)

  6%|▌         | 99/1793 [00:48<05:01,  5.62it/s]

Original image path: ./raw_studies/t1+_thick_ax/169_0_0/169_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/169_0_0/169_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/169_0_0/169_0_0_t1+_thick_ax_VST1ax_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/169_0_0/169_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/169_0_0/169_0_0_t1+_thick_ax_VST1ax_uvauser6_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/169_0_0/169_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/169_0_0/169_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/169_0_0/169_0_0_t2_thin_VST2thick_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/169_0_0/169_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/169_0_0/169_0_0_t2_thin_VST2thick_uvauser6_coregistered.nii.gz)

  6%|▌         | 101/1793 [00:49<05:47,  4.87it/s]

Original image path: ./raw_studies/t1+_thick_cor/169_1_184/169_1_184_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/169_1_184/169_1_184_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/169_1_184/169_1_184_t1+_thick_cor_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/169_1_184/169_1_184_t1+_thick_cor_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t2_thick/169_1_184/169_1_184_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/169_1_184/169_1_184_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

  6%|▌         | 103/1793 [00:49<04:44,  5.94it/s]

Original image path: ./raw_studies/t1+_thick_ax/169_1_184/169_1_184_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/169_1_184/169_1_184_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/169_1_184/169_1_184_t1+_thick_ax_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/169_1_184/169_1_184_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/169_1_184/169_1_184_t1+_thick_ax_LVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/169_1_184/169_1_184_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/169_1_184/169_1_184_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/169_1_184/169_1_184_t2_thin_AX_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/169_1_184/169_1_184_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/169_1_184/169_1_184_t2_thin_AX_VS_uvauser1_coregistered.nii.gz)

  6%|▌         | 105/1793 [00:50<06:14,  4.51it/s]

Original image path: ./raw_studies/t1+_thick_ax/169_1_184/169_1_184_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/169_1_184/169_1_184_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/169_1_184/169_1_184_t1+_thick_ax_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/169_1_184/169_1_184_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/169_1_184/169_1_184_t1+_thick_ax_VS_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/169_2_722/169_2_722_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/169_2_722/169_2_722_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/169_2_722/169_2_722_t1+_thick_cor_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/169_2_722/169_2_722_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/169_2_722/169_2_722_t1+_thick_cor_VS_uvauser5_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/169_2_722/169_2_722_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/169_2_722/169_2_722_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/169_2_722/169_2_722_t2_thin_T2Final_VS_uvauser5-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/169_2_722/169_2_722_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/169_2_722/169_2_722_t2_thin_T2Final_VS_uvauser5-copy_coregistered.nii.gz)

  6%|▌         | 108/1793 [00:51<06:11,  4.54it/s]

Original image path: ./raw_studies/t1+_thick_ax/169_2_722/169_2_722_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/169_2_722/169_2_722_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/169_2_722/169_2_722_t1+_thick_ax_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/169_2_722/169_2_722_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/169_2_722/169_2_722_t1+_thick_ax_VS_uvauser5_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/169_3_835/169_3_835_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/169_3_835/169_3_835_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/169_3_835/169_3_835_t1+_thick_ax_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/169_3_835/169_3_835_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/169_3_835/169_3_835_t1+_thick_ax_AS_uvauser4_coregistered.nii.gz)

  6%|▌         | 109/1793 [00:51<05:31,  5.08it/s]

Original image path: ./raw_studies/t2_thin/169_3_835/169_3_835_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/169_3_835/169_3_835_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/169_3_835/169_3_835_t2_thin_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/169_3_835/169_3_835_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/169_3_835/169_3_835_t2_thin_AS_uvauser4_coregistered.nii.gz)

  6%|▌         | 110/1793 [00:51<07:39,  3.66it/s]

Original image path: ./raw_studies/t1+_thick_cor/169_3_835/169_3_835_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/169_3_835/169_3_835_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/169_3_835/169_3_835_t1+_thick_cor_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/169_3_835/169_3_835_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/169_3_835/169_3_835_t1+_thick_cor_AS_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/170_0_0/170_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/170_0_0/170_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/170_0_0/170_0_0_t2_thin_image_coregistered.nii.gz, nan)

  6%|▌         | 112/1793 [00:52<07:37,  3.67it/s]

Original image path: ./raw_studies/t1+_thin/170_0_0/170_0_0_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/170_0_0/170_0_0_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/170_0_0/170_0_0_t1+_thin_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/170_0_0/170_0_0_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/170_0_0/170_0_0_t1+_thin_VS_uvauser5_coregistered.nii.gz)

  6%|▋         | 113/1793 [00:52<09:13,  3.04it/s]

Original image path: ./raw_studies/t1+_thin/170_1_176/170_1_176_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/170_1_176/170_1_176_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/170_1_176/170_1_176_t1+_thin_VST1ax_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/170_1_176/170_1_176_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/170_1_176/170_1_176_t1+_thin_VST1ax_uvauser6_coregistered.nii.gz)

  6%|▋         | 114/1793 [00:53<10:25,  2.68it/s]

Original image path: ./raw_studies/t2_thin/170_1_176/170_1_176_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/170_1_176/170_1_176_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/170_1_176/170_1_176_t2_thin_VST2thin_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/170_1_176/170_1_176_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/170_1_176/170_1_176_t2_thin_VST2thin_uvauser6_coregistered.nii.gz)

  6%|▋         | 115/1793 [00:53<11:28,  2.44it/s]

Original image path: ./raw_studies/t1+_thin/170_2_382/170_2_382_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/170_2_382/170_2_382_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/170_2_382/170_2_382_t1+_thin_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/170_2_382/170_2_382_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/170_2_382/170_2_382_t1+_thin_AS_uvauser4_coregistered.nii.gz)

  6%|▋         | 116/1793 [00:54<11:49,  2.36it/s]

Original image path: ./raw_studies/t2_thin/170_2_382/170_2_382_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/170_2_382/170_2_382_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/170_2_382/170_2_382_t2_thin_VST2ax_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/170_2_382/170_2_382_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/170_2_382/170_2_382_t2_thin_VST2ax_uvauser6_coregistered.nii.gz)

  7%|▋         | 117/1793 [00:55<16:12,  1.72it/s]

Original image path: ./raw_studies/t1+_thin/170_3_732/170_3_732_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/170_3_732/170_3_732_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/170_3_732/170_3_732_t1+_thin_VST1ax_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/170_3_732/170_3_732_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/170_3_732/170_3_732_t1+_thin_VST1ax_uvauser6_coregistered.nii.gz)

  7%|▋         | 118/1793 [00:57<27:16,  1.02it/s]

Original image path: ./raw_studies/t2_thin/170_3_732/170_3_732_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/170_3_732/170_3_732_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/170_3_732/170_3_732_t2_thin_VST2ax_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/170_3_732/170_3_732_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/170_3_732/170_3_732_t2_thin_VST2ax_uvauser6_coregistered.nii.gz)

  7%|▋         | 120/1793 [00:58<21:02,  1.33it/s]

Original image path: ./raw_studies/t2_thick/175_0_0/175_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/175_0_0/175_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/175_0_0/175_0_0_t2_thick_Manual_uvauser12_uvauser12.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thin/175_0_0/175_0_0_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/175_0_0/175_0_0_t1+_thin_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t1+_thin/175_0_0/175_0_0_t1+_thin_Manual_uvauser12_uvauser12.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t2_thin/178_0_0/178_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/178_0_0/178_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/178_0_0/178_0_0_t2_thin_VS_uvauser1-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/178_0_0/178_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/178_0_0/178_0_0_t2_thin_VS_uvauser1-copy_coregistered.nii.gz)

  7%|▋         | 123/1793 [00:58<11:56,  2.33it/s]

Original image path: ./raw_studies/t1+_thick_cor/178_0_0/178_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/178_0_0/178_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/178_0_0/178_0_0_t1+_thick_cor_VS3_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/178_0_0/178_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/178_0_0/178_0_0_t1+_thick_cor_VS3_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/178_0_0/178_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/178_0_0/178_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/178_0_0/178_0_0_t1+_thick_ax_VS2_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/178_0_0/178_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/178_0_0/178_0_0_t1+_thick_ax_VS2_uvauser1_coregistered.nii.gz)

  7%|▋         | 125/1793 [00:59<08:13,  3.38it/s]

Original image path: ./raw_studies/t1+_thick_cor/178_1_138/178_1_138_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/178_1_138/178_1_138_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/178_1_138/178_1_138_t1+_thick_cor_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t2_thin/178_1_138/178_1_138_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/178_1_138/178_1_138_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/178_1_138/178_1_138_t2_thin_image_coregistered.nii.gz, nan)

  7%|▋         | 127/1793 [00:59<07:43,  3.60it/s]

Original image path: ./raw_studies/t1+_thick_ax/178_1_138/178_1_138_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/178_1_138/178_1_138_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/178_1_138/178_1_138_t1+_thick_ax_Tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/178_1_138/178_1_138_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/178_1_138/178_1_138_t1+_thick_ax_Tumorcore _uvauser3_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thick/178_2_282/178_2_282_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/178_2_282/178_2_282_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/178_2_282/178_2_282_t2_thick_VS2_uvauser1.nii.gz
Returning: (nan, nan)

  7%|▋         | 128/1793 [01:00<09:52,  2.81it/s]

Original image path: ./raw_studies/t1+_thick_cor/178_2_282/178_2_282_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/178_2_282/178_2_282_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/178_2_282/178_2_282_t1+_thick_cor_VS2_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/178_2_282/178_2_282_t1+_thick_cor_image_coregistered.nii.gz, nan)

  7%|▋         | 130/1793 [01:00<07:39,  3.62it/s]

Original image path: ./raw_studies/t1+_thick_ax/178_2_282/178_2_282_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/178_2_282/178_2_282_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/178_2_282/178_2_282_t1+_thick_ax_1_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/178_2_282/178_2_282_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/178_2_282/178_2_282_t1+_thick_ax_1_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/178_3_765/178_3_765_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/178_3_765/178_3_765_t2_thin_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thin/178_3_765/178_3_765_t2_thin_T2Final_VS_uvauser5.nii.gz
Returning: (nan, nan)

  7%|▋         | 132/1793 [01:01<08:16,  3.34it/s]

Original image path: ./raw_studies/t1+_thick_cor/178_3_765/178_3_765_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/178_3_765/178_3_765_t1+_thick_cor_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t1+_thick_cor/178_3_765/178_3_765_t1+_thick_cor_VS_uvauser5.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thick_ax/178_3_765/178_3_765_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/178_3_765/178_3_765_t1+_thick_ax_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t1+_thick_ax/178_3_765/178_3_765_t1+_thick_ax_VS_uvauser5.nii.gz
Returning: (nan, nan)

  7%|▋         | 133/1793 [01:01<07:02,  3.93it/s]

Original image path: ./raw_studies/t1+_thin/178_4_2203/178_4_2203_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/178_4_2203/178_4_2203_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/178_4_2203/178_4_2203_t1+_thin_VST2_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/178_4_2203/178_4_2203_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/178_4_2203/178_4_2203_t1+_thin_VST2_uvauser6_coregistered.nii.gz)

  8%|▊         | 135/1793 [01:02<10:46,  2.57it/s]

Original image path: ./raw_studies/t1+_thick_ax/178_4_2203/178_4_2203_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/178_4_2203/178_4_2203_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/178_4_2203/178_4_2203_t1+_thick_ax_VST1ax_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/178_4_2203/178_4_2203_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/178_4_2203/178_4_2203_t1+_thick_ax_VST1ax_uvauser6_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/178_4_2203/178_4_2203_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/178_4_2203/178_4_2203_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/178_4_2203/178_4_2203_t1+_thick_cor_VST1cor_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/178_4_2203/178_4_2203_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/178_4_2203/178_4_2203_t1+_thick_cor_VST1cor_uvauser6_coregistered.nii.gz)

  8%|▊         | 136/1793 [01:03<08:57,  3.08it/s]

Original image path: ./raw_studies/t2_thin/178_5_2486/178_5_2486_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/178_5_2486/178_5_2486_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/178_5_2486/178_5_2486_t2_thin_AX_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/178_5_2486/178_5_2486_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/178_5_2486/178_5_2486_t2_thin_AX_VS_uvauser1_coregistered.nii.gz)

  8%|▊         | 138/1793 [01:04<10:37,  2.60it/s]

Original image path: ./raw_studies/t1+_thick_ax/178_5_2486/178_5_2486_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/178_5_2486/178_5_2486_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/178_5_2486/178_5_2486_t1+_thick_ax_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/178_5_2486/178_5_2486_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/178_5_2486/178_5_2486_t1+_thick_ax_VS_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/178_5_2486/178_5_2486_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/178_5_2486/178_5_2486_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/178_5_2486/178_5_2486_t1+_thick_cor_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/178_5_2486/178_5_2486_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/178_5_2486/178_5_2486_t1+_thick_cor_VS_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/181_0_0/181_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/181_0_0/181_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/181_0_0/181_0_0_t2_thin_image_coregistered.nii.gz, nan)

  8%|▊         | 140/1793 [01:04<09:49,  2.80it/s]

Original image path: ./raw_studies/t1+_thin/181_0_0/181_0_0_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/181_0_0/181_0_0_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/181_0_0/181_0_0_t1+_thin_image_coregistered.nii.gz, nan)

  8%|▊         | 141/1793 [01:06<16:50,  1.64it/s]

Original image path: ./raw_studies/t1+_thin/181_1_61/181_1_61_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/181_1_61/181_1_61_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/181_1_61/181_1_61_t1+_thin_Manual_0_uvauser11.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/181_1_61/181_1_61_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/181_1_61/181_1_61_t1+_thin_Manual_0_uvauser11_coregistered.nii.gz)

  8%|▊         | 143/1793 [01:07<17:21,  1.58it/s]

Original image path: ./raw_studies/t1+_thick_ax/181_2_194/181_2_194_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/181_2_194/181_2_194_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/181_2_194/181_2_194_t1+_thick_ax_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t2_thin/181_2_194/181_2_194_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/181_2_194/181_2_194_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/181_2_194/181_2_194_t2_thin_CO_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/181_2_194/181_2_194_t2_thin_image_coregistered.nii.gz, nan)

  8%|▊         | 145/1793 [01:08<13:46,  1.99it/s]

Original image path: ./raw_studies/t1+_thick_ax/182_0_0/182_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/182_0_0/182_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/182_0_0/182_0_0_t1+_thick_ax_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t2_thin/182_0_0/182_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/182_0_0/182_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/182_0_0/182_0_0_t2_thin_T2Final_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/182_0_0/182_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/182_0_0/182_0_0_t2_thin_T2Final_VS_uvauser5_coregistered.nii.gz)

  8%|▊         | 146/1793 [01:08<11:34,  2.37it/s]

Original image path: ./raw_studies/t2_thick/182_0_0/182_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/182_0_0/182_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thin/185_0_0/185_0_0_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/185_0_0/185_0_0_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/185_0_0/185_0_0_t1+_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/185_0_0/185_0_0_t1+_thin_image_coregistered.nii.gz, nan)

  8%|▊         | 148/1793 [01:09<09:01,  3.04it/s]

Original image path: ./raw_studies/t1+_thin/185_0_0/185_0_0_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/185_0_0/185_0_0_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/185_0_0/185_0_0_t1+_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/185_0_0/185_0_0_t1+_thin_image_coregistered.nii.gz, nan)

  8%|▊         | 149/1793 [01:09<09:00,  3.04it/s]

Original image path: ./raw_studies/t2_thick/185_0_0/185_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/185_0_0/185_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/185_0_0/185_0_0_t2_thick_LVS _uvauser2.nii.gz
Returning: (nan, nan)

  8%|▊         | 150/1793 [01:09<08:16,  3.31it/s]

Original image path: ./raw_studies/t1+_thin/185_1_277/185_1_277_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/185_1_277/185_1_277_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/185_1_277/185_1_277_t1+_thin_1_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/185_1_277/185_1_277_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/185_1_277/185_1_277_t1+_thin_1_uvauser4_coregistered.nii.gz)

  8%|▊         | 151/1793 [01:10<11:53,  2.30it/s]

Original image path: ./raw_studies/t2_thin/185_1_277/185_1_277_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/185_1_277/185_1_277_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/185_1_277/185_1_277_t2_thin_1_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/185_1_277/185_1_277_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/185_1_277/185_1_277_t2_thin_1_uvauser4_coregistered.nii.gz)

  8%|▊         | 152/1793 [01:10<10:39,  2.57it/s]

Original image path: ./raw_studies/t2_thin/185_2_325/185_2_325_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/185_2_325/185_2_325_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/185_2_325/185_2_325_t2_thin_image_coregistered.nii.gz, nan)

  9%|▊         | 153/1793 [01:11<11:13,  2.44it/s]

Original image path: ./raw_studies/t1+_thin/185_2_325/185_2_325_t1+_thin_image_uint8.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/185_2_325/185_2_325_t1+_thin_image_uint8_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t1+_thin/185_2_325/185_2_325_t1+_thin_VS_uvauser1.nii.gz
Returning: (nan, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/185_2_325/185_2_325_t1+_thin_VS_uvauser1_coregistered.nii.gz)

  9%|▊         | 154/1793 [01:12<18:44,  1.46it/s]

Original image path: ./raw_studies/t2_thin/188_0_0/188_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/188_0_0/188_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/188_0_0/188_0_0_t2_thin_VST2_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/188_0_0/188_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/188_0_0/188_0_0_t2_thin_VST2_uvauser6_coregistered.nii.gz)

  9%|▉         | 157/1793 [01:13<13:23,  2.04it/s]

Original image path: ./raw_studies/t1+_thick_cor/188_0_0/188_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/188_0_0/188_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/188_0_0/188_0_0_t1+_thick_cor_VST1cor_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/188_0_0/188_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/188_0_0/188_0_0_t1+_thick_cor_VST1cor_uvauser6_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/188_0_0/188_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/188_0_0/188_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/188_0_0/188_0_0_t1+_thick_ax_VST1ax_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/188_0_0/188_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/188_0_0/188_0_0_t1+_thick_ax_VST1ax_uvauser6_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/188_1_263/188_1_263_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/188_1_263/188_1_263_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/188_1_263/188_1_263_t1+_thick_cor_Tumorcore  _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/188_1_263/188_1_263_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/188_1_263/188_1_263_t1+_thick_cor_Tumorcore  _uvauser3_coregistered.nii.gz)

  9%|▉         | 159/1793 [01:14<09:35,  2.84it/s]

Original image path: ./raw_studies/t1+_thick_ax/188_1_263/188_1_263_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/188_1_263/188_1_263_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/188_1_263/188_1_263_t1+_thick_ax_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t2_thin/188_1_263/188_1_263_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/188_1_263/188_1_263_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/188_1_263/188_1_263_t2_thin_Tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/188_1_263/188_1_263_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/188_1_263/188_1_263_t2_thin_Tumorcore _uvauser3_coregistered.nii.gz)

  9%|▉         | 161/1793 [01:15<13:17,  2.05it/s]

Original image path: ./raw_studies/t1+_thick_ax/188_2_645/188_2_645_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/188_2_645/188_2_645_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/188_2_645/188_2_645_t1+_thick_ax_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/188_2_645/188_2_645_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/188_2_645/188_2_645_t1+_thick_ax_AS_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/188_2_645/188_2_645_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/188_2_645/188_2_645_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/188_2_645/188_2_645_t2_thin_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/188_2_645/188_2_645_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/188_2_645/188_2_645_t2_thin_AS_uvauser4_coregistered.nii.gz)

  9%|▉         | 163/1793 [01:16<13:36,  2.00it/s]

Original image path: ./raw_studies/t1+_thick_cor/188_2_645/188_2_645_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/188_2_645/188_2_645_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/188_2_645/188_2_645_t1+_thick_cor_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/188_2_645/188_2_645_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/188_2_645/188_2_645_t1+_thick_cor_AS_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/188_3_1033/188_3_1033_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/188_3_1033/188_3_1033_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/188_3_1033/188_3_1033_t2_thin_VST2_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/188_3_1033/188_3_1033_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/188_3_1033/188_3_1033_t2_thin_VST2_uvauser6_coregistered.nii.gz)

  9%|▉         | 165/1793 [01:18<13:47,  1.97it/s]

Original image path: ./raw_studies/t1+_thick_cor/188_3_1033/188_3_1033_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/188_3_1033/188_3_1033_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/188_3_1033/188_3_1033_t1+_thick_cor_VST1cor_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/188_3_1033/188_3_1033_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/188_3_1033/188_3_1033_t1+_thick_cor_VST1cor_uvauser6_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/188_3_1033/188_3_1033_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/188_3_1033/188_3_1033_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/188_3_1033/188_3_1033_t1+_thick_ax_VST1ax_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/188_3_1033/188_3_1033_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/188_3_1033/188_3_1033_t1+_thick_ax_VST1ax_uvauser6_coregistered.nii.gz)

  9%|▉         | 167/1793 [01:18<08:55,  3.04it/s]

Original image path: ./raw_studies/t1+_thick_ax/188_4_1434/188_4_1434_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/188_4_1434/188_4_1434_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/188_4_1434/188_4_1434_t1+_thick_ax_manual_0_uvauser13.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/188_4_1434/188_4_1434_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/188_4_1434/188_4_1434_t1+_thick_ax_manual_0_uvauser13_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/188_4_1434/188_4_1434_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/188_4_1434/188_4_1434_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/188_4_1434/188_4_1434_t1+_thick_cor_image_coregistered.nii.gz, nan)

  9%|▉         | 168/1793 [01:18<07:24,  3.65it/s]

Original image path: ./raw_studies/t2_thin/188_4_1434/188_4_1434_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/188_4_1434/188_4_1434_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/188_4_1434/188_4_1434_t2_thin_manual_0_uvauser13.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/188_4_1434/188_4_1434_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/188_4_1434/188_4_1434_t2_thin_manual_0_uvauser13_coregistered.nii.gz)

  9%|▉         | 170/1793 [01:19<10:19,  2.62it/s]

Original image path: ./raw_studies/t1+_thick_ax/188_5_2399/188_5_2399_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/188_5_2399/188_5_2399_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/188_5_2399/188_5_2399_t1+_thick_ax_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/188_5_2399/188_5_2399_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/188_5_2399/188_5_2399_t1+_thick_ax_VS_uvauser5_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/188_5_2399/188_5_2399_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/188_5_2399/188_5_2399_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/188_5_2399/188_5_2399_t1+_thick_cor_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/188_5_2399/188_5_2399_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/188_5_2399/188_5_2399_t1+_thick_cor_VS_uvauser5_coregistered.nii.gz)

 10%|▉         | 171/1793 [01:19<08:36,  3.14it/s]

Original image path: ./raw_studies/t2_thin/188_5_2399/188_5_2399_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/188_5_2399/188_5_2399_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/188_5_2399/188_5_2399_t2_thin_T2Final_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/188_5_2399/188_5_2399_t2_thin_image_coregistered.nii.gz, nan)

 10%|▉         | 172/1793 [01:21<18:46,  1.44it/s]

Original image path: ./raw_studies/t1+_thin/190_0_0/190_0_0_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/190_0_0/190_0_0_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/190_0_0/190_0_0_t1+_thin_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/190_0_0/190_0_0_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/190_0_0/190_0_0_t1+_thin_LVS _uvauser2_coregistered.nii.gz)

 10%|▉         | 174/1793 [01:22<16:26,  1.64it/s]

Original image path: ./raw_studies/t2_thick/190_0_0/190_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/190_0_0/190_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/190_0_0/190_0_0_t2_thick_LVS _uvauser2.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thin/190_0_0/190_0_0_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/190_0_0/190_0_0_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/190_0_0/190_0_0_t1+_thin_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/190_0_0/190_0_0_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/190_0_0/190_0_0_t1+_thin_LVS _uvauser2_coregistered.nii.gz)

 10%|▉         | 176/1793 [01:23<15:28,  1.74it/s]

Original image path: ./raw_studies/t1+_thick_ax/190_1_150/190_1_150_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/190_1_150/190_1_150_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/190_1_150/190_1_150_t1+_thick_ax_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/190_1_150/190_1_150_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/190_1_150/190_1_150_t1+_thick_ax_VS_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/190_1_150/190_1_150_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/190_1_150/190_1_150_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/190_1_150/190_1_150_t1+_thick_cor_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/190_1_150/190_1_150_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/190_1_150/190_1_150_t1+_thick_cor_VS_uvauser1_coregistered.nii.gz)

 10%|▉         | 177/1793 [01:23<12:00,  2.24it/s]

Original image path: ./raw_studies/t2_thin/190_1_150/190_1_150_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/190_1_150/190_1_150_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/190_1_150/190_1_150_t2_thin_T2_VS_uvauser1-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/190_1_150/190_1_150_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/190_1_150/190_1_150_t2_thin_T2_VS_uvauser1-copy_coregistered.nii.gz)

 10%|▉         | 178/1793 [01:25<16:48,  1.60it/s]

Original image path: ./raw_studies/t2_thin/190_2_1367/190_2_1367_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/190_2_1367/190_2_1367_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/190_2_1367/190_2_1367_t2_thin_AX_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/190_2_1367/190_2_1367_t2_thin_image_coregistered.nii.gz, nan)

 10%|█         | 181/1793 [01:25<10:10,  2.64it/s]

Original image path: ./raw_studies/t1+_thick_ax/190_2_1367/190_2_1367_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/190_2_1367/190_2_1367_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/190_2_1367/190_2_1367_t1+_thick_ax_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/190_2_1367/190_2_1367_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/190_2_1367/190_2_1367_t1+_thick_ax_AS_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/190_2_1367/190_2_1367_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/190_2_1367/190_2_1367_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/190_2_1367/190_2_1367_t1+_thick_cor_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/190_2_1367/190_2_1367_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/190_2_1367/190_2_1367_t1+_thick_cor_AS_uvauser4_coregistered.nii.gz)

 10%|█         | 182/1793 [01:26<09:33,  2.81it/s]

Original image path: ./raw_studies/t2_thick/190_3_2717/190_3_2717_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/190_3_2717/190_3_2717_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

Original image path: ./raw_studies/t2_thin/190_4_2800/190_4_2800_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/190_4_2800/190_4_2800_t2_thin_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 10%|█         | 183/1793 [01:26<08:14,  3.25it/s]

Original image path: ./raw_studies/t2_thin/193_0_0/193_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/193_0_0/193_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/193_0_0/193_0_0_t2_thin_2_uvauser4-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/193_0_0/193_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/193_0_0/193_0_0_t2_thin_2_uvauser4-copy_coregistered.nii.gz)

 10%|█         | 185/1793 [01:26<07:08,  3.75it/s]

Original image path: ./raw_studies/t1+_thick_ax/193_0_0/193_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/193_0_0/193_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/193_0_0/193_0_0_t1+_thick_ax_1_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/193_0_0/193_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/193_0_0/193_0_0_t1+_thick_ax_1_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/193_0_0/193_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/193_0_0/193_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/193_0_0/193_0_0_t1+_thick_cor_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/193_0_0/193_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/193_0_0/193_0_0_t1+_thick_cor_tumorcore _uvauser3_coregistered.nii.gz)

 10%|█         | 187/1793 [01:27<05:38,  4.74it/s]

Original image path: ./raw_studies/t1+_thick_ax/193_1_175/193_1_175_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/193_1_175/193_1_175_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/193_1_175/193_1_175_t1+_thick_ax_Tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/193_1_175/193_1_175_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/193_1_175/193_1_175_t1+_thick_ax_Tumorcore _uvauser3_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/193_1_175/193_1_175_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/193_1_175/193_1_175_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/193_1_175/193_1_175_t1+_thick_cor_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/193_1_175/193_1_175_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/193_1_175/193_1_175_t1+_thick_cor_tumorcore _uvauser3_coregistered.nii.gz)

 10%|█         | 188/1793 [01:27<05:13,  5.12it/s]

Original image path: ./raw_studies/t2_thin/193_1_175/193_1_175_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/193_1_175/193_1_175_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/193_1_175/193_1_175_t2_thin_AX_Tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/193_1_175/193_1_175_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/193_1_175/193_1_175_t2_thin_AX_Tumorcore _uvauser3_coregistered.nii.gz)

 11%|█         | 189/1793 [01:28<11:44,  2.28it/s]

Original image path: ./raw_studies/t2_thin/193_2_314/193_2_314_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/193_2_314/193_2_314_t2_thin_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thin/193_2_314/193_2_314_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/193_2_314/193_2_314_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/193_2_314/193_2_314_t1+_thin_Tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/193_2_314/193_2_314_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/193_2_314/193_2_314_t1+_thin_Tumorcore _uvauser3_coregistered.nii.gz)

 11%|█         | 192/1793 [01:29<12:13,  2.18it/s]

Original image path: ./raw_studies/t2_thin/199_0_0/199_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/199_0_0/199_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/199_0_0/199_0_0_t2_thin_tumorcore _uvauser3-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/199_0_0/199_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/199_0_0/199_0_0_t2_thin_tumorcore _uvauser3-copy_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/199_0_0/199_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/199_0_0/199_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/199_0_0/199_0_0_t1+_thick_ax_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/199_0_0/199_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/199_0_0/199_0_0_t1+_thick_ax_tumorcore _uvauser3_coregistered.nii.gz)

 11%|█         | 194/1793 [01:29<07:58,  3.34it/s]

Original image path: ./raw_studies/t1+_thick_cor/199_0_0/199_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/199_0_0/199_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/199_0_0/199_0_0_t1+_thick_cor_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/199_0_0/199_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/199_0_0/199_0_0_t1+_thick_cor_tumorcore _uvauser3_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/199_1_183/199_1_183_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/199_1_183/199_1_183_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/199_1_183/199_1_183_t1+_thick_ax_1_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/199_1_183/199_1_183_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/199_1_183/199_1_183_t1+_thick_ax_1_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/199_1_183/199_1_183_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/199_1_183/199_1_183_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/199_1_183/199_1_183_t1+_thick_cor_image_coregistered.nii.gz, nan)

 11%|█         | 196/1793 [01:30<05:43,  4.65it/s]

Original image path: ./raw_studies/t2_thin/199_1_183/199_1_183_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/199_1_183/199_1_183_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/199_1_183/199_1_183_t2_thin_1_uvauser4-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/199_1_183/199_1_183_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/199_1_183/199_1_183_t2_thin_1_uvauser4-copy_coregistered.nii.gz)

 11%|█         | 197/1793 [01:30<05:41,  4.68it/s]

Original image path: ./raw_studies/t1+_thin/199_2_292/199_2_292_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/199_2_292/199_2_292_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/199_2_292/199_2_292_t1+_thin_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/199_2_292/199_2_292_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/199_2_292/199_2_292_t1+_thin_tumorcore _uvauser3_coregistered.nii.gz)

 11%|█         | 198/1793 [01:31<12:57,  2.05it/s]

Original image path: ./raw_studies/t2_thin/199_2_292/199_2_292_t2_thin_image_uint8.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/199_2_292/199_2_292_t2_thin_image_uint8_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 11%|█         | 199/1793 [01:34<25:59,  1.02it/s]

Original image path: ./raw_studies/t1+_thin/200_0_0/200_0_0_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/200_0_0/200_0_0_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/200_0_0/200_0_0_t1+_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/200_0_0/200_0_0_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/200_0_0/200_0_0_t1+_thin_VS_uvauser1_coregistered.nii.gz)

 11%|█         | 200/1793 [01:35<26:52,  1.01s/it]

Original image path: ./raw_studies/t2_thin/200_0_0/200_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/200_0_0/200_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/200_0_0/200_0_0_t2_thin_image_coregistered.nii.gz, nan)

 11%|█         | 201/1793 [01:36<27:02,  1.02s/it]

Original image path: ./raw_studies/t1+_thin/200_1_45/200_1_45_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/200_1_45/200_1_45_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/200_1_45/200_1_45_t1+_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/200_1_45/200_1_45_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/200_1_45/200_1_45_t1+_thin_VS_uvauser1_coregistered.nii.gz)

 11%|█▏        | 202/1793 [01:37<30:21,  1.14s/it]

Original image path: ./raw_studies/t2_thin/200_1_45/200_1_45_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/200_1_45/200_1_45_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/200_1_45/200_1_45_t2_thin_image_coregistered.nii.gz, nan)

 11%|█▏        | 203/1793 [01:39<32:33,  1.23s/it]

Original image path: ./raw_studies/t1+_thin/202_0_0/202_0_0_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/202_0_0/202_0_0_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/202_0_0/202_0_0_t1+_thin_Tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/202_0_0/202_0_0_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/202_0_0/202_0_0_t1+_thin_Tumorcore _uvauser3_coregistered.nii.gz)

 11%|█▏        | 204/1793 [01:40<29:43,  1.12s/it]

Original image path: ./raw_studies/t2_thin/202_0_0/202_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/202_0_0/202_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/202_0_0/202_0_0_t2_thin_image_coregistered.nii.gz, nan)

 11%|█▏        | 206/1793 [01:40<19:04,  1.39it/s]

Original image path: ./raw_studies/t2_thick/202_1_667/202_1_667_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/202_1_667/202_1_667_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/202_1_667/202_1_667_t2_thick_LVS _uvauser2-copy.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thick_ax/202_2_826/202_2_826_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/202_2_826/202_2_826_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/202_2_826/202_2_826_t1+_thick_ax_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t2_thin/202_2_826/202_2_826_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/202_2_826/202_2_826_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/202_2_826/202_2_826_t2_thin_image_coregistered.nii.gz, nan)

 12%|█▏        | 208/1793 [01:41<13:05,  2.02it/s]

Original image path: ./raw_studies/t1+_thick_cor/202_2_826/202_2_826_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/202_2_826/202_2_826_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/202_2_826/202_2_826_t1+_thick_cor_Tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/202_2_826/202_2_826_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/202_2_826/202_2_826_t1+_thick_cor_Tumorcore _uvauser3_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/206_0_0/206_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/206_0_0/206_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/206_0_0/206_0_0_t1+_thick_cor_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/206_0_0/206_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/206_0_0/206_0_0_t1+_thick_cor_VS_uvauser5_coregistered.nii.gz)

 12%|█▏        | 210/1793 [01:41<09:00,  2.93it/s]

Original image path: ./raw_studies/t2_thin/206_0_0/206_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/206_0_0/206_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/206_0_0/206_0_0_t2_thin_T2Final_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/206_0_0/206_0_0_t2_thin_image_coregistered.nii.gz, nan)

 12%|█▏        | 212/1793 [01:42<10:42,  2.46it/s]

Original image path: ./raw_studies/t1+_thick_ax/206_0_0/206_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/206_0_0/206_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/206_0_0/206_0_0_t1+_thick_ax_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/206_0_0/206_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/206_0_0/206_0_0_t1+_thick_ax_VS_uvauser5_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/206_1_356/206_1_356_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/206_1_356/206_1_356_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/206_1_356/206_1_356_t2_thin_T2Final_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/206_1_356/206_1_356_t2_thin_image_coregistered.nii.gz, nan)

 12%|█▏        | 215/1793 [01:43<07:30,  3.50it/s]

Original image path: ./raw_studies/t1+_thick_ax/206_1_356/206_1_356_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/206_1_356/206_1_356_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/206_1_356/206_1_356_t1+_thick_ax_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/206_1_356/206_1_356_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/206_1_356/206_1_356_t1+_thick_ax_VS_uvauser5_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/206_1_356/206_1_356_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/206_1_356/206_1_356_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/206_1_356/206_1_356_t1+_thick_cor_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/206_1_356/206_1_356_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/206_1_356/206_1_356_t1+_thick_cor_VS_uvauser5_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/207_0_0/207_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/207_0_0/207_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/207_0_0/207_0_0_t1+_thick_cor_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/207_0_0/207_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/207_0_0/207_0_0_t1+_thick_cor_RVS _uvauser2_coregistered.nii.gz)

 12%|█▏        | 217/1793 [01:43<06:05,  4.31it/s]

Original image path: ./raw_studies/t1+_thick_ax/207_0_0/207_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/207_0_0/207_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/207_0_0/207_0_0_t1+_thick_ax_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/207_0_0/207_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/207_0_0/207_0_0_t1+_thick_ax_RVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/207_0_0/207_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/207_0_0/207_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/207_0_0/207_0_0_t2_thin_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/207_0_0/207_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/207_0_0/207_0_0_t2_thin_RVS _uvauser2_coregistered.nii.gz)

 12%|█▏        | 219/1793 [01:44<09:32,  2.75it/s]

Original image path: ./raw_studies/t1+_thick_ax/207_1_291/207_1_291_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/207_1_291/207_1_291_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/207_1_291/207_1_291_t1+_thick_ax_Tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/207_1_291/207_1_291_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/207_1_291/207_1_291_t1+_thick_ax_Tumorcore _uvauser3_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/207_1_291/207_1_291_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/207_1_291/207_1_291_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/207_1_291/207_1_291_t2_thin_image_coregistered.nii.gz, nan)

 12%|█▏        | 221/1793 [01:46<13:03,  2.01it/s]

Original image path: ./raw_studies/t1+_thick_cor/207_1_291/207_1_291_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/207_1_291/207_1_291_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/207_1_291/207_1_291_t1+_thick_cor_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thick_cor/207_2_651/207_2_651_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/207_2_651/207_2_651_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/207_2_651/207_2_651_t1+_thick_cor_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/207_2_651/207_2_651_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/207_2_651/207_2_651_t1+_thick_cor_VS_uvauser5_coregistered.nii.gz)

 12%|█▏        | 223/1793 [01:46<08:05,  3.23it/s]

Original image path: ./raw_studies/t1+_thick_ax/207_2_651/207_2_651_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/207_2_651/207_2_651_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/207_2_651/207_2_651_t1+_thick_ax_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/207_2_651/207_2_651_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/207_2_651/207_2_651_t1+_thick_ax_VS_uvauser5_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/207_2_651/207_2_651_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/207_2_651/207_2_651_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/207_2_651/207_2_651_t2_thin_T2Final_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/207_2_651/207_2_651_t2_thin_image_coregistered.nii.gz, nan)

 12%|█▏        | 224/1793 [01:48<16:45,  1.56it/s]

Original image path: ./raw_studies/t2_thin/207_3_1194/207_3_1194_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/207_3_1194/207_3_1194_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/207_3_1194/207_3_1194_t2_thin_AX_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/207_3_1194/207_3_1194_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/207_3_1194/207_3_1194_t2_thin_AX_VS_uvauser1_coregistered.nii.gz)

 13%|█▎        | 226/1793 [01:49<16:15,  1.61it/s]

Original image path: ./raw_studies/t1+_thick_ax/207_3_1194/207_3_1194_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/207_3_1194/207_3_1194_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/207_3_1194/207_3_1194_t1+_thick_ax_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/207_3_1194/207_3_1194_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/207_3_1194/207_3_1194_t1+_thick_ax_VS_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/207_3_1194/207_3_1194_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/207_3_1194/207_3_1194_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/207_3_1194/207_3_1194_t1+_thick_cor_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/207_3_1194/207_3_1194_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/207_3_1194/207_3_1194_t1+_thick_cor_VS_uvauser1_coregistered.nii.gz)

 13%|█▎        | 227/1793 [01:49<13:08,  1.99it/s]

Original image path: ./raw_studies/t2_thin/207_4_1986/207_4_1986_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/207_4_1986/207_4_1986_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/207_4_1986/207_4_1986_t2_thin_image_coregistered.nii.gz, nan)

 13%|█▎        | 228/1793 [01:50<17:05,  1.53it/s]

Original image path: ./raw_studies/t1+_thin/207_4_1986/207_4_1986_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/207_4_1986/207_4_1986_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/207_4_1986/207_4_1986_t1+_thin_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/207_4_1986/207_4_1986_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/207_4_1986/207_4_1986_t1+_thin_AS_uvauser4_coregistered.nii.gz)

 13%|█▎        | 230/1793 [01:51<12:35,  2.07it/s]

Original image path: ./raw_studies/t2_thick/208_1_36/208_1_36_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/208_1_36/208_1_36_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/208_1_36/208_1_36_t2_thick_VS_uvauser5.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thick_cor/208_1_36/208_1_36_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/208_1_36/208_1_36_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/208_1_36/208_1_36_t1+_thick_cor_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/208_1_36/208_1_36_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/208_1_36/208_1_36_t1+_thick_cor_VS_uvauser5_coregistered.nii.gz)

 13%|█▎        | 231/1793 [01:51<10:25,  2.50it/s]

Original image path: ./raw_studies/t1+_thick_ax/208_1_36/208_1_36_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/208_1_36/208_1_36_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/208_1_36/208_1_36_t1+_thick_ax_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/208_1_36/208_1_36_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/208_1_36/208_1_36_t1+_thick_ax_VS_uvauser5_coregistered.nii.gz)

 13%|█▎        | 232/1793 [01:51<08:54,  2.92it/s]

Original image path: ./raw_studies/t1+_thin/210_0_0/210_0_0_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/210_0_0/210_0_0_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/210_0_0/210_0_0_t1+_thin_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/210_0_0/210_0_0_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/210_0_0/210_0_0_t1+_thin_LVS _uvauser2_coregistered.nii.gz)

 13%|█▎        | 233/1793 [01:52<09:50,  2.64it/s]

Original image path: ./raw_studies/t1+_thin/210_0_0/210_0_0_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/210_0_0/210_0_0_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/210_0_0/210_0_0_t1+_thin_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/210_0_0/210_0_0_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/210_0_0/210_0_0_t1+_thin_LVS _uvauser2_coregistered.nii.gz)

 13%|█▎        | 235/1793 [01:52<08:41,  2.98it/s]

Original image path: ./raw_studies/t2_thick/210_0_0/210_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/210_0_0/210_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/210_0_0/210_0_0_t2_thick_LVS _uvauser2.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thin/210_1_162/210_1_162_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/210_1_162/210_1_162_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/210_1_162/210_1_162_t1+_thin_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/210_1_162/210_1_162_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/210_1_162/210_1_162_t1+_thin_tumorcore _uvauser3_coregistered.nii.gz)

 13%|█▎        | 236/1793 [01:53<09:44,  2.66it/s]

Original image path: ./raw_studies/t2_thin/210_1_162/210_1_162_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/210_1_162/210_1_162_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/210_1_162/210_1_162_t2_thin_image_coregistered.nii.gz, nan)

 13%|█▎        | 237/1793 [01:54<14:19,  1.81it/s]

Original image path: ./raw_studies/t2_thin/210_2_231/210_2_231_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/210_2_231/210_2_231_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/210_2_231/210_2_231_t2_thin_image_coregistered.nii.gz, nan)

 13%|█▎        | 238/1793 [01:54<15:46,  1.64it/s]

Original image path: ./raw_studies/t1+_thin/210_2_231/210_2_231_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/210_2_231/210_2_231_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/210_2_231/210_2_231_t1+_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/210_2_231/210_2_231_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/210_2_231/210_2_231_t1+_thin_VS_uvauser1_coregistered.nii.gz)

 13%|█▎        | 239/1793 [01:56<23:27,  1.10it/s]

Original image path: ./raw_studies/t2_thin/210_2_231/210_2_231_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/210_2_231/210_2_231_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/210_2_231/210_2_231_t2_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/210_2_231/210_2_231_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/210_2_231/210_2_231_t2_thin_VS_uvauser1_coregistered.nii.gz)

 13%|█▎        | 240/1793 [01:57<22:25,  1.15it/s]

Original image path: ./raw_studies/t2_thin/215_0_0/215_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/215_0_0/215_0_0_t2_thin_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thin/215_0_0/215_0_0_t2_thin_1_uvauser4.nii.gz
Returning: (nan, nan)

 13%|█▎        | 241/1793 [01:58<22:39,  1.14it/s]

Original image path: ./raw_studies/t1+_thick_ax/215_0_0/215_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/215_0_0/215_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t1+_thick_ax/215_0_0/215_0_0_t1+_thick_ax_1_uvauser4.nii.gz
Returning: (nan, nan)

 13%|█▎        | 242/1793 [01:58<17:31,  1.48it/s]

Original image path: ./raw_studies/t1+_thick_cor/215_0_0/215_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/215_0_0/215_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t1+_thick_cor/215_0_0/215_0_0_t1+_thick_cor_1_uvauser4.nii.gz
Returning: (nan, nan)

 14%|█▎        | 244/1793 [01:58<11:36,  2.23it/s]

Original image path: ./raw_studies/t1+_thick_cor/215_1_114/215_1_114_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/215_1_114/215_1_114_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/215_1_114/215_1_114_t1+_thick_cor_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thick_ax/215_1_114/215_1_114_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/215_1_114/215_1_114_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/215_1_114/215_1_114_t1+_thick_ax_image_coregistered.nii.gz, nan)

 14%|█▎        | 245/1793 [01:59<09:21,  2.76it/s]

Original image path: ./raw_studies/t2_thin/215_1_114/215_1_114_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/215_1_114/215_1_114_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/215_1_114/215_1_114_t2_thin_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/215_1_114/215_1_114_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/215_1_114/215_1_114_t2_thin_tumorcore _uvauser3_coregistered.nii.gz)

 14%|█▎        | 246/1793 [01:59<12:25,  2.08it/s]

Original image path: ./raw_studies/t2_thin/215_2_322/215_2_322_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/215_2_322/215_2_322_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/215_2_322/215_2_322_t2_thin_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/215_2_322/215_2_322_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/215_2_322/215_2_322_t2_thin_RVS _uvauser2_coregistered.nii.gz)

 14%|█▍        | 247/1793 [02:00<14:20,  1.80it/s]

Original image path: ./raw_studies/t1+_thick_ax/215_2_322/215_2_322_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/215_2_322/215_2_322_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/215_2_322/215_2_322_t1+_thick_ax_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/215_2_322/215_2_322_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/215_2_322/215_2_322_t1+_thick_ax_RVS _uvauser2_coregistered.nii.gz)

 14%|█▍        | 249/1793 [02:01<09:35,  2.68it/s]

Original image path: ./raw_studies/t1+_thick_cor/215_2_322/215_2_322_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/215_2_322/215_2_322_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/215_2_322/215_2_322_t1+_thick_cor_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/215_2_322/215_2_322_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/215_2_322/215_2_322_t1+_thick_cor_RVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/218_0_0/218_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/218_0_0/218_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/218_0_0/218_0_0_t2_thin_VS_uvauser1-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/218_0_0/218_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/218_0_0/218_0_0_t2_thin_VS_uvauser1-copy_coregistered.nii.gz)

 14%|█▍        | 252/1793 [02:01<06:23,  4.02it/s]

Original image path: ./raw_studies/t1+_thick_ax/218_0_0/218_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/218_0_0/218_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/218_0_0/218_0_0_t1+_thick_ax_VS2_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/218_0_0/218_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/218_0_0/218_0_0_t1+_thick_ax_VS2_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/218_0_0/218_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/218_0_0/218_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/218_0_0/218_0_0_t1+_thick_cor_VS3_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/218_0_0/218_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/218_0_0/218_0_0_t1+_thick_cor_VS3_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/218_1_199/218_1_199_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/218_1_199/218_1_199_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/218_1_199/218_1_199_t1+_thick_ax_Tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/218_1_199/218_1_199_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/218_1_199/218_1_199_t1+_thick_ax_Tumorcore _uvauser3_coregistered.nii.gz)

 14%|█▍        | 254/1793 [02:01<05:11,  4.95it/s]

Original image path: ./raw_studies/t1+_thick_cor/218_1_199/218_1_199_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/218_1_199/218_1_199_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/218_1_199/218_1_199_t1+_thick_cor_Tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/218_1_199/218_1_199_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/218_1_199/218_1_199_t1+_thick_cor_Tumorcore _uvauser3_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/218_1_199/218_1_199_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/218_1_199/218_1_199_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/218_1_199/218_1_199_t2_thin_AX_Tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/218_1_199/218_1_199_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/218_1_199/218_1_199_t2_thin_AX_Tumorcore _uvauser3_coregistered.nii.gz)

 14%|█▍        | 256/1793 [02:02<06:42,  3.81it/s]

Original image path: ./raw_studies/t1+_thick_cor/218_2_731/218_2_731_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/218_2_731/218_2_731_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/218_2_731/218_2_731_t1+_thick_cor_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thick_ax/218_2_731/218_2_731_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/218_2_731/218_2_731_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/218_2_731/218_2_731_t1+_thick_ax_VS2_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/218_2_731/218_2_731_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/218_2_731/218_2_731_t1+_thick_ax_VS2_uvauser1_coregistered.nii.gz)

 14%|█▍        | 257/1793 [02:02<05:49,  4.39it/s]

Original image path: ./raw_studies/t1+_thick_ax/219_0_0/219_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/219_0_0/219_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/219_0_0/219_0_0_t1+_thick_ax_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t2_thin/219_0_0/219_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/219_0_0/219_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/219_0_0/219_0_0_t2_thin_T2Final_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/219_0_0/219_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/219_0_0/219_0_0_t2_thin_T2Final_VS_uvauser5_coregistered.nii.gz)

 15%|█▍        | 260/1793 [02:04<08:14,  3.10it/s]

Original image path: ./raw_studies/t2_thick/219_0_0/219_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/219_0_0/219_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

Original image path: ./raw_studies/t2_thick/222_0_0/222_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/222_0_0/222_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 15%|█▍        | 261/1793 [02:04<08:15,  3.09it/s]

Original image path: ./raw_studies/t1+_thick_cor/222_0_0/222_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/222_0_0/222_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/222_0_0/222_0_0_t1+_thick_cor_image_coregistered.nii.gz, nan)

 15%|█▍        | 262/1793 [02:04<07:39,  3.33it/s]

Original image path: ./raw_studies/t1+_thick_ax/222_0_0/222_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/222_0_0/222_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/222_0_0/222_0_0_t1+_thick_ax_image_coregistered.nii.gz, nan)

 15%|█▍        | 263/1793 [02:04<07:13,  3.53it/s]

Original image path: ./raw_studies/t2_thin/222_1_11/222_1_11_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/222_1_11/222_1_11_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/222_1_11/222_1_11_t2_thin_VST2_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/222_1_11/222_1_11_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/222_1_11/222_1_11_t2_thin_VST2_uvauser6_coregistered.nii.gz)

 15%|█▍        | 264/1793 [02:05<13:00,  1.96it/s]

Original image path: ./raw_studies/t1+_thick_cor/222_1_11/222_1_11_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/222_1_11/222_1_11_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/222_1_11/222_1_11_t1+_thick_cor_VST1cor_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/222_1_11/222_1_11_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/222_1_11/222_1_11_t1+_thick_cor_VST1cor_uvauser6_coregistered.nii.gz)

 15%|█▍        | 265/1793 [02:06<10:52,  2.34it/s]

Original image path: ./raw_studies/t1+_thick_ax/222_2_402/222_2_402_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/222_2_402/222_2_402_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/222_2_402/222_2_402_t1+_thick_ax_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/222_2_402/222_2_402_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/222_2_402/222_2_402_t1+_thick_ax_RVS _uvauser2_coregistered.nii.gz)

 15%|█▍        | 266/1793 [02:06<09:30,  2.68it/s]

Original image path: ./raw_studies/t2_thin/222_2_402/222_2_402_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/222_2_402/222_2_402_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/222_2_402/222_2_402_t2_thin_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/222_2_402/222_2_402_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/222_2_402/222_2_402_t2_thin_RVS _uvauser2_coregistered.nii.gz)

 15%|█▍        | 267/1793 [02:06<09:45,  2.61it/s]

Original image path: ./raw_studies/t1+_thick_cor/222_2_402/222_2_402_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/222_2_402/222_2_402_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/222_2_402/222_2_402_t1+_thick_cor_VST1cor_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/222_2_402/222_2_402_t1+_thick_cor_image_coregistered.nii.gz, nan)

 15%|█▍        | 268/1793 [02:07<09:45,  2.61it/s]

Original image path: ./raw_studies/t1+_thick_ax/229_0_0/229_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/229_0_0/229_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/229_0_0/229_0_0_t1+_thick_ax_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/229_0_0/229_0_0_t1+_thick_ax_image_coregistered.nii.gz, nan)

 15%|█▌        | 269/1793 [02:07<08:26,  3.01it/s]

Original image path: ./raw_studies/t1+_thick_cor/229_0_0/229_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/229_0_0/229_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/229_0_0/229_0_0_t1+_thick_cor_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/229_0_0/229_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/229_0_0/229_0_0_t1+_thick_cor_VS_uvauser5_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thick/229_0_0/229_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/229_0_0/229_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/229_0_0/229_0_0_t2_thick_T2VS_uvauser5.nii.gz
Returning: (nan, nan)

 15%|█▌        | 272/1793 [02:07<05:34,  4.55it/s]

Original image path: ./raw_studies/t1+_thick_ax/229_1_212/229_1_212_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/229_1_212/229_1_212_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/229_1_212/229_1_212_t1+_thick_ax_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/229_1_212/229_1_212_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/229_1_212/229_1_212_t1+_thick_ax_tumorcore _uvauser3_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/229_1_212/229_1_212_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/229_1_212/229_1_212_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/229_1_212/229_1_212_t1+_thick_cor_image_coregistered.nii.gz, nan)

 15%|█▌        | 273/1793 [02:07<05:05,  4.98it/s]

Original image path: ./raw_studies/t2_thin/229_1_212/229_1_212_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/229_1_212/229_1_212_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/229_1_212/229_1_212_t2_thin_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/229_1_212/229_1_212_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/229_1_212/229_1_212_t2_thin_tumorcore _uvauser3_coregistered.nii.gz)

 15%|█▌        | 275/1793 [02:08<05:53,  4.30it/s]

Original image path: ./raw_studies/t1+_thick_cor/229_2_576/229_2_576_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/229_2_576/229_2_576_t1+_thick_cor_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t1+_thick_cor/229_2_576/229_2_576_t1+_thick_cor_VST1cor_uvauser6.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thick_ax/229_2_576/229_2_576_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/229_2_576/229_2_576_t1+_thick_ax_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t1+_thick_ax/229_2_576/229_2_576_t1+_thick_ax_VST1ax_uvauser6.nii.gz
Returning: (nan, nan)

 15%|█▌        | 276/1793 [02:08<05:15,  4.81it/s]

Original image path: ./raw_studies/t2_thin/229_2_576/229_2_576_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/229_2_576/229_2_576_t2_thin_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thin/229_2_576/229_2_576_t2_thin_VST2_uvauser6.nii.gz
Returning: (nan, nan)

 16%|█▌        | 278/1793 [02:09<09:05,  2.78it/s]

Original image path: ./raw_studies/t1+_thick_cor/229_3_938/229_3_938_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/229_3_938/229_3_938_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/229_3_938/229_3_938_t1+_thick_cor_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/229_3_938/229_3_938_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/229_3_938/229_3_938_t1+_thick_cor_VS_uvauser5_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/229_3_938/229_3_938_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/229_3_938/229_3_938_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/229_3_938/229_3_938_t2_thin_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/229_3_938/229_3_938_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/229_3_938/229_3_938_t2_thin_AS_uvauser4_coregistered.nii.gz)

 16%|█▌        | 279/1793 [02:10<09:40,  2.61it/s]

Original image path: ./raw_studies/t1+_thick_ax/229_3_938/229_3_938_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/229_3_938/229_3_938_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/229_3_938/229_3_938_t1+_thick_ax_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/229_3_938/229_3_938_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/229_3_938/229_3_938_t1+_thick_ax_VS_uvauser5_coregistered.nii.gz)

 16%|█▌        | 281/1793 [02:10<07:56,  3.18it/s]

Original image path: ./raw_studies/t1+_thick_ax/229_4_1309/229_4_1309_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/229_4_1309/229_4_1309_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/229_4_1309/229_4_1309_t1+_thick_ax_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/229_4_1309/229_4_1309_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/229_4_1309/229_4_1309_t1+_thick_ax_tumorcore _uvauser3_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/229_4_1309/229_4_1309_t2_thin_image-rotated.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/229_4_1309/229_4_1309_t2_thin_image-rotated_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/229_4_1309/229_4_1309_t2_thin_image-rotated_coregistered.nii.gz, nan)

 16%|█▌        | 283/1793 [02:11<07:46,  3.24it/s]

Original image path: ./raw_studies/t1+_thick_cor/229_4_1309/229_4_1309_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/229_4_1309/229_4_1309_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/229_4_1309/229_4_1309_t1+_thick_cor_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thick_cor/229_5_1666/229_5_1666_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/229_5_1666/229_5_1666_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/229_5_1666/229_5_1666_t1+_thick_cor_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/229_5_1666/229_5_1666_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/229_5_1666/229_5_1666_t1+_thick_cor_VS_uvauser5_coregistered.nii.gz)

 16%|█▌        | 284/1793 [02:11<06:44,  3.73it/s]

Original image path: ./raw_studies/t2_thin/229_5_1666/229_5_1666_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/229_5_1666/229_5_1666_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/229_5_1666/229_5_1666_t2_thin_T2Final_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/229_5_1666/229_5_1666_t2_thin_image_coregistered.nii.gz, nan)

 16%|█▌        | 286/1793 [02:13<12:29,  2.01it/s]

Original image path: ./raw_studies/t1+_thick_ax/229_5_1666/229_5_1666_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/229_5_1666/229_5_1666_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/229_5_1666/229_5_1666_t1+_thick_ax_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/229_5_1666/229_5_1666_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/229_5_1666/229_5_1666_t1+_thick_ax_VS_uvauser5_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/235_0_0/235_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/235_0_0/235_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/235_0_0/235_0_0_t2_thin_1_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/235_0_0/235_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/235_0_0/235_0_0_t2_thin_1_uvauser4_coregistered.nii.gz)

 16%|█▌        | 287/1793 [02:14<17:01,  1.47it/s]

Original image path: ./raw_studies/t1+_thin/235_0_0/235_0_0_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/235_0_0/235_0_0_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/235_0_0/235_0_0_t1+_thin_2_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/235_0_0/235_0_0_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/235_0_0/235_0_0_t1+_thin_2_uvauser4_coregistered.nii.gz)

 16%|█▌        | 288/1793 [02:16<26:43,  1.07s/it]

Original image path: ./raw_studies/t1+_thin/235_1_328/235_1_328_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/235_1_328/235_1_328_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/235_1_328/235_1_328_t1+_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/235_1_328/235_1_328_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/235_1_328/235_1_328_t1+_thin_VS_uvauser1_coregistered.nii.gz)

 16%|█▌        | 289/1793 [02:16<22:15,  1.13it/s]

Original image path: ./raw_studies/t2_thin/235_1_328/235_1_328_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/235_1_328/235_1_328_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/235_1_328/235_1_328_t2_thin_image_coregistered.nii.gz, nan)

 16%|█▌        | 291/1793 [02:18<17:43,  1.41it/s]

Original image path: ./raw_studies/t1+_thick_ax/235_3_552/235_3_552_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/235_3_552/235_3_552_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/235_3_552/235_3_552_t1+_thick_ax_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/235_3_552/235_3_552_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/235_3_552/235_3_552_t1+_thick_ax_RVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/235_3_552/235_3_552_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/235_3_552/235_3_552_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/235_3_552/235_3_552_t2_thin_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/235_3_552/235_3_552_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/235_3_552/235_3_552_t2_thin_RVS _uvauser2_coregistered.nii.gz)

 16%|█▋        | 293/1793 [02:19<17:56,  1.39it/s]

Original image path: ./raw_studies/t1+_thick_cor/235_3_552/235_3_552_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/235_3_552/235_3_552_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/235_3_552/235_3_552_t1+_thick_cor_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/235_3_552/235_3_552_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/235_3_552/235_3_552_t1+_thick_cor_RVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thick/237_2_503/237_2_503_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/237_2_503/237_2_503_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 16%|█▋        | 294/1793 [02:20<14:25,  1.73it/s]

Original image path: ./raw_studies/t1+_thick_ax/237_2_503/237_2_503_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/237_2_503/237_2_503_t1+_thick_ax_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t1+_thick_ax/237_2_503/237_2_503_t1+_thick_ax_manual_0_uvauser8.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thick_ax/242_0_0/242_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/242_0_0/242_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/242_0_0/242_0_0_t1+_thick_ax_image_coregistered.nii.gz, nan)

 17%|█▋        | 297/1793 [02:20<08:02,  3.10it/s]

Original image path: ./raw_studies/t2_thick/242_0_0/242_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/242_0_0/242_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thick_cor/242_0_0/242_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/242_0_0/242_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/242_0_0/242_0_0_t1+_thick_cor_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/242_0_0/242_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/242_0_0/242_0_0_t1+_thick_cor_tumorcore _uvauser3_coregistered.nii.gz)

 17%|█▋        | 298/1793 [02:20<07:23,  3.37it/s]

Original image path: ./raw_studies/t1+_thin/242_1_1092/242_1_1092_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/242_1_1092/242_1_1092_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/242_1_1092/242_1_1092_t1+_thin_VST1_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/242_1_1092/242_1_1092_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/242_1_1092/242_1_1092_t1+_thin_VST1_uvauser6_coregistered.nii.gz)

 17%|█▋        | 300/1793 [02:21<08:59,  2.77it/s]

Original image path: ./raw_studies/t2_thick/242_1_1092/242_1_1092_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/242_1_1092/242_1_1092_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/242_1_1092/242_1_1092_t2_thick_VST2_uvauser6.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t2_thick/242_2_1470/242_2_1470_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/242_2_1470/242_2_1470_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 17%|█▋        | 301/1793 [02:21<07:53,  3.15it/s]

Original image path: ./raw_studies/t1+_thin/242_2_1470/242_2_1470_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/242_2_1470/242_2_1470_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/242_2_1470/242_2_1470_t1+_thin_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/242_2_1470/242_2_1470_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/242_2_1470/242_2_1470_t1+_thin_VS_uvauser5_coregistered.nii.gz)

 17%|█▋        | 303/1793 [02:22<07:51,  3.16it/s]

Original image path: ./raw_studies/t2_thick/242_2_1470/242_2_1470_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/242_2_1470/242_2_1470_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thin/242_3_2080/242_3_2080_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/242_3_2080/242_3_2080_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/242_3_2080/242_3_2080_t1+_thin_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/242_3_2080/242_3_2080_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/242_3_2080/242_3_2080_t1+_thin_VS_uvauser5_coregistered.nii.gz)

 17%|█▋        | 305/1793 [02:23<08:05,  3.06it/s]

Original image path: ./raw_studies/t2_thick/242_3_2080/242_3_2080_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/242_3_2080/242_3_2080_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

Original image path: ./raw_studies/t2_thick/242_4_2304/242_4_2304_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/242_4_2304/242_4_2304_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/242_4_2304/242_4_2304_t2_thick_manual_10_uvauser10.nii.gz
Returning: (nan, nan)

 17%|█▋        | 306/1793 [02:23<08:25,  2.94it/s]

Original image path: ./raw_studies/t1+_thin/242_5_2647/242_5_2647_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/242_5_2647/242_5_2647_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/242_5_2647/242_5_2647_t1+_thin_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/242_5_2647/242_5_2647_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/242_5_2647/242_5_2647_t1+_thin_RVS _uvauser2_coregistered.nii.gz)

 17%|█▋        | 308/1793 [02:24<07:27,  3.32it/s]

Original image path: ./raw_studies/t2_thick/242_5_2647/242_5_2647_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/242_5_2647/242_5_2647_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/242_5_2647/242_5_2647_t2_thick_RVS _uvauser2.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thick_cor/25_2_400/25_2_400_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/25_2_400/25_2_400_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/25_2_400/25_2_400_t1+_thick_cor_image_coregistered.nii.gz, nan)

 17%|█▋        | 310/1793 [02:24<05:50,  4.24it/s]

Original image path: ./raw_studies/t2_thick/25_2_400/25_2_400_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/25_2_400/25_2_400_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

Original image path: ./raw_studies/t2_thin/25_2_400/25_2_400_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/25_2_400/25_2_400_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/25_2_400/25_2_400_t2_thin_T2Final_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/25_2_400/25_2_400_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/25_2_400/25_2_400_t2_thin_T2Final_VS_uvauser5_coregistered.nii.gz)

 17%|█▋        | 311/1793 [02:24<06:18,  3.91it/s]

Original image path: ./raw_studies/t1+_thick_ax/25_2_400/25_2_400_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/25_2_400/25_2_400_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/25_2_400/25_2_400_t1+_thick_ax_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thick_cor/257_0_0/257_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/257_0_0/257_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/257_0_0/257_0_0_t1+_thick_cor_image_coregistered.nii.gz, nan)

 18%|█▊        | 314/1793 [02:25<04:24,  5.60it/s]

Original image path: ./raw_studies/t1+_thick_ax/257_0_0/257_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/257_0_0/257_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/257_0_0/257_0_0_t1+_thick_ax_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t2_thin/257_0_0/257_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/257_0_0/257_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/257_0_0/257_0_0_t2_thin_T2Final_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/257_0_0/257_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/257_0_0/257_0_0_t2_thin_T2Final_VS_uvauser5_coregistered.nii.gz)

 18%|█▊        | 315/1793 [02:25<06:42,  3.68it/s]

Original image path: ./raw_studies/t1+_thin/257_1_233/257_1_233_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/257_1_233/257_1_233_t1+_thin_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t1+_thin/257_1_233/257_1_233_t1+_thin_tumorcore _uvauser3.nii.gz
Returning: (nan, nan)

 18%|█▊        | 316/1793 [02:26<07:06,  3.46it/s]

Original image path: ./raw_studies/t2_thin/257_1_233/257_1_233_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/257_1_233/257_1_233_t2_thin_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 18%|█▊        | 317/1793 [02:27<12:20,  1.99it/s]

Original image path: ./raw_studies/t1+_thin/257_2_475/257_2_475_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/257_2_475/257_2_475_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/257_2_475/257_2_475_t1+_thin_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/257_2_475/257_2_475_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/257_2_475/257_2_475_t1+_thin_VS_uvauser5_coregistered.nii.gz)

 18%|█▊        | 318/1793 [02:27<11:59,  2.05it/s]

Original image path: ./raw_studies/t2_thin/257_2_475/257_2_475_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/257_2_475/257_2_475_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/257_2_475/257_2_475_t2_thin_image_coregistered.nii.gz, nan)

 18%|█▊        | 319/1793 [02:28<15:34,  1.58it/s]

Original image path: ./raw_studies/t2_thin/257_3_1018/257_3_1018_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/257_3_1018/257_3_1018_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/257_3_1018/257_3_1018_t2_thin_image_coregistered.nii.gz, nan)

 18%|█▊        | 320/1793 [02:29<19:18,  1.27it/s]

Original image path: ./raw_studies/t1+_thin/257_3_1018/257_3_1018_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/257_3_1018/257_3_1018_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/257_3_1018/257_3_1018_t1+_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/257_3_1018/257_3_1018_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/257_3_1018/257_3_1018_t1+_thin_VS_uvauser1_coregistered.nii.gz)

 18%|█▊        | 321/1793 [02:30<15:56,  1.54it/s]

Original image path: ./raw_studies/t1+_thick_ax/258_0_0/258_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/258_0_0/258_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/258_0_0/258_0_0_t1+_thick_ax_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t2_thin/258_0_0/258_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/258_0_0/258_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/258_0_0/258_0_0_t2_thin_image_coregistered.nii.gz, nan)

 18%|█▊        | 323/1793 [02:30<11:18,  2.17it/s]

Original image path: ./raw_studies/t1+_thick_cor/258_0_0/258_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/258_0_0/258_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/258_0_0/258_0_0_t1+_thick_cor_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thin/258_0_0/258_0_0_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/258_0_0/258_0_0_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/258_0_0/258_0_0_t1+_thin_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/258_0_0/258_0_0_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/258_0_0/258_0_0_t1+_thin_tumorcore _uvauser3_coregistered.nii.gz)

 18%|█▊        | 325/1793 [02:31<09:18,  2.63it/s]

Original image path: ./raw_studies/t1+_thin/258_1_15/258_1_15_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/258_1_15/258_1_15_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/258_1_15/258_1_15_t1+_thin_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/258_1_15/258_1_15_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/258_1_15/258_1_15_t1+_thin_tumorcore _uvauser3_coregistered.nii.gz)

 18%|█▊        | 326/1793 [02:31<09:39,  2.53it/s]

Original image path: ./raw_studies/t2_thin/258_1_15/258_1_15_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/258_1_15/258_1_15_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/258_1_15/258_1_15_t2_thin_image_coregistered.nii.gz, nan)

 18%|█▊        | 327/1793 [02:32<10:12,  2.39it/s]

Original image path: ./raw_studies/t1+_thin/258_2_96/258_2_96_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/258_2_96/258_2_96_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/258_2_96/258_2_96_t1+_thin_VST1ax_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/258_2_96/258_2_96_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/258_2_96/258_2_96_t1+_thin_VST1ax_uvauser6_coregistered.nii.gz)

 18%|█▊        | 328/1793 [02:32<10:43,  2.28it/s]

Original image path: ./raw_studies/t2_thin/258_2_96/258_2_96_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/258_2_96/258_2_96_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/258_2_96/258_2_96_t2_thin_VST2_uvauser6-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/258_2_96/258_2_96_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/258_2_96/258_2_96_t2_thin_VST2_uvauser6-copy_coregistered.nii.gz)

 18%|█▊        | 329/1793 [02:33<11:35,  2.11it/s]

Original image path: ./raw_studies/t1+_thin/262_0_0/262_0_0_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/262_0_0/262_0_0_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/262_0_0/262_0_0_t1+_thin_image_coregistered.nii.gz, nan)

 18%|█▊        | 331/1793 [02:33<10:41,  2.28it/s]

Original image path: ./raw_studies/t2_thick/262_0_0/262_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/262_0_0/262_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thin/262_0_0/262_0_0_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/262_0_0/262_0_0_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/262_0_0/262_0_0_t1+_thin_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/262_0_0/262_0_0_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/262_0_0/262_0_0_t1+_thin_VS_uvauser5_coregistered.nii.gz)

 19%|█▊        | 332/1793 [02:34<11:58,  2.03it/s]

Original image path: ./raw_studies/t2_thin/262_0_0/262_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/262_0_0/262_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/262_0_0/262_0_0_t2_thin_image_coregistered.nii.gz, nan)

 19%|█▊        | 333/1793 [02:35<11:24,  2.13it/s]

Original image path: ./raw_studies/t1+_thick_ax/262_1_497/262_1_497_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/262_1_497/262_1_497_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/262_1_497/262_1_497_t1+_thick_ax_VST1_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/262_1_497/262_1_497_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/262_1_497/262_1_497_t1+_thick_ax_VST1_uvauser6_coregistered.nii.gz)

 19%|█▊        | 334/1793 [02:35<12:37,  1.92it/s]

Original image path: ./raw_studies/t2_thin/262_1_497/262_1_497_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/262_1_497/262_1_497_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/262_1_497/262_1_497_t2_thin_VST2_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/262_1_497/262_1_497_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/262_1_497/262_1_497_t2_thin_VST2_uvauser6_coregistered.nii.gz)

 19%|█▊        | 335/1793 [02:36<12:01,  2.02it/s]

Original image path: ./raw_studies/t1+_thin/262_1_497/262_1_497_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/262_1_497/262_1_497_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/262_1_497/262_1_497_t1+_thin_image_coregistered.nii.gz, nan)

 19%|█▉        | 337/1793 [02:36<09:07,  2.66it/s]

Original image path: ./raw_studies/t1+_thick_ax/267_0_0/267_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/267_0_0/267_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/267_0_0/267_0_0_t1+_thick_ax_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/267_0_0/267_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/267_0_0/267_0_0_t1+_thick_ax_VS_uvauser5_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/267_0_0/267_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/267_0_0/267_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/267_0_0/267_0_0_t2_thin_T2Final_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/267_0_0/267_0_0_t2_thin_image_coregistered.nii.gz, nan)

 19%|█▉        | 339/1793 [02:38<11:57,  2.03it/s]

Original image path: ./raw_studies/t1+_thick_cor/267_0_0/267_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/267_0_0/267_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/267_0_0/267_0_0_t1+_thick_cor_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/267_0_0/267_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/267_0_0/267_0_0_t1+_thick_cor_VS_uvauser5_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/267_1_195/267_1_195_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/267_1_195/267_1_195_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/267_1_195/267_1_195_t1+_thick_ax_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/267_1_195/267_1_195_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/267_1_195/267_1_195_t1+_thick_ax_tumorcore _uvauser3_coregistered.nii.gz)

 19%|█▉        | 341/1793 [02:38<07:58,  3.04it/s]

Original image path: ./raw_studies/t1+_thick_cor/267_1_195/267_1_195_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/267_1_195/267_1_195_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/267_1_195/267_1_195_t1+_thick_cor_VST1cor_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/267_1_195/267_1_195_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/267_1_195/267_1_195_t1+_thick_cor_VST1cor_uvauser6_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/267_1_195/267_1_195_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/267_1_195/267_1_195_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/267_1_195/267_1_195_t2_thin_VST2_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/267_1_195/267_1_195_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/267_1_195/267_1_195_t2_thin_VST2_uvauser6_coregistered.nii.gz)

 19%|█▉        | 342/1793 [02:39<12:38,  1.91it/s]

Original image path: ./raw_studies/t2_thin/267_2_554/267_2_554_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/267_2_554/267_2_554_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/267_2_554/267_2_554_t2_thin_AX_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/267_2_554/267_2_554_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/267_2_554/267_2_554_t2_thin_AX_VS_uvauser1_coregistered.nii.gz)

 19%|█▉        | 344/1793 [02:40<12:36,  1.91it/s]

Original image path: ./raw_studies/t1+_thick_cor/267_2_554/267_2_554_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/267_2_554/267_2_554_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/267_2_554/267_2_554_t1+_thick_cor_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/267_2_554/267_2_554_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/267_2_554/267_2_554_t1+_thick_cor_VS_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/267_2_554/267_2_554_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/267_2_554/267_2_554_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/267_2_554/267_2_554_t1+_thick_ax_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/267_2_554/267_2_554_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/267_2_554/267_2_554_t1+_thick_ax_VS_uvauser1_coregistered.nii.gz)

 19%|█▉        | 345/1793 [02:40<10:04,  2.39it/s]

Original image path: ./raw_studies/t2_thin/267_3_916/267_3_916_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/267_3_916/267_3_916_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/267_3_916/267_3_916_t2_thin_VST2_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/267_3_916/267_3_916_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/267_3_916/267_3_916_t2_thin_VST2_uvauser6_coregistered.nii.gz)

 19%|█▉        | 347/1793 [02:41<11:09,  2.16it/s]

Original image path: ./raw_studies/t1+_thick_ax/267_3_916/267_3_916_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/267_3_916/267_3_916_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/267_3_916/267_3_916_t1+_thick_ax_VST1ax_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/267_3_916/267_3_916_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/267_3_916/267_3_916_t1+_thick_ax_VST1ax_uvauser6_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/267_3_916/267_3_916_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/267_3_916/267_3_916_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/267_3_916/267_3_916_t1+_thick_cor_VST1cor_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/267_3_916/267_3_916_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/267_3_916/267_3_916_t1+_thick_cor_VST1cor_uvauser6_coregistered.nii.gz)

 19%|█▉        | 349/1793 [02:42<07:15,  3.31it/s]

Original image path: ./raw_studies/t1+_thick_ax/267_4_1278/267_4_1278_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/267_4_1278/267_4_1278_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/267_4_1278/267_4_1278_t1+_thick_ax_VST1ax_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/267_4_1278/267_4_1278_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/267_4_1278/267_4_1278_t1+_thick_ax_VST1ax_uvauser6_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/267_4_1278/267_4_1278_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/267_4_1278/267_4_1278_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/267_4_1278/267_4_1278_t2_thin_VST2_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/267_4_1278/267_4_1278_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/267_4_1278/267_4_1278_t2_thin_VST2_uvauser6_coregistered.nii.gz)

 20%|█▉        | 351/1793 [02:43<10:38,  2.26it/s]

Original image path: ./raw_studies/t1+_thick_cor/267_4_1278/267_4_1278_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/267_4_1278/267_4_1278_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/267_4_1278/267_4_1278_t1+_thick_cor_VST1cor_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/267_4_1278/267_4_1278_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/267_4_1278/267_4_1278_t1+_thick_cor_VST1cor_uvauser6_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/267_5_1693/267_5_1693_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/267_5_1693/267_5_1693_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/267_5_1693/267_5_1693_t1+_thick_ax_VST1ax_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/267_5_1693/267_5_1693_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/267_5_1693/267_5_1693_t1+_thick_ax_VST1ax_uvauser6_coregistered.nii.gz)

 20%|█▉        | 352/1793 [02:43<08:39,  2.78it/s]

Original image path: ./raw_studies/t2_thin/267_5_1693/267_5_1693_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/267_5_1693/267_5_1693_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/267_5_1693/267_5_1693_t2_thin_VST2_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/267_5_1693/267_5_1693_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/267_5_1693/267_5_1693_t2_thin_VST2_uvauser6_coregistered.nii.gz)

 20%|█▉        | 354/1793 [02:44<10:34,  2.27it/s]

Original image path: ./raw_studies/t1+_thick_cor/267_5_1693/267_5_1693_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/267_5_1693/267_5_1693_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/267_5_1693/267_5_1693_t1+_thick_cor_VST1cor_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/267_5_1693/267_5_1693_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/267_5_1693/267_5_1693_t1+_thick_cor_VST1cor_uvauser6_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/270_0_0/270_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/270_0_0/270_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/270_0_0/270_0_0_t1+_thick_ax_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/270_0_0/270_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/270_0_0/270_0_0_t1+_thick_ax_VS_uvauser1_coregistered.nii.gz)

 20%|█▉        | 356/1793 [02:45<06:25,  3.73it/s]

Original image path: ./raw_studies/t1+_thick_cor/270_0_0/270_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/270_0_0/270_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/270_0_0/270_0_0_t1+_thick_cor_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/270_0_0/270_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/270_0_0/270_0_0_t1+_thick_cor_VS_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/270_0_0/270_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/270_0_0/270_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/270_0_0/270_0_0_t2_thin_AX_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/270_0_0/270_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/270_0_0/270_0_0_t2_thin_AX_VS_uvauser1_coregistered.nii.gz)

 20%|█▉        | 357/1793 [02:45<06:44,  3.55it/s]

Original image path: ./raw_studies/t1+_thick_ax/270_1_324/270_1_324_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/270_1_324/270_1_324_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/270_1_324/270_1_324_t1+_thick_ax_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/270_1_324/270_1_324_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/270_1_324/270_1_324_t1+_thick_ax_AS_uvauser4_coregistered.nii.gz)

 20%|██        | 359/1793 [02:45<05:47,  4.13it/s]

Original image path: ./raw_studies/t1+_thick_cor/270_1_324/270_1_324_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/270_1_324/270_1_324_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/270_1_324/270_1_324_t1+_thick_cor_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/270_1_324/270_1_324_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/270_1_324/270_1_324_t1+_thick_cor_AS_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/270_1_324/270_1_324_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/270_1_324/270_1_324_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/270_1_324/270_1_324_t2_thin_AS_uvauser4-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/270_1_324/270_1_324_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/270_1_324/270_1_324_t2_thin_AS_uvauser4-copy_coregistered.nii.gz)

 20%|██        | 360/1793 [02:46<08:53,  2.68it/s]

Original image path: ./raw_studies/t1+_thick_ax/270_2_551/270_2_551_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/270_2_551/270_2_551_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/270_2_551/270_2_551_t1+_thick_ax_VST1ax_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/270_2_551/270_2_551_t1+_thick_ax_image_coregistered.nii.gz, nan)

 20%|██        | 361/1793 [02:47<12:01,  1.98it/s]

Original image path: ./raw_studies/t1+_thick_cor/270_2_551/270_2_551_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/270_2_551/270_2_551_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/270_2_551/270_2_551_t1+_thick_cor_VST1cor_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/270_2_551/270_2_551_t1+_thick_cor_image_coregistered.nii.gz, nan)

 20%|██        | 363/1793 [02:48<11:32,  2.06it/s]

Original image path: ./raw_studies/t2_thick/270_2_551/270_2_551_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/270_2_551/270_2_551_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/270_2_551/270_2_551_t2_thick_VST2_uvauser6.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t2_thick/270_2_551/270_2_551_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/270_2_551/270_2_551_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/270_2_551/270_2_551_t2_thick_LVS _uvauser2.nii.gz
Returning: (nan, nan)

 20%|██        | 365/1793 [02:48<08:04,  2.95it/s]

Original image path: ./raw_studies/t2_thick/275_0_0/275_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/275_0_0/275_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/275_0_0/275_0_0_t2_thick_RVS _uvauser2.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t2_thin/275_1_17/275_1_17_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/275_1_17/275_1_17_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/275_1_17/275_1_17_t2_thin_image_coregistered.nii.gz, nan)

 20%|██        | 366/1793 [02:49<08:53,  2.67it/s]

Original image path: ./raw_studies/t2_thin/275_1_17/275_1_17_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/275_1_17/275_1_17_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/275_1_17/275_1_17_t2_thin_image_coregistered.nii.gz, nan)

 20%|██        | 367/1793 [02:49<09:30,  2.50it/s]

Original image path: ./raw_studies/t1+_thin/275_2_121/275_2_121_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/275_2_121/275_2_121_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/275_2_121/275_2_121_t1+_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/275_2_121/275_2_121_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/275_2_121/275_2_121_t1+_thin_VS_uvauser1_coregistered.nii.gz)

 21%|██        | 368/1793 [02:51<16:37,  1.43it/s]

Original image path: ./raw_studies/t2_thin/275_2_121/275_2_121_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/275_2_121/275_2_121_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/275_2_121/275_2_121_t2_thin_image_coregistered.nii.gz, nan)

 21%|██        | 370/1793 [02:51<11:39,  2.03it/s]

Original image path: ./raw_studies/t1+_thick_ax/286_0_0/286_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/286_0_0/286_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/286_0_0/286_0_0_t1+_thick_ax_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/286_0_0/286_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/286_0_0/286_0_0_t1+_thick_ax_LVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/286_0_0/286_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/286_0_0/286_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/286_0_0/286_0_0_t2_thin_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/286_0_0/286_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/286_0_0/286_0_0_t2_thin_LVS _uvauser2_coregistered.nii.gz)

 21%|██        | 372/1793 [02:52<09:53,  2.39it/s]

Original image path: ./raw_studies/t2_thick/286_0_0/286_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/286_0_0/286_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/286_0_0/286_0_0_t2_thick_LVS _uvauser2.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thick_cor/286_0_0/286_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/286_0_0/286_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/286_0_0/286_0_0_t1+_thick_cor_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/286_0_0/286_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/286_0_0/286_0_0_t1+_thick_cor_LVS _uvauser2_coregistered.nii.gz)

 21%|██        | 374/1793 [02:52<06:23,  3.70it/s]

Original image path: ./raw_studies/t1+_thick_cor/286_1_190/286_1_190_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/286_1_190/286_1_190_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/286_1_190/286_1_190_t1+_thick_cor_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/286_1_190/286_1_190_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/286_1_190/286_1_190_t1+_thick_cor_LVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/286_1_190/286_1_190_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/286_1_190/286_1_190_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/286_1_190/286_1_190_t2_thin_image_coregistered.nii.gz, nan)

 21%|██        | 376/1793 [02:53<07:11,  3.29it/s]

Original image path: ./raw_studies/t2_thick/286_1_190/286_1_190_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/286_1_190/286_1_190_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/286_1_190/286_1_190_t2_thick_LVS _uvauser2.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thick_ax/286_1_190/286_1_190_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/286_1_190/286_1_190_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/286_1_190/286_1_190_t1+_thick_ax_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/286_1_190/286_1_190_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/286_1_190/286_1_190_t1+_thick_ax_LVS _uvauser2_coregistered.nii.gz)

 21%|██        | 377/1793 [02:53<06:28,  3.64it/s]

Original image path: ./raw_studies/t2_thin/286_2_297/286_2_297_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/286_2_297/286_2_297_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/286_2_297/286_2_297_t2_thin_1_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/286_2_297/286_2_297_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/286_2_297/286_2_297_t2_thin_1_uvauser4_coregistered.nii.gz)

 21%|██        | 379/1793 [02:54<06:45,  3.49it/s]

Original image path: ./raw_studies/t1+_thick_ax/286_2_297/286_2_297_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/286_2_297/286_2_297_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/286_2_297/286_2_297_t1+_thick_ax_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thick_cor/286_2_297/286_2_297_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/286_2_297/286_2_297_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/286_2_297/286_2_297_t1+_thick_cor_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thin/286_2_297/286_2_297_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/286_2_297/286_2_297_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/286_2_297/286_2_297_t1+_thin_image_coregistered.nii.gz, nan)

 21%|██        | 381/1793 [02:55<10:59,  2.14it/s]

Original image path: ./raw_studies/t1+_thin/299_1_637/299_1_637_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/299_1_637/299_1_637_t1+_thin_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t1+_thin/299_1_637/299_1_637_t1+_thin_manual_0_uvauser1.nii.gz
Returning: (nan, nan)

 21%|██▏       | 382/1793 [02:56<14:19,  1.64it/s]

Original image path: ./raw_studies/t2_thin/301_0_0/301_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/301_0_0/301_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/301_0_0/301_0_0_t2_thin_RVS _uvauser2-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/301_0_0/301_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/301_0_0/301_0_0_t2_thin_RVS _uvauser2-copy_coregistered.nii.gz)

 21%|██▏       | 383/1793 [02:57<14:17,  1.65it/s]

Original image path: ./raw_studies/t1+_thick_ax/301_0_0/301_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/301_0_0/301_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/301_0_0/301_0_0_t1+_thick_ax_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/301_0_0/301_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/301_0_0/301_0_0_t1+_thick_ax_RVS _uvauser2_coregistered.nii.gz)

 21%|██▏       | 385/1793 [02:57<09:09,  2.56it/s]

Original image path: ./raw_studies/t1+_thick_cor/301_0_0/301_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/301_0_0/301_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/301_0_0/301_0_0_t1+_thick_cor_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/301_0_0/301_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/301_0_0/301_0_0_t1+_thick_cor_RVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thin/301_1_229/301_1_229_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/301_1_229/301_1_229_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/301_1_229/301_1_229_t1+_thin_RVS _uvauser2-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/301_1_229/301_1_229_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/301_1_229/301_1_229_t1+_thin_RVS _uvauser2-copy_coregistered.nii.gz)

 22%|██▏       | 386/1793 [02:59<18:48,  1.25it/s]

Original image path: ./raw_studies/t1+_thick_cor/301_1_229/301_1_229_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/301_1_229/301_1_229_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/301_1_229/301_1_229_t1+_thick_cor_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/301_1_229/301_1_229_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/301_1_229/301_1_229_t1+_thick_cor_RVS _uvauser2_coregistered.nii.gz)

 22%|██▏       | 387/1793 [02:59<14:49,  1.58it/s]

Original image path: ./raw_studies/t2_thin/301_1_229/301_1_229_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/301_1_229/301_1_229_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/301_1_229/301_1_229_t2_thin_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/301_1_229/301_1_229_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/301_1_229/301_1_229_t2_thin_RVS _uvauser2_coregistered.nii.gz)

 22%|██▏       | 388/1793 [03:00<18:04,  1.30it/s]

Original image path: ./raw_studies/t1+_thin/301_2_614/301_2_614_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/301_2_614/301_2_614_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/301_2_614/301_2_614_t1+_thin_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/301_2_614/301_2_614_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/301_2_614/301_2_614_t1+_thin_AS_uvauser4_coregistered.nii.gz)

 22%|██▏       | 389/1793 [03:01<15:42,  1.49it/s]

Original image path: ./raw_studies/t2_thin/301_2_614/301_2_614_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/301_2_614/301_2_614_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/301_2_614/301_2_614_t2_thin_AS1_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/301_2_614/301_2_614_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/301_2_614/301_2_614_t2_thin_AS1_uvauser4_coregistered.nii.gz)

 22%|██▏       | 390/1793 [03:02<18:41,  1.25it/s]

Original image path: ./raw_studies/t1+_thick_cor/301_2_614/301_2_614_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/301_2_614/301_2_614_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/301_2_614/301_2_614_t1+_thick_cor_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/301_2_614/301_2_614_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/301_2_614/301_2_614_t1+_thick_cor_AS_uvauser4_coregistered.nii.gz)

 22%|██▏       | 393/1793 [03:02<08:45,  2.67it/s]

Original image path: ./raw_studies/t1+_thick_cor/304_0_0/304_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/304_0_0/304_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/304_0_0/304_0_0_t1+_thick_cor_VS1_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/304_0_0/304_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/304_0_0/304_0_0_t1+_thick_cor_VS1_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/304_0_0/304_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/304_0_0/304_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/304_0_0/304_0_0_t1+_thick_ax_VS2_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/304_0_0/304_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/304_0_0/304_0_0_t1+_thick_ax_VS2_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/304_0_0/304_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/304_0_0/304_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/304_0_0/304_0_0_t2_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/304_0_0/304_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/304_0_0/304_0_0_t2_thin_VS_uvauser1_coregistered.nii.gz)

 22%|██▏       | 395/1793 [03:03<10:14,  2.27it/s]

Original image path: ./raw_studies/t1+_thick_cor/304_1_206/304_1_206_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/304_1_206/304_1_206_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/304_1_206/304_1_206_t1+_thick_cor_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/304_1_206/304_1_206_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/304_1_206/304_1_206_t1+_thick_cor_RVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/304_1_206/304_1_206_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/304_1_206/304_1_206_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/304_1_206/304_1_206_t2_thin_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/304_1_206/304_1_206_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/304_1_206/304_1_206_t2_thin_RVS _uvauser2_coregistered.nii.gz)

 22%|██▏       | 397/1793 [03:05<10:59,  2.12it/s]

Original image path: ./raw_studies/t1+_thick_ax/304_1_206/304_1_206_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/304_1_206/304_1_206_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/304_1_206/304_1_206_t1+_thick_ax_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/304_1_206/304_1_206_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/304_1_206/304_1_206_t1+_thick_ax_RVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thin/304_2_305/304_2_305_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/304_2_305/304_2_305_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/304_2_305/304_2_305_t1+_thin_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/304_2_305/304_2_305_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/304_2_305/304_2_305_t1+_thin_AS_uvauser4_coregistered.nii.gz)

 22%|██▏       | 398/1793 [03:05<10:27,  2.22it/s]

Original image path: ./raw_studies/t2_thin/304_2_305/304_2_305_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/304_2_305/304_2_305_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/304_2_305/304_2_305_t2_thin_AS1_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/304_2_305/304_2_305_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/304_2_305/304_2_305_t2_thin_AS1_uvauser4_coregistered.nii.gz)

 22%|██▏       | 399/1793 [03:05<09:30,  2.45it/s]

Original image path: ./raw_studies/t1+_thick_ax/308_0_0/308_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/308_0_0/308_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/308_0_0/308_0_0_t1+_thick_ax_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/308_0_0/308_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/308_0_0/308_0_0_t1+_thick_ax_AS_uvauser4_coregistered.nii.gz)

 22%|██▏       | 400/1793 [03:05<08:11,  2.83it/s]

Original image path: ./raw_studies/t1+_thick_cor/308_0_0/308_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/308_0_0/308_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/308_0_0/308_0_0_t1+_thick_cor_AS1_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/308_0_0/308_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/308_0_0/308_0_0_t1+_thick_cor_AS1_uvauser4_coregistered.nii.gz)

 22%|██▏       | 401/1793 [03:06<07:24,  3.13it/s]

Original image path: ./raw_studies/t2_thick/308_0_0/308_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/308_0_0/308_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thick_ax/308_1_189/308_1_189_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/308_1_189/308_1_189_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/308_1_189/308_1_189_t1+_thick_ax_VS1_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/308_1_189/308_1_189_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/308_1_189/308_1_189_t1+_thick_ax_VS1_uvauser1_coregistered.nii.gz)

 22%|██▏       | 403/1793 [03:06<05:16,  4.40it/s]

Original image path: ./raw_studies/t2_thin/308_1_189/308_1_189_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/308_1_189/308_1_189_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/308_1_189/308_1_189_t2_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/308_1_189/308_1_189_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/308_1_189/308_1_189_t2_thin_VS_uvauser1_coregistered.nii.gz)

 23%|██▎       | 405/1793 [03:07<08:23,  2.76it/s]

Original image path: ./raw_studies/t1+_thick_cor/308_1_189/308_1_189_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/308_1_189/308_1_189_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/308_1_189/308_1_189_t1+_thick_cor_VS2_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/308_1_189/308_1_189_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/308_1_189/308_1_189_t1+_thick_cor_VS2_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thin/308_2_521/308_2_521_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/308_2_521/308_2_521_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/308_2_521/308_2_521_t1+_thin_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/308_2_521/308_2_521_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/308_2_521/308_2_521_t1+_thin_RVS _uvauser2_coregistered.nii.gz)

 23%|██▎       | 407/1793 [03:08<06:13,  3.72it/s]

Original image path: ./raw_studies/t1+_thick_cor/308_2_521/308_2_521_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/308_2_521/308_2_521_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/308_2_521/308_2_521_t1+_thick_cor_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/308_2_521/308_2_521_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/308_2_521/308_2_521_t1+_thick_cor_RVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/308_2_521/308_2_521_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/308_2_521/308_2_521_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/308_2_521/308_2_521_t2_thin_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/308_2_521/308_2_521_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/308_2_521/308_2_521_t2_thin_RVS _uvauser2_coregistered.nii.gz)

 23%|██▎       | 409/1793 [03:08<06:10,  3.74it/s]

Original image path: ./raw_studies/t2_thick/309_0_0/309_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/309_0_0/309_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/309_0_0/309_0_0_t2_thick_VST2_uvauser6-copy.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thin/309_0_0/309_0_0_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/309_0_0/309_0_0_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/309_0_0/309_0_0_t1+_thin_VST1thin_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/309_0_0/309_0_0_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/309_0_0/309_0_0_t1+_thin_VST1thin_uvauser6_coregistered.nii.gz)

 23%|██▎       | 410/1793 [03:08<06:57,  3.31it/s]

Original image path: ./raw_studies/t2_thin/309_1_177/309_1_177_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/309_1_177/309_1_177_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/309_1_177/309_1_177_t2_thin_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/309_1_177/309_1_177_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/309_1_177/309_1_177_t2_thin_RVS _uvauser2_coregistered.nii.gz)

 23%|██▎       | 411/1793 [03:09<11:33,  1.99it/s]

Original image path: ./raw_studies/t1+_thin/309_1_177/309_1_177_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/309_1_177/309_1_177_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/309_1_177/309_1_177_t1+_thin_RVS _uvauser2-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/309_1_177/309_1_177_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/309_1_177/309_1_177_t1+_thin_RVS _uvauser2-copy_coregistered.nii.gz)

 23%|██▎       | 412/1793 [03:10<11:14,  2.05it/s]

Original image path: ./raw_studies/t2_thin/309_2_546/309_2_546_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/309_2_546/309_2_546_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/309_2_546/309_2_546_t2_thin_image_coregistered.nii.gz, nan)

 23%|██▎       | 413/1793 [03:11<14:14,  1.62it/s]

Original image path: ./raw_studies/t1+_thin/309_2_546/309_2_546_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/309_2_546/309_2_546_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/309_2_546/309_2_546_t1+_thin_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/309_2_546/309_2_546_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/309_2_546/309_2_546_t1+_thin_VS_uvauser5_coregistered.nii.gz)

 23%|██▎       | 414/1793 [03:11<12:53,  1.78it/s]

Original image path: ./raw_studies/t1+_thin/309_3_917/309_3_917_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/309_3_917/309_3_917_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/309_3_917/309_3_917_t1+_thin_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/309_3_917/309_3_917_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/309_3_917/309_3_917_t1+_thin_RVS _uvauser2_coregistered.nii.gz)

 23%|██▎       | 415/1793 [03:12<11:55,  1.93it/s]

Original image path: ./raw_studies/t2_thin/309_3_917/309_3_917_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/309_3_917/309_3_917_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/309_3_917/309_3_917_t2_thin_RVS _uvauser2-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/309_3_917/309_3_917_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/309_3_917/309_3_917_t2_thin_RVS _uvauser2-copy_coregistered.nii.gz)

 23%|██▎       | 416/1793 [03:13<14:44,  1.56it/s]

Original image path: ./raw_studies/t1+_thin/313_4_1123/313_4_1123_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/313_4_1123/313_4_1123_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/313_4_1123/313_4_1123_t1+_thin_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/313_4_1123/313_4_1123_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/313_4_1123/313_4_1123_t1+_thin_VS_uvauser5_coregistered.nii.gz)

 23%|██▎       | 417/1793 [03:14<19:54,  1.15it/s]

Original image path: ./raw_studies/t1+_thin/313_4_1123/313_4_1123_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/313_4_1123/313_4_1123_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/313_4_1123/313_4_1123_t1+_thin_image_coregistered.nii.gz, nan)

 23%|██▎       | 420/1793 [03:16<13:31,  1.69it/s]

Original image path: ./raw_studies/t1+_thick_ax/315_1_2738/315_1_2738_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/315_1_2738/315_1_2738_t1+_thick_ax_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t1+_thick_ax/315_1_2738/315_1_2738_t1+_thick_ax_manual_0_uvauser1.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thick_cor/315_1_2738/315_1_2738_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/315_1_2738/315_1_2738_t1+_thick_cor_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t1+_thick_cor/315_1_2738/315_1_2738_t1+_thick_cor_manual_0_uvauser1.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t2_thick/315_1_2738/315_1_2738_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/315_1_2738/315_1_2738_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/315_1_2738/315_1_2738_t2_thick_manual_0_uvauser1.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thin/315_2_2947/315_2_2947_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/315_2_2947/315_2_2947_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/315_2_2947/315_2_2947_t1+_thin_VST2_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/315_2_2947/315_2_2947_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/315_2_2947/315_2_2947_t1+_thin_VST2_uvauser6_coregistered.nii.gz)

 24%|██▎       | 422/1793 [03:17<13:53,  1.64it/s]

Original image path: ./raw_studies/t2_thin/315_2_2947/315_2_2947_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/315_2_2947/315_2_2947_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/315_2_2947/315_2_2947_t2_thin_VST1thin_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/315_2_2947/315_2_2947_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/315_2_2947/315_2_2947_t2_thin_VST1thin_uvauser6_coregistered.nii.gz)

 24%|██▎       | 424/1793 [03:18<13:48,  1.65it/s]

Original image path: ./raw_studies/t2_thick/317_0_0/317_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/317_0_0/317_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/317_0_0/317_0_0_t2_thick_VS_uvauser1.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thick_ax/317_0_0/317_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/317_0_0/317_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/317_0_0/317_0_0_t1+_thick_ax_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/317_0_0/317_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/317_0_0/317_0_0_t1+_thick_ax_VS_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/317_1_222/317_1_222_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/317_1_222/317_1_222_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/317_1_222/317_1_222_t2_thin_VST2_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/317_1_222/317_1_222_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/317_1_222/317_1_222_t2_thin_VST2_uvauser6_coregistered.nii.gz)

 24%|██▍       | 428/1793 [03:19<07:10,  3.17it/s]

Original image path: ./raw_studies/t1+_thick_ax/317_1_222/317_1_222_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/317_1_222/317_1_222_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/317_1_222/317_1_222_t1+_thick_ax_VST1ax_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/317_1_222/317_1_222_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/317_1_222/317_1_222_t1+_thick_ax_VST1ax_uvauser6_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/317_1_222/317_1_222_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/317_1_222/317_1_222_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/317_1_222/317_1_222_t1+_thick_cor_VST1cor_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/317_1_222/317_1_222_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/317_1_222/317_1_222_t1+_thick_cor_VST1cor_uvauser6_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thick/317_2_321/317_2_321_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/317_2_321/317_2_321_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/317_2_321/317_2_321_t2_thick_VST2_uvauser6.nii.gz
Returning: (nan, nan)

 24%|██▍       | 429/1793 [03:19<06:49,  3.33it/s]

Original image path: ./raw_studies/t1+_thick_cor/317_2_321/317_2_321_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/317_2_321/317_2_321_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/317_2_321/317_2_321_t1+_thick_cor_VST1cor_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/317_2_321/317_2_321_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/317_2_321/317_2_321_t1+_thick_cor_VST1cor_uvauser6_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thin/317_2_321/317_2_321_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/317_2_321/317_2_321_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/317_2_321/317_2_321_t1+_thin_VST1_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/317_2_321/317_2_321_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/317_2_321/317_2_321_t1+_thin_VST1_uvauser6_coregistered.nii.gz)

 24%|██▍       | 431/1793 [03:19<05:59,  3.79it/s]

Original image path: ./raw_studies/t1+_thin/317_3_529/317_3_529_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/317_3_529/317_3_529_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/317_3_529/317_3_529_t1+_thin_VST1_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/317_3_529/317_3_529_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/317_3_529/317_3_529_t1+_thin_VST1_uvauser6_coregistered.nii.gz)

 24%|██▍       | 432/1793 [03:20<06:41,  3.39it/s]

Original image path: ./raw_studies/t1+_thin/317_3_529/317_3_529_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/317_3_529/317_3_529_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/317_3_529/317_3_529_t1+_thin_VST2_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/317_3_529/317_3_529_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/317_3_529/317_3_529_t1+_thin_VST2_uvauser6_coregistered.nii.gz)

 24%|██▍       | 433/1793 [03:20<07:08,  3.17it/s]

Original image path: ./raw_studies/t2_thin/318_0_0/318_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/318_0_0/318_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/318_0_0/318_0_0_t2_thin_VST2_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/318_0_0/318_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/318_0_0/318_0_0_t2_thin_VST2_uvauser6_coregistered.nii.gz)

 24%|██▍       | 435/1793 [03:21<09:29,  2.39it/s]

Original image path: ./raw_studies/t1+_thick_ax/318_0_0/318_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/318_0_0/318_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/318_0_0/318_0_0_t1+_thick_ax_VST1AX_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/318_0_0/318_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/318_0_0/318_0_0_t1+_thick_ax_VST1AX_uvauser6_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/318_0_0/318_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/318_0_0/318_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/318_0_0/318_0_0_t1+_thick_cor_VST1cor_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/318_0_0/318_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/318_0_0/318_0_0_t1+_thick_cor_VST1cor_uvauser6_coregistered.nii.gz)

 24%|██▍       | 437/1793 [03:22<06:59,  3.23it/s]

Original image path: ./raw_studies/t1+_thick_ax/318_1_192/318_1_192_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/318_1_192/318_1_192_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/318_1_192/318_1_192_t1+_thick_ax_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t2_thin/318_1_192/318_1_192_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/318_1_192/318_1_192_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/318_1_192/318_1_192_t2_thin_tumorcore _uvauser3-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/318_1_192/318_1_192_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/318_1_192/318_1_192_t2_thin_tumorcore _uvauser3-copy_coregistered.nii.gz)

 24%|██▍       | 438/1793 [03:23<12:22,  1.83it/s]

Original image path: ./raw_studies/t1+_thick_cor/318_1_192/318_1_192_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/318_1_192/318_1_192_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/318_1_192/318_1_192_t1+_thick_cor_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/318_1_192/318_1_192_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/318_1_192/318_1_192_t1+_thick_cor_tumorcore _uvauser3_coregistered.nii.gz)

 25%|██▍       | 440/1793 [03:23<08:18,  2.72it/s]

Original image path: ./raw_studies/t1+_thick_ax/320_0_0/320_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/320_0_0/320_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/320_0_0/320_0_0_t1+_thick_ax_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/320_0_0/320_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/320_0_0/320_0_0_t1+_thick_ax_AS_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/320_0_0/320_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/320_0_0/320_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/320_0_0/320_0_0_t2_thin_AS1_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/320_0_0/320_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/320_0_0/320_0_0_t2_thin_AS1_uvauser4_coregistered.nii.gz)

 25%|██▍       | 441/1793 [03:24<10:43,  2.10it/s]

Original image path: ./raw_studies/t2_thin/320_0_0/320_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/320_0_0/320_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/320_0_0/320_0_0_t2_thin_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/320_0_0/320_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/320_0_0/320_0_0_t2_thin_AS_uvauser4_coregistered.nii.gz)

 25%|██▍       | 443/1793 [03:25<09:54,  2.27it/s]

Original image path: ./raw_studies/t1+_thick_cor/320_0_0/320_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/320_0_0/320_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/320_0_0/320_0_0_t1+_thick_cor_AS2_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/320_0_0/320_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/320_0_0/320_0_0_t1+_thick_cor_AS2_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/320_1_183/320_1_183_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/320_1_183/320_1_183_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/320_1_183/320_1_183_t1+_thick_ax_Tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/320_1_183/320_1_183_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/320_1_183/320_1_183_t1+_thick_ax_Tumorcore _uvauser3_coregistered.nii.gz)

 25%|██▍       | 445/1793 [03:25<06:12,  3.62it/s]

Original image path: ./raw_studies/t1+_thick_cor/320_1_183/320_1_183_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/320_1_183/320_1_183_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/320_1_183/320_1_183_t1+_thick_cor_Tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/320_1_183/320_1_183_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/320_1_183/320_1_183_t1+_thick_cor_Tumorcore _uvauser3_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/320_1_183/320_1_183_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/320_1_183/320_1_183_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/320_1_183/320_1_183_t2_thin_AX_Tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/320_1_183/320_1_183_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/320_1_183/320_1_183_t2_thin_AX_Tumorcore _uvauser3_coregistered.nii.gz)

 25%|██▍       | 446/1793 [03:26<07:26,  3.02it/s]

Original image path: ./raw_studies/t1+_thin/320_2_225/320_2_225_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/320_2_225/320_2_225_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/320_2_225/320_2_225_t1+_thin_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/320_2_225/320_2_225_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/320_2_225/320_2_225_t1+_thin_LVS _uvauser2_coregistered.nii.gz)

 25%|██▍       | 447/1793 [03:27<14:07,  1.59it/s]

Original image path: ./raw_studies/t2_thin/320_2_225/320_2_225_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/320_2_225/320_2_225_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/320_2_225/320_2_225_t2_thin_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/320_2_225/320_2_225_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/320_2_225/320_2_225_t2_thin_LVS _uvauser2_coregistered.nii.gz)

 25%|██▍       | 448/1793 [03:28<13:51,  1.62it/s]

Original image path: ./raw_studies/t1+_thick_cor/320_2_225/320_2_225_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/320_2_225/320_2_225_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/320_2_225/320_2_225_t1+_thick_cor_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/320_2_225/320_2_225_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/320_2_225/320_2_225_t1+_thick_cor_LVS _uvauser2_coregistered.nii.gz)

 25%|██▌       | 449/1793 [03:29<17:28,  1.28it/s]

Original image path: ./raw_studies/t2_thin/333_0_0/333_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/333_0_0/333_0_0_t2_thin_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 25%|██▌       | 450/1793 [03:29<14:42,  1.52it/s]

Original image path: ./raw_studies/t2_thin/333_1_279/333_1_279_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/333_1_279/333_1_279_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/333_1_279/333_1_279_t2_thin_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/333_1_279/333_1_279_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/333_1_279/333_1_279_t2_thin_LVS _uvauser2_coregistered.nii.gz)

 25%|██▌       | 452/1793 [03:31<13:19,  1.68it/s]

Original image path: ./raw_studies/t1+_thick_ax/333_1_279/333_1_279_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/333_1_279/333_1_279_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/333_1_279/333_1_279_t1+_thick_ax_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/333_1_279/333_1_279_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/333_1_279/333_1_279_t1+_thick_ax_LVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/333_1_279/333_1_279_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/333_1_279/333_1_279_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/333_1_279/333_1_279_t1+_thick_cor_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/333_1_279/333_1_279_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/333_1_279/333_1_279_t1+_thick_cor_LVS _uvauser2_coregistered.nii.gz)

 25%|██▌       | 454/1793 [03:31<08:38,  2.58it/s]

Original image path: ./raw_studies/t1+_thick_ax/333_2_580/333_2_580_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/333_2_580/333_2_580_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/333_2_580/333_2_580_t1+_thick_ax_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/333_2_580/333_2_580_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/333_2_580/333_2_580_t1+_thick_ax_AS_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/333_2_580/333_2_580_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/333_2_580/333_2_580_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/333_2_580/333_2_580_t2_thin_AS2_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/333_2_580/333_2_580_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/333_2_580/333_2_580_t2_thin_AS2_uvauser4_coregistered.nii.gz)

 25%|██▌       | 456/1793 [03:32<10:26,  2.13it/s]

Original image path: ./raw_studies/t1+_thick_cor/333_2_580/333_2_580_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/333_2_580/333_2_580_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/333_2_580/333_2_580_t1+_thick_cor_AS1_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/333_2_580/333_2_580_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/333_2_580/333_2_580_t1+_thick_cor_AS1_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thick/336_0_0/336_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/336_0_0/336_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 26%|██▌       | 459/1793 [03:33<05:39,  3.93it/s]

Original image path: ./raw_studies/t1+_thick_cor/336_1_274/336_1_274_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/336_1_274/336_1_274_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/336_1_274/336_1_274_t1+_thick_cor_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thick_ax/336_1_274/336_1_274_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/336_1_274/336_1_274_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/336_1_274/336_1_274_t1+_thick_ax_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t2_thick/336_1_274/336_1_274_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/336_1_274/336_1_274_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 26%|██▌       | 461/1793 [03:33<04:25,  5.01it/s]

Original image path: ./raw_studies/t2_thick/336_1_274/336_1_274_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/336_1_274/336_1_274_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

Original image path: ./raw_studies/t2_thin/338_6_3807/338_6_3807_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/338_6_3807/338_6_3807_t2_thin_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 26%|██▌       | 463/1793 [03:33<05:24,  4.10it/s]

Original image path: ./raw_studies/t1+_thick_ax/338_6_3807/338_6_3807_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/338_6_3807/338_6_3807_t1+_thick_ax_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

Original image path: ./raw_studies/t2_thick/339_0_0/339_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/339_0_0/339_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/339_0_0/339_0_0_t2_thick_manual_10_uvauser10.nii.gz
Returning: (nan, nan)

 26%|██▌       | 464/1793 [03:34<05:28,  4.04it/s]

Original image path: ./raw_studies/t1+_thick_ax/339_0_0/339_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/339_0_0/339_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/339_0_0/339_0_0_t1+_thick_ax_manual_10_uvauser10.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/339_0_0/339_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/339_0_0/339_0_0_t1+_thick_ax_manual_10_uvauser10_coregistered.nii.gz)

 26%|██▌       | 467/1793 [03:34<03:56,  5.61it/s]

Original image path: ./raw_studies/t1+_thick_cor/339_0_0/339_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/339_0_0/339_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/339_0_0/339_0_0_t1+_thick_cor_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thick_ax/339_1_248/339_1_248_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/339_1_248/339_1_248_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/339_1_248/339_1_248_t1+_thick_ax_Manual_0_uvauser11.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/339_1_248/339_1_248_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/339_1_248/339_1_248_t1+_thick_ax_Manual_0_uvauser11_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/339_1_248/339_1_248_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/339_1_248/339_1_248_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/339_1_248/339_1_248_t1+_thick_cor_image_coregistered.nii.gz, nan)

 26%|██▌       | 468/1793 [03:34<03:44,  5.91it/s]

Original image path: ./raw_studies/t2_thin/339_1_248/339_1_248_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/339_1_248/339_1_248_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/339_1_248/339_1_248_t2_thin_image_coregistered.nii.gz, nan)

 26%|██▌       | 470/1793 [03:35<04:38,  4.76it/s]

Original image path: ./raw_studies/t1+_thick_cor/339_2_430/339_2_430_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/339_2_430/339_2_430_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/339_2_430/339_2_430_t1+_thick_cor_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/339_2_430/339_2_430_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/339_2_430/339_2_430_t1+_thick_cor_VS_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/339_2_430/339_2_430_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/339_2_430/339_2_430_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/339_2_430/339_2_430_t2_thin_AX_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/339_2_430/339_2_430_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/339_2_430/339_2_430_t2_thin_AX_VS_uvauser1_coregistered.nii.gz)

 26%|██▋       | 472/1793 [03:35<05:24,  4.07it/s]

Original image path: ./raw_studies/t1+_thick_ax/339_2_430/339_2_430_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/339_2_430/339_2_430_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/339_2_430/339_2_430_t1+_thick_ax_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/339_2_430/339_2_430_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/339_2_430/339_2_430_t1+_thick_ax_VS_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/339_3_1203/339_3_1203_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/339_3_1203/339_3_1203_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/339_3_1203/339_3_1203_t1+_thick_cor_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/339_3_1203/339_3_1203_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/339_3_1203/339_3_1203_t1+_thick_cor_VS_uvauser1_coregistered.nii.gz)

 26%|██▋       | 474/1793 [03:36<04:30,  4.88it/s]

Original image path: ./raw_studies/t1+_thick_ax/339_3_1203/339_3_1203_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/339_3_1203/339_3_1203_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/339_3_1203/339_3_1203_t1+_thick_ax_T2Final_VS_uvauser5-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/339_3_1203/339_3_1203_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/339_3_1203/339_3_1203_t1+_thick_ax_T2Final_VS_uvauser5-copy_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/339_3_1203/339_3_1203_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/339_3_1203/339_3_1203_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/339_3_1203/339_3_1203_t1+_thick_ax_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/339_3_1203/339_3_1203_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/339_3_1203/339_3_1203_t1+_thick_ax_VS_uvauser1_coregistered.nii.gz)

 27%|██▋       | 476/1793 [03:36<03:57,  5.53it/s]

Original image path: ./raw_studies/t1+_thick_cor/343_0_0/343_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/343_0_0/343_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/343_0_0/343_0_0_t1+_thick_cor_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t2_thin/343_0_0/343_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/343_0_0/343_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/343_0_0/343_0_0_t2_thin_image_coregistered.nii.gz, nan)

 27%|██▋       | 478/1793 [03:37<07:41,  2.85it/s]

Original image path: ./raw_studies/t1+_thick_ax/343_0_0/343_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/343_0_0/343_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/343_0_0/343_0_0_t1+_thick_ax_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thick_cor/343_1_167/343_1_167_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/343_1_167/343_1_167_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/343_1_167/343_1_167_t1+_thick_cor_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/343_1_167/343_1_167_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/343_1_167/343_1_167_t1+_thick_cor_RVS _uvauser2_coregistered.nii.gz)

 27%|██▋       | 480/1793 [03:38<05:51,  3.74it/s]

Original image path: ./raw_studies/t1+_thick_ax/343_1_167/343_1_167_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/343_1_167/343_1_167_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/343_1_167/343_1_167_t1+_thick_ax_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/343_1_167/343_1_167_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/343_1_167/343_1_167_t1+_thick_ax_RVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/343_1_167/343_1_167_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/343_1_167/343_1_167_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/343_1_167/343_1_167_t2_thin_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/343_1_167/343_1_167_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/343_1_167/343_1_167_t2_thin_RVS _uvauser2_coregistered.nii.gz)

 27%|██▋       | 482/1793 [03:39<08:49,  2.47it/s]

Original image path: ./raw_studies/t1+_thick_cor/343_2_533/343_2_533_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/343_2_533/343_2_533_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/343_2_533/343_2_533_t1+_thick_cor_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/343_2_533/343_2_533_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/343_2_533/343_2_533_t1+_thick_cor_LVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/343_2_533/343_2_533_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/343_2_533/343_2_533_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/343_2_533/343_2_533_t2_thin_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/343_2_533/343_2_533_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/343_2_533/343_2_533_t2_thin_LVS _uvauser2_coregistered.nii.gz)

 27%|██▋       | 484/1793 [03:40<10:05,  2.16it/s]

Original image path: ./raw_studies/t1+_thick_ax/343_2_533/343_2_533_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/343_2_533/343_2_533_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/343_2_533/343_2_533_t1+_thick_ax_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/343_2_533/343_2_533_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/343_2_533/343_2_533_t1+_thick_ax_LVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/344_0_0/344_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/344_0_0/344_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/344_0_0/344_0_0_t1+_thick_ax_Tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/344_0_0/344_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/344_0_0/344_0_0_t1+_thick_ax_Tumorcore _uvauser3_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/344_0_0/344_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/344_0_0/344_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/344_0_0/344_0_0_t2_thin_AX_Tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/344_0_0/344_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/344_0_0/344_0_0_t2_thin_AX_Tumorcore _uvauser3_coregistered.nii.gz)

 27%|██▋       | 488/1793 [03:41<07:17,  2.98it/s]

Original image path: ./raw_studies/t1+_thick_cor/344_0_0/344_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/344_0_0/344_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/344_0_0/344_0_0_t1+_thick_cor_Tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/344_0_0/344_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/344_0_0/344_0_0_t1+_thick_cor_Tumorcore _uvauser3_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/344_1_270/344_1_270_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/344_1_270/344_1_270_t1+_thick_ax_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t1+_thick_ax/344_1_270/344_1_270_t1+_thick_ax_Tumorcore _uvauser3.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t2_thin/344_1_270/344_1_270_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/344_1_270/344_1_270_t2_thin_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thin/344_1_270/344_1_270_t2_thin_AX_Tumorcore _uvauser3.nii.gz
Returning: (nan, nan)

 27%|██▋       | 489/1793 [03:42<10:34,  2.05it/s]

Original image path: ./raw_studies/t1+_thick_cor/344_1_270/344_1_270_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/344_1_270/344_1_270_t1+_thick_cor_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t1+_thick_cor/344_1_270/344_1_270_t1+_thick_cor_Tumorcore _uvauser3.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thin/350_0_0/350_0_0_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/350_0_0/350_0_0_t1+_thin_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t1+_thin/350_0_0/350_0_0_t1+_thin_manual_0_uvauser8.nii.gz
Returning: (nan, nan)

 27%|██▋       | 492/1793 [03:43<06:45,  3.21it/s]

Original image path: ./raw_studies/t2_thick/351_0_0/351_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/351_0_0/351_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thick_ax/353_0_0/353_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/353_0_0/353_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/353_0_0/353_0_0_t1+_thick_ax_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/353_0_0/353_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/353_0_0/353_0_0_t1+_thick_ax_VS_uvauser5_coregistered.nii.gz)

 28%|██▊       | 494/1793 [03:43<05:51,  3.69it/s]

Original image path: ./raw_studies/t2_thick/353_0_0/353_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/353_0_0/353_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/353_0_0/353_0_0_t2_thick_VS_uvauser5.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thick_cor/353_0_0/353_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/353_0_0/353_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/353_0_0/353_0_0_t1+_thick_cor_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/353_0_0/353_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/353_0_0/353_0_0_t1+_thick_cor_VS_uvauser5_coregistered.nii.gz)

 28%|██▊       | 496/1793 [03:44<04:58,  4.34it/s]

Original image path: ./raw_studies/t1+_thick_ax/360_0_0/360_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/360_0_0/360_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t1+_thick_ax/360_0_0/360_0_0_t1+_thick_ax_AS_uvauser4.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t2_thin/360_0_0/360_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/360_0_0/360_0_0_t2_thin_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thin/360_0_0/360_0_0_t2_thin_CO_AS_uvauser4.nii.gz
Returning: (nan, nan)

 28%|██▊       | 498/1793 [03:45<08:54,  2.42it/s]

Original image path: ./raw_studies/t1+_thick_cor/360_0_0/360_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/360_0_0/360_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t1+_thick_cor/360_0_0/360_0_0_t1+_thick_cor_AS_uvauser4.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thick_ax/360_1_211/360_1_211_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/360_1_211/360_1_211_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/360_1_211/360_1_211_t1+_thick_ax_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/360_1_211/360_1_211_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/360_1_211/360_1_211_t1+_thick_ax_tumorcore _uvauser3_coregistered.nii.gz)

 28%|██▊       | 500/1793 [03:45<06:00,  3.59it/s]

Original image path: ./raw_studies/t1+_thick_cor/360_1_211/360_1_211_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/360_1_211/360_1_211_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/360_1_211/360_1_211_t1+_thick_cor_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t2_thin/360_1_211/360_1_211_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/360_1_211/360_1_211_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/360_1_211/360_1_211_t2_thin_AX_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/360_1_211/360_1_211_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/360_1_211/360_1_211_t2_thin_AX_tumorcore _uvauser3_coregistered.nii.gz)

 28%|██▊       | 501/1793 [03:46<10:53,  1.98it/s]

Original image path: ./raw_studies/t2_thin/360_2_516/360_2_516_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/360_2_516/360_2_516_t2_thin_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 28%|██▊       | 502/1793 [03:47<13:10,  1.63it/s]

Original image path: ./raw_studies/t1+_thin/360_2_516/360_2_516_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/360_2_516/360_2_516_t1+_thin_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t1+_thin/360_2_516/360_2_516_t1+_thin_VS_uvauser1.nii.gz
Returning: (nan, nan)

 28%|██▊       | 504/1793 [03:49<13:00,  1.65it/s]

Original image path: ./raw_studies/t1+_thick_ax/364_0_0/364_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/364_0_0/364_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t1+_thick_ax/364_0_0/364_0_0_t1+_thick_ax_manual_0_uvauser8.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thick_ax/374_0_0/374_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/374_0_0/374_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/374_0_0/374_0_0_t1+_thick_ax_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/374_0_0/374_0_0_t1+_thick_ax_image_coregistered.nii.gz, nan)

 28%|██▊       | 505/1793 [03:49<11:40,  1.84it/s]

Original image path: ./raw_studies/t1+_thick_cor/374_0_0/374_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/374_0_0/374_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/374_0_0/374_0_0_t1+_thick_cor_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/374_0_0/374_0_0_t1+_thick_cor_image_coregistered.nii.gz, nan)

 28%|██▊       | 506/1793 [03:50<12:26,  1.72it/s]

Original image path: ./raw_studies/t2_thick/374_0_0/374_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/374_0_0/374_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 28%|██▊       | 507/1793 [03:50<11:52,  1.80it/s]

Original image path: ./raw_studies/t2_thin/374_0_0/374_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/374_0_0/374_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/374_0_0/374_0_0_t2_thin_AX_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/374_0_0/374_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/374_0_0/374_0_0_t2_thin_AX_VS_uvauser1_coregistered.nii.gz)

 28%|██▊       | 510/1793 [03:51<06:38,  3.22it/s]

Original image path: ./raw_studies/t1+_thick_ax/374_1_338/374_1_338_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/374_1_338/374_1_338_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/374_1_338/374_1_338_t1+_thick_ax_VST1ax_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/374_1_338/374_1_338_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/374_1_338/374_1_338_t1+_thick_ax_VST1ax_uvauser6_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/374_1_338/374_1_338_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/374_1_338/374_1_338_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/374_1_338/374_1_338_t1+_thick_cor_VST1cor_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/374_1_338/374_1_338_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/374_1_338/374_1_338_t1+_thick_cor_VST1cor_uvauser6_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/374_1_338/374_1_338_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/374_1_338/374_1_338_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/374_1_338/374_1_338_t2_thin_VST2_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/374_1_338/374_1_338_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/374_1_338/374_1_338_t2_thin_VST2_uvauser6_coregistered.nii.gz)

 28%|██▊       | 511/1793 [03:52<11:14,  1.90it/s]

Original image path: ./raw_studies/t2_thin/374_2_772/374_2_772_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/374_2_772/374_2_772_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/374_2_772/374_2_772_t2_thin_T2Final_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/374_2_772/374_2_772_t2_thin_image_coregistered.nii.gz, nan)

 29%|██▊       | 512/1793 [03:53<15:43,  1.36it/s]

Original image path: ./raw_studies/t1+_thick_cor/374_2_772/374_2_772_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/374_2_772/374_2_772_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/374_2_772/374_2_772_t1+_thick_cor_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/374_2_772/374_2_772_t1+_thick_cor_image_coregistered.nii.gz, nan)

 29%|██▊       | 513/1793 [03:54<14:16,  1.49it/s]

Original image path: ./raw_studies/t1+_thick_ax/374_2_772/374_2_772_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/374_2_772/374_2_772_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/374_2_772/374_2_772_t1+_thick_ax_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/374_2_772/374_2_772_t1+_thick_ax_image_coregistered.nii.gz, nan)

 29%|██▊       | 514/1793 [03:54<13:48,  1.54it/s]

Original image path: ./raw_studies/t1+_thin/374_3_1258/374_3_1258_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/374_3_1258/374_3_1258_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/374_3_1258/374_3_1258_t1+_thin_VST1_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/374_3_1258/374_3_1258_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/374_3_1258/374_3_1258_t1+_thin_VST1_uvauser6_coregistered.nii.gz)

 29%|██▊       | 515/1793 [03:56<21:14,  1.00it/s]

Original image path: ./raw_studies/t2_thin/374_3_1258/374_3_1258_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/374_3_1258/374_3_1258_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/374_3_1258/374_3_1258_t2_thin_VST2_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/374_3_1258/374_3_1258_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/374_3_1258/374_3_1258_t2_thin_VST2_uvauser6_coregistered.nii.gz)

 29%|██▉       | 516/1793 [03:57<21:35,  1.01s/it]

Original image path: ./raw_studies/t1+_thick_ax/383_0_0/383_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/383_0_0/383_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/383_0_0/383_0_0_t1+_thick_ax_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/383_0_0/383_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/383_0_0/383_0_0_t1+_thick_ax_LVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/383_0_0/383_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/383_0_0/383_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/383_0_0/383_0_0_t2_thin_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/383_0_0/383_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/383_0_0/383_0_0_t2_thin_LVS _uvauser2_coregistered.nii.gz)

 29%|██▉       | 520/1793 [03:58<09:05,  2.34it/s]

Original image path: ./raw_studies/t1+_thick_cor/383_0_0/383_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/383_0_0/383_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/383_0_0/383_0_0_t1+_thick_cor_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/383_0_0/383_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/383_0_0/383_0_0_t1+_thick_cor_LVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/383_1_253/383_1_253_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/383_1_253/383_1_253_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/383_1_253/383_1_253_t1+_thick_ax_Tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/383_1_253/383_1_253_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/383_1_253/383_1_253_t1+_thick_ax_Tumorcore _uvauser3_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/383_1_253/383_1_253_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/383_1_253/383_1_253_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/383_1_253/383_1_253_t1+_thick_cor_Tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/383_1_253/383_1_253_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/383_1_253/383_1_253_t1+_thick_cor_Tumorcore _uvauser3_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/383_1_253/383_1_253_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/383_1_253/383_1_253_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/383_1_253/383_1_253_t2_thin_AX_Tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/383_1_253/383_1_253_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/383_1_253/383_1_253_t2_thin_AX_Tumorcore _uvauser3_coregistered.nii.gz)

 29%|██▉       | 522/1793 [03:58<07:38,  2.77it/s]

Original image path: ./raw_studies/t2_thin/383_2_611/383_2_611_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/383_2_611/383_2_611_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/383_2_611/383_2_611_t2_thin_1_uvauser4-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/383_2_611/383_2_611_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/383_2_611/383_2_611_t2_thin_1_uvauser4-copy_coregistered.nii.gz)

 29%|██▉       | 523/1793 [03:59<07:29,  2.82it/s]

Original image path: ./raw_studies/t1+_thin/383_2_611/383_2_611_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/383_2_611/383_2_611_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/383_2_611/383_2_611_t1+_thin_1_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/383_2_611/383_2_611_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/383_2_611/383_2_611_t1+_thin_1_uvauser4_coregistered.nii.gz)

 29%|██▉       | 525/1793 [04:00<10:34,  2.00it/s]

Original image path: ./raw_studies/t1+_thick_ax/385_0_0/385_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/385_0_0/385_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/385_0_0/385_0_0_t1+_thick_ax_VST1AX_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/385_0_0/385_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/385_0_0/385_0_0_t1+_thick_ax_VST1AX_uvauser6_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/385_0_0/385_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/385_0_0/385_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/385_0_0/385_0_0_t1+_thick_cor_VST1COR_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/385_0_0/385_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/385_0_0/385_0_0_t1+_thick_cor_VST1COR_uvauser6_coregistered.nii.gz)

 29%|██▉       | 526/1793 [04:00<08:38,  2.44it/s]

Original image path: ./raw_studies/t2_thin/385_0_0/385_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/385_0_0/385_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/385_0_0/385_0_0_t2_thin_VST2_uvauser6-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/385_0_0/385_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/385_0_0/385_0_0_t2_thin_VST2_uvauser6-copy_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/385_1_476/385_1_476_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/385_1_476/385_1_476_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/385_1_476/385_1_476_t1+_thick_ax_user9-uva-seg-T1post-right_uvauser9.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/385_1_476/385_1_476_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/385_1_476/385_1_476_t1+_thick_ax_user9-uva-seg-T1post-right_uvauser9_coregistered.nii.gz)

 29%|██▉       | 528/1793 [04:01<06:09,  3.42it/s]

Original image path: ./raw_studies/t2_thin/385_1_476/385_1_476_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/385_1_476/385_1_476_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/385_1_476/385_1_476_t2_thin_image_coregistered.nii.gz, nan)

 30%|██▉       | 530/1793 [04:02<08:03,  2.61it/s]

Original image path: ./raw_studies/t1+_thick_ax/395_0_0/395_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/395_0_0/395_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/395_0_0/395_0_0_t1+_thick_ax_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/395_0_0/395_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/395_0_0/395_0_0_t1+_thick_ax_VS_uvauser5_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/395_0_0/395_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/395_0_0/395_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/395_0_0/395_0_0_t1+_thick_cor_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/395_0_0/395_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/395_0_0/395_0_0_t1+_thick_cor_VS_uvauser5_coregistered.nii.gz)

 30%|██▉       | 531/1793 [04:02<06:43,  3.13it/s]

Original image path: ./raw_studies/t2_thin/395_0_0/395_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/395_0_0/395_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/395_0_0/395_0_0_t2_thin_T2Final_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/395_0_0/395_0_0_t2_thin_image_coregistered.nii.gz, nan)

 30%|██▉       | 533/1793 [04:03<07:07,  2.95it/s]

Original image path: ./raw_studies/t1+_thick_cor/395_1_1985/395_1_1985_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/395_1_1985/395_1_1985_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/395_1_1985/395_1_1985_t1+_thick_cor_CO_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/395_1_1985/395_1_1985_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/395_1_1985/395_1_1985_t1+_thick_cor_CO_VS_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/395_1_1985/395_1_1985_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/395_1_1985/395_1_1985_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/395_1_1985/395_1_1985_t2_thin_T2_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/395_1_1985/395_1_1985_t2_thin_image_coregistered.nii.gz, nan)

 30%|██▉       | 535/1793 [04:04<10:24,  2.01it/s]

Original image path: ./raw_studies/t1+_thick_ax/395_1_1985/395_1_1985_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/395_1_1985/395_1_1985_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/395_1_1985/395_1_1985_t1+_thick_ax_AX_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/395_1_1985/395_1_1985_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/395_1_1985/395_1_1985_t1+_thick_ax_AX_VS_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/398_0_0/398_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/398_0_0/398_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/398_0_0/398_0_0_t2_thin_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/398_0_0/398_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/398_0_0/398_0_0_t2_thin_RVS _uvauser2_coregistered.nii.gz)

 30%|██▉       | 536/1793 [04:05<09:27,  2.22it/s]

Original image path: ./raw_studies/t1+_thin/398_0_0/398_0_0_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/398_0_0/398_0_0_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/398_0_0/398_0_0_t1+_thin_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/398_0_0/398_0_0_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/398_0_0/398_0_0_t1+_thin_RVS _uvauser2_coregistered.nii.gz)

 30%|██▉       | 537/1793 [04:05<09:00,  2.33it/s]

Original image path: ./raw_studies/t1+_thin/398_1_1237/398_1_1237_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/398_1_1237/398_1_1237_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/398_1_1237/398_1_1237_t1+_thin_VST1_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/398_1_1237/398_1_1237_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/398_1_1237/398_1_1237_t1+_thin_VST1_uvauser6_coregistered.nii.gz)

 30%|███       | 538/1793 [04:05<08:45,  2.39it/s]

Original image path: ./raw_studies/t2_thin/398_1_1237/398_1_1237_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/398_1_1237/398_1_1237_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/398_1_1237/398_1_1237_t2_thin_VST2_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/398_1_1237/398_1_1237_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/398_1_1237/398_1_1237_t2_thin_VST2_uvauser6_coregistered.nii.gz)

 30%|███       | 539/1793 [04:06<08:38,  2.42it/s]

Original image path: ./raw_studies/t1+_thin/398_2_1573/398_2_1573_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/398_2_1573/398_2_1573_t1+_thin_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t1+_thin/398_2_1573/398_2_1573_t1+_thin_tumorcore _uvauser3.nii.gz
Returning: (nan, nan)

 30%|███       | 540/1793 [04:06<08:29,  2.46it/s]

Original image path: ./raw_studies/t2_thin/398_2_1573/398_2_1573_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/398_2_1573/398_2_1573_t2_thin_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 30%|███       | 541/1793 [04:07<08:11,  2.55it/s]

Original image path: ./raw_studies/t1+_thin/403_2_392/403_2_392_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/403_2_392/403_2_392_t1+_thin_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t1+_thin/403_2_392/403_2_392_t1+_thin_manual_0_uvauser8.nii.gz
Returning: (nan, nan)

 30%|███       | 543/1793 [04:07<07:04,  2.94it/s]

Original image path: ./raw_studies/t2_thick/403_4_938/403_4_938_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/403_4_938/403_4_938_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thick_cor/406_0_0/406_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/406_0_0/406_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/406_0_0/406_0_0_t1+_thick_cor_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/406_0_0/406_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/406_0_0/406_0_0_t1+_thick_cor_LVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/406_0_0/406_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/406_0_0/406_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/406_0_0/406_0_0_t2_thin_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/406_0_0/406_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/406_0_0/406_0_0_t2_thin_LVS _uvauser2_coregistered.nii.gz)

 30%|███       | 546/1793 [04:08<07:35,  2.74it/s]

Original image path: ./raw_studies/t1+_thick_ax/406_0_0/406_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/406_0_0/406_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/406_0_0/406_0_0_t1+_thick_ax_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/406_0_0/406_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/406_0_0/406_0_0_t1+_thick_ax_LVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/406_1_159/406_1_159_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/406_1_159/406_1_159_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/406_1_159/406_1_159_t1+_thick_cor_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t2_thin/406_1_159/406_1_159_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/406_1_159/406_1_159_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/406_1_159/406_1_159_t2_thin_1_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/406_1_159/406_1_159_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/406_1_159/406_1_159_t2_thin_1_uvauser4_coregistered.nii.gz)

 31%|███       | 548/1793 [04:10<09:25,  2.20it/s]

Original image path: ./raw_studies/t1+_thick_ax/406_1_159/406_1_159_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/406_1_159/406_1_159_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/406_1_159/406_1_159_t1+_thick_ax_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thick_cor/406_2_528/406_2_528_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/406_2_528/406_2_528_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/406_2_528/406_2_528_t1+_thick_cor_image_coregistered.nii.gz, nan)

 31%|███       | 551/1793 [04:10<06:10,  3.35it/s]

Original image path: ./raw_studies/t1+_thick_ax/406_2_528/406_2_528_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/406_2_528/406_2_528_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/406_2_528/406_2_528_t1+_thick_ax_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/406_2_528/406_2_528_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/406_2_528/406_2_528_t1+_thick_ax_tumorcore _uvauser3_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/406_2_528/406_2_528_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/406_2_528/406_2_528_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/406_2_528/406_2_528_t2_thin_AX_tumorcore _uvauser3-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/406_2_528/406_2_528_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/406_2_528/406_2_528_t2_thin_AX_tumorcore _uvauser3-copy_coregistered.nii.gz)

 31%|███       | 552/1793 [04:11<07:23,  2.80it/s]

Original image path: ./raw_studies/t1+_thick_cor/406_3_550/406_3_550_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/406_3_550/406_3_550_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/406_3_550/406_3_550_t1+_thick_cor_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/406_3_550/406_3_550_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/406_3_550/406_3_550_t1+_thick_cor_LVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thin/406_3_550/406_3_550_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/406_3_550/406_3_550_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/406_3_550/406_3_550_t1+_thin_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/406_3_550/406_3_550_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/406_3_550/406_3_550_t1+_thin_LVS _uvauser2_coregistered.nii.gz)

 31%|███       | 554/1793 [04:12<10:19,  2.00it/s]

Original image path: ./raw_studies/t2_thin/406_3_550/406_3_550_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/406_3_550/406_3_550_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/406_3_550/406_3_550_t2_thin_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/406_3_550/406_3_550_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/406_3_550/406_3_550_t2_thin_LVS _uvauser2_coregistered.nii.gz)

 31%|███       | 556/1793 [04:13<08:36,  2.40it/s]

Original image path: ./raw_studies/t1+_thick_ax/412_1_371/412_1_371_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/412_1_371/412_1_371_t1+_thick_ax_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t1+_thick_ax/412_1_371/412_1_371_t1+_thick_ax_manual_uvauser12_uvauser12.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t2_thin/412_1_371/412_1_371_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/412_1_371/412_1_371_t2_thin_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 31%|███       | 558/1793 [04:14<09:24,  2.19it/s]

Original image path: ./raw_studies/t1+_thick_cor/412_1_371/412_1_371_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/412_1_371/412_1_371_t1+_thick_cor_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t1+_thick_cor/412_1_371/412_1_371_t1+_thick_cor_manual_uvauser12_uvauser12.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t2_thick/415_0_0/415_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/415_0_0/415_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 31%|███       | 559/1793 [04:14<10:11,  2.02it/s]

Original image path: ./raw_studies/t2_thick/415_0_0/415_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/415_0_0/415_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 31%|███       | 560/1793 [04:15<10:44,  1.91it/s]

Original image path: ./raw_studies/t1+_thick_ax/415_0_0/415_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/415_0_0/415_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/415_0_0/415_0_0_t1+_thick_ax_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/415_0_0/415_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/415_0_0/415_0_0_t1+_thick_ax_tumorcore _uvauser3_coregistered.nii.gz)

 31%|███▏      | 561/1793 [04:15<08:53,  2.31it/s]

Original image path: ./raw_studies/t2_thick/415_1_211/415_1_211_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/415_1_211/415_1_211_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/415_1_211/415_1_211_t2_thick_AS2_uvauser4.nii.gz
Returning: (nan, nan)

 31%|███▏      | 562/1793 [04:16<09:29,  2.16it/s]

Original image path: ./raw_studies/t2_thin/415_1_211/415_1_211_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/415_1_211/415_1_211_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/415_1_211/415_1_211_t2_thin_image_coregistered.nii.gz, nan)

 31%|███▏      | 563/1793 [04:16<10:30,  1.95it/s]

Original image path: ./raw_studies/t1+_thick_ax/415_1_211/415_1_211_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/415_1_211/415_1_211_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/415_1_211/415_1_211_t1+_thick_ax_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/415_1_211/415_1_211_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/415_1_211/415_1_211_t1+_thick_ax_AS_uvauser4_coregistered.nii.gz)

 31%|███▏      | 564/1793 [04:17<08:47,  2.33it/s]

Original image path: ./raw_studies/t2_thin/415_1_211/415_1_211_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/415_1_211/415_1_211_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/415_1_211/415_1_211_t2_thin_AS1_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/415_1_211/415_1_211_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/415_1_211/415_1_211_t2_thin_AS1_uvauser4_coregistered.nii.gz)

 32%|███▏      | 566/1793 [04:17<08:09,  2.51it/s]

Original image path: ./raw_studies/t1+_thick_cor/415_1_211/415_1_211_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/415_1_211/415_1_211_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/415_1_211/415_1_211_t1+_thick_cor_AS2_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/415_1_211/415_1_211_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/415_1_211/415_1_211_t1+_thick_cor_AS2_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/415_1_211/415_1_211_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/415_1_211/415_1_211_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/415_1_211/415_1_211_t1+_thick_cor_image_coregistered.nii.gz, nan)

 32%|███▏      | 567/1793 [04:18<06:53,  2.97it/s]

Original image path: ./raw_studies/t1+_thick_ax/415_1_211/415_1_211_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/415_1_211/415_1_211_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/415_1_211/415_1_211_t1+_thick_ax_image_coregistered.nii.gz, nan)

 32%|███▏      | 568/1793 [04:18<06:09,  3.32it/s]

Original image path: ./raw_studies/t2_thick/415_2_404/415_2_404_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/415_2_404/415_2_404_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/415_2_404/415_2_404_t2_thick_AS2_uvauser4.nii.gz
Returning: (nan, nan)

 32%|███▏      | 569/1793 [04:18<07:02,  2.90it/s]

Original image path: ./raw_studies/t2_thin/415_2_404/415_2_404_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/415_2_404/415_2_404_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/415_2_404/415_2_404_t2_thin_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/415_2_404/415_2_404_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/415_2_404/415_2_404_t2_thin_AS_uvauser4_coregistered.nii.gz)

 32%|███▏      | 571/1793 [04:19<06:46,  3.01it/s]

Original image path: ./raw_studies/t1+_thick_ax/415_2_404/415_2_404_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/415_2_404/415_2_404_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/415_2_404/415_2_404_t1+_thick_ax_AS1_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/415_2_404/415_2_404_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/415_2_404/415_2_404_t1+_thick_ax_AS1_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/415_2_404/415_2_404_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/415_2_404/415_2_404_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/415_2_404/415_2_404_t1+_thick_cor_AS2_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/415_2_404/415_2_404_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/415_2_404/415_2_404_t1+_thick_cor_AS2_uvauser4_coregistered.nii.gz)

 32%|███▏      | 572/1793 [04:19<05:50,  3.48it/s]

Original image path: ./raw_studies/t2_thin/415_2_404/415_2_404_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/415_2_404/415_2_404_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/415_2_404/415_2_404_t2_thin_image_coregistered.nii.gz, nan)

 32%|███▏      | 574/1793 [04:20<06:02,  3.37it/s]

Original image path: ./raw_studies/t1+_thick_ax/415_2_404/415_2_404_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/415_2_404/415_2_404_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/415_2_404/415_2_404_t1+_thick_ax_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thick_ax/415_2_404/415_2_404_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/415_2_404/415_2_404_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/415_2_404/415_2_404_t1+_thick_ax_image_coregistered.nii.gz, nan)

 32%|███▏      | 576/1793 [04:20<04:47,  4.24it/s]

Original image path: ./raw_studies/t1+_thick_cor/415_2_404/415_2_404_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/415_2_404/415_2_404_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/415_2_404/415_2_404_t1+_thick_cor_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t2_thick/415_2_404/415_2_404_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/415_2_404/415_2_404_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 32%|███▏      | 577/1793 [04:21<05:58,  3.40it/s]

Original image path: ./raw_studies/t1+_thick_ax/415_3_757/415_3_757_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/415_3_757/415_3_757_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/415_3_757/415_3_757_t1+_thick_ax_image_coregistered.nii.gz, nan)

 32%|███▏      | 578/1793 [04:21<05:37,  3.60it/s]

Original image path: ./raw_studies/t2_thick/415_3_757/415_3_757_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/415_3_757/415_3_757_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/415_3_757/415_3_757_t2_thick_RVS _uvauser2.nii.gz
Returning: (nan, nan)

 32%|███▏      | 579/1793 [04:22<08:00,  2.53it/s]

Original image path: ./raw_studies/t1+_thick_ax/415_3_757/415_3_757_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/415_3_757/415_3_757_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/415_3_757/415_3_757_t1+_thick_ax_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/415_3_757/415_3_757_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/415_3_757/415_3_757_t1+_thick_ax_RVS _uvauser2_coregistered.nii.gz)

 32%|███▏      | 580/1793 [04:22<07:04,  2.86it/s]

Original image path: ./raw_studies/t1+_thick_cor/415_3_757/415_3_757_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/415_3_757/415_3_757_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/415_3_757/415_3_757_t1+_thick_cor_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/415_3_757/415_3_757_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/415_3_757/415_3_757_t1+_thick_cor_RVS _uvauser2_coregistered.nii.gz)

 32%|███▏      | 581/1793 [04:22<06:18,  3.20it/s]

Original image path: ./raw_studies/t2_thick/415_3_757/415_3_757_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/415_3_757/415_3_757_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 32%|███▏      | 582/1793 [04:23<08:21,  2.41it/s]

Original image path: ./raw_studies/t2_thin/415_3_757/415_3_757_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/415_3_757/415_3_757_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/415_3_757/415_3_757_t2_thin_image_coregistered.nii.gz, nan)

 33%|███▎      | 585/1793 [04:23<05:39,  3.55it/s]

Original image path: ./raw_studies/t1+_thick_ax/415_4_1462/415_4_1462_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/415_4_1462/415_4_1462_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/415_4_1462/415_4_1462_t1+_thick_ax_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thick_cor/415_4_1462/415_4_1462_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/415_4_1462/415_4_1462_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/415_4_1462/415_4_1462_t1+_thick_cor_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t2_thick/415_4_1462/415_4_1462_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/415_4_1462/415_4_1462_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 33%|███▎      | 586/1793 [04:24<04:46,  4.22it/s]

Original image path: ./raw_studies/t1+_thick_ax/415_4_1462/415_4_1462_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/415_4_1462/415_4_1462_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/415_4_1462/415_4_1462_t1+_thick_ax_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t2_thin/415_4_1462/415_4_1462_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/415_4_1462/415_4_1462_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/415_4_1462/415_4_1462_t2_thin_T2Final_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/415_4_1462/415_4_1462_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/415_4_1462/415_4_1462_t2_thin_T2Final_VS_uvauser5_coregistered.nii.gz)

 33%|███▎      | 588/1793 [04:24<03:59,  5.04it/s]

Original image path: ./raw_studies/t2_thin/415_5_1805/415_5_1805_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/415_5_1805/415_5_1805_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/415_5_1805/415_5_1805_t2_thin_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/415_5_1805/415_5_1805_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/415_5_1805/415_5_1805_t2_thin_tumorcore _uvauser3_coregistered.nii.gz)

 33%|███▎      | 591/1793 [04:24<03:16,  6.11it/s]

Original image path: ./raw_studies/t1+_thick_ax/415_5_1805/415_5_1805_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/415_5_1805/415_5_1805_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/415_5_1805/415_5_1805_t1+_thick_ax_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thick_cor/415_5_1805/415_5_1805_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/415_5_1805/415_5_1805_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/415_5_1805/415_5_1805_t1+_thick_cor_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t2_thick/417_0_0/417_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/417_0_0/417_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 33%|███▎      | 592/1793 [04:25<04:22,  4.58it/s]

Original image path: ./raw_studies/t1+_thick_ax/417_0_0/417_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/417_0_0/417_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t1+_thick_ax/417_0_0/417_0_0_t1+_thick_ax_manual_0_uvauser8.nii.gz
Returning: (nan, nan)

 33%|███▎      | 593/1793 [04:25<04:20,  4.61it/s]

Original image path: ./raw_studies/t1+_thick_ax/418_1_1056/418_1_1056_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/418_1_1056/418_1_1056_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/418_1_1056/418_1_1056_t1+_thick_ax_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thin/418_1_1056/418_1_1056_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/418_1_1056/418_1_1056_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/418_1_1056/418_1_1056_t1+_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/418_1_1056/418_1_1056_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/418_1_1056/418_1_1056_t1+_thin_VS_uvauser1_coregistered.nii.gz)

 33%|███▎      | 595/1793 [04:27<11:03,  1.81it/s]

Original image path: ./raw_studies/t2_thin/418_1_1056/418_1_1056_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/418_1_1056/418_1_1056_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/418_1_1056/418_1_1056_t2_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/418_1_1056/418_1_1056_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/418_1_1056/418_1_1056_t2_thin_VS_uvauser1_coregistered.nii.gz)

 33%|███▎      | 597/1793 [04:28<10:56,  1.82it/s]

Original image path: ./raw_studies/t2_thick/418_1_1056/418_1_1056_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/418_1_1056/418_1_1056_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/418_1_1056/418_1_1056_t2_thick_VS_uvauser1.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thick_cor/418_1_1056/418_1_1056_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/418_1_1056/418_1_1056_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/418_1_1056/418_1_1056_t1+_thick_cor_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/418_1_1056/418_1_1056_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/418_1_1056/418_1_1056_t1+_thick_cor_VS_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/418_1_1056/418_1_1056_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/418_1_1056/418_1_1056_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/418_1_1056/418_1_1056_t2_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/418_1_1056/418_1_1056_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/418_1_1056/418_1_1056_t2_thin_VS_uvauser1_coregistered.nii.gz)

 33%|███▎      | 600/1793 [04:29<09:19,  2.13it/s]

Original image path: ./raw_studies/t2_thick/418_1_1056/418_1_1056_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/418_1_1056/418_1_1056_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/418_1_1056/418_1_1056_t2_thick_VS_uvauser1.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t2_thick/418_2_1238/418_2_1238_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/418_2_1238/418_2_1238_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/418_2_1238/418_2_1238_t2_thick_VS_uvauser1.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thick_ax/418_2_1238/418_2_1238_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/418_2_1238/418_2_1238_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/418_2_1238/418_2_1238_t1+_thick_ax_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/418_2_1238/418_2_1238_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/418_2_1238/418_2_1238_t1+_thick_ax_VS_uvauser1_coregistered.nii.gz)

 34%|███▎      | 604/1793 [04:30<04:53,  4.06it/s]

Original image path: ./raw_studies/t2_thick/418_2_1238/418_2_1238_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/418_2_1238/418_2_1238_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/418_2_1238/418_2_1238_t2_thick_VS_uvauser1.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thick_cor/418_2_1238/418_2_1238_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/418_2_1238/418_2_1238_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/418_2_1238/418_2_1238_t1+_thick_cor_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/418_2_1238/418_2_1238_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/418_2_1238/418_2_1238_t1+_thick_cor_VS_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thin/418_2_1238/418_2_1238_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/418_2_1238/418_2_1238_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/418_2_1238/418_2_1238_t1+_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/418_2_1238/418_2_1238_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/418_2_1238/418_2_1238_t1+_thin_VS_uvauser1_coregistered.nii.gz)

 34%|███▎      | 605/1793 [04:30<05:52,  3.37it/s]

Original image path: ./raw_studies/t2_thin/418_2_1238/418_2_1238_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/418_2_1238/418_2_1238_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/418_2_1238/418_2_1238_t2_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/418_2_1238/418_2_1238_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/418_2_1238/418_2_1238_t2_thin_VS_uvauser1_coregistered.nii.gz)

 34%|███▍      | 606/1793 [04:31<06:45,  2.93it/s]

Original image path: ./raw_studies/t2_thin/418_3_1428/418_3_1428_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/418_3_1428/418_3_1428_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/418_3_1428/418_3_1428_t2_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/418_3_1428/418_3_1428_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/418_3_1428/418_3_1428_t2_thin_VS_uvauser1_coregistered.nii.gz)

 34%|███▍      | 608/1793 [04:32<08:16,  2.39it/s]

Original image path: ./raw_studies/t1+_thick_cor/418_3_1428/418_3_1428_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/418_3_1428/418_3_1428_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/418_3_1428/418_3_1428_t1+_thick_cor_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/418_3_1428/418_3_1428_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/418_3_1428/418_3_1428_t1+_thick_cor_VS_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thick/418_3_1428/418_3_1428_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/418_3_1428/418_3_1428_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/418_3_1428/418_3_1428_t2_thick_VS_uvauser1.nii.gz
Returning: (nan, nan)

 34%|███▍      | 609/1793 [04:32<07:09,  2.76it/s]

Original image path: ./raw_studies/t1+_thin/418_3_1428/418_3_1428_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/418_3_1428/418_3_1428_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/418_3_1428/418_3_1428_t1+_thin_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/418_3_1428/418_3_1428_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/418_3_1428/418_3_1428_t1+_thin_AS_uvauser4_coregistered.nii.gz)

 34%|███▍      | 611/1793 [04:34<12:22,  1.59it/s]

Original image path: ./raw_studies/t1+_thick_ax/418_3_1428/418_3_1428_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/418_3_1428/418_3_1428_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/418_3_1428/418_3_1428_t1+_thick_ax_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t2_thick/418_3_1428/418_3_1428_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/418_3_1428/418_3_1428_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 34%|███▍      | 612/1793 [04:35<09:57,  1.98it/s]

Original image path: ./raw_studies/t1+_thick_cor/421_0_0/421_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/421_0_0/421_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/421_0_0/421_0_0_t1+_thick_cor_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t2_thin/421_0_0/421_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/421_0_0/421_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/421_0_0/421_0_0_t2_thin_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/421_0_0/421_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/421_0_0/421_0_0_t2_thin_tumorcore _uvauser3_coregistered.nii.gz)

 34%|███▍      | 616/1793 [04:35<04:44,  4.14it/s]

Original image path: ./raw_studies/t1+_thick_ax/421_0_0/421_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/421_0_0/421_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/421_0_0/421_0_0_t1+_thick_ax_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thick_ax/421_1_264/421_1_264_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/421_1_264/421_1_264_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/421_1_264/421_1_264_t1+_thick_ax_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/421_1_264/421_1_264_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/421_1_264/421_1_264_t1+_thick_ax_AS_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/421_1_264/421_1_264_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/421_1_264/421_1_264_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/421_1_264/421_1_264_t1+_thick_cor_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/421_1_264/421_1_264_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/421_1_264/421_1_264_t1+_thick_cor_AS_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/421_1_264/421_1_264_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/421_1_264/421_1_264_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/421_1_264/421_1_264_t2_thin_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/421_1_264/421_1_264_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/421_1_264/421_1_264_t2_thin_AS_uvauser4_coregistered.nii.gz)

 34%|███▍      | 618/1793 [04:36<07:01,  2.79it/s]

Original image path: ./raw_studies/t1+_thick_cor/421_2_1633/421_2_1633_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/421_2_1633/421_2_1633_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/421_2_1633/421_2_1633_t1+_thick_cor_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/421_2_1633/421_2_1633_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/421_2_1633/421_2_1633_t1+_thick_cor_AS_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/421_2_1633/421_2_1633_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/421_2_1633/421_2_1633_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/421_2_1633/421_2_1633_t2_thin_AS_uvauser4-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/421_2_1633/421_2_1633_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/421_2_1633/421_2_1633_t2_thin_AS_uvauser4-copy_coregistered.nii.gz)

 35%|███▍      | 620/1793 [04:38<08:47,  2.22it/s]

Original image path: ./raw_studies/t1+_thick_ax/421_2_1633/421_2_1633_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/421_2_1633/421_2_1633_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/421_2_1633/421_2_1633_t1+_thick_ax_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/421_2_1633/421_2_1633_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/421_2_1633/421_2_1633_t1+_thick_ax_AS_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thin/421_3_1831/421_3_1831_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/421_3_1831/421_3_1831_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/421_3_1831/421_3_1831_t1+_thin_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/421_3_1831/421_3_1831_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/421_3_1831/421_3_1831_t1+_thin_AS_uvauser4_coregistered.nii.gz)

 35%|███▍      | 623/1793 [04:38<06:43,  2.90it/s]

Original image path: ./raw_studies/t2_thick/421_3_1831/421_3_1831_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/421_3_1831/421_3_1831_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/421_3_1831/421_3_1831_t2_thick_VST2_uvauser6.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thick_cor/421_4_3550/421_4_3550_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/421_4_3550/421_4_3550_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/421_4_3550/421_4_3550_t1+_thick_cor_image_coregistered.nii.gz, nan)

 35%|███▍      | 624/1793 [04:38<06:20,  3.07it/s]

Original image path: ./raw_studies/t2_thin/421_4_3550/421_4_3550_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/421_4_3550/421_4_3550_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/421_4_3550/421_4_3550_t2_thin_image_coregistered.nii.gz, nan)

 35%|███▍      | 625/1793 [04:40<10:25,  1.87it/s]

Original image path: ./raw_studies/t1+_thin/421_4_3550/421_4_3550_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/421_4_3550/421_4_3550_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/421_4_3550/421_4_3550_t1+_thin_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/421_4_3550/421_4_3550_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/421_4_3550/421_4_3550_t1+_thin_tumorcore _uvauser3_coregistered.nii.gz)

 35%|███▍      | 627/1793 [04:42<12:33,  1.55it/s]

Original image path: ./raw_studies/t1+_thick_ax/423_0_0/423_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/423_0_0/423_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/423_0_0/423_0_0_t1+_thick_ax_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thick_cor/423_0_0/423_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/423_0_0/423_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/423_0_0/423_0_0_t1+_thick_cor_image_coregistered.nii.gz, nan)

 35%|███▌      | 628/1793 [04:42<09:53,  1.96it/s]

Original image path: ./raw_studies/t2_thin/423_0_0/423_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/423_0_0/423_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/423_0_0/423_0_0_t2_thin_image_coregistered.nii.gz, nan)

 35%|███▌      | 629/1793 [04:42<09:29,  2.05it/s]

Original image path: ./raw_studies/t2_thin/423_1_434/423_1_434_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/423_1_434/423_1_434_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/423_1_434/423_1_434_t2_thin_AS1_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/423_1_434/423_1_434_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/423_1_434/423_1_434_t2_thin_AS1_uvauser4_coregistered.nii.gz)

 35%|███▌      | 630/1793 [04:43<12:44,  1.52it/s]

Original image path: ./raw_studies/t1+_thick_ax/423_1_434/423_1_434_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/423_1_434/423_1_434_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/423_1_434/423_1_434_t1+_thick_ax_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/423_1_434/423_1_434_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/423_1_434/423_1_434_t1+_thick_ax_AS_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thick/423_1_434/423_1_434_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/423_1_434/423_1_434_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 35%|███▌      | 632/1793 [04:43<08:08,  2.38it/s]

Original image path: ./raw_studies/t1+_thick_cor/423_1_434/423_1_434_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/423_1_434/423_1_434_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/423_1_434/423_1_434_t1+_thick_cor_AS1_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/423_1_434/423_1_434_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/423_1_434/423_1_434_t1+_thick_cor_AS1_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thick/423_1_434/423_1_434_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/423_1_434/423_1_434_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/423_1_434/423_1_434_t2_thick_AS_uvauser4.nii.gz
Returning: (nan, nan)

 35%|███▌      | 634/1793 [04:44<05:56,  3.25it/s]

Original image path: ./raw_studies/t2_thin/423_2_1169/423_2_1169_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/423_2_1169/423_2_1169_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/423_2_1169/423_2_1169_t2_thin_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/423_2_1169/423_2_1169_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/423_2_1169/423_2_1169_t2_thin_RVS _uvauser2_coregistered.nii.gz)

 36%|███▌      | 637/1793 [04:44<04:24,  4.37it/s]

Original image path: ./raw_studies/t1+_thick_ax/423_2_1169/423_2_1169_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/423_2_1169/423_2_1169_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/423_2_1169/423_2_1169_t1+_thick_ax_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/423_2_1169/423_2_1169_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/423_2_1169/423_2_1169_t1+_thick_ax_RVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/423_2_1169/423_2_1169_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/423_2_1169/423_2_1169_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/423_2_1169/423_2_1169_t1+_thick_cor_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/423_2_1169/423_2_1169_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/423_2_1169/423_2_1169_t1+_thick_cor_RVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thin/423_3_1262/423_3_1262_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/423_3_1262/423_3_1262_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/423_3_1262/423_3_1262_t1+_thin_manual_0_uvauser13.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/423_3_1262/423_3_1262_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/423_3_1262/423_3_1262_t1+_thin_manual_0_uvauser13_coregistered.nii.gz)

 36%|███▌      | 638/1793 [04:46<08:46,  2.19it/s]

Original image path: ./raw_studies/t2_thin/423_3_1262/423_3_1262_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/423_3_1262/423_3_1262_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/423_3_1262/423_3_1262_t2_thin_image_coregistered.nii.gz, nan)

 36%|███▌      | 640/1793 [04:46<06:37,  2.90it/s]

Original image path: ./raw_studies/t1+_thick_cor/424_4_2863/424_4_2863_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/424_4_2863/424_4_2863_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/424_4_2863/424_4_2863_t1+_thick_cor_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/424_4_2863/424_4_2863_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/424_4_2863/424_4_2863_t1+_thick_cor_LVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thin/424_4_2863/424_4_2863_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/424_4_2863/424_4_2863_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/424_4_2863/424_4_2863_t1+_thin_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/424_4_2863/424_4_2863_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/424_4_2863/424_4_2863_t1+_thin_LVS _uvauser2_coregistered.nii.gz)

 36%|███▌      | 642/1793 [04:46<05:29,  3.49it/s]

Original image path: ./raw_studies/t2_thin/424_4_2863/424_4_2863_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/424_4_2863/424_4_2863_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/424_4_2863/424_4_2863_t2_thin_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thick_ax/424_4_2863/424_4_2863_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/424_4_2863/424_4_2863_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/424_4_2863/424_4_2863_t1+_thick_ax_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/424_4_2863/424_4_2863_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/424_4_2863/424_4_2863_t1+_thick_ax_LVS _uvauser2_coregistered.nii.gz)

 36%|███▌      | 644/1793 [04:47<04:13,  4.53it/s]

Original image path: ./raw_studies/t2_thin/424_4_2863/424_4_2863_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/424_4_2863/424_4_2863_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/424_4_2863/424_4_2863_t2_thin_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/424_4_2863/424_4_2863_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/424_4_2863/424_4_2863_t2_thin_LVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thick/424_4_2863/424_4_2863_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/424_4_2863/424_4_2863_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 36%|███▌      | 646/1793 [04:47<03:08,  6.09it/s]

Original image path: ./raw_studies/t2_thick/424_4_2863/424_4_2863_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/424_4_2863/424_4_2863_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

Original image path: ./raw_studies/t2_thin/424_5_4003/424_5_4003_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/424_5_4003/424_5_4003_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/424_5_4003/424_5_4003_t2_thin_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/424_5_4003/424_5_4003_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/424_5_4003/424_5_4003_t2_thin_LVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thin/424_5_4003/424_5_4003_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/424_5_4003/424_5_4003_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/424_5_4003/424_5_4003_t1+_thin_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/424_5_4003/424_5_4003_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/424_5_4003/424_5_4003_t1+_thin_LVS _uvauser2_coregistered.nii.gz)

 36%|███▌      | 648/1793 [04:47<03:06,  6.15it/s]

Original image path: ./raw_studies/t1+_thick_ax/424_5_4003/424_5_4003_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/424_5_4003/424_5_4003_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/424_5_4003/424_5_4003_t1+_thick_ax_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/424_5_4003/424_5_4003_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/424_5_4003/424_5_4003_t1+_thick_ax_LVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thick/424_5_4003/424_5_4003_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/424_5_4003/424_5_4003_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 36%|███▋      | 652/1793 [04:48<02:57,  6.44it/s]

Original image path: ./raw_studies/t2_thin/424_5_4003/424_5_4003_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/424_5_4003/424_5_4003_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/424_5_4003/424_5_4003_t2_thin_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thick_cor/424_5_4003/424_5_4003_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/424_5_4003/424_5_4003_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/424_5_4003/424_5_4003_t1+_thick_cor_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/424_5_4003/424_5_4003_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/424_5_4003/424_5_4003_t1+_thick_cor_LVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thick/424_5_4003/424_5_4003_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/424_5_4003/424_5_4003_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 36%|███▋      | 654/1793 [04:48<03:39,  5.18it/s]

Original image path: ./raw_studies/t1+_thick_ax/424_6_4194/424_6_4194_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/424_6_4194/424_6_4194_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/424_6_4194/424_6_4194_t1+_thick_ax_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thin/424_6_4194/424_6_4194_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/424_6_4194/424_6_4194_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/424_6_4194/424_6_4194_t1+_thin_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/424_6_4194/424_6_4194_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/424_6_4194/424_6_4194_t1+_thin_tumorcore _uvauser3_coregistered.nii.gz)

 37%|███▋      | 655/1793 [04:50<09:51,  1.92it/s]

Original image path: ./raw_studies/t2_thin/424_6_4194/424_6_4194_t2_thin_image_uint8.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/424_6_4194/424_6_4194_t2_thin_image_uint8_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 37%|███▋      | 656/1793 [04:52<17:21,  1.09it/s]

Original image path: ./raw_studies/t1+_thick_cor/424_6_4194/424_6_4194_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/424_6_4194/424_6_4194_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/424_6_4194/424_6_4194_t1+_thick_cor_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t2_thick/424_6_4194/424_6_4194_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/424_6_4194/424_6_4194_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 37%|███▋      | 658/1793 [04:52<11:17,  1.68it/s]

Original image path: ./raw_studies/t1+_thick_cor/426_0_0/426_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/426_0_0/426_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

Original image path: ./raw_studies/t2_thin/426_0_0/426_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/426_0_0/426_0_0_t2_thin_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thin/426_0_0/426_0_0_t2_thin_manual_0_uvauser1.nii.gz
Returning: (nan, nan)

 37%|███▋      | 660/1793 [04:53<08:09,  2.31it/s]

Original image path: ./raw_studies/t1+_thick_ax/426_0_0/426_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/426_0_0/426_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t1+_thick_ax/426_0_0/426_0_0_t1+_thick_ax_manual_0_uvauser1.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t2_thin/427_0_0/427_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/427_0_0/427_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/427_0_0/427_0_0_t2_thin_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/427_0_0/427_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/427_0_0/427_0_0_t2_thin_AS_uvauser4_coregistered.nii.gz)

 37%|███▋      | 663/1793 [04:54<07:02,  2.68it/s]

Original image path: ./raw_studies/t1+_thick_cor/427_0_0/427_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/427_0_0/427_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/427_0_0/427_0_0_t1+_thick_cor_AS1_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/427_0_0/427_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/427_0_0/427_0_0_t1+_thick_cor_AS1_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/427_0_0/427_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/427_0_0/427_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/427_0_0/427_0_0_t1+_thick_ax_AS2_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/427_0_0/427_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/427_0_0/427_0_0_t1+_thick_ax_AS2_uvauser4_coregistered.nii.gz)

 37%|███▋      | 665/1793 [04:54<05:23,  3.49it/s]

Original image path: ./raw_studies/t1+_thick_cor/427_1_263/427_1_263_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/427_1_263/427_1_263_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/427_1_263/427_1_263_t1+_thick_cor_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thick_ax/427_1_263/427_1_263_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/427_1_263/427_1_263_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/427_1_263/427_1_263_t1+_thick_ax_Manual_0_uvauser11.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/427_1_263/427_1_263_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/427_1_263/427_1_263_t1+_thick_ax_Manual_0_uvauser11_coregistered.nii.gz)

 37%|███▋      | 666/1793 [04:54<04:39,  4.03it/s]

Original image path: ./raw_studies/t2_thin/427_1_263/427_1_263_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/427_1_263/427_1_263_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/427_1_263/427_1_263_t2_thin_Manual_0_uvauser11.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/427_1_263/427_1_263_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/427_1_263/427_1_263_t2_thin_Manual_0_uvauser11_coregistered.nii.gz)

 37%|███▋      | 667/1793 [04:55<05:37,  3.33it/s]

Original image path: ./raw_studies/t2_thin/427_2_315/427_2_315_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/427_2_315/427_2_315_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/427_2_315/427_2_315_t2_thin_AS1_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/427_2_315/427_2_315_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/427_2_315/427_2_315_t2_thin_AS1_uvauser4_coregistered.nii.gz)

 37%|███▋      | 668/1793 [04:55<06:22,  2.94it/s]

Original image path: ./raw_studies/t1+_thin/427_2_315/427_2_315_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/427_2_315/427_2_315_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/427_2_315/427_2_315_t1+_thin_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/427_2_315/427_2_315_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/427_2_315/427_2_315_t1+_thin_AS_uvauser4_coregistered.nii.gz)

 37%|███▋      | 669/1793 [04:56<12:25,  1.51it/s]

Original image path: ./raw_studies/t1+_thick_cor/429_1_407/429_1_407_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/429_1_407/429_1_407_t1+_thick_cor_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t1+_thick_cor/429_1_407/429_1_407_t1+_thick_cor_VST1cor_uvauser6.nii.gz
Returning: (nan, nan)

 37%|███▋      | 670/1793 [04:57<10:31,  1.78it/s]

Original image path: ./raw_studies/t1+_thick_ax/429_1_407/429_1_407_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/429_1_407/429_1_407_t1+_thick_ax_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t1+_thick_ax/429_1_407/429_1_407_t1+_thick_ax_VST1ax_uvauser6.nii.gz
Returning: (nan, nan)

 37%|███▋      | 672/1793 [04:57<07:11,  2.60it/s]

Original image path: ./raw_studies/t1+_thick_ax/429_1_407/429_1_407_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/429_1_407/429_1_407_t1+_thick_ax_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t1+_thick_ax/429_1_407/429_1_407_t1+_thick_ax_RVS _uvauser2.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t2_thick/429_1_407/429_1_407_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/429_1_407/429_1_407_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/429_1_407/429_1_407_t2_thick_RVS _uvauser2.nii.gz
Returning: (nan, nan)

 38%|███▊      | 674/1793 [04:57<05:04,  3.67it/s]

Original image path: ./raw_studies/t1+_thick_ax/429_2_876/429_2_876_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/429_2_876/429_2_876_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/429_2_876/429_2_876_t1+_thick_ax_manual_0_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/429_2_876/429_2_876_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/429_2_876/429_2_876_t1+_thick_ax_manual_0_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/429_2_876/429_2_876_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/429_2_876/429_2_876_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/429_2_876/429_2_876_t2_thin_image_coregistered.nii.gz, nan)

 38%|███▊      | 675/1793 [04:58<07:13,  2.58it/s]

Original image path: ./raw_studies/t1+_thick_cor/429_2_876/429_2_876_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/429_2_876/429_2_876_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/429_2_876/429_2_876_t1+_thick_cor_manual_0_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/429_2_876/429_2_876_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/429_2_876/429_2_876_t1+_thick_cor_manual_0_uvauser1_coregistered.nii.gz)

 38%|███▊      | 678/1793 [04:59<04:18,  4.32it/s]

Original image path: ./raw_studies/t1+_thick_ax/434_0_0/434_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/434_0_0/434_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/434_0_0/434_0_0_t1+_thick_ax_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thick_cor/434_0_0/434_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/434_0_0/434_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/434_0_0/434_0_0_t1+_thick_cor_manual_0_uvauser8.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/434_0_0/434_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/434_0_0/434_0_0_t1+_thick_cor_manual_0_uvauser8_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/434_0_0/434_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/434_0_0/434_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/434_0_0/434_0_0_t2_thin_image_coregistered.nii.gz, nan)

 38%|███▊      | 679/1793 [04:59<04:07,  4.50it/s]

Original image path: ./raw_studies/t1+_thin/434_1_160/434_1_160_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/434_1_160/434_1_160_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/434_1_160/434_1_160_t1+_thin_tumorcore _uvauser3-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/434_1_160/434_1_160_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/434_1_160/434_1_160_t1+_thin_tumorcore _uvauser3-copy_coregistered.nii.gz)

 38%|███▊      | 680/1793 [05:00<09:45,  1.90it/s]

Original image path: ./raw_studies/t1+_thin/434_1_160/434_1_160_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/434_1_160/434_1_160_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/434_1_160/434_1_160_t1+_thin_image_coregistered.nii.gz, nan)

 38%|███▊      | 682/1793 [05:02<10:43,  1.73it/s]

Original image path: ./raw_studies/t1+_thick_ax/434_1_160/434_1_160_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/434_1_160/434_1_160_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/434_1_160/434_1_160_t1+_thick_ax_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t2_thin/434_1_160/434_1_160_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/434_1_160/434_1_160_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/434_1_160/434_1_160_t2_thin_image_coregistered.nii.gz, nan)

 38%|███▊      | 684/1793 [05:03<09:08,  2.02it/s]

Original image path: ./raw_studies/t2_thick/434_1_160/434_1_160_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/434_1_160/434_1_160_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thin/434_1_160/434_1_160_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/434_1_160/434_1_160_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/434_1_160/434_1_160_t1+_thin_image_coregistered.nii.gz, nan)

 38%|███▊      | 686/1793 [05:04<10:24,  1.77it/s]

Original image path: ./raw_studies/t1+_thick_cor/434_1_160/434_1_160_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/434_1_160/434_1_160_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/434_1_160/434_1_160_t1+_thick_cor_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thick_ax/437_0_0/437_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/437_0_0/437_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/437_0_0/437_0_0_t1+_thick_ax_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/437_0_0/437_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/437_0_0/437_0_0_t1+_thick_ax_RVS _uvauser2_coregistered.nii.gz)

 38%|███▊      | 688/1793 [05:04<06:39,  2.77it/s]

Original image path: ./raw_studies/t1+_thick_cor/437_0_0/437_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/437_0_0/437_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/437_0_0/437_0_0_t1+_thick_cor_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/437_0_0/437_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/437_0_0/437_0_0_t1+_thick_cor_RVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/437_0_0/437_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/437_0_0/437_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/437_0_0/437_0_0_t2_thin_image_coregistered.nii.gz, nan)

 39%|███▊      | 691/1793 [05:05<04:24,  4.17it/s]

Original image path: ./raw_studies/t2_thick/437_0_0/437_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/437_0_0/437_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/437_0_0/437_0_0_t2_thick_RVS _uvauser2.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t2_thick/437_0_0/437_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/437_0_0/437_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thin/437_1_52/437_1_52_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/437_1_52/437_1_52_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/437_1_52/437_1_52_t1+_thin_VST1_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/437_1_52/437_1_52_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/437_1_52/437_1_52_t1+_thin_VST1_uvauser6_coregistered.nii.gz)

 39%|███▊      | 692/1793 [05:06<09:33,  1.92it/s]

Original image path: ./raw_studies/t2_thin/437_1_52/437_1_52_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/437_1_52/437_1_52_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/437_1_52/437_1_52_t2_thin_VST2_uvauser6-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/437_1_52/437_1_52_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/437_1_52/437_1_52_t2_thin_VST2_uvauser6-copy_coregistered.nii.gz)

 39%|███▊      | 694/1793 [05:07<07:32,  2.43it/s]

Original image path: ./raw_studies/t2_thick/439_0_0/439_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/439_0_0/439_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/439_0_0/439_0_0_t2_thick_RVS _uvauser2.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thick_cor/439_0_0/439_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/439_0_0/439_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/439_0_0/439_0_0_t1+_thick_cor_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/439_0_0/439_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/439_0_0/439_0_0_t1+_thick_cor_RVS _uvauser2_coregistered.nii.gz)

 39%|███▉      | 695/1793 [05:07<07:19,  2.50it/s]

Original image path: ./raw_studies/t2_thin/439_0_0/439_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/439_0_0/439_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/439_0_0/439_0_0_t2_thin_image_coregistered.nii.gz, nan)

 39%|███▉      | 696/1793 [05:08<08:55,  2.05it/s]

Original image path: ./raw_studies/t1+_thick_ax/439_0_0/439_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/439_0_0/439_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/439_0_0/439_0_0_t1+_thick_ax_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/439_0_0/439_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/439_0_0/439_0_0_t1+_thick_ax_RVS _uvauser2_coregistered.nii.gz)

 39%|███▉      | 697/1793 [05:09<08:34,  2.13it/s]

Original image path: ./raw_studies/t1+_thick_ax/439_1_12/439_1_12_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/439_1_12/439_1_12_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/439_1_12/439_1_12_t1+_thick_ax_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/439_1_12/439_1_12_t1+_thick_ax_image_coregistered.nii.gz, nan)

 39%|███▉      | 699/1793 [05:09<06:34,  2.77it/s]

Original image path: ./raw_studies/t1+_thick_cor/439_1_12/439_1_12_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/439_1_12/439_1_12_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/439_1_12/439_1_12_t1+_thick_cor_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/439_1_12/439_1_12_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/439_1_12/439_1_12_t1+_thick_cor_RVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/439_1_12/439_1_12_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/439_1_12/439_1_12_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/439_1_12/439_1_12_t2_thin_RVS _uvauser2-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/439_1_12/439_1_12_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/439_1_12/439_1_12_t2_thin_RVS _uvauser2-copy_coregistered.nii.gz)

 39%|███▉      | 701/1793 [05:10<07:32,  2.41it/s]

Original image path: ./raw_studies/t2_thick/439_2_209/439_2_209_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/439_2_209/439_2_209_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thick_ax/439_2_209/439_2_209_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/439_2_209/439_2_209_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/439_2_209/439_2_209_t1+_thick_ax_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/439_2_209/439_2_209_t1+_thick_ax_image_coregistered.nii.gz, nan)

 39%|███▉      | 703/1793 [05:11<07:24,  2.45it/s]

Original image path: ./raw_studies/t1+_thick_cor/439_2_209/439_2_209_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/439_2_209/439_2_209_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/439_2_209/439_2_209_t1+_thick_cor_manual_0_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/439_2_209/439_2_209_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/439_2_209/439_2_209_t1+_thick_cor_manual_0_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/439_2_209/439_2_209_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/439_2_209/439_2_209_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/439_2_209/439_2_209_t2_thin_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/439_2_209/439_2_209_t2_thin_image_coregistered.nii.gz, nan)

 39%|███▉      | 704/1793 [05:12<12:24,  1.46it/s]

Original image path: ./raw_studies/t1+_thick_cor/439_3_437/439_3_437_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/439_3_437/439_3_437_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/439_3_437/439_3_437_t1+_thick_cor_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/439_3_437/439_3_437_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/439_3_437/439_3_437_t1+_thick_cor_RVS _uvauser2_coregistered.nii.gz)

 39%|███▉      | 705/1793 [05:13<09:53,  1.83it/s]

Original image path: ./raw_studies/t2_thin/439_3_437/439_3_437_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/439_3_437/439_3_437_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/439_3_437/439_3_437_t2_thin_RVS _uvauser2-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/439_3_437/439_3_437_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/439_3_437/439_3_437_t2_thin_RVS _uvauser2-copy_coregistered.nii.gz)

 39%|███▉      | 706/1793 [05:15<18:44,  1.03s/it]

Original image path: ./raw_studies/t2_thick/439_3_437/439_3_437_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/439_3_437/439_3_437_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 39%|███▉      | 708/1793 [05:15<11:42,  1.54it/s]

Original image path: ./raw_studies/t1+_thick_ax/439_3_437/439_3_437_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/439_3_437/439_3_437_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/439_3_437/439_3_437_t1+_thick_ax_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/439_3_437/439_3_437_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/439_3_437/439_3_437_t1+_thick_ax_RVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/439_4_489/439_4_489_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/439_4_489/439_4_489_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/439_4_489/439_4_489_t2_thin_image_coregistered.nii.gz, nan)

 40%|███▉      | 709/1793 [05:16<09:45,  1.85it/s]

Original image path: ./raw_studies/t1+_thin/439_4_489/439_4_489_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/439_4_489/439_4_489_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/439_4_489/439_4_489_t1+_thin_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/439_4_489/439_4_489_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/439_4_489/439_4_489_t1+_thin_tumorcore _uvauser3_coregistered.nii.gz)

 40%|███▉      | 711/1793 [05:17<10:48,  1.67it/s]

Original image path: ./raw_studies/t2_thick/442_0_0/442_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/442_0_0/442_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

Original image path: ./raw_studies/t2_thin/442_1_282/442_1_282_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/442_1_282/442_1_282_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/442_1_282/442_1_282_t2_thin_image_coregistered.nii.gz, nan)

 40%|███▉      | 713/1793 [05:18<10:08,  1.78it/s]

Original image path: ./raw_studies/t1+_thick_cor/442_1_282/442_1_282_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/442_1_282/442_1_282_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/442_1_282/442_1_282_t1+_thick_cor_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/442_1_282/442_1_282_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/442_1_282/442_1_282_t1+_thick_cor_AS_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/442_1_282/442_1_282_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/442_1_282/442_1_282_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/442_1_282/442_1_282_t1+_thick_ax_AS1_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/442_1_282/442_1_282_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/442_1_282/442_1_282_t1+_thick_ax_AS1_uvauser4_coregistered.nii.gz)

 40%|███▉      | 714/1793 [05:19<07:53,  2.28it/s]

Original image path: ./raw_studies/t2_thin/442_2_702/442_2_702_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/442_2_702/442_2_702_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/442_2_702/442_2_702_t2_thin_image_coregistered.nii.gz, nan)

 40%|███▉      | 717/1793 [05:20<06:23,  2.81it/s]

Original image path: ./raw_studies/t1+_thick_cor/442_2_702/442_2_702_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/442_2_702/442_2_702_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/442_2_702/442_2_702_t1+_thick_cor_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/442_2_702/442_2_702_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/442_2_702/442_2_702_t1+_thick_cor_tumorcore _uvauser3_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/442_2_702/442_2_702_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/442_2_702/442_2_702_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/442_2_702/442_2_702_t1+_thick_ax_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t2_thin/442_3_702/442_3_702_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/442_3_702/442_3_702_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/442_3_702/442_3_702_t2_thin_Manual_0_uvauser11.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/442_3_702/442_3_702_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/442_3_702/442_3_702_t2_thin_Manual_0_uvauser11_coregistered.nii.gz)

 40%|████      | 720/1793 [05:21<05:55,  3.02it/s]

Original image path: ./raw_studies/t1+_thick_cor/442_3_702/442_3_702_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/442_3_702/442_3_702_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/442_3_702/442_3_702_t1+_thick_cor_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thick_ax/442_3_702/442_3_702_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/442_3_702/442_3_702_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/442_3_702/442_3_702_t1+_thick_ax_Manual_0_uvauser11.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/442_3_702/442_3_702_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/442_3_702/442_3_702_t1+_thick_ax_Manual_0_uvauser11_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/442_5_1272/442_5_1272_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/442_5_1272/442_5_1272_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/442_5_1272/442_5_1272_t1+_thick_ax_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/442_5_1272/442_5_1272_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/442_5_1272/442_5_1272_t1+_thick_ax_VS_uvauser1_coregistered.nii.gz)

 40%|████      | 721/1793 [05:21<05:17,  3.37it/s]

Original image path: ./raw_studies/t2_thin/442_5_1272/442_5_1272_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/442_5_1272/442_5_1272_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/442_5_1272/442_5_1272_t2_thin_AX_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/442_5_1272/442_5_1272_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/442_5_1272/442_5_1272_t2_thin_AX_VS_uvauser1_coregistered.nii.gz)

 40%|████      | 723/1793 [05:22<07:09,  2.49it/s]

Original image path: ./raw_studies/t1+_thick_cor/442_5_1272/442_5_1272_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/442_5_1272/442_5_1272_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/442_5_1272/442_5_1272_t1+_thick_cor_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/442_5_1272/442_5_1272_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/442_5_1272/442_5_1272_t1+_thick_cor_VS_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/442_6_1447/442_6_1447_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/442_6_1447/442_6_1447_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/442_6_1447/442_6_1447_t1+_thick_ax_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/442_6_1447/442_6_1447_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/442_6_1447/442_6_1447_t1+_thick_ax_AS_uvauser4_coregistered.nii.gz)

 40%|████      | 724/1793 [05:22<06:01,  2.96it/s]

Original image path: ./raw_studies/t2_thin/442_6_1447/442_6_1447_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/442_6_1447/442_6_1447_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/442_6_1447/442_6_1447_t2_thin_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/442_6_1447/442_6_1447_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/442_6_1447/442_6_1447_t2_thin_AS_uvauser4_coregistered.nii.gz)

 40%|████      | 726/1793 [05:24<08:04,  2.20it/s]

Original image path: ./raw_studies/t1+_thick_cor/442_6_1447/442_6_1447_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/442_6_1447/442_6_1447_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/442_6_1447/442_6_1447_t1+_thick_cor_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/442_6_1447/442_6_1447_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/442_6_1447/442_6_1447_t1+_thick_cor_AS_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thin/45_4_4326/45_4_4326_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/45_4_4326/45_4_4326_t1+_thin_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t1+_thin/45_4_4326/45_4_4326_t1+_thin_manual_10_uvauser10.nii.gz
Returning: (nan, nan)

 41%|████      | 727/1793 [05:24<08:19,  2.14it/s]

Original image path: ./raw_studies/t1+_thin/45_5_5953/45_5_5953_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/45_5_5953/45_5_5953_t1+_thin_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t1+_thin/45_5_5953/45_5_5953_t1+_thin_manual_0_uvauser8.nii.gz
Returning: (nan, nan)

 41%|████      | 728/1793 [05:25<08:26,  2.10it/s]

Original image path: ./raw_studies/t2_thin/454_0_0/454_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/454_0_0/454_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/454_0_0/454_0_0_t2_thin_Manual_0_uvauser11.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/454_0_0/454_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/454_0_0/454_0_0_t2_thin_Manual_0_uvauser11_coregistered.nii.gz)

 41%|████      | 730/1793 [05:25<06:20,  2.79it/s]

Original image path: ./raw_studies/t1+_thick_cor/454_0_0/454_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/454_0_0/454_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/454_0_0/454_0_0_t1+_thick_cor_AX_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/454_0_0/454_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/454_0_0/454_0_0_t1+_thick_cor_AX_VS_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/454_0_0/454_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/454_0_0/454_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/454_0_0/454_0_0_t1+_thick_ax_Manual_0_uvauser11.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/454_0_0/454_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/454_0_0/454_0_0_t1+_thick_ax_Manual_0_uvauser11_coregistered.nii.gz)

 41%|████      | 733/1793 [05:25<03:26,  5.14it/s]

Original image path: ./raw_studies/t1+_thick_cor/454_1_199/454_1_199_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/454_1_199/454_1_199_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/454_1_199/454_1_199_t1+_thick_cor_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/454_1_199/454_1_199_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/454_1_199/454_1_199_t1+_thick_cor_AS_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/454_1_199/454_1_199_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/454_1_199/454_1_199_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/454_1_199/454_1_199_t1+_thick_ax_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/454_1_199/454_1_199_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/454_1_199/454_1_199_t1+_thick_ax_AS_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/454_1_199/454_1_199_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/454_1_199/454_1_199_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/454_1_199/454_1_199_t2_thin_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/454_1_199/454_1_199_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/454_1_199/454_1_199_t2_thin_AS_uvauser4_coregistered.nii.gz)

 41%|████      | 734/1793 [05:27<07:39,  2.30it/s]

Original image path: ./raw_studies/t1+_thick_ax/454_2_556/454_2_556_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/454_2_556/454_2_556_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/454_2_556/454_2_556_t1+_thick_ax_VST1AX_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/454_2_556/454_2_556_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/454_2_556/454_2_556_t1+_thick_ax_VST1AX_uvauser6_coregistered.nii.gz)

 41%|████      | 736/1793 [05:27<05:50,  3.02it/s]

Original image path: ./raw_studies/t1+_thick_cor/454_2_556/454_2_556_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/454_2_556/454_2_556_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/454_2_556/454_2_556_t1+_thick_cor_VST1COR_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/454_2_556/454_2_556_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/454_2_556/454_2_556_t1+_thick_cor_VST1COR_uvauser6_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/454_2_556/454_2_556_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/454_2_556/454_2_556_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/454_2_556/454_2_556_t2_thin_VST2_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/454_2_556/454_2_556_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/454_2_556/454_2_556_t2_thin_VST2_uvauser6_coregistered.nii.gz)

 41%|████      | 737/1793 [05:28<09:12,  1.91it/s]

Original image path: ./raw_studies/t1+_thin/454_3_2334/454_3_2334_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/454_3_2334/454_3_2334_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/454_3_2334/454_3_2334_t1+_thin_image_coregistered.nii.gz, nan)

 41%|████      | 739/1793 [05:29<07:04,  2.48it/s]

Original image path: ./raw_studies/t1+_thick_cor/454_3_2334/454_3_2334_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/454_3_2334/454_3_2334_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/454_3_2334/454_3_2334_t1+_thick_cor_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t2_thick/454_3_2334/454_3_2334_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/454_3_2334/454_3_2334_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 41%|████▏     | 740/1793 [05:29<05:50,  3.01it/s]

Original image path: ./raw_studies/t2_thin/454_3_2334/454_3_2334_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/454_3_2334/454_3_2334_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/454_3_2334/454_3_2334_t2_thin_image_coregistered.nii.gz, nan)

 41%|████▏     | 742/1793 [05:30<07:27,  2.35it/s]

Original image path: ./raw_studies/t1+_thin/459_3_493/459_3_493_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/459_3_493/459_3_493_t1+_thin_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t1+_thin/459_3_493/459_3_493_t1+_thin_manual_0_uvauser8.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t2_thin/459_3_493/459_3_493_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/459_3_493/459_3_493_t2_thin_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 41%|████▏     | 743/1793 [05:30<07:20,  2.38it/s]

Original image path: ./raw_studies/t1+_thin/461_0_0/461_0_0_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/461_0_0/461_0_0_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/461_0_0/461_0_0_t1+_thin_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/461_0_0/461_0_0_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/461_0_0/461_0_0_t1+_thin_LVS _uvauser2_coregistered.nii.gz)

 41%|████▏     | 744/1793 [05:32<12:35,  1.39it/s]

Original image path: ./raw_studies/t2_thick/461_0_0/461_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/461_0_0/461_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/461_0_0/461_0_0_t2_thick_LVS _uvauser2.nii.gz
Returning: (nan, nan)

 42%|████▏     | 745/1793 [05:32<11:42,  1.49it/s]

Original image path: ./raw_studies/t1+_thick_cor/461_0_0/461_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/461_0_0/461_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/461_0_0/461_0_0_t1+_thick_cor_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/461_0_0/461_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/461_0_0/461_0_0_t1+_thick_cor_LVS _uvauser2_coregistered.nii.gz)

 42%|████▏     | 748/1793 [05:34<09:34,  1.82it/s]

Original image path: ./raw_studies/t1+_thick_ax/461_1_218/461_1_218_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/461_1_218/461_1_218_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/461_1_218/461_1_218_t1+_thick_ax_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thick_cor/461_1_218/461_1_218_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/461_1_218/461_1_218_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/461_1_218/461_1_218_t1+_thick_cor_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/461_1_218/461_1_218_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/461_1_218/461_1_218_t1+_thick_cor_tumorcore _uvauser3_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/461_1_218/461_1_218_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/461_1_218/461_1_218_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/461_1_218/461_1_218_t2_thin_image_coregistered.nii.gz, nan)

 42%|████▏     | 749/1793 [05:35<11:38,  1.49it/s]

Original image path: ./raw_studies/t1+_thick_cor/461_2_617/461_2_617_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/461_2_617/461_2_617_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/461_2_617/461_2_617_t1+_thick_cor_VS2_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/461_2_617/461_2_617_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/461_2_617/461_2_617_t1+_thick_cor_VS2_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/461_2_617/461_2_617_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/461_2_617/461_2_617_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/461_2_617/461_2_617_t2_thin_VS_uvauser1-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/461_2_617/461_2_617_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/461_2_617/461_2_617_t2_thin_VS_uvauser1-copy_coregistered.nii.gz)

 42%|████▏     | 751/1793 [05:36<10:53,  1.59it/s]

Original image path: ./raw_studies/t1+_thick_ax/461_2_617/461_2_617_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/461_2_617/461_2_617_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/461_2_617/461_2_617_t1+_thick_ax_VS1_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/461_2_617/461_2_617_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/461_2_617/461_2_617_t1+_thick_ax_VS1_uvauser1_coregistered.nii.gz)

 42%|████▏     | 753/1793 [05:37<08:11,  2.12it/s]

Original image path: ./raw_studies/t1+_thick_ax/461_3_953/461_3_953_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/461_3_953/461_3_953_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/461_3_953/461_3_953_t1+_thick_ax_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/461_3_953/461_3_953_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/461_3_953/461_3_953_t1+_thick_ax_LVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/461_3_953/461_3_953_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/461_3_953/461_3_953_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/461_3_953/461_3_953_t1+_thick_cor_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/461_3_953/461_3_953_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/461_3_953/461_3_953_t1+_thick_cor_LVS _uvauser2_coregistered.nii.gz)

 42%|████▏     | 754/1793 [05:37<06:49,  2.53it/s]

Original image path: ./raw_studies/t2_thin/461_3_953/461_3_953_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/461_3_953/461_3_953_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/461_3_953/461_3_953_t2_thin_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/461_3_953/461_3_953_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/461_3_953/461_3_953_t2_thin_LVS _uvauser2_coregistered.nii.gz)

 42%|████▏     | 755/1793 [05:38<09:43,  1.78it/s]

Original image path: ./raw_studies/t2_thin/461_4_1331/461_4_1331_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/461_4_1331/461_4_1331_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/461_4_1331/461_4_1331_t2_thin_AX_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/461_4_1331/461_4_1331_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/461_4_1331/461_4_1331_t2_thin_AX_VS_uvauser1_coregistered.nii.gz)

 42%|████▏     | 756/1793 [05:39<12:00,  1.44it/s]

Original image path: ./raw_studies/t1+_thick_ax/461_4_1331/461_4_1331_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/461_4_1331/461_4_1331_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/461_4_1331/461_4_1331_t1+_thick_ax_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/461_4_1331/461_4_1331_t1+_thick_ax_image_coregistered.nii.gz, nan)

 42%|████▏     | 758/1793 [05:40<08:08,  2.12it/s]

Original image path: ./raw_studies/t1+_thick_cor/461_4_1331/461_4_1331_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/461_4_1331/461_4_1331_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/461_4_1331/461_4_1331_t1+_thick_cor_VST1COR_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/461_4_1331/461_4_1331_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/461_4_1331/461_4_1331_t1+_thick_cor_VST1COR_uvauser6_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/461_5_1679/461_5_1679_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/461_5_1679/461_5_1679_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/461_5_1679/461_5_1679_t2_thin_image_coregistered.nii.gz, nan)

 42%|████▏     | 760/1793 [05:40<06:17,  2.74it/s]

Original image path: ./raw_studies/t1+_thick_cor/461_5_1679/461_5_1679_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/461_5_1679/461_5_1679_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/461_5_1679/461_5_1679_t1+_thick_cor_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thin/461_5_1679/461_5_1679_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/461_5_1679/461_5_1679_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/461_5_1679/461_5_1679_t1+_thin_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/461_5_1679/461_5_1679_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/461_5_1679/461_5_1679_t1+_thin_tumorcore _uvauser3_coregistered.nii.gz)

 42%|████▏     | 762/1793 [05:42<09:37,  1.78it/s]

Original image path: ./raw_studies/t1+_thick_ax/461_5_1679/461_5_1679_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/461_5_1679/461_5_1679_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/461_5_1679/461_5_1679_t1+_thick_ax_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thick_ax/467_0_0/467_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/467_0_0/467_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/467_0_0/467_0_0_t1+_thick_ax_VS1_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/467_0_0/467_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/467_0_0/467_0_0_t1+_thick_ax_VS1_uvauser1_coregistered.nii.gz)

 43%|████▎     | 764/1793 [05:42<06:23,  2.68it/s]

Original image path: ./raw_studies/t1+_thick_cor/467_0_0/467_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/467_0_0/467_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/467_0_0/467_0_0_t1+_thick_cor_VS2_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/467_0_0/467_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/467_0_0/467_0_0_t1+_thick_cor_VS2_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/467_0_0/467_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/467_0_0/467_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/467_0_0/467_0_0_t2_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/467_0_0/467_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/467_0_0/467_0_0_t2_thin_VS_uvauser1_coregistered.nii.gz)

 43%|████▎     | 765/1793 [05:43<07:14,  2.36it/s]

Original image path: ./raw_studies/t1+_thin/467_1_412/467_1_412_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/467_1_412/467_1_412_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/467_1_412/467_1_412_t1+_thin_image_coregistered.nii.gz, nan)

 43%|████▎     | 766/1793 [05:45<14:54,  1.15it/s]

Original image path: ./raw_studies/t2_thin/467_1_412/467_1_412_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/467_1_412/467_1_412_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/467_1_412/467_1_412_t2_thin_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/467_1_412/467_1_412_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/467_1_412/467_1_412_t2_thin_LVS _uvauser2_coregistered.nii.gz)

 43%|████▎     | 767/1793 [05:46<17:09,  1.00s/it]

Original image path: ./raw_studies/t1+_thin/467_2_559/467_2_559_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/467_2_559/467_2_559_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/467_2_559/467_2_559_t1+_thin_Manual_0_uvauser11.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/467_2_559/467_2_559_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/467_2_559/467_2_559_t1+_thin_Manual_0_uvauser11_coregistered.nii.gz)

 43%|████▎     | 768/1793 [05:48<22:14,  1.30s/it]

Original image path: ./raw_studies/t2_thin/467_2_559/467_2_559_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/467_2_559/467_2_559_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/467_2_559/467_2_559_t2_thin_image_coregistered.nii.gz, nan)

 43%|████▎     | 769/1793 [05:49<20:31,  1.20s/it]

Original image path: ./raw_studies/t1+_thick_cor/472_0_0/472_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/472_0_0/472_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/472_0_0/472_0_0_t1+_thick_cor_image_coregistered.nii.gz, nan)

 43%|████▎     | 771/1793 [05:50<11:44,  1.45it/s]

Original image path: ./raw_studies/t1+_thick_ax/472_0_0/472_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/472_0_0/472_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/472_0_0/472_0_0_t1+_thick_ax_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t2_thick/472_0_0/472_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/472_0_0/472_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 43%|████▎     | 772/1793 [05:50<09:04,  1.88it/s]

Original image path: ./raw_studies/t2_thin/472_0_0/472_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/472_0_0/472_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/472_0_0/472_0_0_t2_thin_T2Final_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/472_0_0/472_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/472_0_0/472_0_0_t2_thin_T2Final_VS_uvauser5_coregistered.nii.gz)

 43%|████▎     | 774/1793 [05:51<08:03,  2.11it/s]

Original image path: ./raw_studies/t1+_thick_ax/472_0_0/472_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/472_0_0/472_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/472_0_0/472_0_0_t1+_thick_ax_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t2_thin/472_1_64/472_1_64_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/472_1_64/472_1_64_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/472_1_64/472_1_64_t2_thin_T2Final_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/472_1_64/472_1_64_t2_thin_image_coregistered.nii.gz, nan)

 43%|████▎     | 775/1793 [05:52<10:36,  1.60it/s]

Original image path: ./raw_studies/t1+_thin/472_1_64/472_1_64_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/472_1_64/472_1_64_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/472_1_64/472_1_64_t1+_thin_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/472_1_64/472_1_64_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/472_1_64/472_1_64_t1+_thin_RVS _uvauser2_coregistered.nii.gz)

 43%|████▎     | 776/1793 [05:53<14:16,  1.19it/s]

Original image path: ./raw_studies/t1+_thick_cor/472_1_64/472_1_64_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/472_1_64/472_1_64_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/472_1_64/472_1_64_t1+_thick_cor_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/472_1_64/472_1_64_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/472_1_64/472_1_64_t1+_thick_cor_RVS _uvauser2_coregistered.nii.gz)

 43%|████▎     | 777/1793 [05:53<11:45,  1.44it/s]

Original image path: ./raw_studies/t1+_thick_ax/473_0_0/473_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/473_0_0/473_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/473_0_0/473_0_0_t1+_thick_ax_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/473_0_0/473_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/473_0_0/473_0_0_t1+_thick_ax_VS_uvauser5_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thick/473_0_0/473_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/473_0_0/473_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 43%|████▎     | 779/1793 [05:54<07:19,  2.31it/s]

Original image path: ./raw_studies/t2_thin/473_0_0/473_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/473_0_0/473_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/473_0_0/473_0_0_t2_thin_T2Final_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/473_0_0/473_0_0_t2_thin_image_coregistered.nii.gz, nan)

 44%|████▎     | 780/1793 [05:55<11:37,  1.45it/s]

Original image path: ./raw_studies/t1+_thick_cor/473_0_0/473_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/473_0_0/473_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/473_0_0/473_0_0_t1+_thick_cor_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/473_0_0/473_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/473_0_0/473_0_0_t1+_thick_cor_VS_uvauser5_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/473_1_64/473_1_64_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/473_1_64/473_1_64_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/473_1_64/473_1_64_t2_thin_image_coregistered.nii.gz, nan)

 44%|████▎     | 782/1793 [05:55<08:06,  2.08it/s]

Original image path: ./raw_studies/t1+_thin/473_1_64/473_1_64_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/473_1_64/473_1_64_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/473_1_64/473_1_64_t1+_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/473_1_64/473_1_64_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/473_1_64/473_1_64_t1+_thin_VS_uvauser1_coregistered.nii.gz)

 44%|████▎     | 784/1793 [05:57<09:05,  1.85it/s]

Original image path: ./raw_studies/t2_thick/474_0_0/474_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/474_0_0/474_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thick_cor/474_0_0/474_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/474_0_0/474_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/474_0_0/474_0_0_t1+_thick_cor_manual_uvauser12_uvauser12.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/474_0_0/474_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/474_0_0/474_0_0_t1+_thick_cor_manual_uvauser12_uvauser12_coregistered.nii.gz)

 44%|████▍     | 786/1793 [05:57<06:54,  2.43it/s]

Original image path: ./raw_studies/t1+_thick_ax/474_0_0/474_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/474_0_0/474_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/474_0_0/474_0_0_t1+_thick_ax_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t2_thin/474_0_0/474_0_0_t2_thin_image-rotated.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/474_0_0/474_0_0_t2_thin_image-rotated_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/474_0_0/474_0_0_t2_thin_image-rotated_coregistered.nii.gz, nan)

 44%|████▍     | 788/1793 [05:58<05:10,  3.23it/s]

Original image path: ./raw_studies/t2_thick/474_0_0/474_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/474_0_0/474_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thick_ax/474_1_128/474_1_128_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/474_1_128/474_1_128_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/474_1_128/474_1_128_t1+_thick_ax_VST1AX_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/474_1_128/474_1_128_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/474_1_128/474_1_128_t1+_thick_ax_VST1AX_uvauser6_coregistered.nii.gz)

 44%|████▍     | 789/1793 [05:58<05:47,  2.89it/s]

Original image path: ./raw_studies/t2_thin/474_1_128/474_1_128_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/474_1_128/474_1_128_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/474_1_128/474_1_128_t2_thin_VST2_uvauser6-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/474_1_128/474_1_128_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/474_1_128/474_1_128_t2_thin_VST2_uvauser6-copy_coregistered.nii.gz)

 44%|████▍     | 791/1793 [06:00<07:48,  2.14it/s]

Original image path: ./raw_studies/t1+_thick_cor/474_1_128/474_1_128_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/474_1_128/474_1_128_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/474_1_128/474_1_128_t1+_thick_cor_VST1COR_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/474_1_128/474_1_128_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/474_1_128/474_1_128_t1+_thick_cor_VST1COR_uvauser6_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/478_0_0/478_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/478_0_0/478_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/478_0_0/478_0_0_t1+_thick_cor_VS2_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/478_0_0/478_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/478_0_0/478_0_0_t1+_thick_cor_VS2_uvauser1_coregistered.nii.gz)

 44%|████▍     | 793/1793 [06:00<05:16,  3.16it/s]

Original image path: ./raw_studies/t1+_thick_ax/478_0_0/478_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/478_0_0/478_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/478_0_0/478_0_0_t1+_thick_ax_VS1_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/478_0_0/478_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/478_0_0/478_0_0_t1+_thick_ax_VS1_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/478_0_0/478_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/478_0_0/478_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/478_0_0/478_0_0_t2_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/478_0_0/478_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/478_0_0/478_0_0_t2_thin_VS_uvauser1_coregistered.nii.gz)

 44%|████▍     | 794/1793 [06:01<08:42,  1.91it/s]

Original image path: ./raw_studies/t2_thin/478_1_378/478_1_378_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/478_1_378/478_1_378_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/478_1_378/478_1_378_t2_thin_image_coregistered.nii.gz, nan)

 44%|████▍     | 796/1793 [06:02<08:29,  1.96it/s]

Original image path: ./raw_studies/t1+_thick_ax/478_1_378/478_1_378_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/478_1_378/478_1_378_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/478_1_378/478_1_378_t1+_thick_ax_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/478_1_378/478_1_378_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/478_1_378/478_1_378_t1+_thick_ax_AS_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/478_1_378/478_1_378_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/478_1_378/478_1_378_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/478_1_378/478_1_378_t1+_thick_cor_AS1_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/478_1_378/478_1_378_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/478_1_378/478_1_378_t1+_thick_cor_AS1_uvauser4_coregistered.nii.gz)

 44%|████▍     | 797/1793 [06:02<06:41,  2.48it/s]

Original image path: ./raw_studies/t2_thin/478_2_486/478_2_486_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/478_2_486/478_2_486_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/478_2_486/478_2_486_t2_thin_VS1_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/478_2_486/478_2_486_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/478_2_486/478_2_486_t2_thin_VS1_uvauser1_coregistered.nii.gz)

 45%|████▍     | 798/1793 [06:03<09:14,  1.80it/s]

Original image path: ./raw_studies/t1+_thin/478_2_486/478_2_486_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/478_2_486/478_2_486_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/478_2_486/478_2_486_t1+_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/478_2_486/478_2_486_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/478_2_486/478_2_486_t1+_thin_VS_uvauser1_coregistered.nii.gz)

 45%|████▍     | 799/1793 [06:05<16:11,  1.02it/s]

Original image path: ./raw_studies/t1+_thick_ax/483_0_0/483_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/483_0_0/483_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/483_0_0/483_0_0_t1+_thick_ax_Manual_0_uvauser11.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/483_0_0/483_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/483_0_0/483_0_0_t1+_thick_ax_Manual_0_uvauser11_coregistered.nii.gz)

 45%|████▍     | 800/1793 [06:06<14:41,  1.13it/s]

Original image path: ./raw_studies/t2_thin/483_0_0/483_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/483_0_0/483_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/483_0_0/483_0_0_t2_thin_image_coregistered.nii.gz, nan)

 45%|████▍     | 801/1793 [06:08<18:48,  1.14s/it]

Original image path: ./raw_studies/t1+_thick_cor/483_0_0/483_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/483_0_0/483_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/483_0_0/483_0_0_t1+_thick_cor_image_coregistered.nii.gz, nan)

 45%|████▍     | 803/1793 [06:08<10:56,  1.51it/s]

Original image path: ./raw_studies/t1+_thick_ax/483_1_455/483_1_455_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/483_1_455/483_1_455_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/483_1_455/483_1_455_t1+_thick_ax_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/483_1_455/483_1_455_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/483_1_455/483_1_455_t1+_thick_ax_RVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/483_1_455/483_1_455_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/483_1_455/483_1_455_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/483_1_455/483_1_455_t1+_thick_cor_VST1COR_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/483_1_455/483_1_455_t1+_thick_cor_image_coregistered.nii.gz, nan)

 45%|████▍     | 805/1793 [06:09<08:22,  1.97it/s]

Original image path: ./raw_studies/t2_thick/483_1_455/483_1_455_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/483_1_455/483_1_455_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/483_1_455/483_1_455_t2_thick_RVS _uvauser2.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thick_ax/483_2_812/483_2_812_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/483_2_812/483_2_812_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/483_2_812/483_2_812_t1+_thick_ax_image_coregistered.nii.gz, nan)

 45%|████▍     | 806/1793 [06:09<06:51,  2.40it/s]

Original image path: ./raw_studies/t2_thin/483_2_812/483_2_812_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/483_2_812/483_2_812_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/483_2_812/483_2_812_t2_thin_image_coregistered.nii.gz, nan)

 45%|████▌     | 808/1793 [06:10<08:10,  2.01it/s]

Original image path: ./raw_studies/t2_thick/483_2_812/483_2_812_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/483_2_812/483_2_812_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

Original image path: ./raw_studies/t2_thin/483_2_812/483_2_812_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/483_2_812/483_2_812_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/483_2_812/483_2_812_t2_thin_image_coregistered.nii.gz, nan)

 45%|████▌     | 810/1793 [06:12<08:45,  1.87it/s]

Original image path: ./raw_studies/t1+_thick_cor/483_2_812/483_2_812_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/483_2_812/483_2_812_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/483_2_812/483_2_812_t1+_thick_cor_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t2_thin/483_2_812/483_2_812_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/483_2_812/483_2_812_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/483_2_812/483_2_812_t2_thin_image_coregistered.nii.gz, nan)

 45%|████▌     | 812/1793 [06:13<09:12,  1.78it/s]

Original image path: ./raw_studies/t2_thick/483_3_1995/483_3_1995_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/483_3_1995/483_3_1995_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thick_cor/483_3_1995/483_3_1995_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/483_3_1995/483_3_1995_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/483_3_1995/483_3_1995_t1+_thick_cor_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thin/483_3_1995/483_3_1995_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/483_3_1995/483_3_1995_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/483_3_1995/483_3_1995_t1+_thin_image_coregistered.nii.gz, nan)

 45%|████▌     | 814/1793 [06:14<09:35,  1.70it/s]

Original image path: ./raw_studies/t1+_thin/483_3_1995/483_3_1995_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/483_3_1995/483_3_1995_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/483_3_1995/483_3_1995_t1+_thin_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/483_3_1995/483_3_1995_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/483_3_1995/483_3_1995_t1+_thin_VS_uvauser5_coregistered.nii.gz)

 45%|████▌     | 815/1793 [06:16<13:17,  1.23it/s]

Original image path: ./raw_studies/t1+_thin/483_3_1995/483_3_1995_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/483_3_1995/483_3_1995_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/483_3_1995/483_3_1995_t1+_thin_image_coregistered.nii.gz, nan)

 46%|████▌     | 816/1793 [06:17<14:40,  1.11it/s]

Original image path: ./raw_studies/t1+_thick_ax/483_3_1995/483_3_1995_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/483_3_1995/483_3_1995_t1+_thick_ax_image_coregistered.nii.gz

 46%|████▌     | 817/1793 [06:17<13:17,  1.22it/s]

  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/483_3_1995/483_3_1995_t1+_thick_ax_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t2_thin/483_3_1995/483_3_1995_t2_thin_image_uint8.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/483_3_1995/483_3_1995_t2_thin_image_uint8_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 46%|████▌     | 818/1793 [06:20<19:02,  1.17s/it]

Original image path: ./raw_studies/t2_thin/485_0_0/485_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/485_0_0/485_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/485_0_0/485_0_0_t2_thin_image_coregistered.nii.gz, nan)

 46%|████▌     | 820/1793 [06:21<14:18,  1.13it/s]

Original image path: ./raw_studies/t1+_thick_cor/485_0_0/485_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/485_0_0/485_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/485_0_0/485_0_0_t1+_thick_cor_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thick_ax/485_0_0/485_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/485_0_0/485_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/485_0_0/485_0_0_t1+_thick_ax_image_coregistered.nii.gz, nan)

 46%|████▌     | 821/1793 [06:21<10:59,  1.47it/s]

Original image path: ./raw_studies/t2_thin/485_1_343/485_1_343_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/485_1_343/485_1_343_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/485_1_343/485_1_343_t2_thin_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/485_1_343/485_1_343_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/485_1_343/485_1_343_t2_thin_LVS _uvauser2_coregistered.nii.gz)

 46%|████▌     | 824/1793 [06:22<07:27,  2.17it/s]

Original image path: ./raw_studies/t1+_thick_ax/485_1_343/485_1_343_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/485_1_343/485_1_343_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/485_1_343/485_1_343_t1+_thick_ax_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/485_1_343/485_1_343_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/485_1_343/485_1_343_t1+_thick_ax_LVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/485_1_343/485_1_343_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/485_1_343/485_1_343_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/485_1_343/485_1_343_t1+_thick_cor_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/485_1_343/485_1_343_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/485_1_343/485_1_343_t1+_thick_cor_LVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/485_2_734/485_2_734_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/485_2_734/485_2_734_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/485_2_734/485_2_734_t1+_thick_cor_VS_uvauser1-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/485_2_734/485_2_734_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/485_2_734/485_2_734_t1+_thick_cor_VS_uvauser1-copy_coregistered.nii.gz)

 46%|████▌     | 826/1793 [06:22<05:03,  3.19it/s]

Original image path: ./raw_studies/t1+_thick_ax/485_2_734/485_2_734_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/485_2_734/485_2_734_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/485_2_734/485_2_734_t1+_thick_ax_VS_uvauser1-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/485_2_734/485_2_734_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/485_2_734/485_2_734_t1+_thick_ax_VS_uvauser1-copy_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/485_2_734/485_2_734_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/485_2_734/485_2_734_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/485_2_734/485_2_734_t2_thin_AX_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/485_2_734/485_2_734_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/485_2_734/485_2_734_t2_thin_AX_VS_uvauser1_coregistered.nii.gz)

 46%|████▌     | 827/1793 [06:23<07:41,  2.09it/s]

Original image path: ./raw_studies/t1+_thick_ax/485_3_1058/485_3_1058_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/485_3_1058/485_3_1058_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/485_3_1058/485_3_1058_t1+_thick_ax_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/485_3_1058/485_3_1058_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/485_3_1058/485_3_1058_t1+_thick_ax_AS_uvauser4_coregistered.nii.gz)

 46%|████▌     | 829/1793 [06:24<06:04,  2.65it/s]

Original image path: ./raw_studies/t1+_thick_cor/485_3_1058/485_3_1058_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/485_3_1058/485_3_1058_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/485_3_1058/485_3_1058_t1+_thick_cor_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/485_3_1058/485_3_1058_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/485_3_1058/485_3_1058_t1+_thick_cor_AS_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/485_3_1058/485_3_1058_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/485_3_1058/485_3_1058_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/485_3_1058/485_3_1058_t2_thin_AX_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/485_3_1058/485_3_1058_t2_thin_image_coregistered.nii.gz, nan)

 46%|████▋     | 830/1793 [06:25<10:29,  1.53it/s]

Original image path: ./raw_studies/t1+_thick_ax/485_4_1302/485_4_1302_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/485_4_1302/485_4_1302_t1+_thick_ax_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t1+_thick_ax/485_4_1302/485_4_1302_t1+_thick_ax_AS_uvauser4.nii.gz
Returning: (nan, nan)

 46%|████▋     | 832/1793 [06:26<06:57,  2.30it/s]

Original image path: ./raw_studies/t1+_thick_cor/485_4_1302/485_4_1302_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/485_4_1302/485_4_1302_t1+_thick_cor_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t1+_thick_cor/485_4_1302/485_4_1302_t1+_thick_cor_AS_uvauser4.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t2_thin/485_4_1302/485_4_1302_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/485_4_1302/485_4_1302_t2_thin_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thin/485_4_1302/485_4_1302_t2_thin_AS_uvauser4.nii.gz
Returning: (nan, nan)

 46%|████▋     | 833/1793 [06:27<09:56,  1.61it/s]

Original image path: ./raw_studies/t1+_thin/486_2_631/486_2_631_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/486_2_631/486_2_631_t1+_thin_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t1+_thin/486_2_631/486_2_631_t1+_thin_manual_0_uvauser8.nii.gz
Returning: (nan, nan)

 47%|████▋     | 834/1793 [06:29<14:38,  1.09it/s]

Original image path: ./raw_studies/t1+_thick_ax/487_0_0/487_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/487_0_0/487_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/487_0_0/487_0_0_t1+_thick_ax_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/487_0_0/487_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/487_0_0/487_0_0_t1+_thick_ax_VS_uvauser1_coregistered.nii.gz)

 47%|████▋     | 836/1793 [06:29<08:59,  1.77it/s]

Original image path: ./raw_studies/t1+_thick_cor/487_0_0/487_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/487_0_0/487_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/487_0_0/487_0_0_t1+_thick_cor_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/487_0_0/487_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/487_0_0/487_0_0_t1+_thick_cor_VS_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/487_0_0/487_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/487_0_0/487_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/487_0_0/487_0_0_t2_thin_AX_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/487_0_0/487_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/487_0_0/487_0_0_t2_thin_AX_VS_uvauser1_coregistered.nii.gz)

 47%|████▋     | 837/1793 [06:30<11:18,  1.41it/s]

Original image path: ./raw_studies/t2_thin/487_1_427/487_1_427_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/487_1_427/487_1_427_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/487_1_427/487_1_427_t2_thin_AX_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/487_1_427/487_1_427_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/487_1_427/487_1_427_t2_thin_AX_tumorcore _uvauser3_coregistered.nii.gz)

 47%|████▋     | 838/1793 [06:31<13:35,  1.17it/s]

Original image path: ./raw_studies/t1+_thick_cor/487_1_427/487_1_427_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/487_1_427/487_1_427_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/487_1_427/487_1_427_t1+_thick_cor_VST1COR_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/487_1_427/487_1_427_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/487_1_427/487_1_427_t1+_thick_cor_VST1COR_uvauser6_coregistered.nii.gz)

 47%|████▋     | 840/1793 [06:32<08:02,  1.98it/s]

Original image path: ./raw_studies/t1+_thick_ax/487_1_427/487_1_427_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/487_1_427/487_1_427_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/487_1_427/487_1_427_t1+_thick_ax_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/487_1_427/487_1_427_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/487_1_427/487_1_427_t1+_thick_ax_tumorcore _uvauser3_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thin/492_0_0/492_0_0_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/492_0_0/492_0_0_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/492_0_0/492_0_0_t1+_thin_image_coregistered.nii.gz, nan)

 47%|████▋     | 842/1793 [06:33<08:57,  1.77it/s]

Original image path: ./raw_studies/t1+_thick_ax/492_0_0/492_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/492_0_0/492_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/492_0_0/492_0_0_t1+_thick_ax_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thin/492_0_0/492_0_0_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/492_0_0/492_0_0_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/492_0_0/492_0_0_t1+_thin_manual_10_uvauser10.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/492_0_0/492_0_0_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/492_0_0/492_0_0_t1+_thin_manual_10_uvauser10_coregistered.nii.gz)

 47%|████▋     | 844/1793 [06:34<09:23,  1.69it/s]

Original image path: ./raw_studies/t2_thick/492_0_0/492_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/492_0_0/492_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/492_0_0/492_0_0_t2_thick_manual_10_uvauser10.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thin/492_0_0/492_0_0_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/492_0_0/492_0_0_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/492_0_0/492_0_0_t1+_thin_image_coregistered.nii.gz, nan)

 47%|████▋     | 845/1793 [06:36<12:28,  1.27it/s]

Original image path: ./raw_studies/t1+_thin/492_1_391/492_1_391_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/492_1_391/492_1_391_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/492_1_391/492_1_391_t1+_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/492_1_391/492_1_391_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/492_1_391/492_1_391_t1+_thin_VS_uvauser1_coregistered.nii.gz)

 47%|████▋     | 846/1793 [06:36<10:53,  1.45it/s]

Original image path: ./raw_studies/t2_thin/492_1_391/492_1_391_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/492_1_391/492_1_391_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/492_1_391/492_1_391_t2_thin_image_coregistered.nii.gz, nan)

 47%|████▋     | 847/1793 [06:37<12:13,  1.29it/s]

Original image path: ./raw_studies/t2_thin/492_2_757/492_2_757_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/492_2_757/492_2_757_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/492_2_757/492_2_757_t2_thin_image_coregistered.nii.gz, nan)

 47%|████▋     | 848/1793 [06:38<14:12,  1.11it/s]

Original image path: ./raw_studies/t1+_thick_ax/492_2_757/492_2_757_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/492_2_757/492_2_757_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/492_2_757/492_2_757_t1+_thick_ax_image_coregistered.nii.gz, nan)

 47%|████▋     | 850/1793 [06:40<12:29,  1.26it/s]

Original image path: ./raw_studies/t1+_thick_cor/492_2_757/492_2_757_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/492_2_757/492_2_757_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/492_2_757/492_2_757_t1+_thick_cor_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thin/492_2_757/492_2_757_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/492_2_757/492_2_757_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/492_2_757/492_2_757_t1+_thin_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/492_2_757/492_2_757_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/492_2_757/492_2_757_t1+_thin_VS_uvauser5_coregistered.nii.gz)

 47%|████▋     | 851/1793 [06:40<10:55,  1.44it/s]

Original image path: ./raw_studies/t2_thin/492_2_757/492_2_757_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/492_2_757/492_2_757_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/492_2_757/492_2_757_t2_thin_image_coregistered.nii.gz, nan)

 48%|████▊     | 852/1793 [06:41<12:12,  1.28it/s]

Original image path: ./raw_studies/t1+_thin/493_0_0/493_0_0_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/493_0_0/493_0_0_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/493_0_0/493_0_0_t1+_thin_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/493_0_0/493_0_0_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/493_0_0/493_0_0_t1+_thin_tumorcore _uvauser3_coregistered.nii.gz)

 48%|████▊     | 854/1793 [06:42<08:36,  1.82it/s]

Original image path: ./raw_studies/t2_thick/493_0_0/493_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/493_0_0/493_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

Original image path: ./raw_studies/t2_thin/493_1_262/493_1_262_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/493_1_262/493_1_262_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/493_1_262/493_1_262_t2_thin_image_coregistered.nii.gz, nan)

 48%|████▊     | 855/1793 [06:44<13:30,  1.16it/s]

Original image path: ./raw_studies/t1+_thin/493_1_262/493_1_262_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/493_1_262/493_1_262_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/493_1_262/493_1_262_t1+_thin_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/493_1_262/493_1_262_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/493_1_262/493_1_262_t1+_thin_tumorcore _uvauser3_coregistered.nii.gz)

 48%|████▊     | 856/1793 [06:47<23:53,  1.53s/it]

Original image path: ./raw_studies/t1+_thin/493_2_537/493_2_537_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/493_2_537/493_2_537_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/493_2_537/493_2_537_t1+_thin_tumocore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/493_2_537/493_2_537_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/493_2_537/493_2_537_t1+_thin_tumocore _uvauser3_coregistered.nii.gz)

 48%|████▊     | 857/1793 [06:47<18:46,  1.20s/it]

Original image path: ./raw_studies/t2_thin/493_2_537/493_2_537_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/493_2_537/493_2_537_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/493_2_537/493_2_537_t2_thin_image_coregistered.nii.gz, nan)

 48%|████▊     | 858/1793 [06:48<18:16,  1.17s/it]

Original image path: ./raw_studies/t1+_thin/493_2_537/493_2_537_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/493_2_537/493_2_537_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/493_2_537/493_2_537_t1+_thin_image_coregistered.nii.gz, nan)

 48%|████▊     | 859/1793 [06:49<15:02,  1.03it/s]

Original image path: ./raw_studies/t1+_thick_cor/495_0_0/495_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/495_0_0/495_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/495_0_0/495_0_0_t1+_thick_cor_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/495_0_0/495_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/495_0_0/495_0_0_t1+_thick_cor_AS_uvauser4_coregistered.nii.gz)

 48%|████▊     | 860/1793 [06:49<13:40,  1.14it/s]

Original image path: ./raw_studies/t1+_thick_ax/495_0_0/495_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/495_0_0/495_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/495_0_0/495_0_0_t1+_thick_ax_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/495_0_0/495_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/495_0_0/495_0_0_t1+_thick_ax_AS_uvauser4_coregistered.nii.gz)

 48%|████▊     | 861/1793 [06:50<10:35,  1.47it/s]

Original image path: ./raw_studies/t2_thin/495_0_0/495_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/495_0_0/495_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/495_0_0/495_0_0_t2_thin_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/495_0_0/495_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/495_0_0/495_0_0_t2_thin_AS_uvauser4_coregistered.nii.gz)

 48%|████▊     | 863/1793 [06:50<07:52,  1.97it/s]

Original image path: ./raw_studies/t2_thick/495_1_35/495_1_35_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/495_1_35/495_1_35_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thin/495_1_35/495_1_35_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/495_1_35/495_1_35_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/495_1_35/495_1_35_t1+_thin_image_coregistered.nii.gz, nan)

 48%|████▊     | 865/1793 [06:52<07:59,  1.94it/s]

Original image path: ./raw_studies/t1+_thick_ax/495_1_35/495_1_35_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/495_1_35/495_1_35_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/495_1_35/495_1_35_t1+_thick_ax_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thin/495_1_35/495_1_35_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/495_1_35/495_1_35_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/495_1_35/495_1_35_t1+_thin_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/495_1_35/495_1_35_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/495_1_35/495_1_35_t1+_thin_VS_uvauser5_coregistered.nii.gz)

 48%|████▊     | 866/1793 [06:53<11:20,  1.36it/s]

Original image path: ./raw_studies/t2_thin/495_1_35/495_1_35_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/495_1_35/495_1_35_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/495_1_35/495_1_35_t2_thin_image_coregistered.nii.gz, nan)

 48%|████▊     | 867/1793 [06:53<09:27,  1.63it/s]

Original image path: ./raw_studies/t1+_thin/495_1_35/495_1_35_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/495_1_35/495_1_35_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/495_1_35/495_1_35_t1+_thin_image_coregistered.nii.gz, nan)

 48%|████▊     | 869/1793 [06:55<09:04,  1.70it/s]

Original image path: ./raw_studies/t1+_thick_cor/495_1_35/495_1_35_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/495_1_35/495_1_35_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/495_1_35/495_1_35_t1+_thick_cor_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t2_thick/50_0_0/50_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/50_0_0/50_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/50_0_0/50_0_0_t2_thick_T2_thick_user1_uvauser1.nii.gz
Returning: (nan, nan)

 49%|████▊     | 871/1793 [06:56<08:08,  1.89it/s]

Original image path: ./raw_studies/t1+_thick_cor/50_2_108/50_2_108_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/50_2_108/50_2_108_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/50_2_108/50_2_108_t1+_thick_cor_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/50_2_108/50_2_108_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/50_2_108/50_2_108_t1+_thick_cor_AS_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/50_2_108/50_2_108_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/50_2_108/50_2_108_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/50_2_108/50_2_108_t2_thin_AS2_uvauser4-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/50_2_108/50_2_108_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/50_2_108/50_2_108_t2_thin_AS2_uvauser4-copy_coregistered.nii.gz)

 49%|████▊     | 873/1793 [06:56<06:17,  2.43it/s]

Original image path: ./raw_studies/t1+_thick_ax/50_2_108/50_2_108_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/50_2_108/50_2_108_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/50_2_108/50_2_108_t1+_thick_ax_AS1_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/50_2_108/50_2_108_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/50_2_108/50_2_108_t1+_thick_ax_AS1_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thick/50_2_108/50_2_108_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/50_2_108/50_2_108_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 49%|████▉     | 875/1793 [06:57<05:11,  2.95it/s]

Original image path: ./raw_studies/t2_thin/50_2_108/50_2_108_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/50_2_108/50_2_108_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/50_2_108/50_2_108_t2_thin_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t2_thick/50_2_108/50_2_108_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/50_2_108/50_2_108_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 49%|████▉     | 877/1793 [06:57<03:57,  3.85it/s]

Original image path: ./raw_studies/t1+_thick_cor/50_3_283/50_3_283_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/50_3_283/50_3_283_t1+_thick_cor_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t1+_thick_cor/50_3_283/50_3_283_t1+_thick_cor_AS_uvauser4.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t2_thin/50_3_283/50_3_283_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/50_3_283/50_3_283_t2_thin_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thin/50_3_283/50_3_283_t2_thin_AS2_uvauser4-copy.nii.gz
Returning: (nan, nan)

 49%|████▉     | 878/1793 [06:58<06:53,  2.21it/s]

Original image path: ./raw_studies/t2_thin/50_3_283/50_3_283_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/50_3_283/50_3_283_t2_thin_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 49%|████▉     | 880/1793 [06:59<06:48,  2.23it/s]

Original image path: ./raw_studies/t2_thick/50_3_283/50_3_283_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/50_3_283/50_3_283_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

Original image path: ./raw_studies/t2_thin/50_3_283/50_3_283_t2_thin_image_uint8.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/50_3_283/50_3_283_t2_thin_image_uint8_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 49%|████▉     | 882/1793 [07:01<08:25,  1.80it/s]

Original image path: ./raw_studies/t1+_thick_ax/50_3_283/50_3_283_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/50_3_283/50_3_283_t1+_thick_ax_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t1+_thick_ax/50_3_283/50_3_283_t1+_thick_ax_AS1_uvauser4.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t2_thick/50_3_283/50_3_283_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/50_3_283/50_3_283_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 49%|████▉     | 883/1793 [07:01<06:51,  2.21it/s]

Original image path: ./raw_studies/t2_thick/500_0_0/500_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/500_0_0/500_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/500_0_0/500_0_0_t2_thick_RVS _uvauser2.nii.gz
Returning: (nan, nan)

 49%|████▉     | 886/1793 [07:01<04:08,  3.65it/s]

Original image path: ./raw_studies/t1+_thick_ax/500_0_0/500_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/500_0_0/500_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/500_0_0/500_0_0_t1+_thick_ax_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/500_0_0/500_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/500_0_0/500_0_0_t1+_thick_ax_RVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/500_0_0/500_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/500_0_0/500_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/500_0_0/500_0_0_t1+_thick_cor_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t2_thin/500_1_346/500_1_346_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/500_1_346/500_1_346_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/500_1_346/500_1_346_t2_thin_AS_uvauser4-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/500_1_346/500_1_346_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/500_1_346/500_1_346_t2_thin_AS_uvauser4-copy_coregistered.nii.gz)

 50%|████▉     | 888/1793 [07:03<05:51,  2.57it/s]

Original image path: ./raw_studies/t1+_thick_cor/500_1_346/500_1_346_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/500_1_346/500_1_346_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/500_1_346/500_1_346_t1+_thick_cor_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/500_1_346/500_1_346_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/500_1_346/500_1_346_t1+_thick_cor_AS_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/500_1_346/500_1_346_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/500_1_346/500_1_346_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/500_1_346/500_1_346_t1+_thick_ax_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/500_1_346/500_1_346_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/500_1_346/500_1_346_t1+_thick_ax_AS_uvauser4_coregistered.nii.gz)

 50%|████▉     | 890/1793 [07:03<04:22,  3.44it/s]

Original image path: ./raw_studies/t1+_thick_ax/500_2_724/500_2_724_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/500_2_724/500_2_724_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/500_2_724/500_2_724_t1+_thick_ax_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/500_2_724/500_2_724_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/500_2_724/500_2_724_t1+_thick_ax_AS_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/500_2_724/500_2_724_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/500_2_724/500_2_724_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/500_2_724/500_2_724_t2_thin_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/500_2_724/500_2_724_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/500_2_724/500_2_724_t2_thin_AS_uvauser4_coregistered.nii.gz)

 50%|████▉     | 891/1793 [07:03<04:35,  3.27it/s]

Original image path: ./raw_studies/t1+_thick_cor/500_2_724/500_2_724_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/500_2_724/500_2_724_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/500_2_724/500_2_724_t1+_thick_cor_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/500_2_724/500_2_724_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/500_2_724/500_2_724_t1+_thick_cor_AS_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thick/502_0_0/502_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/502_0_0/502_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 50%|████▉     | 893/1793 [07:04<04:02,  3.71it/s]

Original image path: ./raw_studies/t1+_thick_ax/502_0_0/502_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/502_0_0/502_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/502_0_0/502_0_0_t1+_thick_ax_image_coregistered.nii.gz, nan)

 50%|████▉     | 894/1793 [07:04<04:09,  3.61it/s]

Original image path: ./raw_studies/t1+_thick_ax/502_0_0/502_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/502_0_0/502_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/502_0_0/502_0_0_t1+_thick_ax_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/502_0_0/502_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/502_0_0/502_0_0_t1+_thick_ax_VS_uvauser5_coregistered.nii.gz)

 50%|████▉     | 896/1793 [07:05<03:52,  3.86it/s]

Original image path: ./raw_studies/t1+_thick_cor/502_0_0/502_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/502_0_0/502_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/502_0_0/502_0_0_t1+_thick_cor_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/502_0_0/502_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/502_0_0/502_0_0_t1+_thick_cor_VS_uvauser5_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/502_0_0/502_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/502_0_0/502_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/502_0_0/502_0_0_t2_thin_T2Final_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/502_0_0/502_0_0_t2_thin_image_coregistered.nii.gz, nan)

 50%|█████     | 897/1793 [07:07<13:35,  1.10it/s]

Original image path: ./raw_studies/t1+_thin/502_1_71/502_1_71_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/502_1_71/502_1_71_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/502_1_71/502_1_71_t1+_thin_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/502_1_71/502_1_71_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/502_1_71/502_1_71_t1+_thin_tumorcore _uvauser3_coregistered.nii.gz)

 50%|█████     | 899/1793 [07:09<11:26,  1.30it/s]

Original image path: ./raw_studies/t1+_thick_cor/502_1_71/502_1_71_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/502_1_71/502_1_71_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/502_1_71/502_1_71_t1+_thick_cor_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/502_1_71/502_1_71_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/502_1_71/502_1_71_t1+_thick_cor_RVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/502_1_71/502_1_71_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/502_1_71/502_1_71_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/502_1_71/502_1_71_t2_thin_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/502_1_71/502_1_71_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/502_1_71/502_1_71_t2_thin_RVS _uvauser2_coregistered.nii.gz)

 50%|█████     | 900/1793 [07:09<10:00,  1.49it/s]

Original image path: ./raw_studies/t1+_thick_ax/502_1_71/502_1_71_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/502_1_71/502_1_71_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/502_1_71/502_1_71_t1+_thick_ax_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/502_1_71/502_1_71_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/502_1_71/502_1_71_t1+_thick_ax_RVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thin/502_2_314/502_2_314_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/502_2_314/502_2_314_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/502_2_314/502_2_314_t1+_thin_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/502_2_314/502_2_314_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/502_2_314/502_2_314_t1+_thin_VS_uvauser5_coregistered.nii.gz)

 50%|█████     | 903/1793 [07:10<07:26,  1.99it/s]

Original image path: ./raw_studies/t1+_thick_ax/502_2_314/502_2_314_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/502_2_314/502_2_314_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/502_2_314/502_2_314_t1+_thick_ax_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t2_thin/502_2_314/502_2_314_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/502_2_314/502_2_314_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/502_2_314/502_2_314_t2_thin_image_coregistered.nii.gz, nan)

 50%|█████     | 905/1793 [07:12<07:35,  1.95it/s]

Original image path: ./raw_studies/t1+_thick_cor/502_2_314/502_2_314_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/502_2_314/502_2_314_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/502_2_314/502_2_314_t1+_thick_cor_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thin/502_2_314/502_2_314_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/502_2_314/502_2_314_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/502_2_314/502_2_314_t1+_thin_image_coregistered.nii.gz, nan)

 51%|█████     | 907/1793 [07:13<07:40,  1.92it/s]

Original image path: ./raw_studies/t2_thick/502_2_314/502_2_314_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/502_2_314/502_2_314_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thin/502_2_314/502_2_314_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/502_2_314/502_2_314_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/502_2_314/502_2_314_t1+_thin_image_coregistered.nii.gz, nan)

 51%|█████     | 908/1793 [07:14<09:24,  1.57it/s]

Original image path: ./raw_studies/t1+_thick_ax/505_0_0/505_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/505_0_0/505_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/505_0_0/505_0_0_t1+_thick_ax_image_coregistered.nii.gz, nan)

 51%|█████     | 909/1793 [07:14<07:55,  1.86it/s]

Original image path: ./raw_studies/t2_thin/505_0_0/505_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/505_0_0/505_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/505_0_0/505_0_0_t2_thin_image_coregistered.nii.gz, nan)

 51%|█████     | 910/1793 [07:14<07:01,  2.10it/s]

Original image path: ./raw_studies/t1+_thick_cor/505_0_0/505_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/505_0_0/505_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/505_0_0/505_0_0_t1+_thick_cor_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/505_0_0/505_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/505_0_0/505_0_0_t1+_thick_cor_tumorcore _uvauser3_coregistered.nii.gz)

 51%|█████     | 911/1793 [07:15<06:35,  2.23it/s]

Original image path: ./raw_studies/t1+_thick_ax/505_1_210/505_1_210_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/505_1_210/505_1_210_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/505_1_210/505_1_210_t1+_thick_ax_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/505_1_210/505_1_210_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/505_1_210/505_1_210_t1+_thick_ax_LVS _uvauser2_coregistered.nii.gz)

 51%|█████     | 912/1793 [07:15<06:22,  2.31it/s]

Original image path: ./raw_studies/t1+_thick_cor/505_1_210/505_1_210_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/505_1_210/505_1_210_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/505_1_210/505_1_210_t1+_thick_cor_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/505_1_210/505_1_210_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/505_1_210/505_1_210_t1+_thick_cor_LVS _uvauser2_coregistered.nii.gz)

 51%|█████     | 913/1793 [07:15<06:06,  2.40it/s]

Original image path: ./raw_studies/t2_thin/505_1_210/505_1_210_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/505_1_210/505_1_210_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/505_1_210/505_1_210_t2_thin_LVS _uvauser2-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/505_1_210/505_1_210_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/505_1_210/505_1_210_t2_thin_LVS _uvauser2-copy_coregistered.nii.gz)

 51%|█████     | 914/1793 [07:16<05:37,  2.60it/s]

Original image path: ./raw_studies/t1+_thin/505_2_342/505_2_342_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/505_2_342/505_2_342_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/505_2_342/505_2_342_t1+_thin_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/505_2_342/505_2_342_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/505_2_342/505_2_342_t1+_thin_AS_uvauser4_coregistered.nii.gz)

 51%|█████     | 915/1793 [07:17<09:40,  1.51it/s]

Original image path: ./raw_studies/t2_thin/505_2_342/505_2_342_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/505_2_342/505_2_342_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/505_2_342/505_2_342_t2_thin_AS1_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/505_2_342/505_2_342_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/505_2_342/505_2_342_t2_thin_AS1_uvauser4_coregistered.nii.gz)

 51%|█████     | 918/1793 [07:18<04:54,  2.97it/s]

Original image path: ./raw_studies/t1+_thick_cor/505_2_342/505_2_342_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/505_2_342/505_2_342_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/505_2_342/505_2_342_t1+_thick_cor_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thick_ax/505_2_342/505_2_342_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/505_2_342/505_2_342_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/505_2_342/505_2_342_t1+_thick_ax_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thin/508_0_0/508_0_0_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/508_0_0/508_0_0_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/508_0_0/508_0_0_t1+_thin_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/508_0_0/508_0_0_t1+_thin_image_coregistered.nii.gz, nan)

 51%|█████▏    | 919/1793 [07:18<06:58,  2.09it/s]

Original image path: ./raw_studies/t2_thin/508_0_0/508_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/508_0_0/508_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/508_0_0/508_0_0_t2_thin_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/508_0_0/508_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/508_0_0/508_0_0_t2_thin_RVS _uvauser2_coregistered.nii.gz)

 51%|█████▏    | 920/1793 [07:19<05:58,  2.44it/s]

Original image path: ./raw_studies/t1+_thick_cor/508_0_0/508_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/508_0_0/508_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/508_0_0/508_0_0_t1+_thick_cor_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/508_0_0/508_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/508_0_0/508_0_0_t1+_thick_cor_RVS _uvauser2_coregistered.nii.gz)

 51%|█████▏    | 921/1793 [07:19<05:46,  2.52it/s]

Original image path: ./raw_studies/t1+_thin/508_1_260/508_1_260_t1+_thin_image_uint8.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/508_1_260/508_1_260_t1+_thin_image_uint8_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 51%|█████▏    | 923/1793 [07:20<07:08,  2.03it/s]

Original image path: ./raw_studies/t1+_thick_cor/508_1_260/508_1_260_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/508_1_260/508_1_260_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/508_1_260/508_1_260_t1+_thick_cor_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/508_1_260/508_1_260_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/508_1_260/508_1_260_t1+_thick_cor_RVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thin/508_1_260/508_1_260_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/508_1_260/508_1_260_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/508_1_260/508_1_260_t1+_thin_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/508_1_260/508_1_260_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/508_1_260/508_1_260_t1+_thin_VS_uvauser5_coregistered.nii.gz)

 52%|█████▏    | 924/1793 [07:22<11:07,  1.30it/s]

Original image path: ./raw_studies/t2_thin/508_1_260/508_1_260_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/508_1_260/508_1_260_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/508_1_260/508_1_260_t2_thin_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/508_1_260/508_1_260_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/508_1_260/508_1_260_t2_thin_RVS _uvauser2_coregistered.nii.gz)

 52%|█████▏    | 925/1793 [07:22<09:11,  1.58it/s]

Original image path: ./raw_studies/t1+_thick_ax/508_1_260/508_1_260_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/508_1_260/508_1_260_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/508_1_260/508_1_260_t1+_thick_ax_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/508_1_260/508_1_260_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/508_1_260/508_1_260_t1+_thick_ax_RVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thick/508_1_260/508_1_260_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/508_1_260/508_1_260_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 52%|█████▏    | 927/1793 [07:22<06:03,  2.38it/s]

Original image path: ./raw_studies/t2_thin/514_0_0/514_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/514_0_0/514_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/514_0_0/514_0_0_t2_thin_VS_uvauser1-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/514_0_0/514_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/514_0_0/514_0_0_t2_thin_VS_uvauser1-copy_coregistered.nii.gz)

 52%|█████▏    | 929/1793 [07:24<06:21,  2.27it/s]

Original image path: ./raw_studies/t1+_thick_ax/514_0_0/514_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/514_0_0/514_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/514_0_0/514_0_0_t1+_thick_ax_VS1_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/514_0_0/514_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/514_0_0/514_0_0_t1+_thick_ax_VS1_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/514_0_0/514_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/514_0_0/514_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/514_0_0/514_0_0_t1+_thick_cor_VS2_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/514_0_0/514_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/514_0_0/514_0_0_t1+_thick_cor_VS2_uvauser1_coregistered.nii.gz)

 52%|█████▏    | 930/1793 [07:24<05:12,  2.76it/s]

Original image path: ./raw_studies/t1+_thick_cor/514_1_353/514_1_353_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/514_1_353/514_1_353_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/514_1_353/514_1_353_t1+_thick_cor_VS2_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/514_1_353/514_1_353_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/514_1_353/514_1_353_t1+_thick_cor_VS2_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/514_1_353/514_1_353_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/514_1_353/514_1_353_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/514_1_353/514_1_353_t2_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/514_1_353/514_1_353_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/514_1_353/514_1_353_t2_thin_VS_uvauser1_coregistered.nii.gz)

 52%|█████▏    | 932/1793 [07:25<06:24,  2.24it/s]

Original image path: ./raw_studies/t1+_thick_ax/514_1_353/514_1_353_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/514_1_353/514_1_353_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/514_1_353/514_1_353_t1+_thick_ax_VS1_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/514_1_353/514_1_353_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/514_1_353/514_1_353_t1+_thick_ax_VS1_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/514_2_629/514_2_629_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/514_2_629/514_2_629_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/514_2_629/514_2_629_t1+_thick_cor_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/514_2_629/514_2_629_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/514_2_629/514_2_629_t1+_thick_cor_AS_uvauser4_coregistered.nii.gz)

 52%|█████▏    | 935/1793 [07:25<04:04,  3.51it/s]

Original image path: ./raw_studies/t1+_thick_ax/514_2_629/514_2_629_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/514_2_629/514_2_629_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/514_2_629/514_2_629_t1+_thick_ax_AS1_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/514_2_629/514_2_629_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/514_2_629/514_2_629_t1+_thick_ax_AS1_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/514_2_629/514_2_629_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/514_2_629/514_2_629_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/514_2_629/514_2_629_t2_thin_VS1_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/514_2_629/514_2_629_t2_thin_image_coregistered.nii.gz, nan)

 52%|█████▏    | 937/1793 [07:27<06:17,  2.27it/s]

Original image path: ./raw_studies/t1+_thick_ax/514_3_902/514_3_902_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/514_3_902/514_3_902_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/514_3_902/514_3_902_t1+_thick_ax_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/514_3_902/514_3_902_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/514_3_902/514_3_902_t1+_thick_ax_AS_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/514_3_902/514_3_902_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/514_3_902/514_3_902_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/514_3_902/514_3_902_t1+_thick_cor_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/514_3_902/514_3_902_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/514_3_902/514_3_902_t1+_thick_cor_AS_uvauser4_coregistered.nii.gz)

 52%|█████▏    | 938/1793 [07:27<05:12,  2.73it/s]

Original image path: ./raw_studies/t2_thin/514_3_902/514_3_902_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/514_3_902/514_3_902_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/514_3_902/514_3_902_t2_thin_AX_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/514_3_902/514_3_902_t2_thin_image_coregistered.nii.gz, nan)

 52%|█████▏    | 939/1793 [07:29<10:47,  1.32it/s]

Original image path: ./raw_studies/t1+_thin/514_4_996/514_4_996_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/514_4_996/514_4_996_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/514_4_996/514_4_996_t1+_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/514_4_996/514_4_996_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/514_4_996/514_4_996_t1+_thin_VS_uvauser1_coregistered.nii.gz)

 52%|█████▏    | 940/1793 [07:30<12:39,  1.12it/s]

Original image path: ./raw_studies/t2_thin/514_4_996/514_4_996_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/514_4_996/514_4_996_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/514_4_996/514_4_996_t2_thin_image_coregistered.nii.gz, nan)

 52%|█████▏    | 941/1793 [07:30<10:57,  1.29it/s]

Original image path: ./raw_studies/t2_thin/515_0_0/515_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/515_0_0/515_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/515_0_0/515_0_0_t2_thin_T2Final_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/515_0_0/515_0_0_t2_thin_image_coregistered.nii.gz, nan)

 53%|█████▎    | 944/1793 [07:31<06:29,  2.18it/s]

Original image path: ./raw_studies/t1+_thick_ax/515_0_0/515_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/515_0_0/515_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/515_0_0/515_0_0_t1+_thick_ax_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/515_0_0/515_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/515_0_0/515_0_0_t1+_thick_ax_VS_uvauser5_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/515_0_0/515_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/515_0_0/515_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/515_0_0/515_0_0_t1+_thick_cor_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/515_0_0/515_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/515_0_0/515_0_0_t1+_thick_cor_VS_uvauser5_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/515_1_146/515_1_146_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/515_1_146/515_1_146_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/515_1_146/515_1_146_t2_thin_image_coregistered.nii.gz, nan)

 53%|█████▎    | 945/1793 [07:32<05:59,  2.36it/s]

Original image path: ./raw_studies/t1+_thin/515_1_146/515_1_146_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/515_1_146/515_1_146_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/515_1_146/515_1_146_t1+_thin_manual_0_uvauser8-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/515_1_146/515_1_146_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/515_1_146/515_1_146_t1+_thin_manual_0_uvauser8-copy_coregistered.nii.gz)

 53%|█████▎    | 946/1793 [07:33<08:35,  1.64it/s]

Original image path: ./raw_studies/t1+_thin/520_0_0/520_0_0_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/520_0_0/520_0_0_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/520_0_0/520_0_0_t1+_thin_image_coregistered.nii.gz, nan)

 53%|█████▎    | 948/1793 [07:34<08:22,  1.68it/s]

Original image path: ./raw_studies/t2_thick/520_0_0/520_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/520_0_0/520_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/520_0_0/520_0_0_t2_thick_RVS _uvauser2.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thick_ax/520_0_0/520_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/520_0_0/520_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/520_0_0/520_0_0_t1+_thick_ax_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/520_0_0/520_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/520_0_0/520_0_0_t1+_thick_ax_RVS _uvauser2_coregistered.nii.gz)

 53%|█████▎    | 949/1793 [07:34<06:48,  2.06it/s]

Original image path: ./raw_studies/t1+_thin/520_0_0/520_0_0_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/520_0_0/520_0_0_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/520_0_0/520_0_0_t1+_thin_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/520_0_0/520_0_0_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/520_0_0/520_0_0_t1+_thin_RVS _uvauser2_coregistered.nii.gz)

 53%|█████▎    | 950/1793 [07:36<09:47,  1.44it/s]

Original image path: ./raw_studies/t1+_thin/520_1_94/520_1_94_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/520_1_94/520_1_94_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/520_1_94/520_1_94_t1+_thin_VST1_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/520_1_94/520_1_94_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/520_1_94/520_1_94_t1+_thin_VST1_uvauser6_coregistered.nii.gz)

 53%|█████▎    | 952/1793 [07:36<07:17,  1.92it/s]

Original image path: ./raw_studies/t2_thick/520_1_94/520_1_94_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/520_1_94/520_1_94_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/520_1_94/520_1_94_t2_thick_VST2_uvauser6.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t2_thick/520_2_311/520_2_311_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/520_2_311/520_2_311_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 53%|█████▎    | 953/1793 [07:36<05:52,  2.39it/s]

Original image path: ./raw_studies/t1+_thin/520_2_311/520_2_311_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/520_2_311/520_2_311_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/520_2_311/520_2_311_t1+_thin_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/520_2_311/520_2_311_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/520_2_311/520_2_311_t1+_thin_tumorcore _uvauser3_coregistered.nii.gz)

 53%|█████▎    | 955/1793 [07:37<04:21,  3.20it/s]

Original image path: ./raw_studies/t2_thick/521_0_0/521_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/521_0_0/521_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thin/521_0_0/521_0_0_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/521_0_0/521_0_0_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/521_0_0/521_0_0_t1+_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/521_0_0/521_0_0_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/521_0_0/521_0_0_t1+_thin_VS_uvauser1_coregistered.nii.gz)

 53%|█████▎    | 956/1793 [07:37<05:20,  2.61it/s]

Original image path: ./raw_studies/t1+_thin/521_1_93/521_1_93_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/521_1_93/521_1_93_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/521_1_93/521_1_93_t1+_thin_image_coregistered.nii.gz, nan)

 53%|█████▎    | 957/1793 [07:38<05:53,  2.36it/s]

Original image path: ./raw_studies/t2_thin/521_1_93/521_1_93_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/521_1_93/521_1_93_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/521_1_93/521_1_93_t2_thin_image_coregistered.nii.gz, nan)

 53%|█████▎    | 958/1793 [07:39<08:17,  1.68it/s]

Original image path: ./raw_studies/t2_thin/521_2_457/521_2_457_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/521_2_457/521_2_457_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/521_2_457/521_2_457_t2_thin_image_coregistered.nii.gz, nan)

 53%|█████▎    | 959/1793 [07:40<10:06,  1.37it/s]

Original image path: ./raw_studies/t1+_thin/521_2_457/521_2_457_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/521_2_457/521_2_457_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/521_2_457/521_2_457_t1+_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/521_2_457/521_2_457_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/521_2_457/521_2_457_t1+_thin_VS_uvauser1_coregistered.nii.gz)

 54%|█████▎    | 962/1793 [07:41<05:08,  2.69it/s]

Original image path: ./raw_studies/t1+_thick_ax/525_0_0/525_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/525_0_0/525_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/525_0_0/525_0_0_t1+_thick_ax_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/525_0_0/525_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/525_0_0/525_0_0_t1+_thick_ax_AS_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/525_0_0/525_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/525_0_0/525_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/525_0_0/525_0_0_t1+_thick_cor_AS1_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/525_0_0/525_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/525_0_0/525_0_0_t1+_thick_cor_AS1_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/525_0_0/525_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/525_0_0/525_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/525_0_0/525_0_0_t2_thin_AS2_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/525_0_0/525_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/525_0_0/525_0_0_t2_thin_AS2_uvauser4_coregistered.nii.gz)

 54%|█████▎    | 963/1793 [07:42<07:44,  1.79it/s]

Original image path: ./raw_studies/t2_thin/525_1_371/525_1_371_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/525_1_371/525_1_371_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/525_1_371/525_1_371_t2_thin_image_coregistered.nii.gz, nan)

 54%|█████▍    | 964/1793 [07:43<09:27,  1.46it/s]

Original image path: ./raw_studies/t1+_thin/525_1_371/525_1_371_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/525_1_371/525_1_371_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/525_1_371/525_1_371_t1+_thin_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/525_1_371/525_1_371_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/525_1_371/525_1_371_t1+_thin_AS_uvauser4_coregistered.nii.gz)

 54%|█████▍    | 965/1793 [07:43<08:34,  1.61it/s]

Original image path: ./raw_studies/t1+_thick_cor/525_3_465/525_3_465_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/525_3_465/525_3_465_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/525_3_465/525_3_465_t1+_thick_cor_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/525_3_465/525_3_465_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/525_3_465/525_3_465_t1+_thick_cor_LVS _uvauser2_coregistered.nii.gz)

 54%|█████▍    | 966/1793 [07:44<07:39,  1.80it/s]

Original image path: ./raw_studies/t1+_thin/525_3_465/525_3_465_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/525_3_465/525_3_465_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/525_3_465/525_3_465_t1+_thin_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/525_3_465/525_3_465_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/525_3_465/525_3_465_t1+_thin_LVS _uvauser2_coregistered.nii.gz)

 54%|█████▍    | 967/1793 [07:44<07:02,  1.95it/s]

Original image path: ./raw_studies/t2_thin/525_3_465/525_3_465_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/525_3_465/525_3_465_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/525_3_465/525_3_465_t2_thin_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/525_3_465/525_3_465_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/525_3_465/525_3_465_t2_thin_LVS _uvauser2_coregistered.nii.gz)

 54%|█████▍    | 968/1793 [07:47<16:13,  1.18s/it]

Original image path: ./raw_studies/t2_thin/527_0_0/527_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/527_0_0/527_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/527_0_0/527_0_0_t2_thin_image_coregistered.nii.gz, nan)

 54%|█████▍    | 970/1793 [07:47<09:43,  1.41it/s]

Original image path: ./raw_studies/t1+_thick_cor/527_0_0/527_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/527_0_0/527_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/527_0_0/527_0_0_t1+_thick_cor_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thick_cor/527_1_267/527_1_267_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/527_1_267/527_1_267_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/527_1_267/527_1_267_t1+_thick_cor_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/527_1_267/527_1_267_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/527_1_267/527_1_267_t1+_thick_cor_RVS _uvauser2_coregistered.nii.gz)

 54%|█████▍    | 971/1793 [07:47<07:32,  1.81it/s]

Original image path: ./raw_studies/t2_thin/527_1_267/527_1_267_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/527_1_267/527_1_267_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/527_1_267/527_1_267_t2_thin_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/527_1_267/527_1_267_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/527_1_267/527_1_267_t2_thin_RVS _uvauser2_coregistered.nii.gz)

 54%|█████▍    | 973/1793 [07:49<07:25,  1.84it/s]

Original image path: ./raw_studies/t1+_thick_ax/527_1_267/527_1_267_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/527_1_267/527_1_267_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/527_1_267/527_1_267_t1+_thick_ax_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/527_1_267/527_1_267_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/527_1_267/527_1_267_t1+_thick_ax_RVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/527_2_591/527_2_591_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/527_2_591/527_2_591_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/527_2_591/527_2_591_t2_thin_image_coregistered.nii.gz, nan)

 54%|█████▍    | 975/1793 [07:50<07:39,  1.78it/s]

Original image path: ./raw_studies/t1+_thick_cor/527_2_591/527_2_591_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/527_2_591/527_2_591_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/527_2_591/527_2_591_t1+_thick_cor_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thick_ax/527_2_591/527_2_591_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/527_2_591/527_2_591_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/527_2_591/527_2_591_t1+_thick_ax_image_coregistered.nii.gz, nan)

 54%|█████▍    | 976/1793 [07:50<06:05,  2.24it/s]

Original image path: ./raw_studies/t1+_thin/527_3_625/527_3_625_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/527_3_625/527_3_625_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/527_3_625/527_3_625_t1+_thin_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/527_3_625/527_3_625_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/527_3_625/527_3_625_t1+_thin_AS_uvauser4_coregistered.nii.gz)

 54%|█████▍    | 977/1793 [07:52<10:11,  1.33it/s]

Original image path: ./raw_studies/t2_thin/527_3_625/527_3_625_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/527_3_625/527_3_625_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/527_3_625/527_3_625_t2_thin_VST2_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/527_3_625/527_3_625_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/527_3_625/527_3_625_t2_thin_VST2_uvauser6_coregistered.nii.gz)

 55%|█████▍    | 978/1793 [07:52<08:23,  1.62it/s]

Original image path: ./raw_studies/t1+_thick_cor/528_0_0/528_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/528_0_0/528_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/528_0_0/528_0_0_t1+_thick_cor_image_coregistered.nii.gz, nan)

 55%|█████▍    | 979/1793 [07:52<06:46,  2.00it/s]

Original image path: ./raw_studies/t1+_thick_ax/528_0_0/528_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/528_0_0/528_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/528_0_0/528_0_0_t1+_thick_ax_image_coregistered.nii.gz, nan)

 55%|█████▍    | 980/1793 [07:52<05:33,  2.43it/s]

Original image path: ./raw_studies/t1+_thin/528_0_0/528_0_0_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/528_0_0/528_0_0_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/528_0_0/528_0_0_t1+_thin_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/528_0_0/528_0_0_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/528_0_0/528_0_0_t1+_thin_AS_uvauser4_coregistered.nii.gz)

 55%|█████▍    | 981/1793 [07:53<05:22,  2.52it/s]

Original image path: ./raw_studies/t2_thin/528_0_0/528_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/528_0_0/528_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/528_0_0/528_0_0_t2_thin_image_coregistered.nii.gz, nan)

 55%|█████▍    | 982/1793 [07:53<05:51,  2.31it/s]

Original image path: ./raw_studies/t1+_thin/528_1_488/528_1_488_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/528_1_488/528_1_488_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/528_1_488/528_1_488_t1+_thin_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/528_1_488/528_1_488_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/528_1_488/528_1_488_t1+_thin_AS_uvauser4_coregistered.nii.gz)

 55%|█████▍    | 983/1793 [07:54<05:52,  2.30it/s]

Original image path: ./raw_studies/t2_thin/528_1_488/528_1_488_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/528_1_488/528_1_488_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/528_1_488/528_1_488_t2_thin_RVS _uvauser2-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/528_1_488/528_1_488_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/528_1_488/528_1_488_t2_thin_RVS _uvauser2-copy_coregistered.nii.gz)

 55%|█████▍    | 985/1793 [07:54<04:22,  3.08it/s]

Original image path: ./raw_studies/t1+_thick_cor/528_1_488/528_1_488_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/528_1_488/528_1_488_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/528_1_488/528_1_488_t1+_thick_cor_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/528_1_488/528_1_488_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/528_1_488/528_1_488_t1+_thick_cor_RVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/528_2_838/528_2_838_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/528_2_838/528_2_838_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/528_2_838/528_2_838_t1+_thick_ax_image_coregistered.nii.gz, nan)

 55%|█████▌    | 987/1793 [07:54<02:48,  4.79it/s]

Original image path: ./raw_studies/t1+_thick_cor/528_2_838/528_2_838_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/528_2_838/528_2_838_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/528_2_838/528_2_838_t1+_thick_cor_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thick_ax/528_2_838/528_2_838_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/528_2_838/528_2_838_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/528_2_838/528_2_838_t1+_thick_ax_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/528_2_838/528_2_838_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/528_2_838/528_2_838_t1+_thick_ax_tumorcore _uvauser3_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/528_2_838/528_2_838_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/528_2_838/528_2_838_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/528_2_838/528_2_838_t2_thin_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/528_2_838/528_2_838_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/528_2_838/528_2_838_t2_thin_tumorcore _uvauser3_coregistered.nii.gz)

 55%|█████▌    | 989/1793 [07:55<02:48,  4.77it/s]

Original image path: ./raw_studies/t2_thin/528_3_1394/528_3_1394_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/528_3_1394/528_3_1394_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/528_3_1394/528_3_1394_t2_thin_image_coregistered.nii.gz, nan)

 55%|█████▌    | 990/1793 [07:55<03:00,  4.45it/s]

Original image path: ./raw_studies/t1+_thin/528_3_1394/528_3_1394_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/528_3_1394/528_3_1394_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/528_3_1394/528_3_1394_t1+_thin_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/528_3_1394/528_3_1394_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/528_3_1394/528_3_1394_t1+_thin_tumorcore _uvauser3_coregistered.nii.gz)

 55%|█████▌    | 991/1793 [07:55<03:26,  3.88it/s]

Original image path: ./raw_studies/t2_thin/528_4_1772/528_4_1772_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/528_4_1772/528_4_1772_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/528_4_1772/528_4_1772_t2_thin_Manual_0_uvauser11.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/528_4_1772/528_4_1772_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/528_4_1772/528_4_1772_t2_thin_Manual_0_uvauser11_coregistered.nii.gz)

 55%|█████▌    | 992/1793 [07:58<11:51,  1.13it/s]

Original image path: ./raw_studies/t1+_thin/528_4_1772/528_4_1772_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/528_4_1772/528_4_1772_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/528_4_1772/528_4_1772_t1+_thin_image_coregistered.nii.gz, nan)

 55%|█████▌    | 993/1793 [07:59<12:58,  1.03it/s]

Original image path: ./raw_studies/t1+_thin/53_0_0/53_0_0_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/53_0_0/53_0_0_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/53_0_0/53_0_0_t1+_thin_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/53_0_0/53_0_0_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/53_0_0/53_0_0_t1+_thin_tumorcore _uvauser3_coregistered.nii.gz)

 55%|█████▌    | 994/1793 [08:00<10:48,  1.23it/s]

Original image path: ./raw_studies/t2_thick/53_0_0/53_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/53_0_0/53_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 55%|█████▌    | 995/1793 [08:01<11:56,  1.11it/s]

Original image path: ./raw_studies/t2_thick/53_1_484/53_1_484_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/53_1_484/53_1_484_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 56%|█████▌    | 996/1793 [08:01<09:40,  1.37it/s]

Original image path: ./raw_studies/t2_thin/53_2_891/53_2_891_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/53_2_891/53_2_891_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/53_2_891/53_2_891_t2_thin_image_coregistered.nii.gz, nan)

 56%|█████▌    | 997/1793 [08:02<08:50,  1.50it/s]

Original image path: ./raw_studies/t1+_thin/53_2_891/53_2_891_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/53_2_891/53_2_891_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/53_2_891/53_2_891_t1+_thin_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/53_2_891/53_2_891_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/53_2_891/53_2_891_t1+_thin_tumorcore _uvauser3_coregistered.nii.gz)

 56%|█████▌    | 999/1793 [08:04<10:15,  1.29it/s]

Original image path: ./raw_studies/t1+_thick_cor/532_0_0/532_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/532_0_0/532_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/532_0_0/532_0_0_t1+_thick_cor_VS2_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/532_0_0/532_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/532_0_0/532_0_0_t1+_thick_cor_VS2_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/532_0_0/532_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/532_0_0/532_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/532_0_0/532_0_0_t1+_thick_ax_VS1_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/532_0_0/532_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/532_0_0/532_0_0_t1+_thick_ax_VS1_uvauser1_coregistered.nii.gz)

 56%|█████▌    | 1000/1793 [08:04<08:01,  1.65it/s]

Original image path: ./raw_studies/t2_thin/532_0_0/532_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/532_0_0/532_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/532_0_0/532_0_0_t2_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/532_0_0/532_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/532_0_0/532_0_0_t2_thin_VS_uvauser1_coregistered.nii.gz)

 56%|█████▌    | 1002/1793 [08:05<07:46,  1.69it/s]

Original image path: ./raw_studies/t1+_thick_ax/532_1_355/532_1_355_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/532_1_355/532_1_355_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/532_1_355/532_1_355_t1+_thick_ax_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/532_1_355/532_1_355_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/532_1_355/532_1_355_t1+_thick_ax_AS_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/532_1_355/532_1_355_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/532_1_355/532_1_355_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/532_1_355/532_1_355_t2_thin_AS2_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/532_1_355/532_1_355_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/532_1_355/532_1_355_t2_thin_AS2_uvauser4_coregistered.nii.gz)

 56%|█████▌    | 1004/1793 [08:06<07:16,  1.81it/s]

Original image path: ./raw_studies/t1+_thick_cor/532_1_355/532_1_355_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/532_1_355/532_1_355_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/532_1_355/532_1_355_t1+_thick_cor_AS1_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/532_1_355/532_1_355_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/532_1_355/532_1_355_t1+_thick_cor_AS1_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/532_2_624/532_2_624_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/532_2_624/532_2_624_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/532_2_624/532_2_624_t2_thin_image_coregistered.nii.gz, nan)

 56%|█████▌    | 1005/1793 [08:07<06:56,  1.89it/s]

Original image path: ./raw_studies/t1+_thin/532_2_624/532_2_624_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/532_2_624/532_2_624_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/532_2_624/532_2_624_t1+_thin_tumorcore _uvauser3-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/532_2_624/532_2_624_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/532_2_624/532_2_624_t1+_thin_tumorcore _uvauser3-copy_coregistered.nii.gz)

 56%|█████▌    | 1006/1793 [08:08<09:25,  1.39it/s]

Original image path: ./raw_studies/t1+_thin/534_0_0/534_0_0_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/534_0_0/534_0_0_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/534_0_0/534_0_0_t1+_thin_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/534_0_0/534_0_0_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/534_0_0/534_0_0_t1+_thin_tumorcore _uvauser3_coregistered.nii.gz)

 56%|█████▌    | 1008/1793 [08:08<06:00,  2.18it/s]

Original image path: ./raw_studies/t2_thin/534_0_0/534_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/534_0_0/534_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/534_0_0/534_0_0_t2_thin_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t2_thin/534_1_146/534_1_146_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/534_1_146/534_1_146_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/534_1_146/534_1_146_t2_thin_image_coregistered.nii.gz, nan)

 56%|█████▋    | 1009/1793 [08:09<05:27,  2.39it/s]

Original image path: ./raw_studies/t1+_thin/534_1_146/534_1_146_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/534_1_146/534_1_146_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/534_1_146/534_1_146_t1+_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/534_1_146/534_1_146_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/534_1_146/534_1_146_t1+_thin_VS_uvauser1_coregistered.nii.gz)

 56%|█████▋    | 1011/1793 [08:10<07:15,  1.79it/s]

Original image path: ./raw_studies/t1+_thick_ax/537_0_0/537_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/537_0_0/537_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/537_0_0/537_0_0_t1+_thick_ax_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/537_0_0/537_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/537_0_0/537_0_0_t1+_thick_ax_LVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/537_0_0/537_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/537_0_0/537_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/537_0_0/537_0_0_t1+_thick_cor_image_coregistered.nii.gz, nan)

 56%|█████▋    | 1012/1793 [08:11<05:52,  2.21it/s]

Original image path: ./raw_studies/t2_thin/537_0_0/537_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/537_0_0/537_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/537_0_0/537_0_0_t2_thin_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/537_0_0/537_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/537_0_0/537_0_0_t2_thin_tumorcore _uvauser3_coregistered.nii.gz)

 56%|█████▋    | 1013/1793 [08:12<07:41,  1.69it/s]

Original image path: ./raw_studies/t1+_thin/537_0_0/537_0_0_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/537_0_0/537_0_0_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/537_0_0/537_0_0_t1+_thin_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/537_0_0/537_0_0_t1+_thin_image_coregistered.nii.gz, nan)

 57%|█████▋    | 1014/1793 [08:12<08:03,  1.61it/s]

Original image path: ./raw_studies/t2_thin/537_1_110/537_1_110_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/537_1_110/537_1_110_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/537_1_110/537_1_110_t2_thin_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/537_1_110/537_1_110_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/537_1_110/537_1_110_t2_thin_tumorcore _uvauser3_coregistered.nii.gz)

 57%|█████▋    | 1016/1793 [08:13<05:25,  2.39it/s]

Original image path: ./raw_studies/t1+_thin/537_1_110/537_1_110_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/537_1_110/537_1_110_t1+_thin_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

Original image path: ./raw_studies/t2_thick/539_0_0/539_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/539_0_0/539_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 57%|█████▋    | 1018/1793 [08:13<04:40,  2.77it/s]

Original image path: ./raw_studies/t1+_thick_ax/539_0_0/539_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/539_0_0/539_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/539_0_0/539_0_0_t1+_thick_ax_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/539_0_0/539_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/539_0_0/539_0_0_t1+_thick_ax_AS_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/539_0_0/539_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/539_0_0/539_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/539_0_0/539_0_0_t1+_thick_cor_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/539_0_0/539_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/539_0_0/539_0_0_t1+_thick_cor_AS_uvauser4_coregistered.nii.gz)

 57%|█████▋    | 1019/1793 [08:14<04:12,  3.06it/s]

Original image path: ./raw_studies/t1+_thin/539_1_18/539_1_18_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/539_1_18/539_1_18_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/539_1_18/539_1_18_t1+_thin_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/539_1_18/539_1_18_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/539_1_18/539_1_18_t1+_thin_tumorcore _uvauser3_coregistered.nii.gz)

 57%|█████▋    | 1020/1793 [08:15<07:41,  1.68it/s]

Original image path: ./raw_studies/t2_thin/539_1_18/539_1_18_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/539_1_18/539_1_18_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/539_1_18/539_1_18_t2_thin_image_coregistered.nii.gz, nan)

 57%|█████▋    | 1021/1793 [08:15<06:32,  1.96it/s]

Original image path: ./raw_studies/t1+_thin/540_0_0/540_0_0_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/540_0_0/540_0_0_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/540_0_0/540_0_0_t1+_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/540_0_0/540_0_0_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/540_0_0/540_0_0_t1+_thin_VS_uvauser1_coregistered.nii.gz)

 57%|█████▋    | 1022/1793 [08:15<05:46,  2.23it/s]

Original image path: ./raw_studies/t2_thin/540_0_0/540_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/540_0_0/540_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/540_0_0/540_0_0_t2_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/540_0_0/540_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/540_0_0/540_0_0_t2_thin_VS_uvauser1_coregistered.nii.gz)

 57%|█████▋    | 1023/1793 [08:16<06:01,  2.13it/s]

Original image path: ./raw_studies/t1+_thick_ax/540_1_294/540_1_294_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/540_1_294/540_1_294_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/540_1_294/540_1_294_t1+_thick_ax_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/540_1_294/540_1_294_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/540_1_294/540_1_294_t1+_thick_ax_tumorcore _uvauser3_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/540_1_294/540_1_294_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/540_1_294/540_1_294_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/540_1_294/540_1_294_t2_thin_CO_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/540_1_294/540_1_294_t2_thin_image_coregistered.nii.gz, nan)

 57%|█████▋    | 1027/1793 [08:18<05:10,  2.47it/s]

Original image path: ./raw_studies/t1+_thick_cor/540_1_294/540_1_294_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/540_1_294/540_1_294_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/540_1_294/540_1_294_t1+_thick_cor_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/540_1_294/540_1_294_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/540_1_294/540_1_294_t1+_thick_cor_tumorcore _uvauser3_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/540_2_663/540_2_663_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/540_2_663/540_2_663_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/540_2_663/540_2_663_t1+_thick_cor_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/540_2_663/540_2_663_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/540_2_663/540_2_663_t1+_thick_cor_LVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/540_2_663/540_2_663_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/540_2_663/540_2_663_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/540_2_663/540_2_663_t2_thin_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/540_2_663/540_2_663_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/540_2_663/540_2_663_t2_thin_LVS _uvauser2_coregistered.nii.gz)

 57%|█████▋    | 1028/1793 [08:19<06:56,  1.84it/s]

Original image path: ./raw_studies/t1+_thick_ax/540_2_663/540_2_663_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/540_2_663/540_2_663_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/540_2_663/540_2_663_t1+_thick_ax_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/540_2_663/540_2_663_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/540_2_663/540_2_663_t1+_thick_ax_LVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thin/540_3_1126/540_3_1126_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/540_3_1126/540_3_1126_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/540_3_1126/540_3_1126_t1+_thin_VST1_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/540_3_1126/540_3_1126_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/540_3_1126/540_3_1126_t1+_thin_VST1_uvauser6_coregistered.nii.gz)

 57%|█████▋    | 1030/1793 [08:20<07:43,  1.65it/s]

Original image path: ./raw_studies/t2_thin/540_3_1126/540_3_1126_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/540_3_1126/540_3_1126_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/540_3_1126/540_3_1126_t2_thin_VST2_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/540_3_1126/540_3_1126_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/540_3_1126/540_3_1126_t2_thin_VST2_uvauser6_coregistered.nii.gz)

 58%|█████▊    | 1031/1793 [08:21<07:39,  1.66it/s]

Original image path: ./raw_studies/t1+_thin/541_0_0/541_0_0_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/541_0_0/541_0_0_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/541_0_0/541_0_0_t1+_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/541_0_0/541_0_0_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/541_0_0/541_0_0_t1+_thin_VS_uvauser1_coregistered.nii.gz)

 58%|█████▊    | 1032/1793 [08:21<07:01,  1.81it/s]

Original image path: ./raw_studies/t2_thin/541_0_0/541_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/541_0_0/541_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/541_0_0/541_0_0_t2_thin_image_coregistered.nii.gz, nan)

 58%|█████▊    | 1034/1793 [08:22<05:33,  2.28it/s]

Original image path: ./raw_studies/t1+_thick_cor/541_1_201/541_1_201_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/541_1_201/541_1_201_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/541_1_201/541_1_201_t1+_thick_cor_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/541_1_201/541_1_201_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/541_1_201/541_1_201_t1+_thick_cor_AS_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/541_1_201/541_1_201_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/541_1_201/541_1_201_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/541_1_201/541_1_201_t1+_thick_ax_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/541_1_201/541_1_201_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/541_1_201/541_1_201_t1+_thick_ax_AS_uvauser4_coregistered.nii.gz)

 58%|█████▊    | 1035/1793 [08:22<04:32,  2.78it/s]

Original image path: ./raw_studies/t2_thin/541_1_201/541_1_201_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/541_1_201/541_1_201_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/541_1_201/541_1_201_t2_thin_AX_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/541_1_201/541_1_201_t2_thin_image_coregistered.nii.gz, nan)

 58%|█████▊    | 1038/1793 [08:23<03:30,  3.59it/s]

Original image path: ./raw_studies/t1+_thick_cor/546_0_0/546_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/546_0_0/546_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/546_0_0/546_0_0_t1+_thick_cor_T1COR_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/546_0_0/546_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/546_0_0/546_0_0_t1+_thick_cor_T1COR_uvauser6_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/546_0_0/546_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/546_0_0/546_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/546_0_0/546_0_0_t1+_thick_ax_T1AX_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/546_0_0/546_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/546_0_0/546_0_0_t1+_thick_ax_T1AX_uvauser6_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/546_0_0/546_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/546_0_0/546_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/546_0_0/546_0_0_t2_thin_AX_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/546_0_0/546_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/546_0_0/546_0_0_t2_thin_AX_VS_uvauser1_coregistered.nii.gz)

 58%|█████▊    | 1040/1793 [08:23<03:42,  3.38it/s]

Original image path: ./raw_studies/t1+_thick_cor/546_1_195/546_1_195_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/546_1_195/546_1_195_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/546_1_195/546_1_195_t1+_thick_cor_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/546_1_195/546_1_195_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/546_1_195/546_1_195_t1+_thick_cor_RVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/546_1_195/546_1_195_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/546_1_195/546_1_195_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/546_1_195/546_1_195_t1+_thick_ax_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/546_1_195/546_1_195_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/546_1_195/546_1_195_t1+_thick_ax_RVS _uvauser2_coregistered.nii.gz)

 58%|█████▊    | 1041/1793 [08:24<03:17,  3.81it/s]

Original image path: ./raw_studies/t1+_thick_cor/548_0_0/548_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/548_0_0/548_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/548_0_0/548_0_0_t1+_thick_cor_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/548_0_0/548_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/548_0_0/548_0_0_t1+_thick_cor_VS_uvauser5_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/548_0_0/548_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/548_0_0/548_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/548_0_0/548_0_0_t2_thin_manual_10_uvauser10.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/548_0_0/548_0_0_t2_thin_image_coregistered.nii.gz, nan)

 58%|█████▊    | 1043/1793 [08:24<03:07,  4.00it/s]

Original image path: ./raw_studies/t2_thin/548_1_377/548_1_377_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/548_1_377/548_1_377_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/548_1_377/548_1_377_t2_thin_T2_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/548_1_377/548_1_377_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/548_1_377/548_1_377_t2_thin_T2_uvauser6_coregistered.nii.gz)

 58%|█████▊    | 1044/1793 [08:24<03:25,  3.65it/s]

Original image path: ./raw_studies/t1+_thin/548_1_377/548_1_377_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/548_1_377/548_1_377_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/548_1_377/548_1_377_t1+_thin_T1_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/548_1_377/548_1_377_t1+_thin_image_coregistered.nii.gz, nan)

 58%|█████▊    | 1045/1793 [08:26<07:46,  1.60it/s]

Original image path: ./raw_studies/t1+_thin/553_0_0/553_0_0_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/553_0_0/553_0_0_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/553_0_0/553_0_0_t1+_thin_T1_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/553_0_0/553_0_0_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/553_0_0/553_0_0_t1+_thin_T1_uvauser6_coregistered.nii.gz)

 58%|█████▊    | 1046/1793 [08:28<10:37,  1.17it/s]

Original image path: ./raw_studies/t2_thin/553_0_0/553_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/553_0_0/553_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/553_0_0/553_0_0_t2_thin_T2_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/553_0_0/553_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/553_0_0/553_0_0_t2_thin_T2_uvauser6_coregistered.nii.gz)

 58%|█████▊    | 1047/1793 [08:28<08:50,  1.41it/s]

Original image path: ./raw_studies/t2_thin/553_1_194/553_1_194_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/553_1_194/553_1_194_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/553_1_194/553_1_194_t2_thin_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/553_1_194/553_1_194_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/553_1_194/553_1_194_t2_thin_LVS _uvauser2_coregistered.nii.gz)

 59%|█████▊    | 1049/1793 [08:28<06:09,  2.01it/s]

Original image path: ./raw_studies/t1+_thick_cor/553_1_194/553_1_194_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/553_1_194/553_1_194_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/553_1_194/553_1_194_t1+_thick_cor_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/553_1_194/553_1_194_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/553_1_194/553_1_194_t1+_thick_cor_LVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thin/553_1_194/553_1_194_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/553_1_194/553_1_194_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/553_1_194/553_1_194_t1+_thin_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/553_1_194/553_1_194_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/553_1_194/553_1_194_t1+_thin_LVS _uvauser2_coregistered.nii.gz)

 59%|█████▊    | 1051/1793 [08:30<07:42,  1.60it/s]

Original image path: ./raw_studies/t1+_thick_cor/556_0_0/556_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/556_0_0/556_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/556_0_0/556_0_0_t1+_thick_cor_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/556_0_0/556_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/556_0_0/556_0_0_t1+_thick_cor_LVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/556_0_0/556_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/556_0_0/556_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/556_0_0/556_0_0_t2_thin_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/556_0_0/556_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/556_0_0/556_0_0_t2_thin_LVS _uvauser2_coregistered.nii.gz)

 59%|█████▊    | 1053/1793 [08:31<04:57,  2.48it/s]

Original image path: ./raw_studies/t1+_thick_ax/556_0_0/556_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/556_0_0/556_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/556_0_0/556_0_0_t1+_thick_ax_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/556_0_0/556_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/556_0_0/556_0_0_t1+_thick_ax_LVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/556_1_187/556_1_187_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/556_1_187/556_1_187_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/556_1_187/556_1_187_t2_thin_image_coregistered.nii.gz, nan)

 59%|█████▉    | 1054/1793 [08:31<04:41,  2.63it/s]

Original image path: ./raw_studies/t1+_thick_ax/556_1_187/556_1_187_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/556_1_187/556_1_187_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/556_1_187/556_1_187_t1+_thick_ax_image_coregistered.nii.gz, nan)

 59%|█████▉    | 1055/1793 [08:31<04:14,  2.89it/s]

Original image path: ./raw_studies/t1+_thick_cor/556_1_187/556_1_187_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/556_1_187/556_1_187_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/556_1_187/556_1_187_t1+_thick_cor_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thin/556_2_286/556_2_286_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/556_2_286/556_2_286_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/556_2_286/556_2_286_t1+_thin_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/556_2_286/556_2_286_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/556_2_286/556_2_286_t1+_thin_AS_uvauser4_coregistered.nii.gz)

 59%|█████▉    | 1057/1793 [08:32<03:37,  3.39it/s]

Original image path: ./raw_studies/t1+_thick_ax/557_0_0/557_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/557_0_0/557_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/557_0_0/557_0_0_t1+_thick_ax_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/557_0_0/557_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/557_0_0/557_0_0_t1+_thick_ax_RVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/557_0_0/557_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/557_0_0/557_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/557_0_0/557_0_0_t2_thin_RVS _uvauser2-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/557_0_0/557_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/557_0_0/557_0_0_t2_thin_RVS _uvauser2-copy_coregistered.nii.gz)

 59%|█████▉    | 1060/1793 [08:32<02:55,  4.17it/s]

Original image path: ./raw_studies/t2_thick/557_0_0/557_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/557_0_0/557_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/557_0_0/557_0_0_t2_thick_RVS _uvauser2.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thick_cor/557_0_0/557_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/557_0_0/557_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/557_0_0/557_0_0_t1+_thick_cor_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/557_0_0/557_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/557_0_0/557_0_0_t1+_thick_cor_RVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/557_1_72/557_1_72_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/557_1_72/557_1_72_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/557_1_72/557_1_72_t1+_thick_ax_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/557_1_72/557_1_72_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/557_1_72/557_1_72_t1+_thick_ax_RVS _uvauser2_coregistered.nii.gz)

 59%|█████▉    | 1062/1793 [08:32<02:10,  5.62it/s]

Original image path: ./raw_studies/t1+_thick_cor/557_1_72/557_1_72_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/557_1_72/557_1_72_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/557_1_72/557_1_72_t1+_thick_cor_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/557_1_72/557_1_72_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/557_1_72/557_1_72_t1+_thick_cor_RVS _uvauser2_coregistered.nii.gz)

 59%|█████▉    | 1063/1793 [08:33<02:28,  4.91it/s]

Original image path: ./raw_studies/t2_thin/557_1_72/557_1_72_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/557_1_72/557_1_72_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/557_1_72/557_1_72_t2_thin_RVS _uvauser2-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/557_1_72/557_1_72_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/557_1_72/557_1_72_t2_thin_RVS _uvauser2-copy_coregistered.nii.gz)

 59%|█████▉    | 1065/1793 [08:34<04:12,  2.88it/s]

Original image path: ./raw_studies/t1+_thin/557_2_488/557_2_488_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/557_2_488/557_2_488_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/557_2_488/557_2_488_t1+_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/557_2_488/557_2_488_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/557_2_488/557_2_488_t1+_thin_VS_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/557_2_488/557_2_488_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/557_2_488/557_2_488_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/557_2_488/557_2_488_t2_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/557_2_488/557_2_488_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/557_2_488/557_2_488_t2_thin_VS_uvauser1_coregistered.nii.gz)

 60%|█████▉    | 1067/1793 [08:37<09:55,  1.22it/s]

Original image path: ./raw_studies/t2_thick/558_0_0/558_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/558_0_0/558_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/558_0_0/558_0_0_t2_thick_VS3_uvauser1.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thick_cor/558_0_0/558_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/558_0_0/558_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/558_0_0/558_0_0_t1+_thick_cor_VS1_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/558_0_0/558_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/558_0_0/558_0_0_t1+_thick_cor_VS1_uvauser1_coregistered.nii.gz)

 60%|█████▉    | 1068/1793 [08:37<07:56,  1.52it/s]

Original image path: ./raw_studies/t1+_thick_cor/558_0_0/558_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/558_0_0/558_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/558_0_0/558_0_0_t1+_thick_cor_VS2_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/558_0_0/558_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/558_0_0/558_0_0_t1+_thick_cor_VS2_uvauser1_coregistered.nii.gz)

 60%|█████▉    | 1071/1793 [08:38<03:54,  3.07it/s]

Original image path: ./raw_studies/t1+_thick_cor/558_1_307/558_1_307_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/558_1_307/558_1_307_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/558_1_307/558_1_307_t1+_thick_cor_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thick_ax/558_1_307/558_1_307_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/558_1_307/558_1_307_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/558_1_307/558_1_307_t1+_thick_ax_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/558_1_307/558_1_307_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/558_1_307/558_1_307_t1+_thick_ax_tumorcore _uvauser3_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/558_1_307/558_1_307_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/558_1_307/558_1_307_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/558_1_307/558_1_307_t2_thin_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/558_1_307/558_1_307_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/558_1_307/558_1_307_t2_thin_tumorcore _uvauser3_coregistered.nii.gz)

 60%|█████▉    | 1073/1793 [08:38<02:56,  4.08it/s]

Original image path: ./raw_studies/t1+_thick_ax/558_2_756/558_2_756_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/558_2_756/558_2_756_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/558_2_756/558_2_756_t1+_thick_ax_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/558_2_756/558_2_756_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/558_2_756/558_2_756_t1+_thick_ax_RVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/558_2_756/558_2_756_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/558_2_756/558_2_756_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/558_2_756/558_2_756_t2_thin_RVS _uvauser2-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/558_2_756/558_2_756_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/558_2_756/558_2_756_t2_thin_RVS _uvauser2-copy_coregistered.nii.gz)

 60%|█████▉    | 1075/1793 [08:39<04:26,  2.69it/s]

Original image path: ./raw_studies/t1+_thick_cor/558_2_756/558_2_756_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/558_2_756/558_2_756_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/558_2_756/558_2_756_t1+_thick_cor_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/558_2_756/558_2_756_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/558_2_756/558_2_756_t1+_thick_cor_RVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/558_3_1211/558_3_1211_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/558_3_1211/558_3_1211_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/558_3_1211/558_3_1211_t1+_thick_cor_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/558_3_1211/558_3_1211_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/558_3_1211/558_3_1211_t1+_thick_cor_AS_uvauser4_coregistered.nii.gz)

 60%|██████    | 1076/1793 [08:39<03:43,  3.21it/s]

Original image path: ./raw_studies/t2_thin/558_3_1211/558_3_1211_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/558_3_1211/558_3_1211_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/558_3_1211/558_3_1211_t2_thin_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/558_3_1211/558_3_1211_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/558_3_1211/558_3_1211_t2_thin_AS_uvauser4_coregistered.nii.gz)

 60%|██████    | 1077/1793 [08:40<06:17,  1.90it/s]

Original image path: ./raw_studies/t1+_thick_ax/558_3_1211/558_3_1211_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/558_3_1211/558_3_1211_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/558_3_1211/558_3_1211_t1+_thick_ax_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/558_3_1211/558_3_1211_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/558_3_1211/558_3_1211_t1+_thick_ax_AS_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/558_4_1655/558_4_1655_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/558_4_1655/558_4_1655_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/558_4_1655/558_4_1655_t1+_thick_ax_manual_10_uvauser10.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/558_4_1655/558_4_1655_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/558_4_1655/558_4_1655_t1+_thick_ax_manual_10_uvauser10_coregistered.nii.gz)

 60%|██████    | 1079/1793 [08:41<04:07,  2.88it/s]

Original image path: ./raw_studies/t2_thin/558_4_1655/558_4_1655_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/558_4_1655/558_4_1655_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/558_4_1655/558_4_1655_t2_thin_CO_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/558_4_1655/558_4_1655_t2_thin_image_coregistered.nii.gz, nan)

 60%|██████    | 1080/1793 [08:42<06:11,  1.92it/s]

Original image path: ./raw_studies/t2_thin/558_4_1655/558_4_1655_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/558_4_1655/558_4_1655_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/558_4_1655/558_4_1655_t2_thin_image_coregistered.nii.gz, nan)

 60%|██████    | 1082/1793 [08:43<06:03,  1.95it/s]

Original image path: ./raw_studies/t1+_thick_cor/558_4_1655/558_4_1655_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/558_4_1655/558_4_1655_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/558_4_1655/558_4_1655_t1+_thick_cor_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/558_4_1655/558_4_1655_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/558_4_1655/558_4_1655_t1+_thick_cor_tumorcore _uvauser3_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/558_5_1775/558_5_1775_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/558_5_1775/558_5_1775_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/558_5_1775/558_5_1775_t1+_thick_ax_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/558_5_1775/558_5_1775_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/558_5_1775/558_5_1775_t1+_thick_ax_VS_uvauser5_coregistered.nii.gz)

 60%|██████    | 1083/1793 [08:43<04:55,  2.40it/s]

Original image path: ./raw_studies/t1+_thick_cor/558_5_1775/558_5_1775_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/558_5_1775/558_5_1775_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/558_5_1775/558_5_1775_t1+_thick_cor_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/558_5_1775/558_5_1775_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/558_5_1775/558_5_1775_t1+_thick_cor_VS_uvauser5_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thin/558_5_1775/558_5_1775_t1+_thin_image_uint8.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/558_5_1775/558_5_1775_t1+_thin_image_uint8_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 61%|██████    | 1086/1793 [08:45<05:34,  2.11it/s]

Original image path: ./raw_studies/t2_thick/558_5_1775/558_5_1775_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/558_5_1775/558_5_1775_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thin/558_5_1775/558_5_1775_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/558_5_1775/558_5_1775_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/558_5_1775/558_5_1775_t1+_thin_image_coregistered.nii.gz, nan)

 61%|██████    | 1087/1793 [08:46<07:52,  1.49it/s]

Original image path: ./raw_studies/t1+_thin/558_5_1775/558_5_1775_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/558_5_1775/558_5_1775_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/558_5_1775/558_5_1775_t1+_thin_T1Final_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/558_5_1775/558_5_1775_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/558_5_1775/558_5_1775_t1+_thin_T1Final_VS_uvauser5_coregistered.nii.gz)

 61%|██████    | 1088/1793 [08:47<09:48,  1.20it/s]

Original image path: ./raw_studies/t2_thin/558_5_1775/558_5_1775_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/558_5_1775/558_5_1775_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/558_5_1775/558_5_1775_t2_thin_image_coregistered.nii.gz, nan)

 61%|██████    | 1089/1793 [08:48<08:38,  1.36it/s]

Original image path: ./raw_studies/t1+_thin/559_0_0/559_0_0_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/559_0_0/559_0_0_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/559_0_0/559_0_0_t1+_thin_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/559_0_0/559_0_0_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/559_0_0/559_0_0_t1+_thin_AS_uvauser4_coregistered.nii.gz)

 61%|██████    | 1092/1793 [08:48<04:20,  2.69it/s]

Original image path: ./raw_studies/t2_thick/559_0_0/559_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/559_0_0/559_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thick_cor/559_1_188/559_1_188_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/559_1_188/559_1_188_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/559_1_188/559_1_188_t1+_thick_cor_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t2_thick/559_1_188/559_1_188_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/559_1_188/559_1_188_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 61%|██████    | 1093/1793 [08:48<03:58,  2.93it/s]

Original image path: ./raw_studies/t1+_thin/559_1_188/559_1_188_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/559_1_188/559_1_188_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/559_1_188/559_1_188_t1+_thin_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/559_1_188/559_1_188_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/559_1_188/559_1_188_t1+_thin_tumorcore _uvauser3_coregistered.nii.gz)

 61%|██████    | 1094/1793 [08:50<06:51,  1.70it/s]

Original image path: ./raw_studies/t1+_thick_ax/559_1_188/559_1_188_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/559_1_188/559_1_188_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/559_1_188/559_1_188_t1+_thick_ax_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thin/559_1_188/559_1_188_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/559_1_188/559_1_188_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/559_1_188/559_1_188_t1+_thin_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/559_1_188/559_1_188_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/559_1_188/559_1_188_t1+_thin_VS_uvauser5_coregistered.nii.gz)

 61%|██████    | 1096/1793 [08:51<07:04,  1.64it/s]

Original image path: ./raw_studies/t1+_thin/559_1_188/559_1_188_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/559_1_188/559_1_188_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/559_1_188/559_1_188_t1+_thin_image_coregistered.nii.gz, nan)

 61%|██████    | 1097/1793 [08:52<08:32,  1.36it/s]

Original image path: ./raw_studies/t2_thin/559_1_188/559_1_188_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/559_1_188/559_1_188_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/559_1_188/559_1_188_t2_thin_image_coregistered.nii.gz, nan)

 61%|██████▏   | 1100/1793 [08:53<04:31,  2.56it/s]

Original image path: ./raw_studies/t1+_thick_cor/560_0_0/560_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/560_0_0/560_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/560_0_0/560_0_0_t1+_thick_cor_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thick_ax/560_0_0/560_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/560_0_0/560_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/560_0_0/560_0_0_t1+_thick_ax_Manual_0_uvauser11.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/560_0_0/560_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/560_0_0/560_0_0_t1+_thick_ax_Manual_0_uvauser11_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/560_0_0/560_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/560_0_0/560_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/560_0_0/560_0_0_t1+_thick_ax_image_coregistered.nii.gz, nan)

 61%|██████▏   | 1102/1793 [08:53<03:07,  3.68it/s]

Original image path: ./raw_studies/t2_thin/560_0_0/560_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/560_0_0/560_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/560_0_0/560_0_0_t2_thin_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t2_thick/560_0_0/560_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/560_0_0/560_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/560_0_0/560_0_0_t2_thick_Manual_0_uvauser11.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thin/560_1_146/560_1_146_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/560_1_146/560_1_146_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/560_1_146/560_1_146_t1+_thin_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/560_1_146/560_1_146_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/560_1_146/560_1_146_t1+_thin_tumorcore _uvauser3_coregistered.nii.gz)

 62%|██████▏   | 1105/1793 [08:54<04:18,  2.66it/s]

Original image path: ./raw_studies/t2_thick/560_1_146/560_1_146_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/560_1_146/560_1_146_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thin/560_1_146/560_1_146_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/560_1_146/560_1_146_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/560_1_146/560_1_146_t1+_thin_image_coregistered.nii.gz, nan)

 62%|██████▏   | 1106/1793 [08:55<06:26,  1.78it/s]

Original image path: ./raw_studies/t1+_thick_cor/560_1_146/560_1_146_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/560_1_146/560_1_146_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/560_1_146/560_1_146_t1+_thick_cor_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t2_thin/560_1_146/560_1_146_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/560_1_146/560_1_146_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/560_1_146/560_1_146_t2_thin_image_coregistered.nii.gz, nan)

 62%|██████▏   | 1108/1793 [08:56<04:47,  2.39it/s]

Original image path: ./raw_studies/t1+_thin/560_1_146/560_1_146_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/560_1_146/560_1_146_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/560_1_146/560_1_146_t1+_thin_image_coregistered.nii.gz, nan)

 62%|██████▏   | 1109/1793 [08:57<06:43,  1.69it/s]

Original image path: ./raw_studies/t1+_thin/561_0_0/561_0_0_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/561_0_0/561_0_0_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/561_0_0/561_0_0_t1+_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/561_0_0/561_0_0_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/561_0_0/561_0_0_t1+_thin_VS_uvauser1_coregistered.nii.gz)

 62%|██████▏   | 1110/1793 [08:58<06:35,  1.73it/s]

Original image path: ./raw_studies/t2_thin/561_0_0/561_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/561_0_0/561_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/561_0_0/561_0_0_t2_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/561_0_0/561_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/561_0_0/561_0_0_t2_thin_VS_uvauser1_coregistered.nii.gz)

 62%|██████▏   | 1111/1793 [08:59<07:36,  1.50it/s]

Original image path: ./raw_studies/t1+_thin/561_1_146/561_1_146_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/561_1_146/561_1_146_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/561_1_146/561_1_146_t1+_thin_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/561_1_146/561_1_146_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/561_1_146/561_1_146_t1+_thin_AS_uvauser4_coregistered.nii.gz)

 62%|██████▏   | 1112/1793 [09:00<09:02,  1.26it/s]

Original image path: ./raw_studies/t2_thin/561_1_146/561_1_146_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/561_1_146/561_1_146_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/561_1_146/561_1_146_t2_thin_image_coregistered.nii.gz, nan)

 62%|██████▏   | 1115/1793 [09:01<05:52,  1.93it/s]

Original image path: ./raw_studies/t1+_thick_ax/561_2_524/561_2_524_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/561_2_524/561_2_524_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/561_2_524/561_2_524_t1+_thick_ax_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/561_2_524/561_2_524_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/561_2_524/561_2_524_t1+_thick_ax_tumorcore _uvauser3_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/561_2_524/561_2_524_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/561_2_524/561_2_524_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/561_2_524/561_2_524_t1+_thick_cor_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/561_2_524/561_2_524_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/561_2_524/561_2_524_t1+_thick_cor_tumorcore _uvauser3_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/561_2_524/561_2_524_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/561_2_524/561_2_524_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/561_2_524/561_2_524_t2_thin_CO_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/561_2_524/561_2_524_t2_thin_image_coregistered.nii.gz, nan)

 62%|██████▏   | 1116/1793 [09:02<08:07,  1.39it/s]

Original image path: ./raw_studies/t1+_thick_cor/561_3_874/561_3_874_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/561_3_874/561_3_874_t1+_thick_cor_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t1+_thick_cor/561_3_874/561_3_874_t1+_thick_cor_RVS _uvauser2.nii.gz
Returning: (nan, nan)

 62%|██████▏   | 1117/1793 [09:03<07:31,  1.50it/s]

Original image path: ./raw_studies/t2_thin/561_3_874/561_3_874_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/561_3_874/561_3_874_t2_thin_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thin/561_3_874/561_3_874_t2_thin_RVS _uvauser2.nii.gz
Returning: (nan, nan)

 62%|██████▏   | 1118/1793 [09:04<09:21,  1.20it/s]

Original image path: ./raw_studies/t1+_thick_ax/561_3_874/561_3_874_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/561_3_874/561_3_874_t1+_thick_ax_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t1+_thick_ax/561_3_874/561_3_874_t1+_thick_ax_tumorcore _uvauser3.nii.gz
Returning: (nan, nan)

 62%|██████▏   | 1120/1793 [09:05<06:30,  1.72it/s]

Original image path: ./raw_studies/t1+_thick_cor/561_4_1259/561_4_1259_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/561_4_1259/561_4_1259_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/561_4_1259/561_4_1259_t1+_thick_cor_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/561_4_1259/561_4_1259_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/561_4_1259/561_4_1259_t1+_thick_cor_VS_uvauser5_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/561_4_1259/561_4_1259_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/561_4_1259/561_4_1259_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/561_4_1259/561_4_1259_t2_thin_T2Final_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/561_4_1259/561_4_1259_t2_thin_image_coregistered.nii.gz, nan)

 63%|██████▎   | 1122/1793 [09:06<06:49,  1.64it/s]

Original image path: ./raw_studies/t2_thick/561_4_1259/561_4_1259_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/561_4_1259/561_4_1259_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thick_ax/561_4_1259/561_4_1259_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/561_4_1259/561_4_1259_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/561_4_1259/561_4_1259_t1+_thick_ax_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/561_4_1259/561_4_1259_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/561_4_1259/561_4_1259_t1+_thick_ax_VS_uvauser5_coregistered.nii.gz)

 63%|██████▎   | 1123/1793 [09:06<05:18,  2.10it/s]

Original image path: ./raw_studies/t1+_thick_ax/561_5_1314/561_5_1314_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/561_5_1314/561_5_1314_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/561_5_1314/561_5_1314_t1+_thick_ax_image_coregistered.nii.gz, nan)

 63%|██████▎   | 1125/1793 [09:07<04:02,  2.76it/s]

Original image path: ./raw_studies/t2_thick/561_5_1314/561_5_1314_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/561_5_1314/561_5_1314_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thin/561_5_1314/561_5_1314_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/561_5_1314/561_5_1314_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/561_5_1314/561_5_1314_t1+_thin_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/561_5_1314/561_5_1314_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/561_5_1314/561_5_1314_t1+_thin_tumorcore _uvauser3_coregistered.nii.gz)

 63%|██████▎   | 1126/1793 [09:09<08:34,  1.30it/s]

Original image path: ./raw_studies/t1+_thin/561_5_1314/561_5_1314_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/561_5_1314/561_5_1314_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/561_5_1314/561_5_1314_t1+_thin_image_coregistered.nii.gz, nan)

 63%|██████▎   | 1128/1793 [09:10<08:28,  1.31it/s]

Original image path: ./raw_studies/t1+_thick_cor/561_5_1314/561_5_1314_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/561_5_1314/561_5_1314_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/561_5_1314/561_5_1314_t1+_thick_cor_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thin/561_5_1314/561_5_1314_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/561_5_1314/561_5_1314_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/561_5_1314/561_5_1314_t1+_thin_image_coregistered.nii.gz, nan)

 63%|██████▎   | 1129/1793 [09:12<11:30,  1.04s/it]

Original image path: ./raw_studies/t2_thin/561_5_1314/561_5_1314_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/561_5_1314/561_5_1314_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/561_5_1314/561_5_1314_t2_thin_image_coregistered.nii.gz, nan)

 63%|██████▎   | 1130/1793 [09:13<09:39,  1.14it/s]

Original image path: ./raw_studies/t2_thick/562_2_550/562_2_550_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/562_2_550/562_2_550_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 63%|██████▎   | 1131/1793 [09:13<07:51,  1.40it/s]

Original image path: ./raw_studies/t1+_thick_cor/563_0_0/563_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/563_0_0/563_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/563_0_0/563_0_0_t1+_thick_cor_VS2_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/563_0_0/563_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/563_0_0/563_0_0_t1+_thick_cor_VS2_uvauser1_coregistered.nii.gz)

 63%|██████▎   | 1132/1793 [09:13<06:18,  1.75it/s]

Original image path: ./raw_studies/t1+_thick_ax/563_0_0/563_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/563_0_0/563_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/563_0_0/563_0_0_t1+_thick_ax_VS1_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/563_0_0/563_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/563_0_0/563_0_0_t1+_thick_ax_VS1_uvauser1_coregistered.nii.gz)

 63%|██████▎   | 1133/1793 [09:13<05:09,  2.13it/s]

Original image path: ./raw_studies/t2_thin/563_0_0/563_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/563_0_0/563_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/563_0_0/563_0_0_t2_thin_VS_uvauser1-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/563_0_0/563_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/563_0_0/563_0_0_t2_thin_VS_uvauser1-copy_coregistered.nii.gz)

 63%|██████▎   | 1134/1793 [09:14<05:34,  1.97it/s]

Original image path: ./raw_studies/t1+_thick_cor/563_1_204/563_1_204_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/563_1_204/563_1_204_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/563_1_204/563_1_204_t1+_thick_cor_VS2_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/563_1_204/563_1_204_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/563_1_204/563_1_204_t1+_thick_cor_VS2_uvauser1_coregistered.nii.gz)

 63%|██████▎   | 1135/1793 [09:14<04:42,  2.33it/s]

Original image path: ./raw_studies/t2_thin/563_1_204/563_1_204_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/563_1_204/563_1_204_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/563_1_204/563_1_204_t2_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/563_1_204/563_1_204_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/563_1_204/563_1_204_t2_thin_VS_uvauser1_coregistered.nii.gz)

 63%|██████▎   | 1136/1793 [09:15<05:31,  1.98it/s]

Original image path: ./raw_studies/t1+_thick_ax/563_1_204/563_1_204_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/563_1_204/563_1_204_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/563_1_204/563_1_204_t1+_thick_ax_VS1_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/563_1_204/563_1_204_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/563_1_204/563_1_204_t1+_thick_ax_VS1_uvauser1_coregistered.nii.gz)

 63%|██████▎   | 1137/1793 [09:15<04:41,  2.33it/s]

Original image path: ./raw_studies/t1+_thick_cor/563_2_377/563_2_377_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/563_2_377/563_2_377_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/563_2_377/563_2_377_t1+_thick_cor_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/563_2_377/563_2_377_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/563_2_377/563_2_377_t1+_thick_cor_LVS _uvauser2_coregistered.nii.gz)

 63%|██████▎   | 1138/1793 [09:15<04:06,  2.66it/s]

Original image path: ./raw_studies/t1+_thick_ax/563_2_377/563_2_377_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/563_2_377/563_2_377_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/563_2_377/563_2_377_t1+_thick_ax_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/563_2_377/563_2_377_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/563_2_377/563_2_377_t1+_thick_ax_LVS _uvauser2_coregistered.nii.gz)

 64%|██████▎   | 1139/1793 [09:16<03:38,  3.00it/s]

Original image path: ./raw_studies/t2_thin/563_2_377/563_2_377_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/563_2_377/563_2_377_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/563_2_377/563_2_377_t2_thin_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/563_2_377/563_2_377_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/563_2_377/563_2_377_t2_thin_LVS _uvauser2_coregistered.nii.gz)

 64%|██████▎   | 1140/1793 [09:16<04:26,  2.45it/s]

Original image path: ./raw_studies/t1+_thin/563_3_522/563_3_522_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/563_3_522/563_3_522_t1+_thin_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t1+_thin/563_3_522/563_3_522_t1+_thin_T1_uvauser6.nii.gz
Returning: (nan, nan)

 64%|██████▎   | 1141/1793 [09:17<06:50,  1.59it/s]

Original image path: ./raw_studies/t2_thin/563_3_522/563_3_522_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/563_3_522/563_3_522_t2_thin_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thin/563_3_522/563_3_522_t2_thin_T2_uvauser6.nii.gz
Returning: (nan, nan)

 64%|██████▎   | 1142/1793 [09:18<05:49,  1.86it/s]

Original image path: ./raw_studies/t2_thin/565_0_0/565_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/565_0_0/565_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/565_0_0/565_0_0_t2_thin_T2_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/565_0_0/565_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/565_0_0/565_0_0_t2_thin_T2_uvauser6_coregistered.nii.gz)

 64%|██████▍   | 1145/1793 [09:18<03:02,  3.55it/s]

Original image path: ./raw_studies/t1+_thick_ax/565_0_0/565_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/565_0_0/565_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/565_0_0/565_0_0_t1+_thick_ax_T1AX_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/565_0_0/565_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/565_0_0/565_0_0_t1+_thick_ax_T1AX_uvauser6_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/565_0_0/565_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/565_0_0/565_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/565_0_0/565_0_0_t1+_thick_cor_T1COR_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/565_0_0/565_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/565_0_0/565_0_0_t1+_thick_cor_T1COR_uvauser6_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/565_1_90/565_1_90_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/565_1_90/565_1_90_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/565_1_90/565_1_90_t1+_thick_ax_Manual_0_uvauser11.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/565_1_90/565_1_90_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/565_1_90/565_1_90_t1+_thick_ax_Manual_0_uvauser11_coregistered.nii.gz)

 64%|██████▍   | 1147/1793 [09:18<02:35,  4.16it/s]

Original image path: ./raw_studies/t1+_thick_cor/565_1_90/565_1_90_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/565_1_90/565_1_90_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/565_1_90/565_1_90_t1+_thick_cor_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/565_1_90/565_1_90_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/565_1_90/565_1_90_t1+_thick_cor_RVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/565_1_90/565_1_90_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/565_1_90/565_1_90_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/565_1_90/565_1_90_t2_thin_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/565_1_90/565_1_90_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/565_1_90/565_1_90_t2_thin_RVS _uvauser2_coregistered.nii.gz)

 64%|██████▍   | 1149/1793 [09:20<04:23,  2.45it/s]

Original image path: ./raw_studies/t1+_thick_cor/568_0_0/568_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/568_0_0/568_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/568_0_0/568_0_0_t1+_thick_cor_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t2_thin/568_0_0/568_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/568_0_0/568_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/568_0_0/568_0_0_t2_thin_T2Final_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/568_0_0/568_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/568_0_0/568_0_0_t2_thin_T2Final_VS_uvauser5_coregistered.nii.gz)

 64%|██████▍   | 1151/1793 [09:21<05:09,  2.07it/s]

Original image path: ./raw_studies/t1+_thick_ax/568_0_0/568_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/568_0_0/568_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/568_0_0/568_0_0_t1+_thick_ax_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thick_ax/568_1_255/568_1_255_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/568_1_255/568_1_255_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/568_1_255/568_1_255_t1+_thick_ax_T1AX_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/568_1_255/568_1_255_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/568_1_255/568_1_255_t1+_thick_ax_T1AX_uvauser6_coregistered.nii.gz)

 64%|██████▍   | 1153/1793 [09:21<03:27,  3.09it/s]

Original image path: ./raw_studies/t1+_thick_cor/568_1_255/568_1_255_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/568_1_255/568_1_255_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/568_1_255/568_1_255_t1+_thick_cor_T1COR_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/568_1_255/568_1_255_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/568_1_255/568_1_255_t1+_thick_cor_T1COR_uvauser6_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/568_1_255/568_1_255_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/568_1_255/568_1_255_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/568_1_255/568_1_255_t2_thin_T2_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/568_1_255/568_1_255_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/568_1_255/568_1_255_t2_thin_T2_uvauser6_coregistered.nii.gz)

 64%|██████▍   | 1154/1793 [09:22<05:25,  1.97it/s]

Original image path: ./raw_studies/t2_thin/568_2_328/568_2_328_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/568_2_328/568_2_328_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/568_2_328/568_2_328_t2_thin_image_coregistered.nii.gz, nan)

 64%|██████▍   | 1155/1793 [09:23<05:20,  1.99it/s]

Original image path: ./raw_studies/t1+_thin/568_2_328/568_2_328_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/568_2_328/568_2_328_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/568_2_328/568_2_328_t1+_thin_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/568_2_328/568_2_328_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/568_2_328/568_2_328_t1+_thin_VS_uvauser5_coregistered.nii.gz)

 65%|██████▍   | 1157/1793 [09:24<05:54,  1.79it/s]

Original image path: ./raw_studies/t1+_thick_ax/569_0_0/569_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/569_0_0/569_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/569_0_0/569_0_0_t1+_thick_ax_user9-uva-seg-T1post-right_uvauser9.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/569_0_0/569_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/569_0_0/569_0_0_t1+_thick_ax_user9-uva-seg-T1post-right_uvauser9_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/569_0_0/569_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/569_0_0/569_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/569_0_0/569_0_0_t1+_thick_ax_user9-uva-seg-T1post-right_uvauser9.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/569_0_0/569_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/569_0_0/569_0_0_t1+_thick_ax_user9-uva-seg-T1post-right_uvauser9_coregistered.nii.gz)

 65%|██████▍   | 1159/1793 [09:25<03:32,  2.98it/s]

Original image path: ./raw_studies/t2_thin/569_0_0/569_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/569_0_0/569_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/569_0_0/569_0_0_t2_thin_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thick_cor/569_0_0/569_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/569_0_0/569_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/569_0_0/569_0_0_t1+_thick_cor_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t2_thin/569_0_0/569_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/569_0_0/569_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/569_0_0/569_0_0_t2_thin_image_coregistered.nii.gz, nan)

 65%|██████▍   | 1161/1793 [09:25<02:17,  4.59it/s]

Original image path: ./raw_studies/t2_thin/569_1_54/569_1_54_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/569_1_54/569_1_54_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/569_1_54/569_1_54_t2_thin_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/569_1_54/569_1_54_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/569_1_54/569_1_54_t2_thin_RVS _uvauser2_coregistered.nii.gz)

 65%|██████▍   | 1162/1793 [09:25<02:33,  4.10it/s]

Original image path: ./raw_studies/t1+_thin/569_1_54/569_1_54_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/569_1_54/569_1_54_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/569_1_54/569_1_54_t1+_thin_user9-uva-seg-T1post-right_uvauser9.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/569_1_54/569_1_54_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/569_1_54/569_1_54_t1+_thin_user9-uva-seg-T1post-right_uvauser9_coregistered.nii.gz)

 65%|██████▍   | 1163/1793 [09:26<05:38,  1.86it/s]

Original image path: ./raw_studies/t2_thin/57_0_0/57_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/57_0_0/57_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/57_0_0/57_0_0_t2_thin_image_coregistered.nii.gz, nan)

 65%|██████▍   | 1164/1793 [09:27<05:22,  1.95it/s]

Original image path: ./raw_studies/t1+_thin/57_0_0/57_0_0_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/57_0_0/57_0_0_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/57_0_0/57_0_0_t1+_thin_image_coregistered.nii.gz, nan)

 65%|██████▍   | 1165/1793 [09:27<05:17,  1.98it/s]

Original image path: ./raw_studies/t1+_thin/57_1_208/57_1_208_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/57_1_208/57_1_208_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/57_1_208/57_1_208_t1+_thin_2_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/57_1_208/57_1_208_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/57_1_208/57_1_208_t1+_thin_2_uvauser4_coregistered.nii.gz)

 65%|██████▌   | 1166/1793 [09:28<05:07,  2.04it/s]

Original image path: ./raw_studies/t2_thin/57_1_208/57_1_208_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/57_1_208/57_1_208_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/57_1_208/57_1_208_t2_thin_image_coregistered.nii.gz, nan)

 65%|██████▌   | 1167/1793 [09:29<06:23,  1.63it/s]

Original image path: ./raw_studies/t1+_thin/57_2_572/57_2_572_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/57_2_572/57_2_572_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/57_2_572/57_2_572_t1+_thin_1_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/57_2_572/57_2_572_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/57_2_572/57_2_572_t1+_thin_1_uvauser4_coregistered.nii.gz)

 65%|██████▌   | 1168/1793 [09:29<05:47,  1.80it/s]

Original image path: ./raw_studies/t2_thin/57_2_572/57_2_572_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/57_2_572/57_2_572_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/57_2_572/57_2_572_t2_thin_image_coregistered.nii.gz, nan)

 65%|██████▌   | 1169/1793 [09:30<07:06,  1.46it/s]

Original image path: ./raw_studies/t1+_thick_cor/571_0_0/571_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/571_0_0/571_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/571_0_0/571_0_0_t1+_thick_cor_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/571_0_0/571_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/571_0_0/571_0_0_t1+_thick_cor_AS_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/571_0_0/571_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/571_0_0/571_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/571_0_0/571_0_0_t2_thin_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/571_0_0/571_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/571_0_0/571_0_0_t2_thin_AS_uvauser4_coregistered.nii.gz)

 65%|██████▌   | 1172/1793 [09:31<05:05,  2.03it/s]

Original image path: ./raw_studies/t1+_thick_ax/571_0_0/571_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/571_0_0/571_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/571_0_0/571_0_0_t1+_thick_ax_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/571_0_0/571_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/571_0_0/571_0_0_t1+_thick_ax_AS_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/571_1_228/571_1_228_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/571_1_228/571_1_228_t1+_thick_ax_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t1+_thick_ax/571_1_228/571_1_228_t1+_thick_ax_AS_uvauser4.nii.gz
Returning: (nan, nan)

 65%|██████▌   | 1174/1793 [09:32<03:33,  2.89it/s]

Original image path: ./raw_studies/t1+_thick_cor/571_1_228/571_1_228_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/571_1_228/571_1_228_t1+_thick_cor_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t1+_thick_cor/571_1_228/571_1_228_t1+_thick_cor_AS_uvauser4.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t2_thin/571_1_228/571_1_228_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/571_1_228/571_1_228_t2_thin_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thin/571_1_228/571_1_228_t2_thin_AX_VS_uvauser1.nii.gz
Returning: (nan, nan)

 66%|██████▌   | 1175/1793 [09:33<06:36,  1.56it/s]

Original image path: ./raw_studies/t1+_thin/571_2_1366/571_2_1366_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/571_2_1366/571_2_1366_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/571_2_1366/571_2_1366_t1+_thin_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/571_2_1366/571_2_1366_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/571_2_1366/571_2_1366_t1+_thin_tumorcore _uvauser3_coregistered.nii.gz)

 66%|██████▌   | 1176/1793 [09:33<05:45,  1.79it/s]

Original image path: ./raw_studies/t2_thin/571_2_1366/571_2_1366_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/571_2_1366/571_2_1366_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/571_2_1366/571_2_1366_t2_thin_image_coregistered.nii.gz, nan)

 66%|██████▌   | 1177/1793 [09:34<05:30,  1.86it/s]

Original image path: ./raw_studies/t1+_thin/571_2_1366/571_2_1366_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/571_2_1366/571_2_1366_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/571_2_1366/571_2_1366_t1+_thin_image_coregistered.nii.gz, nan)

 66%|██████▌   | 1178/1793 [09:34<04:53,  2.10it/s]

Original image path: ./raw_studies/t1+_thin/571_2_1366/571_2_1366_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/571_2_1366/571_2_1366_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/571_2_1366/571_2_1366_t1+_thin_image_coregistered.nii.gz, nan)

 66%|██████▌   | 1180/1793 [09:35<03:35,  2.85it/s]

Original image path: ./raw_studies/t1+_thick_cor/571_2_1366/571_2_1366_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/571_2_1366/571_2_1366_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/571_2_1366/571_2_1366_t1+_thick_cor_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t2_thick/571_2_1366/571_2_1366_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/571_2_1366/571_2_1366_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 66%|██████▌   | 1182/1793 [09:35<02:51,  3.56it/s]

Original image path: ./raw_studies/t1+_thick_ax/571_2_1366/571_2_1366_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/571_2_1366/571_2_1366_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/571_2_1366/571_2_1366_t1+_thick_ax_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thick_cor/573_0_0/573_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/573_0_0/573_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/573_0_0/573_0_0_t1+_thick_cor_image_coregistered.nii.gz, nan)

 66%|██████▌   | 1184/1793 [09:35<01:55,  5.29it/s]

Original image path: ./raw_studies/t1+_thick_ax/573_0_0/573_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/573_0_0/573_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/573_0_0/573_0_0_t1+_thick_ax_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t2_thick/573_0_0/573_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/573_0_0/573_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 66%|██████▌   | 1185/1793 [09:35<01:46,  5.70it/s]

Original image path: ./raw_studies/t2_thin/573_0_0/573_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/573_0_0/573_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/573_0_0/573_0_0_t2_thin_T2Final_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/573_0_0/573_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/573_0_0/573_0_0_t2_thin_T2Final_VS_uvauser5_coregistered.nii.gz)

 66%|██████▌   | 1186/1793 [09:36<01:58,  5.11it/s]

Original image path: ./raw_studies/t1+_thin/573_1_58/573_1_58_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/573_1_58/573_1_58_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/573_1_58/573_1_58_t1+_thin_VS_uvauser5-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/573_1_58/573_1_58_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/573_1_58/573_1_58_t1+_thin_VS_uvauser5-copy_coregistered.nii.gz)

 66%|██████▌   | 1187/1793 [09:37<04:31,  2.23it/s]

Original image path: ./raw_studies/t1+_thick_ax/573_1_58/573_1_58_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/573_1_58/573_1_58_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/573_1_58/573_1_58_t1+_thick_ax_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t2_thick/573_1_58/573_1_58_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/573_1_58/573_1_58_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 66%|██████▋   | 1189/1793 [09:37<03:19,  3.02it/s]

Original image path: ./raw_studies/t2_thin/573_1_58/573_1_58_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/573_1_58/573_1_58_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/573_1_58/573_1_58_t2_thin_image_coregistered.nii.gz, nan)

 66%|██████▋   | 1190/1793 [09:37<03:15,  3.08it/s]

Original image path: ./raw_studies/t1+_thin/573_1_58/573_1_58_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/573_1_58/573_1_58_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/573_1_58/573_1_58_t1+_thin_image_coregistered.nii.gz, nan)

 66%|██████▋   | 1191/1793 [09:39<05:08,  1.95it/s]

Original image path: ./raw_studies/t1+_thin/573_1_58/573_1_58_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/573_1_58/573_1_58_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/573_1_58/573_1_58_t1+_thin_image_coregistered.nii.gz, nan)

 66%|██████▋   | 1192/1793 [09:40<06:36,  1.52it/s]

Original image path: ./raw_studies/t1+_thick_cor/573_1_58/573_1_58_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/573_1_58/573_1_58_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/573_1_58/573_1_58_t1+_thick_cor_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thin/575_0_0/575_0_0_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/575_0_0/575_0_0_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/575_0_0/575_0_0_t1+_thin_T1_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/575_0_0/575_0_0_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/575_0_0/575_0_0_t1+_thin_T1_uvauser6_coregistered.nii.gz)

 67%|██████▋   | 1196/1793 [09:40<03:05,  3.23it/s]

Original image path: ./raw_studies/t2_thick/575_0_0/575_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/575_0_0/575_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/575_0_0/575_0_0_t2_thick_T2_uvauser6.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t2_thick/575_1_391/575_1_391_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/575_1_391/575_1_391_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thin/575_1_391/575_1_391_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/575_1_391/575_1_391_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/575_1_391/575_1_391_t1+_thin_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/575_1_391/575_1_391_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/575_1_391/575_1_391_t1+_thin_tumorcore _uvauser3_coregistered.nii.gz)

 67%|██████▋   | 1197/1793 [09:40<02:51,  3.48it/s]

Original image path: ./raw_studies/t2_thin/575_2_443/575_2_443_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/575_2_443/575_2_443_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/575_2_443/575_2_443_t2_thin_image_coregistered.nii.gz, nan)

 67%|██████▋   | 1198/1793 [09:41<02:56,  3.37it/s]

Original image path: ./raw_studies/t1+_thin/575_2_443/575_2_443_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/575_2_443/575_2_443_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/575_2_443/575_2_443_t1+_thin_T1_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/575_2_443/575_2_443_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/575_2_443/575_2_443_t1+_thin_T1_uvauser6_coregistered.nii.gz)

 67%|██████▋   | 1200/1793 [09:42<04:44,  2.09it/s]

Original image path: ./raw_studies/t2_thick/575_2_443/575_2_443_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/575_2_443/575_2_443_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/575_2_443/575_2_443_t2_thick_T2_uvauser6.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t2_thin/576_0_0/576_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/576_0_0/576_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/576_0_0/576_0_0_t2_thin_image_coregistered.nii.gz, nan)

 67%|██████▋   | 1202/1793 [09:44<06:36,  1.49it/s]

Original image path: ./raw_studies/t1+_thick_cor/576_0_0/576_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/576_0_0/576_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/576_0_0/576_0_0_t1+_thick_cor_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thick_ax/576_0_0/576_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/576_0_0/576_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/576_0_0/576_0_0_t1+_thick_ax_Manual_0_uvauser11.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/576_0_0/576_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/576_0_0/576_0_0_t1+_thick_ax_Manual_0_uvauser11_coregistered.nii.gz)

 67%|██████▋   | 1204/1793 [09:45<04:25,  2.22it/s]

Original image path: ./raw_studies/t2_thick/576_0_0/576_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/576_0_0/576_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/576_0_0/576_0_0_t2_thick_Manual_0_uvauser11.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t2_thin/576_1_172/576_1_172_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/576_1_172/576_1_172_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/576_1_172/576_1_172_t2_thin_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/576_1_172/576_1_172_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/576_1_172/576_1_172_t2_thin_AS_uvauser4_coregistered.nii.gz)

 67%|██████▋   | 1206/1793 [09:47<06:46,  1.44it/s]

Original image path: ./raw_studies/t1+_thick_cor/576_1_172/576_1_172_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/576_1_172/576_1_172_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/576_1_172/576_1_172_t1+_thick_cor_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/576_1_172/576_1_172_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/576_1_172/576_1_172_t1+_thick_cor_AS_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/576_1_172/576_1_172_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/576_1_172/576_1_172_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/576_1_172/576_1_172_t1+_thick_ax_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/576_1_172/576_1_172_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/576_1_172/576_1_172_t1+_thick_ax_AS_uvauser4_coregistered.nii.gz)

 67%|██████▋   | 1207/1793 [09:47<05:25,  1.80it/s]

Original image path: ./raw_studies/t2_thin/576_2_250/576_2_250_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/576_2_250/576_2_250_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/576_2_250/576_2_250_t2_thin_image_coregistered.nii.gz, nan)

 67%|██████▋   | 1208/1793 [09:48<04:47,  2.03it/s]

Original image path: ./raw_studies/t1+_thin/576_2_250/576_2_250_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/576_2_250/576_2_250_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/576_2_250/576_2_250_t1+_thin_manual_0_uvauser11.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/576_2_250/576_2_250_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/576_2_250/576_2_250_t1+_thin_manual_0_uvauser11_coregistered.nii.gz)

 67%|██████▋   | 1209/1793 [09:49<07:57,  1.22it/s]

Original image path: ./raw_studies/t1+_thick_cor/577_0_0/577_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/577_0_0/577_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/577_0_0/577_0_0_t1+_thick_cor_VS2_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/577_0_0/577_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/577_0_0/577_0_0_t1+_thick_cor_VS2_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/577_0_0/577_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/577_0_0/577_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/577_0_0/577_0_0_t2_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/577_0_0/577_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/577_0_0/577_0_0_t2_thin_VS_uvauser1_coregistered.nii.gz)

 68%|██████▊   | 1211/1793 [09:49<04:53,  1.98it/s]

Original image path: ./raw_studies/t1+_thick_ax/577_0_0/577_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/577_0_0/577_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/577_0_0/577_0_0_t1+_thick_ax_VS1_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/577_0_0/577_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/577_0_0/577_0_0_t1+_thick_ax_VS1_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/577_1_239/577_1_239_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/577_1_239/577_1_239_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/577_1_239/577_1_239_t1+_thick_cor_manual_10_uvauser10.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/577_1_239/577_1_239_t1+_thick_cor_image_coregistered.nii.gz, nan)

 68%|██████▊   | 1214/1793 [09:50<03:12,  3.00it/s]

Original image path: ./raw_studies/t2_thick/577_1_239/577_1_239_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/577_1_239/577_1_239_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

Original image path: ./raw_studies/t2_thin/577_1_239/577_1_239_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/577_1_239/577_1_239_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/577_1_239/577_1_239_t2_thin_ai_0_uvauser10.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/577_1_239/577_1_239_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/577_1_239/577_1_239_t2_thin_ai_0_uvauser10_coregistered.nii.gz)

 68%|██████▊   | 1215/1793 [09:51<04:45,  2.02it/s]

Original image path: ./raw_studies/t1+_thick_ax/577_1_239/577_1_239_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/577_1_239/577_1_239_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/577_1_239/577_1_239_t1+_thick_ax_manual_10_uvauser10.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/577_1_239/577_1_239_t1+_thick_ax_image_coregistered.nii.gz, nan)

 68%|██████▊   | 1216/1793 [09:51<04:21,  2.21it/s]

Original image path: ./raw_studies/t2_thin/577_2_568/577_2_568_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/577_2_568/577_2_568_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/577_2_568/577_2_568_t2_thin_image_coregistered.nii.gz, nan)

 68%|██████▊   | 1217/1793 [09:52<05:45,  1.67it/s]

Original image path: ./raw_studies/t1+_thin/577_2_568/577_2_568_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/577_2_568/577_2_568_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/577_2_568/577_2_568_t1+_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/577_2_568/577_2_568_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/577_2_568/577_2_568_t1+_thin_VS_uvauser1_coregistered.nii.gz)

 68%|██████▊   | 1218/1793 [09:53<06:39,  1.44it/s]

Original image path: ./raw_studies/t2_thin/577_3_932/577_3_932_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/577_3_932/577_3_932_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/577_3_932/577_3_932_t2_thin_t2_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/577_3_932/577_3_932_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/577_3_932/577_3_932_t2_thin_t2_uvauser6_coregistered.nii.gz)

 68%|██████▊   | 1221/1793 [09:54<04:30,  2.12it/s]

Original image path: ./raw_studies/t1+_thick_cor/577_3_932/577_3_932_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/577_3_932/577_3_932_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/577_3_932/577_3_932_t1+_thick_cor_t1COR_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/577_3_932/577_3_932_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/577_3_932/577_3_932_t1+_thick_cor_t1COR_uvauser6_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/577_3_932/577_3_932_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/577_3_932/577_3_932_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/577_3_932/577_3_932_t1+_thick_ax_T1AX_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/577_3_932/577_3_932_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/577_3_932/577_3_932_t1+_thick_ax_T1AX_uvauser6_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/577_4_1366/577_4_1366_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/577_4_1366/577_4_1366_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/577_4_1366/577_4_1366_t2_thin_T2_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/577_4_1366/577_4_1366_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/577_4_1366/577_4_1366_t2_thin_T2_uvauser6_coregistered.nii.gz)

 68%|██████▊   | 1222/1793 [09:55<05:41,  1.67it/s]

Original image path: ./raw_studies/t1+_thin/577_4_1366/577_4_1366_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/577_4_1366/577_4_1366_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/577_4_1366/577_4_1366_t1+_thin_T1_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/577_4_1366/577_4_1366_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/577_4_1366/577_4_1366_t1+_thin_T1_uvauser6_coregistered.nii.gz)

 68%|██████▊   | 1223/1793 [09:57<09:14,  1.03it/s]

Original image path: ./raw_studies/t2_thin/577_5_2563/577_5_2563_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/577_5_2563/577_5_2563_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/577_5_2563/577_5_2563_t2_thin_image_coregistered.nii.gz, nan)

 68%|██████▊   | 1226/1793 [09:59<05:35,  1.69it/s]

Original image path: ./raw_studies/t2_thin/578_0_0/578_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/578_0_0/578_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/578_0_0/578_0_0_t2_thin_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thick_cor/578_0_0/578_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/578_0_0/578_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/578_0_0/578_0_0_t1+_thick_cor_manual_0_uvauser8.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/578_0_0/578_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/578_0_0/578_0_0_t1+_thick_cor_manual_0_uvauser8_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/578_0_0/578_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/578_0_0/578_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/578_0_0/578_0_0_t1+_thick_ax_image_coregistered.nii.gz, nan)

 68%|██████▊   | 1228/1793 [09:59<03:41,  2.55it/s]

Original image path: ./raw_studies/t2_thin/578_0_0/578_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/578_0_0/578_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/578_0_0/578_0_0_t2_thin_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thick_cor/578_1_317/578_1_317_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/578_1_317/578_1_317_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/578_1_317/578_1_317_t1+_thick_cor_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/578_1_317/578_1_317_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/578_1_317/578_1_317_t1+_thick_cor_RVS _uvauser2_coregistered.nii.gz)

 69%|██████▊   | 1230/1793 [09:59<02:54,  3.22it/s]

Original image path: ./raw_studies/t1+_thick_ax/578_1_317/578_1_317_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/578_1_317/578_1_317_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/578_1_317/578_1_317_t1+_thick_ax_manual_10_uvauser10.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/578_1_317/578_1_317_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/578_1_317/578_1_317_t1+_thick_ax_manual_10_uvauser10_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/578_1_317/578_1_317_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/578_1_317/578_1_317_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/578_1_317/578_1_317_t2_thin_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/578_1_317/578_1_317_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/578_1_317/578_1_317_t2_thin_RVS _uvauser2_coregistered.nii.gz)

 69%|██████▊   | 1231/1793 [10:00<04:55,  1.90it/s]

Original image path: ./raw_studies/t1+_thick_ax/579_0_0/579_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/579_0_0/579_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/579_0_0/579_0_0_t1+_thick_ax_manual_10_uvauser10.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/579_0_0/579_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/579_0_0/579_0_0_t1+_thick_ax_manual_10_uvauser10_coregistered.nii.gz)

 69%|██████▊   | 1232/1793 [10:01<04:11,  2.23it/s]

Original image path: ./raw_studies/t2_thin/579_0_0/579_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/579_0_0/579_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/579_0_0/579_0_0_t2_thin_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/579_0_0/579_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/579_0_0/579_0_0_t2_thin_LVS _uvauser2_coregistered.nii.gz)

 69%|██████▉   | 1234/1793 [10:01<03:25,  2.72it/s]

Original image path: ./raw_studies/t1+_thick_cor/579_0_0/579_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/579_0_0/579_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/579_0_0/579_0_0_t1+_thick_cor_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/579_0_0/579_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/579_0_0/579_0_0_t1+_thick_cor_LVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/579_0_0/579_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/579_0_0/579_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/579_0_0/579_0_0_t1+_thick_ax_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/579_0_0/579_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/579_0_0/579_0_0_t1+_thick_ax_LVS _uvauser2_coregistered.nii.gz)

 69%|██████▉   | 1236/1793 [10:02<02:41,  3.45it/s]

Original image path: ./raw_studies/t2_thick/579_1_198/579_1_198_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/579_1_198/579_1_198_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thick_ax/579_1_198/579_1_198_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/579_1_198/579_1_198_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/579_1_198/579_1_198_t1+_thick_ax_T1AX_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/579_1_198/579_1_198_t1+_thick_ax_image_coregistered.nii.gz, nan)

 69%|██████▉   | 1238/1793 [10:02<02:12,  4.19it/s]

Original image path: ./raw_studies/t1+_thick_cor/579_1_198/579_1_198_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/579_1_198/579_1_198_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/579_1_198/579_1_198_t1+_thick_cor_t1cor_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/579_1_198/579_1_198_t1+_thick_cor_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t2_thin/579_1_198/579_1_198_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/579_1_198/579_1_198_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/579_1_198/579_1_198_t2_thin_T2_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/579_1_198/579_1_198_t2_thin_image_coregistered.nii.gz, nan)

 69%|██████▉   | 1240/1793 [10:04<04:32,  2.03it/s]

Original image path: ./raw_studies/t1+_thick_ax/579_2_697/579_2_697_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/579_2_697/579_2_697_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/579_2_697/579_2_697_t1+_thick_ax_manual_0_uvauser13.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/579_2_697/579_2_697_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/579_2_697/579_2_697_t1+_thick_ax_manual_0_uvauser13_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/579_2_697/579_2_697_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/579_2_697/579_2_697_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/579_2_697/579_2_697_t2_thin_image_coregistered.nii.gz, nan)

 69%|██████▉   | 1241/1793 [10:05<06:41,  1.37it/s]

Original image path: ./raw_studies/t1+_thick_cor/579_2_697/579_2_697_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/579_2_697/579_2_697_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/579_2_697/579_2_697_t1+_thick_cor_manual_0_uvauser13.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/579_2_697/579_2_697_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/579_2_697/579_2_697_t1+_thick_cor_manual_0_uvauser13_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thin/579_3_1222/579_3_1222_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/579_3_1222/579_3_1222_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/579_3_1222/579_3_1222_t1+_thin_VS_uvauser5-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/579_3_1222/579_3_1222_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/579_3_1222/579_3_1222_t1+_thin_VS_uvauser5-copy_coregistered.nii.gz)

 69%|██████▉   | 1243/1793 [10:06<04:48,  1.91it/s]

Original image path: ./raw_studies/t2_thin/579_3_1222/579_3_1222_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/579_3_1222/579_3_1222_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/579_3_1222/579_3_1222_t2_thin_image_coregistered.nii.gz, nan)

 69%|██████▉   | 1244/1793 [10:07<06:18,  1.45it/s]

Original image path: ./raw_studies/t2_thin/579_4_1600/579_4_1600_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/579_4_1600/579_4_1600_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/579_4_1600/579_4_1600_t2_thin_T2_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/579_4_1600/579_4_1600_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/579_4_1600/579_4_1600_t2_thin_T2_uvauser6_coregistered.nii.gz)

 69%|██████▉   | 1245/1793 [10:08<07:11,  1.27it/s]

Original image path: ./raw_studies/t1+_thin/579_4_1600/579_4_1600_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/579_4_1600/579_4_1600_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/579_4_1600/579_4_1600_t1+_thin_T1_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/579_4_1600/579_4_1600_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/579_4_1600/579_4_1600_t1+_thin_T1_uvauser6_coregistered.nii.gz)

 69%|██████▉   | 1246/1793 [10:08<06:29,  1.41it/s]

Original image path: ./raw_studies/t2_thin/579_5_2048/579_5_2048_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/579_5_2048/579_5_2048_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/579_5_2048/579_5_2048_t2_thin_image_coregistered.nii.gz, nan)

 70%|██████▉   | 1247/1793 [10:09<07:23,  1.23it/s]

Original image path: ./raw_studies/t1+_thin/579_5_2048/579_5_2048_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/579_5_2048/579_5_2048_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/579_5_2048/579_5_2048_t1+_thin_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/579_5_2048/579_5_2048_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/579_5_2048/579_5_2048_t1+_thin_AS_uvauser4_coregistered.nii.gz)

 70%|██████▉   | 1248/1793 [10:10<06:32,  1.39it/s]

Original image path: ./raw_studies/t1+_thin/58_0_0/58_0_0_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/58_0_0/58_0_0_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/58_0_0/58_0_0_t1+_thin_image_coregistered.nii.gz, nan)

 70%|██████▉   | 1249/1793 [10:11<08:21,  1.08it/s]

Original image path: ./raw_studies/t2_thick/58_0_0/58_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/58_0_0/58_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 70%|██████▉   | 1251/1793 [10:12<05:55,  1.53it/s]

Original image path: ./raw_studies/t1+_thick_ax/58_1_214/58_1_214_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/58_1_214/58_1_214_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/58_1_214/58_1_214_t1+_thick_ax_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/58_1_214/58_1_214_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/58_1_214/58_1_214_t1+_thick_ax_VS_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/58_1_214/58_1_214_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/58_1_214/58_1_214_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/58_1_214/58_1_214_t1+_thick_cor_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/58_1_214/58_1_214_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/58_1_214/58_1_214_t1+_thick_cor_VS_uvauser1_coregistered.nii.gz)

 70%|██████▉   | 1252/1793 [10:12<04:34,  1.97it/s]

Original image path: ./raw_studies/t2_thin/58_1_214/58_1_214_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/58_1_214/58_1_214_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/58_1_214/58_1_214_t2_thin_T2_VS_uvauser1-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/58_1_214/58_1_214_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/58_1_214/58_1_214_t2_thin_T2_VS_uvauser1-copy_coregistered.nii.gz)

 70%|██████▉   | 1255/1793 [10:14<03:32,  2.53it/s]

Original image path: ./raw_studies/t1+_thick_cor/58_2_532/58_2_532_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/58_2_532/58_2_532_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/58_2_532/58_2_532_t1+_thick_cor_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/58_2_532/58_2_532_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/58_2_532/58_2_532_t1+_thick_cor_AS_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/58_2_532/58_2_532_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/58_2_532/58_2_532_t2_thin_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thin/58_2_532/58_2_532_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/58_2_532/58_2_532_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/58_2_532/58_2_532_t1+_thin_AS2_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/58_2_532/58_2_532_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/58_2_532/58_2_532_t1+_thin_AS2_uvauser4_coregistered.nii.gz)

 70%|███████   | 1256/1793 [10:14<04:30,  1.98it/s]

Original image path: ./raw_studies/t1+_thick_ax/58_2_532/58_2_532_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/58_2_532/58_2_532_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/58_2_532/58_2_532_t1+_thick_ax_AS1_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/58_2_532/58_2_532_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/58_2_532/58_2_532_t1+_thick_ax_AS1_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/580_0_0/580_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/580_0_0/580_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/580_0_0/580_0_0_t1+_thick_cor_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/580_0_0/580_0_0_t1+_thick_cor_image_coregistered.nii.gz, nan)

 70%|███████   | 1258/1793 [10:15<03:05,  2.88it/s]

Original image path: ./raw_studies/t1+_thick_ax/580_0_0/580_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/580_0_0/580_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/580_0_0/580_0_0_t1+_thick_ax_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/580_0_0/580_0_0_t1+_thick_ax_image_coregistered.nii.gz, nan)

 70%|███████   | 1260/1793 [10:15<02:29,  3.57it/s]

Original image path: ./raw_studies/t2_thin/580_0_0/580_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/580_0_0/580_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/580_0_0/580_0_0_t2_thin_AX_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/580_0_0/580_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/580_0_0/580_0_0_t2_thin_AX_VS_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thin/580_1_91/580_1_91_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/580_1_91/580_1_91_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/580_1_91/580_1_91_t1+_thin_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/580_1_91/580_1_91_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/580_1_91/580_1_91_t1+_thin_tumorcore _uvauser3_coregistered.nii.gz)

 70%|███████   | 1261/1793 [10:16<04:22,  2.03it/s]

Original image path: ./raw_studies/t1+_thin/580_1_91/580_1_91_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/580_1_91/580_1_91_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/580_1_91/580_1_91_t1+_thin_image_coregistered.nii.gz, nan)

 70%|███████   | 1262/1793 [10:17<05:48,  1.53it/s]

Original image path: ./raw_studies/t2_thin/580_1_91/580_1_91_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/580_1_91/580_1_91_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/580_1_91/580_1_91_t2_thin_image_coregistered.nii.gz, nan)

 70%|███████   | 1263/1793 [10:18<04:53,  1.81it/s]

Original image path: ./raw_studies/t2_thin/581_0_0/581_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/581_0_0/581_0_0_t2_thin_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 70%|███████   | 1264/1793 [10:18<05:31,  1.60it/s]

Original image path: ./raw_studies/t1+_thin/581_0_0/581_0_0_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/581_0_0/581_0_0_t1+_thin_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t1+_thin/581_0_0/581_0_0_t1+_thin_VS_uvauser1.nii.gz
Returning: (nan, nan)

 71%|███████   | 1265/1793 [10:19<04:38,  1.90it/s]

Original image path: ./raw_studies/t1+_thin/581_1_152/581_1_152_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/581_1_152/581_1_152_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/581_1_152/581_1_152_t1+_thin_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/581_1_152/581_1_152_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/581_1_152/581_1_152_t1+_thin_VS_uvauser5_coregistered.nii.gz)

 71%|███████   | 1266/1793 [10:19<04:03,  2.16it/s]

Original image path: ./raw_studies/t2_thin/581_1_152/581_1_152_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/581_1_152/581_1_152_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/581_1_152/581_1_152_t2_thin_image_coregistered.nii.gz, nan)

 71%|███████   | 1267/1793 [10:20<05:31,  1.58it/s]

Original image path: ./raw_studies/t2_thin/581_2_440/581_2_440_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/581_2_440/581_2_440_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/581_2_440/581_2_440_t2_thin_T2Final_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/581_2_440/581_2_440_t2_thin_image_coregistered.nii.gz, nan)

 71%|███████   | 1270/1793 [10:21<04:18,  2.02it/s]

Original image path: ./raw_studies/t1+_thick_ax/581_2_440/581_2_440_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/581_2_440/581_2_440_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/581_2_440/581_2_440_t1+_thick_ax_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/581_2_440/581_2_440_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/581_2_440/581_2_440_t1+_thick_ax_VS_uvauser5_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/581_2_440/581_2_440_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/581_2_440/581_2_440_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/581_2_440/581_2_440_t1+_thick_cor_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/581_2_440/581_2_440_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/581_2_440/581_2_440_t1+_thick_cor_VS_uvauser5_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/582_0_0/582_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/582_0_0/582_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/582_0_0/582_0_0_t1+_thick_cor_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/582_0_0/582_0_0_t1+_thick_cor_image_coregistered.nii.gz, nan)

 71%|███████   | 1271/1793 [10:22<04:20,  2.01it/s]

Original image path: ./raw_studies/t2_thin/582_0_0/582_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/582_0_0/582_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/582_0_0/582_0_0_t2_thin_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/582_0_0/582_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/582_0_0/582_0_0_t2_thin_RVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thick/582_0_0/582_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/582_0_0/582_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/582_0_0/582_0_0_t2_thick_user9-uva-seg-T2-right_uvauser9.nii.gz
Returning: (nan, nan)

 71%|███████   | 1273/1793 [10:23<03:30,  2.47it/s]

Original image path: ./raw_studies/t1+_thick_ax/582_0_0/582_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/582_0_0/582_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/582_0_0/582_0_0_t1+_thick_ax_user9-uva-seg-T1post-right_uvauser9.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/582_0_0/582_0_0_t1+_thick_ax_image_coregistered.nii.gz, nan)

 71%|███████   | 1275/1793 [10:23<02:43,  3.17it/s]

Original image path: ./raw_studies/t1+_thick_cor/582_1_185/582_1_185_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/582_1_185/582_1_185_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/582_1_185/582_1_185_t1+_thick_cor_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/582_1_185/582_1_185_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/582_1_185/582_1_185_t1+_thick_cor_VS_uvauser5_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/582_1_185/582_1_185_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/582_1_185/582_1_185_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/582_1_185/582_1_185_t1+_thick_ax_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/582_1_185/582_1_185_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/582_1_185/582_1_185_t1+_thick_ax_VS_uvauser5_coregistered.nii.gz)

 71%|███████   | 1276/1793 [10:23<02:20,  3.68it/s]

Original image path: ./raw_studies/t2_thin/582_1_185/582_1_185_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/582_1_185/582_1_185_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/582_1_185/582_1_185_t2_thin_T2Final_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/582_1_185/582_1_185_t2_thin_image_coregistered.nii.gz, nan)

 71%|███████▏  | 1278/1793 [10:25<03:45,  2.28it/s]

Original image path: ./raw_studies/t1+_thick_ax/582_2_556/582_2_556_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/582_2_556/582_2_556_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/582_2_556/582_2_556_t1+_thick_ax_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thick_cor/582_2_556/582_2_556_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/582_2_556/582_2_556_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/582_2_556/582_2_556_t1+_thick_cor_image_coregistered.nii.gz, nan)

 71%|███████▏  | 1279/1793 [10:25<03:06,  2.75it/s]

Original image path: ./raw_studies/t2_thin/582_2_556/582_2_556_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/582_2_556/582_2_556_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/582_2_556/582_2_556_t2_thin_T2Final_VS_uvauser5-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/582_2_556/582_2_556_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/582_2_556/582_2_556_t2_thin_T2Final_VS_uvauser5-copy_coregistered.nii.gz)

 72%|███████▏  | 1282/1793 [10:26<02:54,  2.93it/s]

Original image path: ./raw_studies/t1+_thick_ax/582_3_945/582_3_945_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/582_3_945/582_3_945_t1+_thick_ax_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t1+_thick_ax/582_3_945/582_3_945_t1+_thick_ax_tumorcore _uvauser3.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thick_cor/582_3_945/582_3_945_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/582_3_945/582_3_945_t1+_thick_cor_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

Original image path: ./raw_studies/t2_thin/582_3_945/582_3_945_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/582_3_945/582_3_945_t2_thin_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thin/582_3_945/582_3_945_t2_thin_T2Final_VS_uvauser5.nii.gz
Returning: (nan, nan)

 72%|███████▏  | 1284/1793 [10:27<03:58,  2.13it/s]

Original image path: ./raw_studies/t1+_thick_ax/583_0_0/583_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/583_0_0/583_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/583_0_0/583_0_0_t1+_thick_ax_T1AX_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/583_0_0/583_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/583_0_0/583_0_0_t1+_thick_ax_T1AX_uvauser6_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/583_0_0/583_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/583_0_0/583_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/583_0_0/583_0_0_t2_thin_T2_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/583_0_0/583_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/583_0_0/583_0_0_t2_thin_T2_uvauser6_coregistered.nii.gz)

 72%|███████▏  | 1286/1793 [10:28<03:11,  2.64it/s]

Original image path: ./raw_studies/t1+_thick_cor/583_0_0/583_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/583_0_0/583_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/583_0_0/583_0_0_t1+_thick_cor_T1COR_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/583_0_0/583_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/583_0_0/583_0_0_t1+_thick_cor_T1COR_uvauser6_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/583_1_86/583_1_86_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/583_1_86/583_1_86_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/583_1_86/583_1_86_t1+_thick_cor_manual_uvauser12_uvauser12.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/583_1_86/583_1_86_t1+_thick_cor_image_coregistered.nii.gz, nan)

 72%|███████▏  | 1287/1793 [10:28<03:09,  2.67it/s]

Original image path: ./raw_studies/t1+_thick_ax/583_1_86/583_1_86_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/583_1_86/583_1_86_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/583_1_86/583_1_86_t1+_thick_ax_manual_uvauser12_uvauser12.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/583_1_86/583_1_86_t1+_thick_ax_image_coregistered.nii.gz, nan)

 72%|███████▏  | 1288/1793 [10:29<02:56,  2.85it/s]

Original image path: ./raw_studies/t2_thin/583_1_86/583_1_86_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/583_1_86/583_1_86_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/583_1_86/583_1_86_t2_thin_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/583_1_86/583_1_86_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/583_1_86/583_1_86_t2_thin_LVS _uvauser2_coregistered.nii.gz)

 72%|███████▏  | 1289/1793 [10:29<02:47,  3.00it/s]

Original image path: ./raw_studies/t2_thin/583_2_278/583_2_278_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/583_2_278/583_2_278_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/583_2_278/583_2_278_t2_thin_T2_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/583_2_278/583_2_278_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/583_2_278/583_2_278_t2_thin_T2_uvauser6_coregistered.nii.gz)

 72%|███████▏  | 1292/1793 [10:30<02:18,  3.61it/s]

Original image path: ./raw_studies/t1+_thick_ax/583_2_278/583_2_278_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/583_2_278/583_2_278_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/583_2_278/583_2_278_t1+_thick_ax_T1AX_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/583_2_278/583_2_278_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/583_2_278/583_2_278_t1+_thick_ax_T1AX_uvauser6_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/583_2_278/583_2_278_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/583_2_278/583_2_278_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/583_2_278/583_2_278_t1+_thick_cor_T1COR_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/583_2_278/583_2_278_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/583_2_278/583_2_278_t1+_thick_cor_T1COR_uvauser6_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/583_3_460/583_3_460_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/583_3_460/583_3_460_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/583_3_460/583_3_460_t2_thin_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/583_3_460/583_3_460_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/583_3_460/583_3_460_t2_thin_LVS _uvauser2_coregistered.nii.gz)

 72%|███████▏  | 1294/1793 [10:31<03:14,  2.56it/s]

Original image path: ./raw_studies/t1+_thick_ax/583_3_460/583_3_460_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/583_3_460/583_3_460_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/583_3_460/583_3_460_t1+_thick_ax_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/583_3_460/583_3_460_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/583_3_460/583_3_460_t1+_thick_ax_LVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/583_3_460/583_3_460_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/583_3_460/583_3_460_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/583_3_460/583_3_460_t1+_thick_cor_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/583_3_460/583_3_460_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/583_3_460/583_3_460_t1+_thick_cor_LVS _uvauser2_coregistered.nii.gz)

 72%|███████▏  | 1295/1793 [10:31<02:42,  3.06it/s]

Original image path: ./raw_studies/t1+_thick_ax/584_0_0/584_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/584_0_0/584_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/584_0_0/584_0_0_t1+_thick_ax_VS2_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/584_0_0/584_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/584_0_0/584_0_0_t1+_thick_ax_VS2_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/584_0_0/584_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/584_0_0/584_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/584_0_0/584_0_0_t2_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/584_0_0/584_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/584_0_0/584_0_0_t2_thin_VS_uvauser1_coregistered.nii.gz)

 72%|███████▏  | 1297/1793 [10:32<02:07,  3.88it/s]

Original image path: ./raw_studies/t1+_thick_cor/584_0_0/584_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/584_0_0/584_0_0_t1+_thick_cor_image_coregistered.nii.gz

 72%|███████▏  | 1298/1793 [10:32<02:15,  3.65it/s]

  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/584_0_0/584_0_0_t1+_thick_cor_VS2_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/584_0_0/584_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/584_0_0/584_0_0_t1+_thick_cor_VS2_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/584_1_297/584_1_297_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/584_1_297/584_1_297_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/584_1_297/584_1_297_t2_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/584_1_297/584_1_297_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/584_1_297/584_1_297_t2_thin_VS_uvauser1_coregistered.nii.gz)

 73%|███████▎  | 1300/1793 [10:33<03:34,  2.30it/s]

Original image path: ./raw_studies/t1+_thick_cor/584_1_297/584_1_297_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/584_1_297/584_1_297_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/584_1_297/584_1_297_t1+_thick_cor_VS2_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/584_1_297/584_1_297_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/584_1_297/584_1_297_t1+_thick_cor_VS2_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/584_1_297/584_1_297_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/584_1_297/584_1_297_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/584_1_297/584_1_297_t1+_thick_ax_VS1_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/584_1_297/584_1_297_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/584_1_297/584_1_297_t1+_thick_ax_VS1_uvauser1_coregistered.nii.gz)

 73%|███████▎  | 1302/1793 [10:34<02:33,  3.19it/s]

Original image path: ./raw_studies/t1+_thick_ax/584_2_507/584_2_507_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/584_2_507/584_2_507_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/584_2_507/584_2_507_t1+_thick_ax_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/584_2_507/584_2_507_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/584_2_507/584_2_507_t1+_thick_ax_LVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/584_2_507/584_2_507_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/584_2_507/584_2_507_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/584_2_507/584_2_507_t1+_thick_cor_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/584_2_507/584_2_507_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/584_2_507/584_2_507_t1+_thick_cor_LVS _uvauser2_coregistered.nii.gz)

 73%|███████▎  | 1303/1793 [10:34<02:20,  3.48it/s]

Original image path: ./raw_studies/t2_thin/584_2_507/584_2_507_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/584_2_507/584_2_507_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/584_2_507/584_2_507_t2_thin_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/584_2_507/584_2_507_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/584_2_507/584_2_507_t2_thin_LVS _uvauser2_coregistered.nii.gz)

 73%|███████▎  | 1304/1793 [10:35<04:14,  1.92it/s]

Original image path: ./raw_studies/t2_thin/585_0_0/585_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/585_0_0/585_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/585_0_0/585_0_0_t2_thin_T2Final_VS_uvauser5-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/585_0_0/585_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/585_0_0/585_0_0_t2_thin_T2Final_VS_uvauser5-copy_coregistered.nii.gz)

 73%|███████▎  | 1306/1793 [10:36<03:23,  2.39it/s]

Original image path: ./raw_studies/t1+_thick_ax/585_0_0/585_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/585_0_0/585_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/585_0_0/585_0_0_t1+_thick_ax_T1AX_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/585_0_0/585_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/585_0_0/585_0_0_t1+_thick_ax_T1AX_uvauser6_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/585_0_0/585_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/585_0_0/585_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/585_0_0/585_0_0_t1+_thick_cor_T1COR_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/585_0_0/585_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/585_0_0/585_0_0_t1+_thick_cor_T1COR_uvauser6_coregistered.nii.gz)

 73%|███████▎  | 1307/1793 [10:36<02:50,  2.85it/s]

Original image path: ./raw_studies/t1+_thick_ax/585_1_280/585_1_280_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/585_1_280/585_1_280_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/585_1_280/585_1_280_t1+_thick_ax_T1AX_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/585_1_280/585_1_280_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/585_1_280/585_1_280_t1+_thick_ax_T1AX_uvauser6_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/585_1_280/585_1_280_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/585_1_280/585_1_280_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/585_1_280/585_1_280_t2_thin_T2_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/585_1_280/585_1_280_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/585_1_280/585_1_280_t2_thin_T2_uvauser6_coregistered.nii.gz)

 73%|███████▎  | 1310/1793 [10:37<02:56,  2.73it/s]

Original image path: ./raw_studies/t1+_thick_cor/585_1_280/585_1_280_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/585_1_280/585_1_280_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/585_1_280/585_1_280_t1+_thick_cor_T1COR_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/585_1_280/585_1_280_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/585_1_280/585_1_280_t1+_thick_cor_T1COR_uvauser6_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/585_2_637/585_2_637_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/585_2_637/585_2_637_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/585_2_637/585_2_637_t2_thin_T2Final_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/585_2_637/585_2_637_t2_thin_image_coregistered.nii.gz, nan)

 73%|███████▎  | 1312/1793 [10:39<04:12,  1.90it/s]

Original image path: ./raw_studies/t1+_thick_ax/585_2_637/585_2_637_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/585_2_637/585_2_637_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/585_2_637/585_2_637_t1+_thick_ax_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/585_2_637/585_2_637_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/585_2_637/585_2_637_t1+_thick_ax_VS_uvauser5_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/585_2_637/585_2_637_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/585_2_637/585_2_637_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/585_2_637/585_2_637_t1+_thick_cor_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/585_2_637/585_2_637_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/585_2_637/585_2_637_t1+_thick_cor_VS_uvauser5_coregistered.nii.gz)

 73%|███████▎  | 1313/1793 [10:39<03:32,  2.26it/s]

Original image path: ./raw_studies/t2_thin/585_3_1003/585_3_1003_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/585_3_1003/585_3_1003_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/585_3_1003/585_3_1003_t2_thin_AX_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/585_3_1003/585_3_1003_t2_thin_image_coregistered.nii.gz, nan)

 73%|███████▎  | 1314/1793 [10:40<05:50,  1.37it/s]

Original image path: ./raw_studies/t1+_thick_cor/585_3_1003/585_3_1003_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/585_3_1003/585_3_1003_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/585_3_1003/585_3_1003_t1+_thick_cor_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/585_3_1003/585_3_1003_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/585_3_1003/585_3_1003_t1+_thick_cor_AS_uvauser4_coregistered.nii.gz)

 73%|███████▎  | 1315/1793 [10:41<04:40,  1.70it/s]

Original image path: ./raw_studies/t1+_thick_ax/585_3_1003/585_3_1003_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/585_3_1003/585_3_1003_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/585_3_1003/585_3_1003_t1+_thick_ax_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/585_3_1003/585_3_1003_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/585_3_1003/585_3_1003_t1+_thick_ax_AS_uvauser4_coregistered.nii.gz)

 73%|███████▎  | 1317/1793 [10:41<03:05,  2.56it/s]

Original image path: ./raw_studies/t1+_thick_cor/585_4_1348/585_4_1348_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/585_4_1348/585_4_1348_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/585_4_1348/585_4_1348_t1+_thick_cor_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/585_4_1348/585_4_1348_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/585_4_1348/585_4_1348_t1+_thick_cor_LVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/585_4_1348/585_4_1348_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/585_4_1348/585_4_1348_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/585_4_1348/585_4_1348_t2_thin_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/585_4_1348/585_4_1348_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/585_4_1348/585_4_1348_t2_thin_LVS _uvauser2_coregistered.nii.gz)

 74%|███████▎  | 1318/1793 [10:42<04:44,  1.67it/s]

Original image path: ./raw_studies/t1+_thin/585_4_1348/585_4_1348_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/585_4_1348/585_4_1348_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/585_4_1348/585_4_1348_t1+_thin_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/585_4_1348/585_4_1348_t1+_thin_image_coregistered.nii.gz, nan)

 74%|███████▎  | 1319/1793 [10:43<04:55,  1.61it/s]

Original image path: ./raw_studies/t1+_thin/587_0_0/587_0_0_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/587_0_0/587_0_0_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/587_0_0/587_0_0_t1+_thin_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/587_0_0/587_0_0_t1+_thin_image_coregistered.nii.gz, nan)

 74%|███████▎  | 1320/1793 [10:44<07:14,  1.09it/s]

Original image path: ./raw_studies/t2_thick/587_0_0/587_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/587_0_0/587_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/587_0_0/587_0_0_t2_thick_RVS _uvauser2.nii.gz
Returning: (nan, nan)

 74%|███████▎  | 1321/1793 [10:45<05:57,  1.32it/s]

Original image path: ./raw_studies/t1+_thin/587_0_0/587_0_0_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/587_0_0/587_0_0_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/587_0_0/587_0_0_t1+_thin_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/587_0_0/587_0_0_t1+_thin_image_coregistered.nii.gz, nan)

 74%|███████▎  | 1322/1793 [10:46<07:52,  1.00s/it]

Original image path: ./raw_studies/t1+_thin/587_1_340/587_1_340_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/587_1_340/587_1_340_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/587_1_340/587_1_340_t1+_thin_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/587_1_340/587_1_340_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/587_1_340/587_1_340_t1+_thin_VS_uvauser5_coregistered.nii.gz)

 74%|███████▍  | 1323/1793 [10:47<06:41,  1.17it/s]

Original image path: ./raw_studies/t2_thin/587_1_340/587_1_340_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/587_1_340/587_1_340_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/587_1_340/587_1_340_t2_thin_image_coregistered.nii.gz, nan)

 74%|███████▍  | 1324/1793 [10:47<05:55,  1.32it/s]

Original image path: ./raw_studies/t1+_thick_ax/588_1_1/588_1_1_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/588_1_1/588_1_1_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/588_1_1/588_1_1_t1+_thick_ax_manual_0_uvauser13.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/588_1_1/588_1_1_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/588_1_1/588_1_1_t1+_thick_ax_manual_0_uvauser13_coregistered.nii.gz)

 74%|███████▍  | 1325/1793 [10:48<04:58,  1.57it/s]

Original image path: ./raw_studies/t1+_thick_cor/589_0_0/589_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/589_0_0/589_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/589_0_0/589_0_0_t1+_thick_cor_T1COR_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/589_0_0/589_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/589_0_0/589_0_0_t1+_thick_cor_T1COR_uvauser6_coregistered.nii.gz)

 74%|███████▍  | 1326/1793 [10:48<04:03,  1.92it/s]

Original image path: ./raw_studies/t2_thin/589_0_0/589_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/589_0_0/589_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/589_0_0/589_0_0_t2_thin_T2_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/589_0_0/589_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/589_0_0/589_0_0_t2_thin_T2_uvauser6_coregistered.nii.gz)

 74%|███████▍  | 1328/1793 [10:50<04:37,  1.67it/s]

Original image path: ./raw_studies/t1+_thick_ax/589_0_0/589_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/589_0_0/589_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/589_0_0/589_0_0_t1+_thick_ax_T1AX_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/589_0_0/589_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/589_0_0/589_0_0_t1+_thick_ax_T1AX_uvauser6_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/589_1_223/589_1_223_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/589_1_223/589_1_223_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/589_1_223/589_1_223_t2_thin_AX_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/589_1_223/589_1_223_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/589_1_223/589_1_223_t2_thin_AX_VS_uvauser1_coregistered.nii.gz)

 74%|███████▍  | 1331/1793 [10:51<03:29,  2.21it/s]

Original image path: ./raw_studies/t1+_thick_cor/589_1_223/589_1_223_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/589_1_223/589_1_223_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/589_1_223/589_1_223_t1+_thick_cor_T1COR_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/589_1_223/589_1_223_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/589_1_223/589_1_223_t1+_thick_cor_T1COR_uvauser6_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/589_1_223/589_1_223_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/589_1_223/589_1_223_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/589_1_223/589_1_223_t1+_thick_ax_T1AX_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/589_1_223/589_1_223_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/589_1_223/589_1_223_t1+_thick_ax_T1AX_uvauser6_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/590_0_0/590_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/590_0_0/590_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/590_0_0/590_0_0_t1+_thick_ax_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/590_0_0/590_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/590_0_0/590_0_0_t1+_thick_ax_RVS _uvauser2_coregistered.nii.gz)

 74%|███████▍  | 1333/1793 [10:51<02:31,  3.04it/s]

Original image path: ./raw_studies/t1+_thick_cor/590_0_0/590_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/590_0_0/590_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/590_0_0/590_0_0_t1+_thick_cor_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/590_0_0/590_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/590_0_0/590_0_0_t1+_thick_cor_RVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/590_0_0/590_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/590_0_0/590_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/590_0_0/590_0_0_t2_thin_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/590_0_0/590_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/590_0_0/590_0_0_t2_thin_RVS _uvauser2_coregistered.nii.gz)

 74%|███████▍  | 1334/1793 [10:52<03:55,  1.95it/s]

Original image path: ./raw_studies/t1+_thick_cor/590_1_179/590_1_179_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/590_1_179/590_1_179_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/590_1_179/590_1_179_t1+_thick_cor_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/590_1_179/590_1_179_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/590_1_179/590_1_179_t1+_thick_cor_RVS _uvauser2_coregistered.nii.gz)

 75%|███████▍  | 1336/1793 [10:53<02:52,  2.65it/s]

Original image path: ./raw_studies/t1+_thick_ax/590_1_179/590_1_179_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/590_1_179/590_1_179_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/590_1_179/590_1_179_t1+_thick_ax_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/590_1_179/590_1_179_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/590_1_179/590_1_179_t1+_thick_ax_RVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/590_1_179/590_1_179_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/590_1_179/590_1_179_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/590_1_179/590_1_179_t2_thin_RVS _uvauser2-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/590_1_179/590_1_179_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/590_1_179/590_1_179_t2_thin_RVS _uvauser2-copy_coregistered.nii.gz)

 75%|███████▍  | 1337/1793 [10:54<04:34,  1.66it/s]

Original image path: ./raw_studies/t2_thin/590_2_539/590_2_539_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/590_2_539/590_2_539_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/590_2_539/590_2_539_t2_thin_image_coregistered.nii.gz, nan)

 75%|███████▍  | 1339/1793 [10:55<04:12,  1.80it/s]

Original image path: ./raw_studies/t1+_thick_cor/590_2_539/590_2_539_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/590_2_539/590_2_539_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/590_2_539/590_2_539_t1+_thick_cor_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thick_ax/590_2_539/590_2_539_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/590_2_539/590_2_539_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/590_2_539/590_2_539_t1+_thick_ax_image_coregistered.nii.gz, nan)

 75%|███████▍  | 1341/1793 [10:55<02:40,  2.82it/s]

Original image path: ./raw_studies/t1+_thick_cor/592_0_0/592_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/592_0_0/592_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/592_0_0/592_0_0_t1+_thick_cor_T1COR_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/592_0_0/592_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/592_0_0/592_0_0_t1+_thick_cor_T1COR_uvauser6_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/592_0_0/592_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/592_0_0/592_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/592_0_0/592_0_0_t1+_thick_ax_T1AX_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/592_0_0/592_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/592_0_0/592_0_0_t1+_thick_ax_T1AX_uvauser6_coregistered.nii.gz)

 75%|███████▍  | 1342/1793 [10:56<02:12,  3.41it/s]

Original image path: ./raw_studies/t2_thick/592_0_0/592_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/592_0_0/592_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/592_0_0/592_0_0_t2_thick_T2_uvauser6.nii.gz
Returning: (nan, nan)

 75%|███████▍  | 1343/1793 [10:56<02:30,  2.99it/s]

Original image path: ./raw_studies/t2_thin/592_1_253/592_1_253_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/592_1_253/592_1_253_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/592_1_253/592_1_253_t2_thin_image_coregistered.nii.gz, nan)

 75%|███████▌  | 1345/1793 [10:57<03:13,  2.31it/s]

Original image path: ./raw_studies/t1+_thick_ax/592_1_253/592_1_253_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/592_1_253/592_1_253_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/592_1_253/592_1_253_t1+_thick_ax_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thick_cor/592_1_253/592_1_253_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/592_1_253/592_1_253_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/592_1_253/592_1_253_t1+_thick_cor_manual_0_uvauser8.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/592_1_253/592_1_253_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/592_1_253/592_1_253_t1+_thick_cor_manual_0_uvauser8_coregistered.nii.gz)

 75%|███████▌  | 1346/1793 [10:57<02:38,  2.81it/s]

Original image path: ./raw_studies/t1+_thin/592_2_1030/592_2_1030_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/592_2_1030/592_2_1030_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/592_2_1030/592_2_1030_t1+_thin_VS_uvauser5-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/592_2_1030/592_2_1030_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/592_2_1030/592_2_1030_t1+_thin_VS_uvauser5-copy_coregistered.nii.gz)

 75%|███████▌  | 1347/1793 [10:59<06:17,  1.18it/s]

Original image path: ./raw_studies/t2_thin/592_2_1030/592_2_1030_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/592_2_1030/592_2_1030_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/592_2_1030/592_2_1030_t2_thin_image_coregistered.nii.gz, nan)

 75%|███████▌  | 1349/1793 [11:01<04:59,  1.48it/s]

Original image path: ./raw_studies/t1+_thick_ax/593_0_0/593_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/593_0_0/593_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/593_0_0/593_0_0_t1+_thick_ax_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/593_0_0/593_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/593_0_0/593_0_0_t1+_thick_ax_VS_uvauser5_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/593_0_0/593_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/593_0_0/593_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/593_0_0/593_0_0_t1+_thick_cor_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/593_0_0/593_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/593_0_0/593_0_0_t1+_thick_cor_VS_uvauser5_coregistered.nii.gz)

 75%|███████▌  | 1350/1793 [11:01<03:54,  1.89it/s]

Original image path: ./raw_studies/t2_thin/593_0_0/593_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/593_0_0/593_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/593_0_0/593_0_0_t2_thin_T2Final_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/593_0_0/593_0_0_t2_thin_image_coregistered.nii.gz, nan)

 75%|███████▌  | 1352/1793 [11:02<03:22,  2.18it/s]

Original image path: ./raw_studies/t1+_thick_ax/593_1_403/593_1_403_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/593_1_403/593_1_403_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/593_1_403/593_1_403_t1+_thick_ax_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/593_1_403/593_1_403_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/593_1_403/593_1_403_t1+_thick_ax_VS_uvauser5_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/593_1_403/593_1_403_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/593_1_403/593_1_403_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/593_1_403/593_1_403_t2_thin_T2Final_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/593_1_403/593_1_403_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/593_1_403/593_1_403_t2_thin_T2Final_VS_uvauser5_coregistered.nii.gz)

 76%|███████▌  | 1354/1793 [11:03<03:35,  2.04it/s]

Original image path: ./raw_studies/t1+_thick_cor/593_1_403/593_1_403_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/593_1_403/593_1_403_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/593_1_403/593_1_403_t1+_thick_cor_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/593_1_403/593_1_403_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/593_1_403/593_1_403_t1+_thick_cor_VS_uvauser5_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/593_2_781/593_2_781_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/593_2_781/593_2_781_t1+_thick_cor_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t1+_thick_cor/593_2_781/593_2_781_t1+_thick_cor_VS_uvauser5.nii.gz
Returning: (nan, nan)

 76%|███████▌  | 1356/1793 [11:03<02:22,  3.06it/s]

Original image path: ./raw_studies/t1+_thick_ax/593_2_781/593_2_781_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/593_2_781/593_2_781_t1+_thick_ax_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t1+_thick_ax/593_2_781/593_2_781_t1+_thick_ax_VS_uvauser5.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t2_thin/593_2_781/593_2_781_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/593_2_781/593_2_781_t2_thin_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thin/593_2_781/593_2_781_t2_thin_T2Final_VS_uvauser5.nii.gz
Returning: (nan, nan)

 76%|███████▌  | 1357/1793 [11:05<05:01,  1.44it/s]

Original image path: ./raw_studies/t1+_thin/593_3_2370/593_3_2370_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/593_3_2370/593_3_2370_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/593_3_2370/593_3_2370_t1+_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/593_3_2370/593_3_2370_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/593_3_2370/593_3_2370_t1+_thin_VS_uvauser1_coregistered.nii.gz)

 76%|███████▌  | 1358/1793 [11:05<04:29,  1.61it/s]

Original image path: ./raw_studies/t2_thin/593_3_2370/593_3_2370_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/593_3_2370/593_3_2370_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/593_3_2370/593_3_2370_t2_thin_image_coregistered.nii.gz, nan)

 76%|███████▌  | 1361/1793 [11:06<03:02,  2.37it/s]

Original image path: ./raw_studies/t1+_thick_ax/595_0_0/595_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/595_0_0/595_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/595_0_0/595_0_0_t1+_thick_ax_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/595_0_0/595_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/595_0_0/595_0_0_t1+_thick_ax_AS_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/595_0_0/595_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/595_0_0/595_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/595_0_0/595_0_0_t1+_thick_cor_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/595_0_0/595_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/595_0_0/595_0_0_t1+_thick_cor_AS_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/595_0_0/595_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/595_0_0/595_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/595_0_0/595_0_0_t1+_thick_ax_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/595_0_0/595_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/595_0_0/595_0_0_t1+_thick_ax_tumorcore _uvauser3_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/595_0_0/595_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/595_0_0/595_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/595_0_0/595_0_0_t2_thin_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/595_0_0/595_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/595_0_0/595_0_0_t2_thin_AS_uvauser4_coregistered.nii.gz)

 76%|███████▌  | 1363/1793 [11:07<02:28,  2.90it/s]

Original image path: ./raw_studies/t2_thin/595_1_357/595_1_357_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/595_1_357/595_1_357_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/595_1_357/595_1_357_t2_thin_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/595_1_357/595_1_357_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/595_1_357/595_1_357_t2_thin_RVS _uvauser2_coregistered.nii.gz)

 76%|███████▌  | 1364/1793 [11:07<02:59,  2.39it/s]

Original image path: ./raw_studies/t1+_thick_ax/595_1_357/595_1_357_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/595_1_357/595_1_357_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/595_1_357/595_1_357_t1+_thick_ax_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/595_1_357/595_1_357_t1+_thick_ax_image_coregistered.nii.gz, nan)

 76%|███████▌  | 1366/1793 [11:08<02:30,  2.85it/s]

Original image path: ./raw_studies/t1+_thick_cor/595_1_357/595_1_357_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/595_1_357/595_1_357_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/595_1_357/595_1_357_t1+_thick_cor_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/595_1_357/595_1_357_t1+_thick_cor_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thick_cor/595_2_652/595_2_652_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/595_2_652/595_2_652_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/595_2_652/595_2_652_t1+_thick_cor_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t2_thin/595_2_652/595_2_652_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/595_2_652/595_2_652_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/595_2_652/595_2_652_t2_thin_T2Final_VS_uvauser5-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/595_2_652/595_2_652_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/595_2_652/595_2_652_t2_thin_T2Final_VS_uvauser5-copy_coregistered.nii.gz)

 76%|███████▋  | 1370/1793 [11:08<01:29,  4.70it/s]

Original image path: ./raw_studies/t1+_thick_ax/595_2_652/595_2_652_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/595_2_652/595_2_652_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/595_2_652/595_2_652_t1+_thick_ax_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thick_cor/595_3_1268/595_3_1268_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/595_3_1268/595_3_1268_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/595_3_1268/595_3_1268_t1+_thick_cor_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t2_thin/595_3_1268/595_3_1268_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/595_3_1268/595_3_1268_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/595_3_1268/595_3_1268_t2_thin_T2Final_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/595_3_1268/595_3_1268_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/595_3_1268/595_3_1268_t2_thin_T2Final_VS_uvauser5_coregistered.nii.gz)

 76%|███████▋  | 1371/1793 [11:09<01:42,  4.11it/s]

Original image path: ./raw_studies/t1+_thick_ax/595_3_1268/595_3_1268_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/595_3_1268/595_3_1268_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/595_3_1268/595_3_1268_t1+_thick_ax_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t2_thin/595_4_1631/595_4_1631_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/595_4_1631/595_4_1631_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/595_4_1631/595_4_1631_t2_thin_T2_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/595_4_1631/595_4_1631_t2_thin_image_coregistered.nii.gz, nan)

 77%|███████▋  | 1375/1793 [11:10<01:55,  3.62it/s]

Original image path: ./raw_studies/t1+_thick_cor/595_4_1631/595_4_1631_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/595_4_1631/595_4_1631_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/595_4_1631/595_4_1631_t1+_thick_cor_AS_uvauser4-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/595_4_1631/595_4_1631_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/595_4_1631/595_4_1631_t1+_thick_cor_AS_uvauser4-copy_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/595_4_1631/595_4_1631_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/595_4_1631/595_4_1631_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/595_4_1631/595_4_1631_t1+_thick_ax_AS_uvauser4-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/595_4_1631/595_4_1631_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/595_4_1631/595_4_1631_t1+_thick_ax_AS_uvauser4-copy_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/595_4_1631/595_4_1631_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/595_4_1631/595_4_1631_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/595_4_1631/595_4_1631_t1+_thick_cor_T1COR_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/595_4_1631/595_4_1631_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/595_4_1631/595_4_1631_t1+_thick_cor_T1COR_uvauser6_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/595_5_1995/595_5_1995_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/595_5_1995/595_5_1995_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/595_5_1995/595_5_1995_t2_thin_T2Final_VS_uvauser5-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/595_5_1995/595_5_1995_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/595_5_1995/595_5_1995_t2_thin_T2Final_VS_uvauser5-copy_coregistered.nii.gz)

 77%|███████▋  | 1379/1793 [11:11<01:32,  4.46it/s]

Original image path: ./raw_studies/t2_thick/598_0_0/598_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/598_0_0/598_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thick_cor/598_1_62/598_1_62_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/598_1_62/598_1_62_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/598_1_62/598_1_62_t1+_thick_cor_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thick_ax/598_1_62/598_1_62_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/598_1_62/598_1_62_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/598_1_62/598_1_62_t1+_thick_ax_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t2_thick/598_1_62/598_1_62_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/598_1_62/598_1_62_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 77%|███████▋  | 1381/1793 [11:11<01:27,  4.68it/s]

Original image path: ./raw_studies/t1+_thin/598_14_3982/598_14_3982_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/598_14_3982/598_14_3982_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/598_14_3982/598_14_3982_t1+_thin_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/598_14_3982/598_14_3982_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/598_14_3982/598_14_3982_t1+_thin_VS_uvauser5_coregistered.nii.gz)

 77%|███████▋  | 1382/1793 [11:13<03:39,  1.87it/s]

Original image path: ./raw_studies/t1+_thin/598_16_4431/598_16_4431_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/598_16_4431/598_16_4431_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/598_16_4431/598_16_4431_t1+_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/598_16_4431/598_16_4431_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/598_16_4431/598_16_4431_t1+_thin_VS_uvauser1_coregistered.nii.gz)

 77%|███████▋  | 1384/1793 [11:14<02:53,  2.36it/s]

Original image path: ./raw_studies/t2_thick/598_16_4431/598_16_4431_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/598_16_4431/598_16_4431_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thick_cor/598_2_73/598_2_73_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/598_2_73/598_2_73_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/598_2_73/598_2_73_t1+_thick_cor_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t2_thick/598_2_73/598_2_73_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/598_2_73/598_2_73_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 77%|███████▋  | 1386/1793 [11:14<02:02,  3.32it/s]

Original image path: ./raw_studies/t1+_thick_ax/598_2_73/598_2_73_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/598_2_73/598_2_73_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/598_2_73/598_2_73_t1+_thick_ax_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thick_cor/600_0_0/600_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/600_0_0/600_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/600_0_0/600_0_0_t1+_thick_cor_T1COR_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/600_0_0/600_0_0_t1+_thick_cor_image_coregistered.nii.gz, nan)

 77%|███████▋  | 1388/1793 [11:15<01:50,  3.67it/s]

Original image path: ./raw_studies/t2_thin/600_0_0/600_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/600_0_0/600_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/600_0_0/600_0_0_t2_thin_T2_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/600_0_0/600_0_0_t2_thin_image_coregistered.nii.gz, nan)

 77%|███████▋  | 1389/1793 [11:19<07:28,  1.11s/it]

Original image path: ./raw_studies/t1+_thick_ax/600_0_0/600_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/600_0_0/600_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/600_0_0/600_0_0_t1+_thick_ax_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/600_0_0/600_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/600_0_0/600_0_0_t1+_thick_ax_AS_uvauser4_coregistered.nii.gz)

 78%|███████▊  | 1390/1793 [11:19<06:10,  1.09it/s]

Original image path: ./raw_studies/t1+_thick_ax/600_0_0/600_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/600_0_0/600_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/600_0_0/600_0_0_t1+_thick_ax_T1AX_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/600_0_0/600_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/600_0_0/600_0_0_t1+_thick_ax_T1AX_uvauser6_coregistered.nii.gz)

 78%|███████▊  | 1393/1793 [11:20<03:11,  2.09it/s]

Original image path: ./raw_studies/t1+_thick_cor/600_1_168/600_1_168_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/600_1_168/600_1_168_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/600_1_168/600_1_168_t1+_thick_cor_T1COR_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/600_1_168/600_1_168_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/600_1_168/600_1_168_t1+_thick_cor_T1COR_uvauser6_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/600_1_168/600_1_168_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/600_1_168/600_1_168_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/600_1_168/600_1_168_t1+_thick_ax_T1AX_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/600_1_168/600_1_168_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/600_1_168/600_1_168_t1+_thick_ax_T1AX_uvauser6_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/600_1_168/600_1_168_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/600_1_168/600_1_168_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/600_1_168/600_1_168_t2_thin_T2_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/600_1_168/600_1_168_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/600_1_168/600_1_168_t2_thin_T2_uvauser6_coregistered.nii.gz)

 78%|███████▊  | 1395/1793 [11:21<03:19,  2.00it/s]

Original image path: ./raw_studies/t1+_thick_cor/601_0_0/601_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/601_0_0/601_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/601_0_0/601_0_0_t1+_thick_cor_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/601_0_0/601_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/601_0_0/601_0_0_t1+_thick_cor_tumorcore _uvauser3_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/601_0_0/601_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/601_0_0/601_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/601_0_0/601_0_0_t1+_thick_ax_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/601_0_0/601_0_0_t1+_thick_ax_image_coregistered.nii.gz, nan)

 78%|███████▊  | 1396/1793 [11:21<03:22,  1.96it/s]

Original image path: ./raw_studies/t2_thin/601_0_0/601_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/601_0_0/601_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/601_0_0/601_0_0_t2_thin_CO_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/601_0_0/601_0_0_t2_thin_image_coregistered.nii.gz, nan)

 78%|███████▊  | 1397/1793 [11:23<04:58,  1.33it/s]

Original image path: ./raw_studies/t2_thin/601_1_201/601_1_201_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/601_1_201/601_1_201_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/601_1_201/601_1_201_t2_thin_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/601_1_201/601_1_201_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/601_1_201/601_1_201_t2_thin_RVS _uvauser2_coregistered.nii.gz)

 78%|███████▊  | 1398/1793 [11:24<05:56,  1.11it/s]

Original image path: ./raw_studies/t1+_thin/601_1_201/601_1_201_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/601_1_201/601_1_201_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/601_1_201/601_1_201_t1+_thin_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/601_1_201/601_1_201_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/601_1_201/601_1_201_t1+_thin_RVS _uvauser2_coregistered.nii.gz)

 78%|███████▊  | 1399/1793 [11:26<07:03,  1.08s/it]

Original image path: ./raw_studies/t1+_thin/601_1_201/601_1_201_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/601_1_201/601_1_201_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/601_1_201/601_1_201_t1+_thin_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/601_1_201/601_1_201_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/601_1_201/601_1_201_t1+_thin_RVS _uvauser2_coregistered.nii.gz)

 78%|███████▊  | 1400/1793 [11:27<07:52,  1.20s/it]

Original image path: ./raw_studies/t1+_thin/601_2_616/601_2_616_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/601_2_616/601_2_616_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/601_2_616/601_2_616_t1+_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/601_2_616/601_2_616_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/601_2_616/601_2_616_t1+_thin_VS_uvauser1_coregistered.nii.gz)

 78%|███████▊  | 1401/1793 [11:29<09:39,  1.48s/it]

Original image path: ./raw_studies/t2_thin/601_2_616/601_2_616_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/601_2_616/601_2_616_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/601_2_616/601_2_616_t2_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/601_2_616/601_2_616_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/601_2_616/601_2_616_t2_thin_VS_uvauser1_coregistered.nii.gz)

 78%|███████▊  | 1402/1793 [11:30<08:27,  1.30s/it]

Original image path: ./raw_studies/t1+_thin/603_0_0/603_0_0_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/603_0_0/603_0_0_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/603_0_0/603_0_0_t1+_thin_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/603_0_0/603_0_0_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/603_0_0/603_0_0_t1+_thin_tumorcore _uvauser3_coregistered.nii.gz)

 78%|███████▊  | 1403/1793 [11:31<06:48,  1.05s/it]

Original image path: ./raw_studies/t2_thin/603_0_0/603_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/603_0_0/603_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/603_0_0/603_0_0_t2_thin_VS0_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/603_0_0/603_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/603_0_0/603_0_0_t2_thin_VS0_uvauser1_coregistered.nii.gz)

 78%|███████▊  | 1404/1793 [11:31<05:32,  1.17it/s]

Original image path: ./raw_studies/t2_thin/603_1_860/603_1_860_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/603_1_860/603_1_860_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/603_1_860/603_1_860_t2_thin_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/603_1_860/603_1_860_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/603_1_860/603_1_860_t2_thin_RVS _uvauser2_coregistered.nii.gz)

 78%|███████▊  | 1406/1793 [11:32<03:39,  1.76it/s]

Original image path: ./raw_studies/t1+_thick_cor/603_1_860/603_1_860_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/603_1_860/603_1_860_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/603_1_860/603_1_860_t1+_thick_cor_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/603_1_860/603_1_860_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/603_1_860/603_1_860_t1+_thick_cor_RVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/603_1_860/603_1_860_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/603_1_860/603_1_860_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/603_1_860/603_1_860_t1+_thick_ax_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/603_1_860/603_1_860_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/603_1_860/603_1_860_t1+_thick_ax_RVS _uvauser2_coregistered.nii.gz)

 78%|███████▊  | 1407/1793 [11:32<02:51,  2.24it/s]

Original image path: ./raw_studies/t1+_thin/603_2_1141/603_2_1141_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/603_2_1141/603_2_1141_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/603_2_1141/603_2_1141_t1+_thin_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/603_2_1141/603_2_1141_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/603_2_1141/603_2_1141_t1+_thin_AS_uvauser4_coregistered.nii.gz)

 79%|███████▊  | 1408/1793 [11:33<04:37,  1.39it/s]

Original image path: ./raw_studies/t2_thin/603_2_1141/603_2_1141_t2_thin_image_uint8.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/603_2_1141/603_2_1141_t2_thin_image_uint8_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 79%|███████▊  | 1409/1793 [11:36<08:04,  1.26s/it]

Original image path: ./raw_studies/t1+_thick_cor/604_0_0/604_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/604_0_0/604_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/604_0_0/604_0_0_t1+_thick_cor_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/604_0_0/604_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/604_0_0/604_0_0_t1+_thick_cor_AS_uvauser4_coregistered.nii.gz)

 79%|███████▊  | 1410/1793 [11:36<06:15,  1.02it/s]

Original image path: ./raw_studies/t1+_thick_ax/604_0_0/604_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/604_0_0/604_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/604_0_0/604_0_0_t1+_thick_ax_AS1_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/604_0_0/604_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/604_0_0/604_0_0_t1+_thick_ax_AS1_uvauser4_coregistered.nii.gz)

 79%|███████▉  | 1412/1793 [11:37<03:55,  1.62it/s]

Original image path: ./raw_studies/t2_thick/604_0_0/604_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/604_0_0/604_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thick_ax/604_1_178/604_1_178_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/604_1_178/604_1_178_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/604_1_178/604_1_178_t1+_thick_ax_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/604_1_178/604_1_178_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/604_1_178/604_1_178_t1+_thick_ax_AS_uvauser4_coregistered.nii.gz)

 79%|███████▉  | 1414/1793 [11:37<02:22,  2.65it/s]

Original image path: ./raw_studies/t1+_thick_cor/604_1_178/604_1_178_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/604_1_178/604_1_178_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/604_1_178/604_1_178_t1+_thick_cor_AS1_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/604_1_178/604_1_178_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/604_1_178/604_1_178_t1+_thick_cor_AS1_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/604_1_178/604_1_178_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/604_1_178/604_1_178_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/604_1_178/604_1_178_t2_thin_AS2_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/604_1_178/604_1_178_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/604_1_178/604_1_178_t2_thin_AS2_uvauser4_coregistered.nii.gz)

 79%|███████▉  | 1415/1793 [11:38<03:38,  1.73it/s]

Original image path: ./raw_studies/t1+_thin/604_2_258/604_2_258_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/604_2_258/604_2_258_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/604_2_258/604_2_258_t1+_thin_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/604_2_258/604_2_258_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/604_2_258/604_2_258_t1+_thin_tumorcore _uvauser3_coregistered.nii.gz)

 79%|███████▉  | 1416/1793 [11:39<04:33,  1.38it/s]

Original image path: ./raw_studies/t2_thin/604_2_258/604_2_258_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/604_2_258/604_2_258_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/604_2_258/604_2_258_t2_thin_image_coregistered.nii.gz, nan)

 79%|███████▉  | 1419/1793 [11:40<02:26,  2.55it/s]

Original image path: ./raw_studies/t1+_thick_ax/606_0_0/606_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/606_0_0/606_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/606_0_0/606_0_0_t1+_thick_ax_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/606_0_0/606_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/606_0_0/606_0_0_t1+_thick_ax_VS_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/606_0_0/606_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/606_0_0/606_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/606_0_0/606_0_0_t1+_thick_cor_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/606_0_0/606_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/606_0_0/606_0_0_t1+_thick_cor_VS_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/606_0_0/606_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/606_0_0/606_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/606_0_0/606_0_0_t2_thin_AX_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/606_0_0/606_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/606_0_0/606_0_0_t2_thin_AX_VS_uvauser1_coregistered.nii.gz)

 79%|███████▉  | 1420/1793 [11:40<02:33,  2.42it/s]

Original image path: ./raw_studies/t2_thin/606_1_181/606_1_181_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/606_1_181/606_1_181_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/606_1_181/606_1_181_t2_thin_AX_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/606_1_181/606_1_181_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/606_1_181/606_1_181_t2_thin_AX_tumorcore _uvauser3_coregistered.nii.gz)

 79%|███████▉  | 1423/1793 [11:41<02:23,  2.58it/s]

Original image path: ./raw_studies/t1+_thick_ax/606_1_181/606_1_181_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/606_1_181/606_1_181_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/606_1_181/606_1_181_t1+_thick_ax_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thick_cor/606_1_181/606_1_181_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/606_1_181/606_1_181_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/606_1_181/606_1_181_t1+_thick_cor_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/606_1_181/606_1_181_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/606_1_181/606_1_181_t1+_thick_cor_tumorcore _uvauser3_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/606_2_545/606_2_545_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/606_2_545/606_2_545_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/606_2_545/606_2_545_t1+_thick_ax_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/606_2_545/606_2_545_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/606_2_545/606_2_545_t1+_thick_ax_VS_uvauser1_coregistered.nii.gz)

 79%|███████▉  | 1425/1793 [11:42<01:39,  3.70it/s]

Original image path: ./raw_studies/t1+_thick_cor/606_2_545/606_2_545_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/606_2_545/606_2_545_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/606_2_545/606_2_545_t1+_thick_cor_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/606_2_545/606_2_545_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/606_2_545/606_2_545_t1+_thick_cor_VS_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/606_2_545/606_2_545_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/606_2_545/606_2_545_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/606_2_545/606_2_545_t2_thin_AX_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/606_2_545/606_2_545_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/606_2_545/606_2_545_t2_thin_AX_VS_uvauser1_coregistered.nii.gz)

 80%|███████▉  | 1426/1793 [11:43<02:58,  2.06it/s]

Original image path: ./raw_studies/t1+_thin/606_3_914/606_3_914_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/606_3_914/606_3_914_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/606_3_914/606_3_914_t1+_thin_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/606_3_914/606_3_914_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/606_3_914/606_3_914_t1+_thin_RVS _uvauser2_coregistered.nii.gz)

 80%|███████▉  | 1428/1793 [11:44<02:25,  2.51it/s]

Original image path: ./raw_studies/t2_thin/606_3_914/606_3_914_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/606_3_914/606_3_914_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/606_3_914/606_3_914_t2_thin_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/606_3_914/606_3_914_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/606_3_914/606_3_914_t2_thin_RVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/606_3_914/606_3_914_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/606_3_914/606_3_914_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/606_3_914/606_3_914_t1+_thick_cor_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/606_3_914/606_3_914_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/606_3_914/606_3_914_t1+_thick_cor_RVS _uvauser2_coregistered.nii.gz)

 80%|███████▉  | 1429/1793 [11:44<02:35,  2.35it/s]

Original image path: ./raw_studies/t2_thin/606_4_1278/606_4_1278_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/606_4_1278/606_4_1278_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/606_4_1278/606_4_1278_t2_thin_image_coregistered.nii.gz, nan)

 80%|███████▉  | 1430/1793 [11:45<03:34,  1.69it/s]

Original image path: ./raw_studies/t1+_thin/606_4_1278/606_4_1278_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/606_4_1278/606_4_1278_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/606_4_1278/606_4_1278_t1+_thin_VS_uvauser5-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/606_4_1278/606_4_1278_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/606_4_1278/606_4_1278_t1+_thin_VS_uvauser5-copy_coregistered.nii.gz)

 80%|███████▉  | 1431/1793 [11:46<03:21,  1.80it/s]

Original image path: ./raw_studies/t2_thin/606_5_2001/606_5_2001_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/606_5_2001/606_5_2001_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/606_5_2001/606_5_2001_t2_thin_image_coregistered.nii.gz, nan)

 80%|███████▉  | 1432/1793 [11:46<03:57,  1.52it/s]

Original image path: ./raw_studies/t1+_thin/606_5_2001/606_5_2001_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/606_5_2001/606_5_2001_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/606_5_2001/606_5_2001_t1+_thin_VS_uvauser5-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/606_5_2001/606_5_2001_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/606_5_2001/606_5_2001_t1+_thin_VS_uvauser5-copy_coregistered.nii.gz)

 80%|███████▉  | 1434/1793 [11:47<02:46,  2.15it/s]

Original image path: ./raw_studies/t1+_thick_cor/609_0_0/609_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/609_0_0/609_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/609_0_0/609_0_0_t1+_thick_cor_T1COR_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/609_0_0/609_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/609_0_0/609_0_0_t1+_thick_cor_T1COR_uvauser6_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/609_0_0/609_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/609_0_0/609_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/609_0_0/609_0_0_t1+_thick_ax_T1AX_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/609_0_0/609_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/609_0_0/609_0_0_t1+_thick_ax_T1AX_uvauser6_coregistered.nii.gz)

 80%|████████  | 1435/1793 [11:47<02:09,  2.77it/s]

Original image path: ./raw_studies/t2_thin/609_0_0/609_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/609_0_0/609_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/609_0_0/609_0_0_t2_thin_T2_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/609_0_0/609_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/609_0_0/609_0_0_t2_thin_T2_uvauser6_coregistered.nii.gz)

 80%|████████  | 1437/1793 [11:48<02:00,  2.95it/s]

Original image path: ./raw_studies/t1+_thick_ax/609_1_167/609_1_167_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/609_1_167/609_1_167_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/609_1_167/609_1_167_t1+_thick_ax_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/609_1_167/609_1_167_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/609_1_167/609_1_167_t1+_thick_ax_VS_uvauser5_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/609_1_167/609_1_167_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/609_1_167/609_1_167_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/609_1_167/609_1_167_t2_thin_T2Final_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/609_1_167/609_1_167_t2_thin_image_coregistered.nii.gz, nan)

 80%|████████  | 1439/1793 [11:49<02:48,  2.10it/s]

Original image path: ./raw_studies/t1+_thick_cor/609_1_167/609_1_167_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/609_1_167/609_1_167_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/609_1_167/609_1_167_t1+_thick_cor_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/609_1_167/609_1_167_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/609_1_167/609_1_167_t1+_thick_cor_VS_uvauser5_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/609_2_536/609_2_536_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/609_2_536/609_2_536_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/609_2_536/609_2_536_t1+_thick_ax_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/609_2_536/609_2_536_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/609_2_536/609_2_536_t1+_thick_ax_AS_uvauser4_coregistered.nii.gz)

 80%|████████  | 1440/1793 [11:49<02:12,  2.66it/s]

Original image path: ./raw_studies/t2_thin/609_2_536/609_2_536_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/609_2_536/609_2_536_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/609_2_536/609_2_536_t2_thin_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/609_2_536/609_2_536_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/609_2_536/609_2_536_t2_thin_AS_uvauser4_coregistered.nii.gz)

 80%|████████  | 1442/1793 [11:51<02:36,  2.24it/s]

Original image path: ./raw_studies/t1+_thick_cor/609_2_536/609_2_536_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/609_2_536/609_2_536_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/609_2_536/609_2_536_t1+_thick_cor_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/609_2_536/609_2_536_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/609_2_536/609_2_536_t1+_thick_cor_AS_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thin/609_3_902/609_3_902_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/609_3_902/609_3_902_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/609_3_902/609_3_902_t1+_thin_T1_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/609_3_902/609_3_902_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/609_3_902/609_3_902_t1+_thin_T1_uvauser6_coregistered.nii.gz)

 80%|████████  | 1443/1793 [11:52<04:46,  1.22it/s]

Original image path: ./raw_studies/t2_thin/609_3_902/609_3_902_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/609_3_902/609_3_902_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/609_3_902/609_3_902_t2_thin_T2_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/609_3_902/609_3_902_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/609_3_902/609_3_902_t2_thin_T2_uvauser6_coregistered.nii.gz)

 81%|████████  | 1445/1793 [11:53<03:51,  1.51it/s]

Original image path: ./raw_studies/t1+_thick_cor/610_0_0/610_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/610_0_0/610_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/610_0_0/610_0_0_t1+_thick_cor_T1COR_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/610_0_0/610_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/610_0_0/610_0_0_t1+_thick_cor_T1COR_uvauser6_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/610_0_0/610_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/610_0_0/610_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/610_0_0/610_0_0_t1+_thick_ax_T2_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/610_0_0/610_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/610_0_0/610_0_0_t1+_thick_ax_T2_uvauser6_coregistered.nii.gz)

 81%|████████  | 1446/1793 [11:54<03:08,  1.84it/s]

Original image path: ./raw_studies/t1+_thick_ax/610_0_0/610_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/610_0_0/610_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/610_0_0/610_0_0_t1+_thick_ax_T1AX_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/610_0_0/610_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/610_0_0/610_0_0_t1+_thick_ax_T1AX_uvauser6_coregistered.nii.gz)

 81%|████████  | 1448/1793 [11:54<02:03,  2.78it/s]

Original image path: ./raw_studies/t1+_thick_cor/610_1_210/610_1_210_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/610_1_210/610_1_210_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/610_1_210/610_1_210_t1+_thick_cor_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/610_1_210/610_1_210_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/610_1_210/610_1_210_t1+_thick_cor_VS_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/610_1_210/610_1_210_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/610_1_210/610_1_210_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/610_1_210/610_1_210_t1+_thick_ax_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/610_1_210/610_1_210_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/610_1_210/610_1_210_t1+_thick_ax_VS_uvauser1_coregistered.nii.gz)

 81%|████████  | 1449/1793 [11:54<01:41,  3.40it/s]

Original image path: ./raw_studies/t2_thin/610_1_210/610_1_210_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/610_1_210/610_1_210_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/610_1_210/610_1_210_t2_thin_AX_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/610_1_210/610_1_210_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/610_1_210/610_1_210_t2_thin_AX_VS_uvauser1_coregistered.nii.gz)

 81%|████████  | 1450/1793 [11:55<02:56,  1.94it/s]

Original image path: ./raw_studies/t1+_thick_cor/610_2_619/610_2_619_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/610_2_619/610_2_619_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/610_2_619/610_2_619_t1+_thick_cor_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/610_2_619/610_2_619_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/610_2_619/610_2_619_t1+_thick_cor_LVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/610_2_619/610_2_619_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/610_2_619/610_2_619_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/610_2_619/610_2_619_t2_thin_T2Final_VS_uvauser5.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/610_2_619/610_2_619_t2_thin_image_coregistered.nii.gz, nan)

 81%|████████  | 1453/1793 [11:56<02:13,  2.55it/s]

Original image path: ./raw_studies/t1+_thick_ax/610_2_619/610_2_619_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/610_2_619/610_2_619_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/610_2_619/610_2_619_t1+_thick_ax_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/610_2_619/610_2_619_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/610_2_619/610_2_619_t1+_thick_ax_LVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thin/610_3_1008/610_3_1008_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/610_3_1008/610_3_1008_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/610_3_1008/610_3_1008_t1+_thin_T1AX_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/610_3_1008/610_3_1008_t1+_thin_image_coregistered.nii.gz, nan)

 81%|████████  | 1454/1793 [11:57<02:45,  2.05it/s]

Original image path: ./raw_studies/t2_thin/610_3_1008/610_3_1008_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/610_3_1008/610_3_1008_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/610_3_1008/610_3_1008_t2_thin_T2_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/610_3_1008/610_3_1008_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/610_3_1008/610_3_1008_t2_thin_T2_uvauser6_coregistered.nii.gz)

 81%|████████  | 1455/1793 [11:57<02:45,  2.05it/s]

Original image path: ./raw_studies/t1+_thin/610_4_1386/610_4_1386_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/610_4_1386/610_4_1386_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/610_4_1386/610_4_1386_t1+_thin_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/610_4_1386/610_4_1386_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/610_4_1386/610_4_1386_t1+_thin_AS_uvauser4_coregistered.nii.gz)

 81%|████████  | 1456/1793 [11:58<02:42,  2.08it/s]

Original image path: ./raw_studies/t2_thin/610_4_1386/610_4_1386_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/610_4_1386/610_4_1386_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/610_4_1386/610_4_1386_t2_thin_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/610_4_1386/610_4_1386_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/610_4_1386/610_4_1386_t2_thin_LVS _uvauser2_coregistered.nii.gz)

 81%|████████▏ | 1457/1793 [11:59<03:22,  1.66it/s]

Original image path: ./raw_studies/t2_thin/610_5_1757/610_5_1757_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/610_5_1757/610_5_1757_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/610_5_1757/610_5_1757_t2_thin_image_coregistered.nii.gz, nan)

 81%|████████▏ | 1458/1793 [12:00<03:54,  1.43it/s]

Original image path: ./raw_studies/t1+_thin/610_5_1757/610_5_1757_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/610_5_1757/610_5_1757_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/610_5_1757/610_5_1757_t1+_thin_AS_uvauser4-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/610_5_1757/610_5_1757_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/610_5_1757/610_5_1757_t1+_thin_AS_uvauser4-copy_coregistered.nii.gz)

 81%|████████▏ | 1460/1793 [12:00<02:42,  2.05it/s]

Original image path: ./raw_studies/t1+_thick_cor/611_0_0/611_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/611_0_0/611_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/611_0_0/611_0_0_t1+_thick_cor_VS2_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/611_0_0/611_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/611_0_0/611_0_0_t1+_thick_cor_VS2_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/611_0_0/611_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/611_0_0/611_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/611_0_0/611_0_0_t1+_thick_ax_VS1_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/611_0_0/611_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/611_0_0/611_0_0_t1+_thick_ax_VS1_uvauser1_coregistered.nii.gz)

 81%|████████▏ | 1461/1793 [12:01<02:09,  2.57it/s]

Original image path: ./raw_studies/t2_thin/611_0_0/611_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/611_0_0/611_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/611_0_0/611_0_0_t2_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/611_0_0/611_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/611_0_0/611_0_0_t2_thin_VS_uvauser1_coregistered.nii.gz)

 82%|████████▏ | 1462/1793 [12:01<02:18,  2.39it/s]

Original image path: ./raw_studies/t1+_thick_ax/611_1_186/611_1_186_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/611_1_186/611_1_186_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/611_1_186/611_1_186_t1+_thick_ax_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/611_1_186/611_1_186_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/611_1_186/611_1_186_t1+_thick_ax_tumorcore _uvauser3_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/611_1_186/611_1_186_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/611_1_186/611_1_186_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/611_1_186/611_1_186_t2_thin_CO_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/611_1_186/611_1_186_t2_thin_image_coregistered.nii.gz, nan)

 82%|████████▏ | 1465/1793 [12:03<02:46,  1.97it/s]

Original image path: ./raw_studies/t1+_thick_cor/611_1_186/611_1_186_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/611_1_186/611_1_186_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/611_1_186/611_1_186_t1+_thick_cor_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/611_1_186/611_1_186_t1+_thick_cor_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thick_ax/611_1_186/611_1_186_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/611_1_186/611_1_186_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/611_1_186/611_1_186_t1+_thick_ax_manual_0_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/611_1_186/611_1_186_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/611_1_186/611_1_186_t1+_thick_ax_manual_0_uvauser1_coregistered.nii.gz)

 82%|████████▏ | 1467/1793 [12:03<01:54,  2.84it/s]

Original image path: ./raw_studies/t1+_thick_cor/611_2_466/611_2_466_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/611_2_466/611_2_466_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/611_2_466/611_2_466_t1+_thick_cor_VS2_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/611_2_466/611_2_466_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/611_2_466/611_2_466_t1+_thick_cor_VS2_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/611_2_466/611_2_466_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/611_2_466/611_2_466_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/611_2_466/611_2_466_t1+_thick_ax_VS1_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/611_2_466/611_2_466_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/611_2_466/611_2_466_t1+_thick_ax_VS1_uvauser1_coregistered.nii.gz)

 82%|████████▏ | 1468/1793 [12:03<01:41,  3.20it/s]

Original image path: ./raw_studies/t2_thin/611_2_466/611_2_466_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/611_2_466/611_2_466_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/611_2_466/611_2_466_t2_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/611_2_466/611_2_466_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/611_2_466/611_2_466_t2_thin_VS_uvauser1_coregistered.nii.gz)

 82%|████████▏ | 1470/1793 [12:05<02:13,  2.42it/s]

Original image path: ./raw_studies/t1+_thick_cor/616_0_0/616_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/616_0_0/616_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/616_0_0/616_0_0_t1+_thick_cor_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/616_0_0/616_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/616_0_0/616_0_0_t1+_thick_cor_AS_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/616_0_0/616_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/616_0_0/616_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/616_0_0/616_0_0_t2_thin_AS1_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/616_0_0/616_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/616_0_0/616_0_0_t2_thin_AS1_uvauser4_coregistered.nii.gz)

 82%|████████▏ | 1471/1793 [12:05<02:11,  2.45it/s]

Original image path: ./raw_studies/t1+_thick_ax/616_0_0/616_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/616_0_0/616_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/616_0_0/616_0_0_t1+_thick_ax_VS1_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/616_0_0/616_0_0_t1+_thick_ax_image_coregistered.nii.gz, nan)

 82%|████████▏ | 1473/1793 [12:06<01:45,  3.02it/s]

Original image path: ./raw_studies/t1+_thick_cor/616_1_315/616_1_315_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/616_1_315/616_1_315_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/616_1_315/616_1_315_t1+_thick_cor_VS2_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/616_1_315/616_1_315_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/616_1_315/616_1_315_t1+_thick_cor_VS2_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/616_1_315/616_1_315_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/616_1_315/616_1_315_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/616_1_315/616_1_315_t2_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/616_1_315/616_1_315_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/616_1_315/616_1_315_t2_thin_VS_uvauser1_coregistered.nii.gz)

 82%|████████▏ | 1475/1793 [12:07<02:18,  2.30it/s]

Original image path: ./raw_studies/t1+_thick_ax/616_1_315/616_1_315_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/616_1_315/616_1_315_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/616_1_315/616_1_315_t1+_thick_ax_VS1_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/616_1_315/616_1_315_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/616_1_315/616_1_315_t1+_thick_ax_VS1_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thin/616_2_1078/616_2_1078_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/616_2_1078/616_2_1078_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/616_2_1078/616_2_1078_t1+_thin_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/616_2_1078/616_2_1078_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/616_2_1078/616_2_1078_t1+_thin_AS_uvauser4_coregistered.nii.gz)

 82%|████████▏ | 1476/1793 [12:07<02:30,  2.10it/s]

Original image path: ./raw_studies/t2_thin/616_2_1078/616_2_1078_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/616_2_1078/616_2_1078_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/616_2_1078/616_2_1078_t2_thin_image_coregistered.nii.gz, nan)

 82%|████████▏ | 1478/1793 [12:08<01:59,  2.63it/s]

Original image path: ./raw_studies/t1+_thick_ax/618_0_0/618_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/618_0_0/618_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/618_0_0/618_0_0_t1+_thick_ax_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/618_0_0/618_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/618_0_0/618_0_0_t1+_thick_ax_AS_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/618_0_0/618_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/618_0_0/618_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/618_0_0/618_0_0_t1+_thick_cor_AS1_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/618_0_0/618_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/618_0_0/618_0_0_t1+_thick_cor_AS1_uvauser4_coregistered.nii.gz)

 82%|████████▏ | 1479/1793 [12:08<01:41,  3.09it/s]

Original image path: ./raw_studies/t2_thin/618_0_0/618_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/618_0_0/618_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/618_0_0/618_0_0_t2_thin_AS1_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/618_0_0/618_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/618_0_0/618_0_0_t2_thin_AS1_uvauser4_coregistered.nii.gz)

 83%|████████▎ | 1480/1793 [12:09<01:48,  2.87it/s]

Original image path: ./raw_studies/t2_thin/618_1_291/618_1_291_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/618_1_291/618_1_291_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/618_1_291/618_1_291_t2_thin_CO_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/618_1_291/618_1_291_t2_thin_image_coregistered.nii.gz, nan)

 83%|████████▎ | 1482/1793 [12:10<02:34,  2.01it/s]

Original image path: ./raw_studies/t1+_thick_cor/618_1_291/618_1_291_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/618_1_291/618_1_291_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/618_1_291/618_1_291_t1+_thick_cor_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/618_1_291/618_1_291_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/618_1_291/618_1_291_t1+_thick_cor_tumorcore _uvauser3_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thick/618_1_291/618_1_291_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/618_1_291/618_1_291_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 83%|████████▎ | 1484/1793 [12:10<01:34,  3.27it/s]

Original image path: ./raw_studies/t2_thick/618_1_291/618_1_291_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/618_1_291/618_1_291_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thick_ax/618_1_291/618_1_291_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/618_1_291/618_1_291_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/618_1_291/618_1_291_t1+_thick_ax_manual_10_uvauser10.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/618_1_291/618_1_291_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/618_1_291/618_1_291_t1+_thick_ax_manual_10_uvauser10_coregistered.nii.gz)

 83%|████████▎ | 1486/1793 [12:11<01:13,  4.15it/s]

Original image path: ./raw_studies/t1+_thick_ax/618_2_627/618_2_627_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/618_2_627/618_2_627_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/618_2_627/618_2_627_t1+_thick_ax_VS1_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/618_2_627/618_2_627_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/618_2_627/618_2_627_t1+_thick_ax_VS1_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/618_2_627/618_2_627_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/618_2_627/618_2_627_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/618_2_627/618_2_627_t1+_thick_cor_VS2_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/618_2_627/618_2_627_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/618_2_627/618_2_627_t1+_thick_cor_VS2_uvauser1_coregistered.nii.gz)

 83%|████████▎ | 1487/1793 [12:11<01:06,  4.61it/s]

Original image path: ./raw_studies/t2_thin/618_2_627/618_2_627_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/618_2_627/618_2_627_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/618_2_627/618_2_627_t2_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/618_2_627/618_2_627_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/618_2_627/618_2_627_t2_thin_VS_uvauser1_coregistered.nii.gz)

 83%|████████▎ | 1489/1793 [12:12<01:55,  2.63it/s]

Original image path: ./raw_studies/t1+_thick_ax/625_1_1139/625_1_1139_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/625_1_1139/625_1_1139_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/625_1_1139/625_1_1139_t1+_thick_ax_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/625_1_1139/625_1_1139_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/625_1_1139/625_1_1139_t1+_thick_ax_LVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/625_1_1139/625_1_1139_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/625_1_1139/625_1_1139_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/625_1_1139/625_1_1139_t2_thin_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/625_1_1139/625_1_1139_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/625_1_1139/625_1_1139_t2_thin_LVS _uvauser2_coregistered.nii.gz)

 83%|████████▎ | 1490/1793 [12:13<03:17,  1.54it/s]

Original image path: ./raw_studies/t1+_thick_cor/625_1_1139/625_1_1139_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/625_1_1139/625_1_1139_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/625_1_1139/625_1_1139_t1+_thick_cor_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/625_1_1139/625_1_1139_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/625_1_1139/625_1_1139_t1+_thick_cor_LVS _uvauser2_coregistered.nii.gz)

 83%|████████▎ | 1491/1793 [12:13<02:38,  1.91it/s]

Original image path: ./raw_studies/t1+_thick_cor/625_2_1420/625_2_1420_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/625_2_1420/625_2_1420_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/625_2_1420/625_2_1420_t1+_thick_cor_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/625_2_1420/625_2_1420_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/625_2_1420/625_2_1420_t1+_thick_cor_tumorcore _uvauser3_coregistered.nii.gz)

 83%|████████▎ | 1493/1793 [12:14<01:54,  2.62it/s]

Original image path: ./raw_studies/t2_thick/625_2_1420/625_2_1420_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/625_2_1420/625_2_1420_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thick_cor/625_2_1420/625_2_1420_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/625_2_1420/625_2_1420_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/625_2_1420/625_2_1420_t1+_thick_cor_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/625_2_1420/625_2_1420_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/625_2_1420/625_2_1420_t1+_thick_cor_tumorcore _uvauser3_coregistered.nii.gz)

 83%|████████▎ | 1494/1793 [12:14<01:38,  3.04it/s]

Original image path: ./raw_studies/t2_thin/625_2_1420/625_2_1420_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/625_2_1420/625_2_1420_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/625_2_1420/625_2_1420_t2_thin_CO_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/625_2_1420/625_2_1420_t2_thin_image_coregistered.nii.gz, nan)

 83%|████████▎ | 1495/1793 [12:16<03:31,  1.41it/s]

Original image path: ./raw_studies/t1+_thick_ax/625_2_1420/625_2_1420_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/625_2_1420/625_2_1420_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/625_2_1420/625_2_1420_t1+_thick_ax_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/625_2_1420/625_2_1420_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/625_2_1420/625_2_1420_t1+_thick_ax_LVS _uvauser2_coregistered.nii.gz)

 83%|████████▎ | 1496/1793 [12:16<02:51,  1.73it/s]

Original image path: ./raw_studies/t1+_thick_ax/625_2_1420/625_2_1420_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/625_2_1420/625_2_1420_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/625_2_1420/625_2_1420_t1+_thick_ax_image_coregistered.nii.gz, nan)

 83%|████████▎ | 1497/1793 [12:16<02:22,  2.07it/s]

Original image path: ./raw_studies/t1+_thin/625_3_1544/625_3_1544_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/625_3_1544/625_3_1544_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/625_3_1544/625_3_1544_t1+_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/625_3_1544/625_3_1544_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/625_3_1544/625_3_1544_t1+_thin_VS_uvauser1_coregistered.nii.gz)

 84%|████████▎ | 1498/1793 [12:18<03:36,  1.36it/s]

Original image path: ./raw_studies/t2_thin/625_3_1544/625_3_1544_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/625_3_1544/625_3_1544_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/625_3_1544/625_3_1544_t2_thin_image_coregistered.nii.gz, nan)

 84%|████████▎ | 1499/1793 [12:20<06:14,  1.27s/it]

Original image path: ./raw_studies/t1+_thin/629_0_0/629_0_0_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/629_0_0/629_0_0_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/629_0_0/629_0_0_t1+_thin_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/629_0_0/629_0_0_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/629_0_0/629_0_0_t1+_thin_LVS _uvauser2_coregistered.nii.gz)

 84%|████████▎ | 1500/1793 [12:21<05:13,  1.07s/it]

Original image path: ./raw_studies/t2_thin/629_0_0/629_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/629_0_0/629_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/629_0_0/629_0_0_t2_thin_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/629_0_0/629_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/629_0_0/629_0_0_t2_thin_LVS _uvauser2_coregistered.nii.gz)

 84%|████████▎ | 1501/1793 [12:21<04:15,  1.14it/s]

Original image path: ./raw_studies/t2_thin/629_1_413/629_1_413_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/629_1_413/629_1_413_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/629_1_413/629_1_413_t2_thin_AS1_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/629_1_413/629_1_413_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/629_1_413/629_1_413_t2_thin_AS1_uvauser4_coregistered.nii.gz)

 84%|████████▍ | 1502/1793 [12:22<04:03,  1.20it/s]

Original image path: ./raw_studies/t2_thin/629_2_810/629_2_810_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/629_2_810/629_2_810_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/629_2_810/629_2_810_t2_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/629_2_810/629_2_810_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/629_2_810/629_2_810_t2_thin_VS_uvauser1_coregistered.nii.gz)

 84%|████████▍ | 1503/1793 [12:23<04:12,  1.15it/s]

Original image path: ./raw_studies/t1+_thin/629_2_810/629_2_810_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/629_2_810/629_2_810_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/629_2_810/629_2_810_t1+_thin_VS1_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/629_2_810/629_2_810_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/629_2_810/629_2_810_t1+_thin_VS1_uvauser1_coregistered.nii.gz)

 84%|████████▍ | 1504/1793 [12:24<04:04,  1.18it/s]

Original image path: ./raw_studies/t1+_thick_cor/629_2_810/629_2_810_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/629_2_810/629_2_810_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/629_2_810/629_2_810_t1+_thick_cor_VS2_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/629_2_810/629_2_810_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/629_2_810/629_2_810_t1+_thick_cor_VS2_uvauser1_coregistered.nii.gz)

 84%|████████▍ | 1505/1793 [12:24<03:10,  1.52it/s]

Original image path: ./raw_studies/t2_thin/632_0_0/632_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/632_0_0/632_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/632_0_0/632_0_0_t2_thin_AS2_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/632_0_0/632_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/632_0_0/632_0_0_t2_thin_AS2_uvauser4_coregistered.nii.gz)

 84%|████████▍ | 1507/1793 [12:24<02:16,  2.10it/s]

Original image path: ./raw_studies/t1+_thick_cor/632_0_0/632_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/632_0_0/632_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/632_0_0/632_0_0_t1+_thick_cor_AS1_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/632_0_0/632_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/632_0_0/632_0_0_t1+_thick_cor_AS1_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/632_0_0/632_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/632_0_0/632_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/632_0_0/632_0_0_t1+_thick_ax_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/632_0_0/632_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/632_0_0/632_0_0_t1+_thick_ax_AS_uvauser4_coregistered.nii.gz)

 84%|████████▍ | 1510/1793 [12:25<01:07,  4.16it/s]

Original image path: ./raw_studies/t1+_thick_cor/632_1_246/632_1_246_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/632_1_246/632_1_246_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/632_1_246/632_1_246_t1+_thick_cor_VS2_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/632_1_246/632_1_246_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/632_1_246/632_1_246_t1+_thick_cor_VS2_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/632_1_246/632_1_246_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/632_1_246/632_1_246_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/632_1_246/632_1_246_t1+_thick_ax_VS1_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/632_1_246/632_1_246_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/632_1_246/632_1_246_t1+_thick_ax_VS1_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/632_1_246/632_1_246_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/632_1_246/632_1_246_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/632_1_246/632_1_246_t2_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/632_1_246/632_1_246_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/632_1_246/632_1_246_t2_thin_VS_uvauser1_coregistered.nii.gz)

 84%|████████▍ | 1511/1793 [12:26<02:04,  2.26it/s]

Original image path: ./raw_studies/t1+_thick_cor/632_2_527/632_2_527_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/632_2_527/632_2_527_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/632_2_527/632_2_527_t1+_thick_cor_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/632_2_527/632_2_527_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/632_2_527/632_2_527_t1+_thick_cor_RVS _uvauser2_coregistered.nii.gz)

 84%|████████▍ | 1513/1793 [12:26<01:32,  3.03it/s]

Original image path: ./raw_studies/t1+_thick_ax/632_2_527/632_2_527_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/632_2_527/632_2_527_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/632_2_527/632_2_527_t1+_thick_ax_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/632_2_527/632_2_527_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/632_2_527/632_2_527_t1+_thick_ax_RVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/632_2_527/632_2_527_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/632_2_527/632_2_527_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/632_2_527/632_2_527_t2_thin_image_coregistered.nii.gz, nan)

 84%|████████▍ | 1514/1793 [12:28<03:39,  1.27it/s]

Original image path: ./raw_studies/t2_thick/632_2_527/632_2_527_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/632_2_527/632_2_527_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/632_2_527/632_2_527_t2_thick_LVS _uvauser2.nii.gz
Returning: (nan, nan)

 85%|████████▍ | 1516/1793 [12:29<02:28,  1.86it/s]

Original image path: ./raw_studies/t1+_thick_ax/636_0_0/636_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/636_0_0/636_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/636_0_0/636_0_0_t1+_thick_ax_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/636_0_0/636_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/636_0_0/636_0_0_t1+_thick_ax_LVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/636_0_0/636_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/636_0_0/636_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/636_0_0/636_0_0_t2_thin_LVS _uvauser2-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/636_0_0/636_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/636_0_0/636_0_0_t2_thin_LVS _uvauser2-copy_coregistered.nii.gz)

 85%|████████▍ | 1517/1793 [12:30<02:59,  1.53it/s]

Original image path: ./raw_studies/t1+_thick_cor/636_0_0/636_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/636_0_0/636_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/636_0_0/636_0_0_t1+_thick_cor_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/636_0_0/636_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/636_0_0/636_0_0_t1+_thick_cor_LVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/636_1_181/636_1_181_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/636_1_181/636_1_181_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/636_1_181/636_1_181_t2_thin_AS_uvauser4-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/636_1_181/636_1_181_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/636_1_181/636_1_181_t2_thin_AS_uvauser4-copy_coregistered.nii.gz)

 85%|████████▍ | 1520/1793 [12:31<02:10,  2.09it/s]

Original image path: ./raw_studies/t1+_thick_ax/636_1_181/636_1_181_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/636_1_181/636_1_181_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/636_1_181/636_1_181_t1+_thick_ax_AS1_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/636_1_181/636_1_181_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/636_1_181/636_1_181_t1+_thick_ax_AS1_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/636_1_181/636_1_181_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/636_1_181/636_1_181_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/636_1_181/636_1_181_t1+_thick_cor_AS2_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/636_1_181/636_1_181_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/636_1_181/636_1_181_t1+_thick_cor_AS2_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/636_4_978/636_4_978_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/636_4_978/636_4_978_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/636_4_978/636_4_978_t2_thin_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/636_4_978/636_4_978_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/636_4_978/636_4_978_t2_thin_LVS _uvauser2_coregistered.nii.gz)

 85%|████████▍ | 1522/1793 [12:33<03:39,  1.23it/s]

Original image path: ./raw_studies/t1+_thin/636_4_978/636_4_978_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/636_4_978/636_4_978_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/636_4_978/636_4_978_t1+_thin_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/636_4_978/636_4_978_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/636_4_978/636_4_978_t1+_thin_LVS _uvauser2_coregistered.nii.gz)

 85%|████████▍ | 1523/1793 [12:35<04:10,  1.08it/s]

Original image path: ./raw_studies/t1+_thick_cor/636_4_978/636_4_978_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/636_4_978/636_4_978_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/636_4_978/636_4_978_t1+_thick_cor_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/636_4_978/636_4_978_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/636_4_978/636_4_978_t1+_thick_cor_LVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/636_4_978/636_4_978_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/636_4_978/636_4_978_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/636_4_978/636_4_978_t1+_thick_ax_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/636_4_978/636_4_978_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/636_4_978/636_4_978_t1+_thick_ax_LVS _uvauser2_coregistered.nii.gz)

 85%|████████▌ | 1527/1793 [12:35<01:52,  2.37it/s]

Original image path: ./raw_studies/t1+_thick_cor/646_0_0/646_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/646_0_0/646_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/646_0_0/646_0_0_t1+_thick_cor_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/646_0_0/646_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/646_0_0/646_0_0_t1+_thick_cor_AS_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/646_0_0/646_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/646_0_0/646_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/646_0_0/646_0_0_t1+_thick_ax_AS1_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/646_0_0/646_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/646_0_0/646_0_0_t1+_thick_ax_AS1_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/646_0_0/646_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/646_0_0/646_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/646_0_0/646_0_0_t2_thin_image_coregistered.nii.gz, nan)

 85%|████████▌ | 1528/1793 [12:36<01:50,  2.41it/s]

Original image path: ./raw_studies/t1+_thick_cor/646_1_195/646_1_195_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/646_1_195/646_1_195_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/646_1_195/646_1_195_t1+_thick_cor_VS1_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/646_1_195/646_1_195_t1+_thick_cor_image_coregistered.nii.gz, nan)

 85%|████████▌ | 1530/1793 [12:36<01:26,  3.06it/s]

Original image path: ./raw_studies/t1+_thick_ax/646_1_195/646_1_195_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/646_1_195/646_1_195_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/646_1_195/646_1_195_t1+_thick_ax_VS2_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/646_1_195/646_1_195_t1+_thick_ax_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t2_thin/646_1_195/646_1_195_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/646_1_195/646_1_195_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/646_1_195/646_1_195_t2_thin_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/646_1_195/646_1_195_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/646_1_195/646_1_195_t2_thin_RVS _uvauser2_coregistered.nii.gz)

 85%|████████▌ | 1531/1793 [12:36<01:31,  2.88it/s]

Original image path: ./raw_studies/t1+_thin/646_2_265/646_2_265_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/646_2_265/646_2_265_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/646_2_265/646_2_265_t1+_thin_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/646_2_265/646_2_265_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/646_2_265/646_2_265_t1+_thin_AS_uvauser4_coregistered.nii.gz)

 85%|████████▌ | 1532/1793 [12:38<02:32,  1.71it/s]

Original image path: ./raw_studies/t2_thin/646_2_265/646_2_265_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/646_2_265/646_2_265_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/646_2_265/646_2_265_t2_thin_image_coregistered.nii.gz, nan)

 85%|████████▌ | 1533/1793 [12:38<02:23,  1.81it/s]

Original image path: ./raw_studies/t1+_thin/647_1_14/647_1_14_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/647_1_14/647_1_14_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/647_1_14/647_1_14_t1+_thin_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/647_1_14/647_1_14_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/647_1_14/647_1_14_t1+_thin_AS_uvauser4_coregistered.nii.gz)

 86%|████████▌ | 1534/1793 [12:38<02:06,  2.05it/s]

Original image path: ./raw_studies/t2_thin/647_1_14/647_1_14_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/647_1_14/647_1_14_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/647_1_14/647_1_14_t2_thin_image_coregistered.nii.gz, nan)

 86%|████████▌ | 1536/1793 [12:39<01:30,  2.84it/s]

Original image path: ./raw_studies/t1+_thick_ax/647_2_176/647_2_176_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/647_2_176/647_2_176_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/647_2_176/647_2_176_t1+_thick_ax_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/647_2_176/647_2_176_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/647_2_176/647_2_176_t1+_thick_ax_LVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/647_2_176/647_2_176_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/647_2_176/647_2_176_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/647_2_176/647_2_176_t1+_thick_cor_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/647_2_176/647_2_176_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/647_2_176/647_2_176_t1+_thick_cor_LVS _uvauser2_coregistered.nii.gz)

 86%|████████▌ | 1537/1793 [12:39<01:12,  3.55it/s]

Original image path: ./raw_studies/t2_thin/647_2_176/647_2_176_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/647_2_176/647_2_176_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/647_2_176/647_2_176_t2_thin_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/647_2_176/647_2_176_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/647_2_176/647_2_176_t2_thin_LVS _uvauser2_coregistered.nii.gz)

 86%|████████▌ | 1538/1793 [12:40<01:27,  2.90it/s]

Original image path: ./raw_studies/t1+_thin/647_3_212/647_3_212_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/647_3_212/647_3_212_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/647_3_212/647_3_212_t1+_thin_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/647_3_212/647_3_212_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/647_3_212/647_3_212_t1+_thin_AS_uvauser4_coregistered.nii.gz)

 86%|████████▌ | 1539/1793 [12:41<02:47,  1.51it/s]

Original image path: ./raw_studies/t2_thin/647_3_212/647_3_212_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/647_3_212/647_3_212_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/647_3_212/647_3_212_t2_thin_image_coregistered.nii.gz, nan)

 86%|████████▌ | 1540/1793 [12:42<02:40,  1.57it/s]

Original image path: ./raw_studies/t2_thick/648_0_0/648_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/648_0_0/648_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/648_0_0/648_0_0_t2_thick_VS_uvauser1.nii.gz
Returning: (nan, nan)

 86%|████████▌ | 1541/1793 [12:42<02:24,  1.74it/s]

Original image path: ./raw_studies/t1+_thick_cor/648_0_0/648_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/648_0_0/648_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t1+_thick_cor/648_0_0/648_0_0_t1+_thick_cor_VS2_uvauser1.nii.gz
Returning: (nan, nan)

 86%|████████▌ | 1542/1793 [12:42<02:13,  1.88it/s]

Original image path: ./raw_studies/t2_thin/648_2_411/648_2_411_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/648_2_411/648_2_411_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/648_2_411/648_2_411_t2_thin_image_coregistered.nii.gz, nan)

 86%|████████▌ | 1543/1793 [12:43<02:11,  1.90it/s]

Original image path: ./raw_studies/t1+_thin/648_2_411/648_2_411_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/648_2_411/648_2_411_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/648_2_411/648_2_411_t1+_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/648_2_411/648_2_411_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/648_2_411/648_2_411_t1+_thin_VS_uvauser1_coregistered.nii.gz)

 86%|████████▌ | 1544/1793 [12:43<02:10,  1.90it/s]

Original image path: ./raw_studies/t1+_thin/648_3_519/648_3_519_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/648_3_519/648_3_519_t1+_thin_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t1+_thin/648_3_519/648_3_519_t1+_thin_tumorcore _uvauser3.nii.gz
Returning: (nan, nan)

 86%|████████▌ | 1545/1793 [12:45<03:19,  1.24it/s]

Original image path: ./raw_studies/t2_thin/648_3_519/648_3_519_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/648_3_519/648_3_519_t2_thin_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 86%|████████▋ | 1548/1793 [12:46<01:44,  2.34it/s]

Original image path: ./raw_studies/t1+_thick_cor/649_0_0/649_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/649_0_0/649_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/649_0_0/649_0_0_t1+_thick_cor_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/649_0_0/649_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/649_0_0/649_0_0_t1+_thick_cor_LVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/649_0_0/649_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/649_0_0/649_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/649_0_0/649_0_0_t1+_thick_ax_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/649_0_0/649_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/649_0_0/649_0_0_t1+_thick_ax_LVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/649_0_0/649_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/649_0_0/649_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/649_0_0/649_0_0_t2_thin_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/649_0_0/649_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/649_0_0/649_0_0_t2_thin_LVS _uvauser2_coregistered.nii.gz)

 86%|████████▋ | 1550/1793 [12:47<01:52,  2.17it/s]

Original image path: ./raw_studies/t1+_thick_ax/649_1_37/649_1_37_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/649_1_37/649_1_37_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/649_1_37/649_1_37_t1+_thick_ax_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t2_thick/649_1_37/649_1_37_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/649_1_37/649_1_37_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 87%|████████▋ | 1552/1793 [12:47<01:15,  3.19it/s]

Original image path: ./raw_studies/t1+_thick_cor/649_1_37/649_1_37_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/649_1_37/649_1_37_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/649_1_37/649_1_37_t1+_thick_cor_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t2_thin/649_1_37/649_1_37_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/649_1_37/649_1_37_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/649_1_37/649_1_37_t2_thin_image_coregistered.nii.gz, nan)

 87%|████████▋ | 1553/1793 [12:48<02:03,  1.95it/s]

Original image path: ./raw_studies/t1+_thin/649_1_37/649_1_37_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/649_1_37/649_1_37_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/649_1_37/649_1_37_t1+_thin_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/649_1_37/649_1_37_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/649_1_37/649_1_37_t1+_thin_tumorcore _uvauser3_coregistered.nii.gz)

 87%|████████▋ | 1554/1793 [12:49<02:41,  1.48it/s]

Original image path: ./raw_studies/t1+_thin/649_1_37/649_1_37_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/649_1_37/649_1_37_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/649_1_37/649_1_37_t1+_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/649_1_37/649_1_37_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/649_1_37/649_1_37_t1+_thin_VS_uvauser1_coregistered.nii.gz)

 87%|████████▋ | 1555/1793 [12:50<03:09,  1.26it/s]

Original image path: ./raw_studies/t1+_thin/649_2_148/649_2_148_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/649_2_148/649_2_148_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/649_2_148/649_2_148_t1+_thin_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/649_2_148/649_2_148_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/649_2_148/649_2_148_t1+_thin_LVS _uvauser2_coregistered.nii.gz)

 87%|████████▋ | 1556/1793 [12:52<03:52,  1.02it/s]

Original image path: ./raw_studies/t1+_thick_ax/649_2_148/649_2_148_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/649_2_148/649_2_148_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/649_2_148/649_2_148_t1+_thick_ax_image_coregistered.nii.gz, nan)

 87%|████████▋ | 1557/1793 [12:52<02:57,  1.33it/s]

Original image path: ./raw_studies/t2_thin/649_2_148/649_2_148_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/649_2_148/649_2_148_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/649_2_148/649_2_148_t2_thin_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/649_2_148/649_2_148_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/649_2_148/649_2_148_t2_thin_LVS _uvauser2_coregistered.nii.gz)

 87%|████████▋ | 1559/1793 [12:52<01:58,  1.97it/s]

Original image path: ./raw_studies/t1+_thick_cor/649_2_148/649_2_148_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/649_2_148/649_2_148_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/649_2_148/649_2_148_t1+_thick_cor_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/649_2_148/649_2_148_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/649_2_148/649_2_148_t1+_thick_cor_LVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/651_1_1351/651_1_1351_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/651_1_1351/651_1_1351_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/651_1_1351/651_1_1351_t2_thin_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/651_1_1351/651_1_1351_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/651_1_1351/651_1_1351_t2_thin_RVS _uvauser2_coregistered.nii.gz)

 87%|████████▋ | 1560/1793 [12:53<02:31,  1.54it/s]

Original image path: ./raw_studies/t1+_thin/651_1_1351/651_1_1351_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/651_1_1351/651_1_1351_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/651_1_1351/651_1_1351_t1+_thin_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/651_1_1351/651_1_1351_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/651_1_1351/651_1_1351_t1+_thin_RVS _uvauser2_coregistered.nii.gz)

 87%|████████▋ | 1561/1793 [12:55<03:23,  1.14it/s]

Original image path: ./raw_studies/t1+_thin/651_1_1351/651_1_1351_t1+_thin_image_uint8.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/651_1_1351/651_1_1351_t1+_thin_image_uint8_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t1+_thin/651_1_1351/651_1_1351_t1+_thin_RVS _uvauser2.nii.gz
Returning: (nan, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/651_1_1351/651_1_1351_t1+_thin_RVS _uvauser2_coregistered.nii.gz)

 87%|████████▋ | 1562/1793 [12:58<05:51,  1.52s/it]

Original image path: ./raw_studies/t1+_thick_cor/651_2_1535/651_2_1535_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/651_2_1535/651_2_1535_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/651_2_1535/651_2_1535_t1+_thick_cor_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/651_2_1535/651_2_1535_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/651_2_1535/651_2_1535_t1+_thick_cor_RVS _uvauser2_coregistered.nii.gz)

 87%|████████▋ | 1563/1793 [12:58<04:19,  1.13s/it]

Original image path: ./raw_studies/t1+_thin/651_2_1535/651_2_1535_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/651_2_1535/651_2_1535_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/651_2_1535/651_2_1535_t1+_thin_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/651_2_1535/651_2_1535_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/651_2_1535/651_2_1535_t1+_thin_RVS _uvauser2_coregistered.nii.gz)

 87%|████████▋ | 1565/1793 [12:59<02:46,  1.37it/s]

Original image path: ./raw_studies/t2_thick/651_2_1535/651_2_1535_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/651_2_1535/651_2_1535_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/651_2_1535/651_2_1535_t2_thick_RVS _uvauser2.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t2_thin/651_3_1653/651_3_1653_t2_thin_image_uint8.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/651_3_1653/651_3_1653_t2_thin_image_uint8_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 87%|████████▋ | 1566/1793 [13:01<04:37,  1.22s/it]

Original image path: ./raw_studies/t2_thin/652_0_0/652_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/652_0_0/652_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/652_0_0/652_0_0_t2_thin_AX_VS1_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/652_0_0/652_0_0_t2_thin_image_coregistered.nii.gz, nan)

 87%|████████▋ | 1567/1793 [13:02<03:46,  1.00s/it]

Original image path: ./raw_studies/t1+_thin/652_0_0/652_0_0_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/652_0_0/652_0_0_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/652_0_0/652_0_0_t1+_thin_VS1_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/652_0_0/652_0_0_t1+_thin_image_coregistered.nii.gz, nan)

 88%|████████▊ | 1569/1793 [13:03<02:38,  1.42it/s]

Original image path: ./raw_studies/t1+_thick_cor/652_0_0/652_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/652_0_0/652_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/652_0_0/652_0_0_t1+_thick_cor_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/652_0_0/652_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/652_0_0/652_0_0_t1+_thick_cor_tumorcore _uvauser3_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/652_0_0/652_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/652_0_0/652_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/652_0_0/652_0_0_t1+_thick_ax_image_coregistered.nii.gz, nan)

 88%|████████▊ | 1571/1793 [13:03<01:33,  2.37it/s]

Original image path: ./raw_studies/t1+_thick_ax/652_1_326/652_1_326_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/652_1_326/652_1_326_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/652_1_326/652_1_326_t1+_thick_ax_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/652_1_326/652_1_326_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/652_1_326/652_1_326_t1+_thick_ax_RVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/652_1_326/652_1_326_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/652_1_326/652_1_326_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/652_1_326/652_1_326_t2_thin_RVS _uvauser2-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/652_1_326/652_1_326_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/652_1_326/652_1_326_t2_thin_RVS _uvauser2-copy_coregistered.nii.gz)

 88%|████████▊ | 1573/1793 [13:04<01:45,  2.08it/s]

Original image path: ./raw_studies/t1+_thick_cor/652_1_326/652_1_326_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/652_1_326/652_1_326_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/652_1_326/652_1_326_t1+_thick_cor_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/652_1_326/652_1_326_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/652_1_326/652_1_326_t1+_thick_cor_RVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thin/652_1_326/652_1_326_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/652_1_326/652_1_326_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/652_1_326/652_1_326_t1+_thin_image_coregistered.nii.gz, nan)

 88%|████████▊ | 1574/1793 [13:05<01:43,  2.11it/s]

Original image path: ./raw_studies/t1+_thin/652_2_869/652_2_869_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/652_2_869/652_2_869_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/652_2_869/652_2_869_t1+_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/652_2_869/652_2_869_t1+_thin_image_coregistered.nii.gz, nan)

 88%|████████▊ | 1575/1793 [13:06<02:21,  1.54it/s]

Original image path: ./raw_studies/t1+_thick_cor/652_2_869/652_2_869_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/652_2_869/652_2_869_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/652_2_869/652_2_869_t1+_thick_cor_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/652_2_869/652_2_869_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/652_2_869/652_2_869_t1+_thick_cor_RVS _uvauser2_coregistered.nii.gz)

 88%|████████▊ | 1576/1793 [13:06<01:55,  1.87it/s]

Original image path: ./raw_studies/t2_thin/652_2_869/652_2_869_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/652_2_869/652_2_869_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/652_2_869/652_2_869_t2_thin_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/652_2_869/652_2_869_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/652_2_869/652_2_869_t2_thin_RVS _uvauser2_coregistered.nii.gz)

 88%|████████▊ | 1577/1793 [13:06<01:42,  2.11it/s]

Original image path: ./raw_studies/t1+_thin/662_0_0/662_0_0_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/662_0_0/662_0_0_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/662_0_0/662_0_0_t1+_thin_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/662_0_0/662_0_0_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/662_0_0/662_0_0_t1+_thin_RVS _uvauser2_coregistered.nii.gz)

 88%|████████▊ | 1579/1793 [13:07<01:10,  3.02it/s]

Original image path: ./raw_studies/t2_thick/662_0_0/662_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/662_0_0/662_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/662_0_0/662_0_0_t2_thick_RVS _uvauser2.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t2_thin/662_0_0/662_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/662_0_0/662_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/662_0_0/662_0_0_t2_thin_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/662_0_0/662_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/662_0_0/662_0_0_t2_thin_RVS _uvauser2_coregistered.nii.gz)

 88%|████████▊ | 1581/1793 [13:07<01:11,  2.95it/s]

Original image path: ./raw_studies/t1+_thin/662_0_0/662_0_0_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/662_0_0/662_0_0_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/662_0_0/662_0_0_t1+_thin_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/662_0_0/662_0_0_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/662_0_0/662_0_0_t1+_thin_RVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/662_1_183/662_1_183_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/662_1_183/662_1_183_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/662_1_183/662_1_183_t1+_thick_ax_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/662_1_183/662_1_183_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/662_1_183/662_1_183_t1+_thick_ax_tumorcore _uvauser3_coregistered.nii.gz)

 88%|████████▊ | 1582/1793 [13:08<01:01,  3.45it/s]

Original image path: ./raw_studies/t2_thin/662_1_183/662_1_183_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/662_1_183/662_1_183_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/662_1_183/662_1_183_t2_thin_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/662_1_183/662_1_183_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/662_1_183/662_1_183_t2_thin_tumorcore _uvauser3_coregistered.nii.gz)

 88%|████████▊ | 1583/1793 [13:09<01:45,  2.00it/s]

Original image path: ./raw_studies/t2_thin/662_1_183/662_1_183_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/662_1_183/662_1_183_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/662_1_183/662_1_183_t2_thin_image_coregistered.nii.gz, nan)

 88%|████████▊ | 1584/1793 [13:10<02:12,  1.58it/s]

Original image path: ./raw_studies/t1+_thick_cor/662_1_183/662_1_183_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/662_1_183/662_1_183_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/662_1_183/662_1_183_t1+_thick_cor_image_coregistered.nii.gz, nan)

 88%|████████▊ | 1585/1793 [13:10<01:44,  1.98it/s]

Original image path: ./raw_studies/t2_thin/662_2_260/662_2_260_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/662_2_260/662_2_260_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/662_2_260/662_2_260_t2_thin_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/662_2_260/662_2_260_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/662_2_260/662_2_260_t2_thin_RVS _uvauser2_coregistered.nii.gz)

 88%|████████▊ | 1586/1793 [13:10<01:43,  1.99it/s]

Original image path: ./raw_studies/t1+_thick_ax/662_2_260/662_2_260_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/662_2_260/662_2_260_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/662_2_260/662_2_260_t1+_thick_ax_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/662_2_260/662_2_260_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/662_2_260/662_2_260_t1+_thick_ax_RVS _uvauser2_coregistered.nii.gz)

 89%|████████▊ | 1588/1793 [13:11<01:07,  3.05it/s]

Original image path: ./raw_studies/t1+_thick_cor/662_2_260/662_2_260_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/662_2_260/662_2_260_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/662_2_260/662_2_260_t1+_thick_cor_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/662_2_260/662_2_260_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/662_2_260/662_2_260_t1+_thick_cor_RVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thin/662_2_260/662_2_260_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/662_2_260/662_2_260_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/662_2_260/662_2_260_t1+_thin_image_coregistered.nii.gz, nan)

 89%|████████▊ | 1590/1793 [13:12<01:36,  2.10it/s]

Original image path: ./raw_studies/t1+_thick_ax/664_0_0/664_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/664_0_0/664_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/664_0_0/664_0_0_t1+_thick_ax_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thin/664_0_0/664_0_0_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/664_0_0/664_0_0_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/664_0_0/664_0_0_t1+_thin_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/664_0_0/664_0_0_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/664_0_0/664_0_0_t1+_thin_tumorcore _uvauser3_coregistered.nii.gz)

 89%|████████▊ | 1591/1793 [13:12<01:19,  2.56it/s]

Original image path: ./raw_studies/t2_thin/664_0_0/664_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/664_0_0/664_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/664_0_0/664_0_0_t2_thin_image_coregistered.nii.gz, nan)

 89%|████████▉ | 1592/1793 [13:12<01:10,  2.87it/s]

Original image path: ./raw_studies/t2_thin/664_0_0/664_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/664_0_0/664_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/664_0_0/664_0_0_t2_thin_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/664_0_0/664_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/664_0_0/664_0_0_t2_thin_tumorcore _uvauser3_coregistered.nii.gz)

 89%|████████▉ | 1594/1793 [13:13<01:03,  3.14it/s]

Original image path: ./raw_studies/t2_thick/664_1_175/664_1_175_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/664_1_175/664_1_175_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thick_ax/664_1_175/664_1_175_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/664_1_175/664_1_175_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/664_1_175/664_1_175_t1+_thick_ax_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thin/664_1_175/664_1_175_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/664_1_175/664_1_175_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/664_1_175/664_1_175_t1+_thin_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/664_1_175/664_1_175_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/664_1_175/664_1_175_t1+_thin_tumorcore _uvauser3_coregistered.nii.gz)

 89%|████████▉ | 1596/1793 [13:14<01:38,  2.01it/s]

Original image path: ./raw_studies/t1+_thin/664_1_175/664_1_175_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/664_1_175/664_1_175_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/664_1_175/664_1_175_t1+_thin_image_coregistered.nii.gz, nan)

 89%|████████▉ | 1597/1793 [13:16<02:15,  1.44it/s]

Original image path: ./raw_studies/t2_thin/664_1_175/664_1_175_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/664_1_175/664_1_175_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/664_1_175/664_1_175_t2_thin_image_coregistered.nii.gz, nan)

 89%|████████▉ | 1599/1793 [13:17<02:06,  1.54it/s]

Original image path: ./raw_studies/t1+_thick_cor/664_1_175/664_1_175_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/664_1_175/664_1_175_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/664_1_175/664_1_175_t1+_thick_cor_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thin/664_1_175/664_1_175_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/664_1_175/664_1_175_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/664_1_175/664_1_175_t1+_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/664_1_175/664_1_175_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/664_1_175/664_1_175_t1+_thin_VS_uvauser1_coregistered.nii.gz)

 89%|████████▉ | 1600/1793 [13:18<02:42,  1.19it/s]

Original image path: ./raw_studies/t1+_thin/664_2_210/664_2_210_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/664_2_210/664_2_210_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/664_2_210/664_2_210_t1+_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/664_2_210/664_2_210_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/664_2_210/664_2_210_t1+_thin_VS_uvauser1_coregistered.nii.gz)

 89%|████████▉ | 1601/1793 [13:19<02:50,  1.13it/s]

Original image path: ./raw_studies/t2_thin/664_2_210/664_2_210_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/664_2_210/664_2_210_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/664_2_210/664_2_210_t2_thin_image_coregistered.nii.gz, nan)

 89%|████████▉ | 1603/1793 [13:20<01:53,  1.67it/s]

Original image path: ./raw_studies/t1+_thick_ax/676_0_0/676_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/676_0_0/676_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/676_0_0/676_0_0_t1+_thick_ax_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/676_0_0/676_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/676_0_0/676_0_0_t1+_thick_ax_AS_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/676_0_0/676_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/676_0_0/676_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/676_0_0/676_0_0_t2_thin_AS2_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/676_0_0/676_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/676_0_0/676_0_0_t2_thin_AS2_uvauser4_coregistered.nii.gz)

 90%|████████▉ | 1605/1793 [13:21<01:23,  2.26it/s]

Original image path: ./raw_studies/t1+_thick_cor/676_0_0/676_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/676_0_0/676_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/676_0_0/676_0_0_t1+_thick_cor_AS1_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/676_0_0/676_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/676_0_0/676_0_0_t1+_thick_cor_AS1_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thin/676_1_276/676_1_276_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/676_1_276/676_1_276_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/676_1_276/676_1_276_t1+_thin_image_coregistered.nii.gz, nan)

 90%|████████▉ | 1607/1793 [13:21<00:51,  3.62it/s]

Original image path: ./raw_studies/t1+_thick_cor/676_1_276/676_1_276_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/676_1_276/676_1_276_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/676_1_276/676_1_276_t1+_thick_cor_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/676_1_276/676_1_276_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/676_1_276/676_1_276_t1+_thick_cor_tumorcore _uvauser3_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/676_1_276/676_1_276_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/676_1_276/676_1_276_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/676_1_276/676_1_276_t2_thin_image_coregistered.nii.gz, nan)

 90%|████████▉ | 1608/1793 [13:21<00:55,  3.33it/s]

Original image path: ./raw_studies/t2_thin/676_2_354/676_2_354_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/676_2_354/676_2_354_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/676_2_354/676_2_354_t2_thin_image_coregistered.nii.gz, nan)

 90%|████████▉ | 1609/1793 [13:22<01:04,  2.87it/s]

Original image path: ./raw_studies/t1+_thin/676_2_354/676_2_354_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/676_2_354/676_2_354_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/676_2_354/676_2_354_t1+_thin_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/676_2_354/676_2_354_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/676_2_354/676_2_354_t1+_thin_tumorcore _uvauser3_coregistered.nii.gz)

 90%|████████▉ | 1610/1793 [13:23<01:55,  1.59it/s]

Original image path: ./raw_studies/t1+_thin/679_0_0/679_0_0_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/679_0_0/679_0_0_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/679_0_0/679_0_0_t1+_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/679_0_0/679_0_0_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/679_0_0/679_0_0_t1+_thin_VS_uvauser1_coregistered.nii.gz)

 90%|████████▉ | 1611/1793 [13:23<01:34,  1.92it/s]

Original image path: ./raw_studies/t2_thin/679_0_0/679_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/679_0_0/679_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/679_0_0/679_0_0_t2_thin_image_coregistered.nii.gz, nan)

 90%|████████▉ | 1612/1793 [13:24<01:22,  2.19it/s]

Original image path: ./raw_studies/t1+_thick_cor/679_1_94/679_1_94_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/679_1_94/679_1_94_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/679_1_94/679_1_94_t1+_thick_cor_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/679_1_94/679_1_94_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/679_1_94/679_1_94_t1+_thick_cor_RVS _uvauser2_coregistered.nii.gz)

 90%|████████▉ | 1613/1793 [13:24<01:09,  2.61it/s]

Original image path: ./raw_studies/t1+_thick_ax/679_1_94/679_1_94_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/679_1_94/679_1_94_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/679_1_94/679_1_94_t1+_thick_ax_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/679_1_94/679_1_94_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/679_1_94/679_1_94_t1+_thick_ax_RVS _uvauser2_coregistered.nii.gz)

 90%|█████████ | 1614/1793 [13:24<00:59,  3.01it/s]

Original image path: ./raw_studies/t2_thin/679_1_94/679_1_94_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/679_1_94/679_1_94_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/679_1_94/679_1_94_t2_thin_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/679_1_94/679_1_94_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/679_1_94/679_1_94_t2_thin_RVS _uvauser2_coregistered.nii.gz)

 90%|█████████ | 1615/1793 [13:24<01:04,  2.74it/s]

Original image path: ./raw_studies/t2_thin/679_2_148/679_2_148_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/679_2_148/679_2_148_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/679_2_148/679_2_148_t2_thin_AS3_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/679_2_148/679_2_148_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/679_2_148/679_2_148_t2_thin_AS3_uvauser4_coregistered.nii.gz)

 90%|█████████ | 1616/1793 [13:25<01:10,  2.50it/s]

Original image path: ./raw_studies/t1+_thin/679_2_148/679_2_148_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/679_2_148/679_2_148_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/679_2_148/679_2_148_t1+_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/679_2_148/679_2_148_t1+_thin_image_coregistered.nii.gz, nan)

 90%|█████████ | 1618/1793 [13:27<01:38,  1.78it/s]

Original image path: ./raw_studies/t1+_thick_ax/69_0_0/69_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/69_0_0/69_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/69_0_0/69_0_0_t1+_thick_ax_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/69_0_0/69_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/69_0_0/69_0_0_t1+_thick_ax_AS_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/69_0_0/69_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/69_0_0/69_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/69_0_0/69_0_0_t1+_thick_cor_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/69_0_0/69_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/69_0_0/69_0_0_t1+_thick_cor_AS_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thick/69_0_0/69_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/69_0_0/69_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/69_0_0/69_0_0_t2_thick_AS1_uvauser4.nii.gz
Returning: (nan, nan)

 90%|█████████ | 1620/1793 [13:28<01:43,  1.67it/s]

Original image path: ./raw_studies/t2_thin/69_1_106/69_1_106_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/69_1_106/69_1_106_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/69_1_106/69_1_106_t2_thin_CO_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/69_1_106/69_1_106_t2_thin_image_coregistered.nii.gz, nan)

 90%|█████████ | 1622/1793 [13:29<01:41,  1.69it/s]

Original image path: ./raw_studies/t1+_thick_ax/69_1_106/69_1_106_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/69_1_106/69_1_106_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/69_1_106/69_1_106_t1+_thick_ax_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/69_1_106/69_1_106_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/69_1_106/69_1_106_t1+_thick_ax_tumorcore _uvauser3_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/69_1_106/69_1_106_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/69_1_106/69_1_106_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/69_1_106/69_1_106_t1+_thick_cor_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/69_1_106/69_1_106_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/69_1_106/69_1_106_t1+_thick_cor_tumorcore _uvauser3_coregistered.nii.gz)

 91%|█████████ | 1623/1793 [13:29<01:20,  2.11it/s]

Original image path: ./raw_studies/t2_thin/69_2_469/69_2_469_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/69_2_469/69_2_469_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/69_2_469/69_2_469_t2_thin_image_coregistered.nii.gz, nan)

 91%|█████████ | 1624/1793 [13:30<01:47,  1.58it/s]

Original image path: ./raw_studies/t1+_thin/69_2_469/69_2_469_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/69_2_469/69_2_469_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/69_2_469/69_2_469_t1+_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/69_2_469/69_2_469_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/69_2_469/69_2_469_t1+_thin_VS_uvauser1_coregistered.nii.gz)

 91%|█████████ | 1626/1793 [13:31<01:19,  2.10it/s]

Original image path: ./raw_studies/t1+_thick_cor/690_0_0/690_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/690_0_0/690_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/690_0_0/690_0_0_t1+_thick_cor_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/690_0_0/690_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/690_0_0/690_0_0_t1+_thick_cor_tumorcore _uvauser3_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/690_0_0/690_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/690_0_0/690_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/690_0_0/690_0_0_t2_thin_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/690_0_0/690_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/690_0_0/690_0_0_t2_thin_tumorcore _uvauser3_coregistered.nii.gz)

 91%|█████████ | 1627/1793 [13:33<02:48,  1.02s/it]

Original image path: ./raw_studies/t2_thick/690_0_0/690_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/690_0_0/690_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 91%|█████████ | 1628/1793 [13:34<02:17,  1.20it/s]

Original image path: ./raw_studies/t1+_thick_ax/690_0_0/690_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/690_0_0/690_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/690_0_0/690_0_0_t1+_thick_ax_image_coregistered.nii.gz, nan)

 91%|█████████ | 1629/1793 [13:34<01:54,  1.43it/s]

Original image path: ./raw_studies/t1+_thin/690_1_188/690_1_188_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/690_1_188/690_1_188_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/690_1_188/690_1_188_t1+_thin_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/690_1_188/690_1_188_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/690_1_188/690_1_188_t1+_thin_AS_uvauser4_coregistered.nii.gz)

 91%|█████████ | 1631/1793 [13:36<01:44,  1.55it/s]

Original image path: ./raw_studies/t1+_thick_ax/690_1_188/690_1_188_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/690_1_188/690_1_188_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/690_1_188/690_1_188_t1+_thick_ax_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/690_1_188/690_1_188_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/690_1_188/690_1_188_t1+_thick_ax_RVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/690_1_188/690_1_188_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/690_1_188/690_1_188_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/690_1_188/690_1_188_t1+_thick_cor_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/690_1_188/690_1_188_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/690_1_188/690_1_188_t1+_thick_cor_RVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/690_1_188/690_1_188_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/690_1_188/690_1_188_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/690_1_188/690_1_188_t2_thin_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/690_1_188/690_1_188_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/690_1_188/690_1_188_t2_thin_RVS _uvauser2_coregistered.nii.gz)

 91%|█████████ | 1633/1793 [13:36<01:17,  2.06it/s]

Original image path: ./raw_studies/t2_thin/690_2_488/690_2_488_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/690_2_488/690_2_488_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/690_2_488/690_2_488_t2_thin_image_coregistered.nii.gz, nan)

 91%|█████████ | 1635/1793 [13:38<01:50,  1.43it/s]

Original image path: ./raw_studies/t2_thick/696_0_0/696_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/696_0_0/696_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/696_0_0/696_0_0_t2_thick_RVS _uvauser2.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t2_thin/696_0_0/696_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/696_0_0/696_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/696_0_0/696_0_0_t2_thin_image_coregistered.nii.gz, nan)

 91%|█████████▏| 1637/1793 [13:39<01:24,  1.85it/s]

Original image path: ./raw_studies/t1+_thick_ax/696_0_0/696_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/696_0_0/696_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/696_0_0/696_0_0_t1+_thick_ax_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/696_0_0/696_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/696_0_0/696_0_0_t1+_thick_ax_RVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/696_0_0/696_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/696_0_0/696_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/696_0_0/696_0_0_t1+_thick_cor_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/696_0_0/696_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/696_0_0/696_0_0_t1+_thick_cor_RVS _uvauser2_coregistered.nii.gz)

 91%|█████████▏| 1638/1793 [13:39<01:09,  2.23it/s]

Original image path: ./raw_studies/t2_thin/696_1_179/696_1_179_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/696_1_179/696_1_179_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/696_1_179/696_1_179_t2_thin_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/696_1_179/696_1_179_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/696_1_179/696_1_179_t2_thin_RVS _uvauser2_coregistered.nii.gz)

 91%|█████████▏| 1640/1793 [13:41<01:15,  2.04it/s]

Original image path: ./raw_studies/t1+_thick_cor/696_1_179/696_1_179_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/696_1_179/696_1_179_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/696_1_179/696_1_179_t1+_thick_cor_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/696_1_179/696_1_179_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/696_1_179/696_1_179_t1+_thick_cor_RVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thin/696_1_179/696_1_179_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/696_1_179/696_1_179_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/696_1_179/696_1_179_t1+_thin_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/696_1_179/696_1_179_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/696_1_179/696_1_179_t1+_thin_RVS _uvauser2_coregistered.nii.gz)

 92%|█████████▏| 1641/1793 [13:41<01:13,  2.07it/s]

Original image path: ./raw_studies/t2_thin/696_2_223/696_2_223_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/696_2_223/696_2_223_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/696_2_223/696_2_223_t2_thin_image_coregistered.nii.gz, nan)

 92%|█████████▏| 1642/1793 [13:42<01:13,  2.05it/s]

Original image path: ./raw_studies/t1+_thin/696_2_223/696_2_223_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/696_2_223/696_2_223_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/696_2_223/696_2_223_t1+_thin_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/696_2_223/696_2_223_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/696_2_223/696_2_223_t1+_thin_AS_uvauser4_coregistered.nii.gz)

 92%|█████████▏| 1644/1793 [13:43<01:14,  2.00it/s]

Original image path: ./raw_studies/t1+_thick_ax/701_0_0/701_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/701_0_0/701_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/701_0_0/701_0_0_t1+_thick_ax_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/701_0_0/701_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/701_0_0/701_0_0_t1+_thick_ax_LVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/701_0_0/701_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/701_0_0/701_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/701_0_0/701_0_0_t1+_thick_cor_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/701_0_0/701_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/701_0_0/701_0_0_t1+_thick_cor_LVS _uvauser2_coregistered.nii.gz)

 92%|█████████▏| 1645/1793 [13:43<00:58,  2.53it/s]

Original image path: ./raw_studies/t2_thin/701_0_0/701_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/701_0_0/701_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/701_0_0/701_0_0_t2_thin_LVS _uvauser2-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/701_0_0/701_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/701_0_0/701_0_0_t2_thin_LVS _uvauser2-copy_coregistered.nii.gz)

 92%|█████████▏| 1646/1793 [13:44<01:21,  1.80it/s]

Original image path: ./raw_studies/t1+_thin/701_1_184/701_1_184_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/701_1_184/701_1_184_t1+_thin_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t1+_thin/701_1_184/701_1_184_t1+_thin_tumorcore _uvauser3.nii.gz
Returning: (nan, nan)

 92%|█████████▏| 1647/1793 [13:46<02:28,  1.02s/it]

Original image path: ./raw_studies/t2_thin/701_1_184/701_1_184_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/701_1_184/701_1_184_t2_thin_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 92%|█████████▏| 1648/1793 [13:47<02:09,  1.12it/s]

Original image path: ./raw_studies/t2_thin/701_2_240/701_2_240_t2_thin_image_uint8.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/701_2_240/701_2_240_t2_thin_image_uint8_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 92%|█████████▏| 1649/1793 [13:49<03:11,  1.33s/it]

Original image path: ./raw_studies/t1+_thin/701_2_240/701_2_240_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/701_2_240/701_2_240_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/701_2_240/701_2_240_t1+_thin_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/701_2_240/701_2_240_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/701_2_240/701_2_240_t1+_thin_tumorcore _uvauser3_coregistered.nii.gz)

 92%|█████████▏| 1650/1793 [13:50<03:09,  1.32s/it]

Original image path: ./raw_studies/t1+_thin/709_0_0/709_0_0_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/709_0_0/709_0_0_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/709_0_0/709_0_0_t1+_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/709_0_0/709_0_0_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/709_0_0/709_0_0_t1+_thin_VS_uvauser1_coregistered.nii.gz)

 92%|█████████▏| 1651/1793 [13:51<02:45,  1.17s/it]

Original image path: ./raw_studies/t2_thin/709_0_0/709_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/709_0_0/709_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/709_0_0/709_0_0_t2_thin_image_coregistered.nii.gz, nan)

 92%|█████████▏| 1652/1793 [13:51<02:08,  1.10it/s]

Original image path: ./raw_studies/t2_thin/709_1_371/709_1_371_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/709_1_371/709_1_371_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/709_1_371/709_1_371_t2_thin_image_coregistered.nii.gz, nan)

 92%|█████████▏| 1653/1793 [13:52<02:07,  1.10it/s]

Original image path: ./raw_studies/t1+_thick_ax/709_1_371/709_1_371_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/709_1_371/709_1_371_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/709_1_371/709_1_371_t1+_thick_ax_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/709_1_371/709_1_371_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/709_1_371/709_1_371_t1+_thick_ax_AS_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thin/709_1_371/709_1_371_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/709_1_371/709_1_371_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/709_1_371/709_1_371_t1+_thin_image_coregistered.nii.gz, nan)

 92%|█████████▏| 1656/1793 [13:53<01:14,  1.83it/s]

Original image path: ./raw_studies/t1+_thick_cor/709_1_371/709_1_371_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/709_1_371/709_1_371_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/709_1_371/709_1_371_t1+_thick_cor_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thin/709_2_763/709_2_763_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/709_2_763/709_2_763_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/709_2_763/709_2_763_t1+_thin_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/709_2_763/709_2_763_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/709_2_763/709_2_763_t1+_thin_tumorcore _uvauser3_coregistered.nii.gz)

 92%|█████████▏| 1657/1793 [13:54<01:08,  1.99it/s]

Original image path: ./raw_studies/t2_thin/709_2_763/709_2_763_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/709_2_763/709_2_763_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/709_2_763/709_2_763_t2_thin_image_coregistered.nii.gz, nan)

 93%|█████████▎| 1659/1793 [13:54<00:53,  2.49it/s]

Original image path: ./raw_studies/t1+_thick_ax/715_1_1362/715_1_1362_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/715_1_1362/715_1_1362_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/715_1_1362/715_1_1362_t1+_thick_ax_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thick_cor/715_1_1362/715_1_1362_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/715_1_1362/715_1_1362_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/715_1_1362/715_1_1362_t1+_thick_cor_image_coregistered.nii.gz, nan)

 93%|█████████▎| 1660/1793 [13:54<00:45,  2.95it/s]

Original image path: ./raw_studies/t2_thin/715_1_1362/715_1_1362_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/715_1_1362/715_1_1362_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/715_1_1362/715_1_1362_t2_thin_image_coregistered.nii.gz, nan)

 93%|█████████▎| 1661/1793 [13:55<00:49,  2.69it/s]

Original image path: ./raw_studies/t2_thin/715_2_1654/715_2_1654_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/715_2_1654/715_2_1654_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/715_2_1654/715_2_1654_t2_thin_image_coregistered.nii.gz, nan)

 93%|█████████▎| 1662/1793 [13:56<01:16,  1.72it/s]

Original image path: ./raw_studies/t1+_thin/715_2_1654/715_2_1654_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/715_2_1654/715_2_1654_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/715_2_1654/715_2_1654_t1+_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/715_2_1654/715_2_1654_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/715_2_1654/715_2_1654_t1+_thin_VS_uvauser1_coregistered.nii.gz)

 93%|█████████▎| 1663/1793 [13:56<01:10,  1.84it/s]

Original image path: ./raw_studies/t2_thin/715_3_1969/715_3_1969_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/715_3_1969/715_3_1969_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/715_3_1969/715_3_1969_t2_thin_image_coregistered.nii.gz, nan)

 93%|█████████▎| 1664/1793 [13:57<01:27,  1.47it/s]

Original image path: ./raw_studies/t1+_thin/715_3_1969/715_3_1969_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/715_3_1969/715_3_1969_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/715_3_1969/715_3_1969_t1+_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/715_3_1969/715_3_1969_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/715_3_1969/715_3_1969_t1+_thin_VS_uvauser1_coregistered.nii.gz)

 93%|█████████▎| 1665/1793 [14:00<02:23,  1.12s/it]

Original image path: ./raw_studies/t1+_thick_ax/728_1_2471/728_1_2471_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/728_1_2471/728_1_2471_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/728_1_2471/728_1_2471_t1+_thick_ax_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t2_thin/728_1_2471/728_1_2471_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/728_1_2471/728_1_2471_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/728_1_2471/728_1_2471_t2_thin_T2_uvauser6.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/728_1_2471/728_1_2471_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/728_1_2471/728_1_2471_t2_thin_T2_uvauser6_coregistered.nii.gz)

 93%|█████████▎| 1667/1793 [14:00<01:24,  1.50it/s]

Original image path: ./raw_studies/t1+_thick_cor/728_1_2471/728_1_2471_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/728_1_2471/728_1_2471_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/728_1_2471/728_1_2471_t1+_thick_cor_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t2_thick/731_4_4744/731_4_4744_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/731_4_4744/731_4_4744_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 93%|█████████▎| 1669/1793 [14:00<00:57,  2.14it/s]

Original image path: ./raw_studies/t1+_thin/731_4_4744/731_4_4744_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/731_4_4744/731_4_4744_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/731_4_4744/731_4_4744_t1+_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/731_4_4744/731_4_4744_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/731_4_4744/731_4_4744_t1+_thin_VS_uvauser1_coregistered.nii.gz)

 93%|█████████▎| 1670/1793 [14:02<01:32,  1.33it/s]

Original image path: ./raw_studies/t2_thin/731_5_4977/731_5_4977_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/731_5_4977/731_5_4977_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/731_5_4977/731_5_4977_t2_thin_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/731_5_4977/731_5_4977_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/731_5_4977/731_5_4977_t2_thin_LVS _uvauser2_coregistered.nii.gz)

 93%|█████████▎| 1671/1793 [14:03<01:31,  1.33it/s]

Original image path: ./raw_studies/t1+_thick_ax/731_5_4977/731_5_4977_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/731_5_4977/731_5_4977_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/731_5_4977/731_5_4977_t1+_thick_ax_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/731_5_4977/731_5_4977_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/731_5_4977/731_5_4977_t1+_thick_ax_LVS _uvauser2_coregistered.nii.gz)

 93%|█████████▎| 1672/1793 [14:03<01:14,  1.62it/s]

Original image path: ./raw_studies/t1+_thick_cor/731_5_4977/731_5_4977_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/731_5_4977/731_5_4977_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/731_5_4977/731_5_4977_t1+_thick_cor_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/731_5_4977/731_5_4977_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/731_5_4977/731_5_4977_t1+_thick_cor_LVS _uvauser2_coregistered.nii.gz)

 93%|█████████▎| 1673/1793 [14:03<01:02,  1.93it/s]

Original image path: ./raw_studies/t1+_thick_ax/731_6_5458/731_6_5458_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/731_6_5458/731_6_5458_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/731_6_5458/731_6_5458_t1+_thick_ax_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/731_6_5458/731_6_5458_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/731_6_5458/731_6_5458_t1+_thick_ax_LVS _uvauser2_coregistered.nii.gz)

 93%|█████████▎| 1674/1793 [14:03<00:53,  2.22it/s]

Original image path: ./raw_studies/t1+_thick_cor/731_6_5458/731_6_5458_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/731_6_5458/731_6_5458_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/731_6_5458/731_6_5458_t1+_thick_cor_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/731_6_5458/731_6_5458_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/731_6_5458/731_6_5458_t1+_thick_cor_LVS _uvauser2_coregistered.nii.gz)

 93%|█████████▎| 1675/1793 [14:04<00:46,  2.53it/s]

Original image path: ./raw_studies/t2_thin/731_6_5458/731_6_5458_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/731_6_5458/731_6_5458_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/731_6_5458/731_6_5458_t2_thin_LVS _uvauser2-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/731_6_5458/731_6_5458_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/731_6_5458/731_6_5458_t2_thin_LVS _uvauser2-copy_coregistered.nii.gz)

 94%|█████████▎| 1677/1793 [14:05<00:53,  2.18it/s]

Original image path: ./raw_studies/t2_thick/733_0_0/733_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/733_0_0/733_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

Original image path: ./raw_studies/t2_thin/733_1_53/733_1_53_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/733_1_53/733_1_53_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/733_1_53/733_1_53_t2_thin_AS2_uvauser4-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/733_1_53/733_1_53_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/733_1_53/733_1_53_t2_thin_AS2_uvauser4-copy_coregistered.nii.gz)

 94%|█████████▎| 1679/1793 [14:07<01:22,  1.38it/s]

Original image path: ./raw_studies/t1+_thick_ax/733_1_53/733_1_53_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/733_1_53/733_1_53_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/733_1_53/733_1_53_t1+_thick_ax_AS1_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/733_1_53/733_1_53_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/733_1_53/733_1_53_t1+_thick_ax_AS1_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/733_1_53/733_1_53_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/733_1_53/733_1_53_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/733_1_53/733_1_53_t1+_thick_cor_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/733_1_53/733_1_53_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/733_1_53/733_1_53_t1+_thick_cor_AS_uvauser4_coregistered.nii.gz)

 94%|█████████▎| 1680/1793 [14:07<01:01,  1.83it/s]

Original image path: ./raw_studies/t2_thin/733_2_242/733_2_242_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/733_2_242/733_2_242_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/733_2_242/733_2_242_t2_thin_image_coregistered.nii.gz, nan)

 94%|█████████▍| 1681/1793 [14:08<01:14,  1.51it/s]

Original image path: ./raw_studies/t1+_thin/733_2_242/733_2_242_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/733_2_242/733_2_242_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/733_2_242/733_2_242_t1+_thin_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/733_2_242/733_2_242_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/733_2_242/733_2_242_t1+_thin_tumorcore _uvauser3_coregistered.nii.gz)

 94%|█████████▍| 1682/1793 [14:09<01:06,  1.67it/s]

Original image path: ./raw_studies/t1+_thick_ax/734_1_365/734_1_365_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/734_1_365/734_1_365_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/734_1_365/734_1_365_t1+_thick_ax_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/734_1_365/734_1_365_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/734_1_365/734_1_365_t1+_thick_ax_LVS _uvauser2_coregistered.nii.gz)

 94%|█████████▍| 1683/1793 [14:09<00:58,  1.87it/s]

Original image path: ./raw_studies/t2_thin/734_1_365/734_1_365_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/734_1_365/734_1_365_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/734_1_365/734_1_365_t2_thin_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/734_1_365/734_1_365_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/734_1_365/734_1_365_t2_thin_LVS _uvauser2_coregistered.nii.gz)

 94%|█████████▍| 1684/1793 [14:12<02:07,  1.17s/it]

Original image path: ./raw_studies/t1+_thick_ax/734_1_365/734_1_365_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/734_1_365/734_1_365_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/734_1_365/734_1_365_t1+_thick_ax_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/734_1_365/734_1_365_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/734_1_365/734_1_365_t1+_thick_ax_LVS _uvauser2_coregistered.nii.gz)

 94%|█████████▍| 1686/1793 [14:12<01:15,  1.42it/s]

Original image path: ./raw_studies/t1+_thick_cor/734_1_365/734_1_365_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/734_1_365/734_1_365_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/734_1_365/734_1_365_t1+_thick_cor_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/734_1_365/734_1_365_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/734_1_365/734_1_365_t1+_thick_cor_LVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/734_2_768/734_2_768_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/734_2_768/734_2_768_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/734_2_768/734_2_768_t1+_thick_cor_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/734_2_768/734_2_768_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/734_2_768/734_2_768_t1+_thick_cor_AS_uvauser4_coregistered.nii.gz)

 94%|█████████▍| 1687/1793 [14:13<00:59,  1.78it/s]

Original image path: ./raw_studies/t2_thin/734_2_768/734_2_768_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/734_2_768/734_2_768_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/734_2_768/734_2_768_t2_thin_AS2_uvauser4-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/734_2_768/734_2_768_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/734_2_768/734_2_768_t2_thin_AS2_uvauser4-copy_coregistered.nii.gz)

 94%|█████████▍| 1688/1793 [14:15<01:51,  1.06s/it]

Original image path: ./raw_studies/t1+_thick_ax/734_2_768/734_2_768_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/734_2_768/734_2_768_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/734_2_768/734_2_768_t1+_thick_ax_AS1_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/734_2_768/734_2_768_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/734_2_768/734_2_768_t1+_thick_ax_AS1_uvauser4_coregistered.nii.gz)

 94%|█████████▍| 1689/1793 [14:15<01:25,  1.21it/s]

Original image path: ./raw_studies/t2_thin/734_3_1093/734_3_1093_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/734_3_1093/734_3_1093_t2_thin_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thin/734_3_1093/734_3_1093_t2_thin_tumorcore _uvauser3.nii.gz
Returning: (nan, nan)

 94%|█████████▍| 1690/1793 [14:17<02:05,  1.22s/it]

Original image path: ./raw_studies/t2_thin/735_1_357/735_1_357_t2_thin_image_uint8.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/735_1_357/735_1_357_t2_thin_image_uint8_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 94%|█████████▍| 1691/1793 [14:19<02:26,  1.44s/it]

Original image path: ./raw_studies/t1+_thin/735_1_357/735_1_357_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/735_1_357/735_1_357_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/735_1_357/735_1_357_t1+_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/735_1_357/735_1_357_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/735_1_357/735_1_357_t1+_thin_VS_uvauser1_coregistered.nii.gz)

 94%|█████████▍| 1692/1793 [14:21<02:24,  1.43s/it]

Original image path: ./raw_studies/t1+_thin/735_2_721/735_2_721_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/735_2_721/735_2_721_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/735_2_721/735_2_721_t1+_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/735_2_721/735_2_721_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/735_2_721/735_2_721_t1+_thin_VS_uvauser1_coregistered.nii.gz)

 94%|█████████▍| 1693/1793 [14:21<01:52,  1.13s/it]

Original image path: ./raw_studies/t2_thin/735_2_721/735_2_721_t2_thin_image_uint8.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/735_2_721/735_2_721_t2_thin_image_uint8_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 94%|█████████▍| 1694/1793 [14:23<02:21,  1.43s/it]

Original image path: ./raw_studies/t2_thin/735_3_1012/735_3_1012_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/735_3_1012/735_3_1012_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/735_3_1012/735_3_1012_t2_thin_image_coregistered.nii.gz, nan)

 95%|█████████▍| 1695/1793 [14:24<02:07,  1.30s/it]

Original image path: ./raw_studies/t1+_thin/735_3_1012/735_3_1012_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/735_3_1012/735_3_1012_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/735_3_1012/735_3_1012_t1+_thin_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/735_3_1012/735_3_1012_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/735_3_1012/735_3_1012_t1+_thin_tumorcore _uvauser3_coregistered.nii.gz)

 95%|█████████▍| 1696/1793 [14:24<01:40,  1.03s/it]

Original image path: ./raw_studies/t2_thin/74_0_0/74_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/74_0_0/74_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/74_0_0/74_0_0_t2_thin_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/74_0_0/74_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/74_0_0/74_0_0_t2_thin_tumorcore _uvauser3_coregistered.nii.gz)

 95%|█████████▍| 1698/1793 [14:25<00:59,  1.59it/s]

Original image path: ./raw_studies/t1+_thick_ax/74_0_0/74_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/74_0_0/74_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/74_0_0/74_0_0_t1+_thick_ax_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/74_0_0/74_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/74_0_0/74_0_0_t1+_thick_ax_tumorcore _uvauser3_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/74_0_0/74_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/74_0_0/74_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/74_0_0/74_0_0_t1+_thick_cor_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/74_0_0/74_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/74_0_0/74_0_0_t1+_thick_cor_tumorcore _uvauser3_coregistered.nii.gz)

 95%|█████████▍| 1700/1793 [14:25<00:36,  2.52it/s]

Original image path: ./raw_studies/t1+_thick_ax/74_1_1274/74_1_1274_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/74_1_1274/74_1_1274_t1+_thick_ax_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t1+_thick_ax/74_1_1274/74_1_1274_t1+_thick_ax_tumorcore _uvauser3.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thick_cor/74_1_1274/74_1_1274_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/74_1_1274/74_1_1274_t1+_thick_cor_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

Original image path: ./raw_studies/t2_thin/74_1_1274/74_1_1274_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/74_1_1274/74_1_1274_t2_thin_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thin/74_1_1274/74_1_1274_t2_thin_AX_tumorcore _uvauser3.nii.gz
Returning: (nan, nan)

 95%|█████████▍| 1702/1793 [14:26<00:31,  2.89it/s]

Original image path: ./raw_studies/t1+_thin/74_2_1367/74_2_1367_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/74_2_1367/74_2_1367_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/74_2_1367/74_2_1367_t1+_thin_image_coregistered.nii.gz, nan)

 95%|█████████▍| 1703/1793 [14:27<00:51,  1.75it/s]

Original image path: ./raw_studies/t2_thin/74_2_1367/74_2_1367_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/74_2_1367/74_2_1367_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/74_2_1367/74_2_1367_t2_thin_image_coregistered.nii.gz, nan)

 95%|█████████▌| 1704/1793 [14:28<00:48,  1.82it/s]

Original image path: ./raw_studies/t2_thin/741_0_0/741_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/741_0_0/741_0_0_t2_thin_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thin/741_0_0/741_0_0_t2_thin_CO_tumorcore _uvauser3.nii.gz
Returning: (nan, nan)

 95%|█████████▌| 1705/1793 [14:29<01:07,  1.30it/s]

Original image path: ./raw_studies/t1+_thick_cor/741_0_0/741_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/741_0_0/741_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t1+_thick_cor/741_0_0/741_0_0_t1+_thick_cor_tumorcore _uvauser3.nii.gz
Returning: (nan, nan)

 95%|█████████▌| 1706/1793 [14:29<00:53,  1.63it/s]

Original image path: ./raw_studies/t1+_thick_ax/741_0_0/741_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/741_0_0/741_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t1+_thick_ax/741_0_0/741_0_0_t1+_thick_ax_tumorcore _uvauser3.nii.gz
Returning: (nan, nan)

 95%|█████████▌| 1707/1793 [14:30<00:44,  1.93it/s]

Original image path: ./raw_studies/t2_thin/741_1_221/741_1_221_t2_thin_image_uint8.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/741_1_221/741_1_221_t2_thin_image_uint8_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 95%|█████████▌| 1708/1793 [14:31<01:16,  1.11it/s]

Original image path: ./raw_studies/t1+_thin/741_1_221/741_1_221_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/741_1_221/741_1_221_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/741_1_221/741_1_221_t1+_thin_image_coregistered.nii.gz, nan)

 95%|█████████▌| 1709/1793 [14:32<01:05,  1.29it/s]

Original image path: ./raw_studies/t1+_thin/741_2_473/741_2_473_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/741_2_473/741_2_473_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/741_2_473/741_2_473_t1+_thin_image_coregistered.nii.gz, nan)

 95%|█████████▌| 1710/1793 [14:32<00:56,  1.47it/s]

Original image path: ./raw_studies/t2_thin/743_0_0/743_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/743_0_0/743_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/743_0_0/743_0_0_t2_thin_AX_VS_uvauser1-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/743_0_0/743_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/743_0_0/743_0_0_t2_thin_AX_VS_uvauser1-copy_coregistered.nii.gz)

 95%|█████████▌| 1712/1793 [14:33<00:39,  2.05it/s]

Original image path: ./raw_studies/t1+_thick_cor/743_0_0/743_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/743_0_0/743_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/743_0_0/743_0_0_t1+_thick_cor_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/743_0_0/743_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/743_0_0/743_0_0_t1+_thick_cor_VS_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/743_0_0/743_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/743_0_0/743_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/743_0_0/743_0_0_t1+_thick_ax_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/743_0_0/743_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/743_0_0/743_0_0_t1+_thick_ax_VS_uvauser1_coregistered.nii.gz)

 96%|█████████▌| 1714/1793 [14:33<00:24,  3.22it/s]

Original image path: ./raw_studies/t1+_thick_ax/743_1_420/743_1_420_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/743_1_420/743_1_420_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/743_1_420/743_1_420_t1+_thick_ax_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/743_1_420/743_1_420_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/743_1_420/743_1_420_t1+_thick_ax_VS_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/743_1_420/743_1_420_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/743_1_420/743_1_420_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/743_1_420/743_1_420_t2_thin_AX_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/743_1_420/743_1_420_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/743_1_420/743_1_420_t2_thin_AX_VS_uvauser1_coregistered.nii.gz)

 96%|█████████▌| 1716/1793 [14:34<00:27,  2.76it/s]

Original image path: ./raw_studies/t1+_thick_cor/743_1_420/743_1_420_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/743_1_420/743_1_420_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/743_1_420/743_1_420_t1+_thick_cor_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/743_1_420/743_1_420_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/743_1_420/743_1_420_t1+_thick_cor_VS_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/743_3_631/743_3_631_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/743_3_631/743_3_631_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/743_3_631/743_3_631_t1+_thick_cor_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/743_3_631/743_3_631_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/743_3_631/743_3_631_t1+_thick_cor_RVS _uvauser2_coregistered.nii.gz)

 96%|█████████▌| 1718/1793 [14:34<00:19,  3.89it/s]

Original image path: ./raw_studies/t1+_thick_ax/743_3_631/743_3_631_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/743_3_631/743_3_631_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/743_3_631/743_3_631_t1+_thick_ax_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/743_3_631/743_3_631_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/743_3_631/743_3_631_t1+_thick_ax_RVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thin/743_3_631/743_3_631_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/743_3_631/743_3_631_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/743_3_631/743_3_631_t1+_thin_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/743_3_631/743_3_631_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/743_3_631/743_3_631_t1+_thin_AS_uvauser4_coregistered.nii.gz)

 96%|█████████▌| 1719/1793 [14:36<00:49,  1.49it/s]

Original image path: ./raw_studies/t2_thin/743_3_631/743_3_631_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/743_3_631/743_3_631_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/743_3_631/743_3_631_t2_thin_RVS _uvauser2-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/743_3_631/743_3_631_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/743_3_631/743_3_631_t2_thin_RVS _uvauser2-copy_coregistered.nii.gz)

 96%|█████████▌| 1721/1793 [14:39<01:08,  1.05it/s]

Original image path: ./raw_studies/t1+_thick_cor/744_0_0/744_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/744_0_0/744_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/744_0_0/744_0_0_t1+_thick_cor_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/744_0_0/744_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/744_0_0/744_0_0_t1+_thick_cor_VS_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/744_0_0/744_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/744_0_0/744_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/744_0_0/744_0_0_t2_thin_AX_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/744_0_0/744_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/744_0_0/744_0_0_t2_thin_AX_VS_uvauser1_coregistered.nii.gz)

 96%|█████████▌| 1723/1793 [14:40<00:42,  1.65it/s]

Original image path: ./raw_studies/t1+_thick_ax/744_0_0/744_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/744_0_0/744_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/744_0_0/744_0_0_t1+_thick_ax_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/744_0_0/744_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/744_0_0/744_0_0_t1+_thick_ax_VS_uvauser1_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/744_1_295/744_1_295_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/744_1_295/744_1_295_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/744_1_295/744_1_295_t1+_thick_ax_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/744_1_295/744_1_295_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/744_1_295/744_1_295_t1+_thick_ax_AS_uvauser4_coregistered.nii.gz)

 96%|█████████▌| 1725/1793 [14:40<00:26,  2.55it/s]

Original image path: ./raw_studies/t1+_thick_cor/744_1_295/744_1_295_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/744_1_295/744_1_295_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/744_1_295/744_1_295_t1+_thick_cor_AS1_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/744_1_295/744_1_295_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/744_1_295/744_1_295_t1+_thick_cor_AS1_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/744_1_295/744_1_295_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/744_1_295/744_1_295_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/744_1_295/744_1_295_t2_thin_AS2_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/744_1_295/744_1_295_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/744_1_295/744_1_295_t2_thin_AS2_uvauser4_coregistered.nii.gz)

 96%|█████████▋| 1727/1793 [14:41<00:24,  2.68it/s]

Original image path: ./raw_studies/t1+_thick_cor/744_2_478/744_2_478_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/744_2_478/744_2_478_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/744_2_478/744_2_478_t1+_thick_cor_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t2_thin/744_2_478/744_2_478_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/744_2_478/744_2_478_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/744_2_478/744_2_478_t2_thin_tumorcore _uvauser3-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/744_2_478/744_2_478_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/744_2_478/744_2_478_t2_thin_tumorcore _uvauser3-copy_coregistered.nii.gz)

 96%|█████████▋| 1729/1793 [14:41<00:21,  3.00it/s]

Original image path: ./raw_studies/t1+_thick_ax/744_2_478/744_2_478_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/744_2_478/744_2_478_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/744_2_478/744_2_478_t1+_thick_ax_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t2_thin/745_1_403/745_1_403_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/745_1_403/745_1_403_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/745_1_403/745_1_403_t2_thin_RVS _uvauser2-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/745_1_403/745_1_403_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/745_1_403/745_1_403_t2_thin_RVS _uvauser2-copy_coregistered.nii.gz)

 96%|█████████▋| 1730/1793 [14:42<00:28,  2.20it/s]

Original image path: ./raw_studies/t1+_thick_cor/745_1_403/745_1_403_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/745_1_403/745_1_403_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/745_1_403/745_1_403_t1+_thick_cor_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/745_1_403/745_1_403_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/745_1_403/745_1_403_t1+_thick_cor_RVS _uvauser2_coregistered.nii.gz)

 97%|█████████▋| 1731/1793 [14:42<00:23,  2.58it/s]

Original image path: ./raw_studies/t1+_thick_ax/745_1_403/745_1_403_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/745_1_403/745_1_403_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/745_1_403/745_1_403_t1+_thick_ax_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/745_1_403/745_1_403_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/745_1_403/745_1_403_t1+_thick_ax_RVS _uvauser2_coregistered.nii.gz)

 97%|█████████▋| 1732/1793 [14:43<00:21,  2.89it/s]

Original image path: ./raw_studies/t1+_thin/745_2_589/745_2_589_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/745_2_589/745_2_589_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/745_2_589/745_2_589_t1+_thin_VS_uvauser1.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/745_2_589/745_2_589_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/745_2_589/745_2_589_t1+_thin_VS_uvauser1_coregistered.nii.gz)

 97%|█████████▋| 1734/1793 [14:45<00:37,  1.56it/s]

Original image path: ./raw_studies/t1+_thick_cor/745_2_589/745_2_589_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/745_2_589/745_2_589_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/745_2_589/745_2_589_t1+_thick_cor_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/745_2_589/745_2_589_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/745_2_589/745_2_589_t1+_thick_cor_RVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thin/745_2_589/745_2_589_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/745_2_589/745_2_589_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/745_2_589/745_2_589_t1+_thin_image_coregistered.nii.gz, nan)

 97%|█████████▋| 1735/1793 [14:47<00:59,  1.03s/it]

Original image path: ./raw_studies/t1+_thin/745_2_589/745_2_589_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/745_2_589/745_2_589_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/745_2_589/745_2_589_t1+_thin_image_coregistered.nii.gz, nan)

 97%|█████████▋| 1736/1793 [14:49<01:14,  1.30s/it]

Original image path: ./raw_studies/t1+_thin/745_2_589/745_2_589_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/745_2_589/745_2_589_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/745_2_589/745_2_589_t1+_thin_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/745_2_589/745_2_589_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/745_2_589/745_2_589_t1+_thin_RVS _uvauser2_coregistered.nii.gz)

 97%|█████████▋| 1738/1793 [14:51<01:00,  1.10s/it]

Original image path: ./raw_studies/t1+_thick_ax/745_2_589/745_2_589_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/745_2_589/745_2_589_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/745_2_589/745_2_589_t1+_thick_ax_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/745_2_589/745_2_589_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/745_2_589/745_2_589_t1+_thick_ax_RVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/745_2_589/745_2_589_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/745_2_589/745_2_589_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/745_2_589/745_2_589_t2_thin_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/745_2_589/745_2_589_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/745_2_589/745_2_589_t2_thin_RVS _uvauser2_coregistered.nii.gz)

 97%|█████████▋| 1739/1793 [14:52<01:00,  1.11s/it]

Original image path: ./raw_studies/t1+_thin/745_2_589/745_2_589_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/745_2_589/745_2_589_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/745_2_589/745_2_589_t1+_thin_image_coregistered.nii.gz, nan)

 97%|█████████▋| 1740/1793 [14:54<01:12,  1.36s/it]

Original image path: ./raw_studies/t1+_thin/745_2_589/745_2_589_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/745_2_589/745_2_589_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/745_2_589/745_2_589_t1+_thin_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/745_2_589/745_2_589_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/745_2_589/745_2_589_t1+_thin_RVS _uvauser2_coregistered.nii.gz)

 97%|█████████▋| 1742/1793 [14:56<01:00,  1.18s/it]

Original image path: ./raw_studies/t2_thick/745_2_589/745_2_589_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/745_2_589/745_2_589_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/745_2_589/745_2_589_t2_thick_RVS _uvauser2.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t1+_thick_cor/745_3_960/745_3_960_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/745_3_960/745_3_960_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/745_3_960/745_3_960_t1+_thick_cor_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/745_3_960/745_3_960_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/745_3_960/745_3_960_t1+_thick_cor_RVS _uvauser2_coregistered.nii.gz)

 97%|█████████▋| 1743/1793 [14:56<00:44,  1.13it/s]

Original image path: ./raw_studies/t2_thin/745_3_960/745_3_960_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/745_3_960/745_3_960_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/745_3_960/745_3_960_t2_thin_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/745_3_960/745_3_960_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/745_3_960/745_3_960_t2_thin_RVS _uvauser2_coregistered.nii.gz)

 97%|█████████▋| 1744/1793 [14:58<00:45,  1.08it/s]

Original image path: ./raw_studies/t1+_thin/745_3_960/745_3_960_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/745_3_960/745_3_960_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/745_3_960/745_3_960_t1+_thin_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/745_3_960/745_3_960_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/745_3_960/745_3_960_t1+_thin_RVS _uvauser2_coregistered.nii.gz)

 97%|█████████▋| 1746/1793 [14:58<00:28,  1.67it/s]

Original image path: ./raw_studies/t1+_thick_ax/745_3_960/745_3_960_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/745_3_960/745_3_960_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/745_3_960/745_3_960_t1+_thick_ax_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/745_3_960/745_3_960_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/745_3_960/745_3_960_t1+_thick_ax_RVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/747_1_6/747_1_6_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/747_1_6/747_1_6_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/747_1_6/747_1_6_t1+_thick_ax_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/747_1_6/747_1_6_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/747_1_6/747_1_6_t1+_thick_ax_RVS _uvauser2_coregistered.nii.gz)

 97%|█████████▋| 1748/1793 [14:58<00:16,  2.71it/s]

Original image path: ./raw_studies/t1+_thick_cor/747_1_6/747_1_6_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/747_1_6/747_1_6_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/747_1_6/747_1_6_t1+_thick_cor_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/747_1_6/747_1_6_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/747_1_6/747_1_6_t1+_thick_cor_RVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/747_1_6/747_1_6_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/747_1_6/747_1_6_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/747_1_6/747_1_6_t2_thin_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/747_1_6/747_1_6_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/747_1_6/747_1_6_t2_thin_RVS _uvauser2_coregistered.nii.gz)

 98%|█████████▊| 1749/1793 [15:00<00:27,  1.62it/s]

Original image path: ./raw_studies/t1+_thin/747_1_6/747_1_6_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/747_1_6/747_1_6_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/747_1_6/747_1_6_t1+_thin_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/747_1_6/747_1_6_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/747_1_6/747_1_6_t1+_thin_RVS _uvauser2_coregistered.nii.gz)

 98%|█████████▊| 1750/1793 [15:02<00:43,  1.02s/it]

Original image path: ./raw_studies/t2_thin/747_2_201/747_2_201_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/747_2_201/747_2_201_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/747_2_201/747_2_201_t2_thin_image_coregistered.nii.gz, nan)

 98%|█████████▊| 1751/1793 [15:02<00:36,  1.16it/s]

Original image path: ./raw_studies/t1+_thin/747_2_201/747_2_201_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/747_2_201/747_2_201_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/747_2_201/747_2_201_t1+_thin_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/747_2_201/747_2_201_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/747_2_201/747_2_201_t1+_thin_AS_uvauser4_coregistered.nii.gz)

 98%|█████████▊| 1752/1793 [15:03<00:31,  1.32it/s]

Original image path: ./raw_studies/t1+_thin/747_3_565/747_3_565_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/747_3_565/747_3_565_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/747_3_565/747_3_565_t1+_thin_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/747_3_565/747_3_565_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/747_3_565/747_3_565_t1+_thin_AS_uvauser4_coregistered.nii.gz)

 98%|█████████▊| 1753/1793 [15:03<00:26,  1.54it/s]

Original image path: ./raw_studies/t2_thin/747_3_565/747_3_565_t2_thin_image_uint8.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/747_3_565/747_3_565_t2_thin_image_uint8_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 98%|█████████▊| 1755/1793 [15:05<00:31,  1.20it/s]

Original image path: ./raw_studies/t2_thick/788_0_0/788_0_0_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/788_0_0/788_0_0_t2_thick_image_coregistered.nii.gz
  → File NOT found
Original segmentation path: ./raw_studies/t2_thick/788_0_0/788_0_0_t2_thick_manual_0_uvauser1.nii.gz
Returning: (nan, nan)

Original image path: ./raw_studies/t2_thin/80_1_106/80_1_106_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/80_1_106/80_1_106_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/80_1_106/80_1_106_t2_thin_image_coregistered.nii.gz, nan)

 98%|█████████▊| 1756/1793 [15:06<00:32,  1.14it/s]

Original image path: ./raw_studies/t1+_thin/80_1_106/80_1_106_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/80_1_106/80_1_106_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/80_1_106/80_1_106_t1+_thin_AS1_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/80_1_106/80_1_106_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/80_1_106/80_1_106_t1+_thin_AS1_uvauser4_coregistered.nii.gz)

 98%|█████████▊| 1757/1793 [15:07<00:26,  1.37it/s]

Original image path: ./raw_studies/t1+_thin/80_2_294/80_2_294_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/80_2_294/80_2_294_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/80_2_294/80_2_294_t1+_thin_1_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/80_2_294/80_2_294_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/80_2_294/80_2_294_t1+_thin_1_uvauser4_coregistered.nii.gz)

 98%|█████████▊| 1758/1793 [15:08<00:31,  1.12it/s]

Original image path: ./raw_studies/t2_thin/80_2_294/80_2_294_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/80_2_294/80_2_294_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/80_2_294/80_2_294_t2_thin_image_coregistered.nii.gz, nan)

 98%|█████████▊| 1759/1793 [15:09<00:31,  1.09it/s]

Original image path: ./raw_studies/t2_thin/80_3_661/80_3_661_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/80_3_661/80_3_661_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/80_3_661/80_3_661_t2_thin_image_coregistered.nii.gz, nan)

 98%|█████████▊| 1760/1793 [15:10<00:31,  1.06it/s]

Original image path: ./raw_studies/t1+_thin/80_3_661/80_3_661_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/80_3_661/80_3_661_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/80_3_661/80_3_661_t1+_thin_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/80_3_661/80_3_661_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/80_3_661/80_3_661_t1+_thin_tumorcore _uvauser3_coregistered.nii.gz)

 98%|█████████▊| 1761/1793 [15:11<00:34,  1.08s/it]

Original image path: ./raw_studies/t2_thin/84_1_851/84_1_851_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/84_1_851/84_1_851_t2_thin_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 98%|█████████▊| 1762/1793 [15:12<00:29,  1.06it/s]

Original image path: ./raw_studies/t1+_thin/87_1_1322/87_1_1322_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/87_1_1322/87_1_1322_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/87_1_1322/87_1_1322_t1+_thin_tumorcore _uvauser3.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/87_1_1322/87_1_1322_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/87_1_1322/87_1_1322_t1+_thin_tumorcore _uvauser3_coregistered.nii.gz)

 98%|█████████▊| 1763/1793 [15:14<00:34,  1.14s/it]

Original image path: ./raw_studies/t2_thin/87_1_1322/87_1_1322_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/87_1_1322/87_1_1322_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/87_1_1322/87_1_1322_t2_thin_image_coregistered.nii.gz, nan)

 98%|█████████▊| 1764/1793 [15:15<00:32,  1.12s/it]

Original image path: ./raw_studies/t1+_thick_cor/87_1_1322/87_1_1322_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/87_1_1322/87_1_1322_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/87_1_1322/87_1_1322_t1+_thick_cor_image_coregistered.nii.gz, nan)

 98%|█████████▊| 1766/1793 [15:15<00:17,  1.57it/s]

Original image path: ./raw_studies/t1+_thick_ax/87_1_1322/87_1_1322_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/87_1_1322/87_1_1322_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/87_1_1322/87_1_1322_t1+_thick_ax_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t2_thick/87_2_1322/87_2_1322_t2_thick_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thick/87_2_1322/87_2_1322_t2_thick_image_coregistered.nii.gz
  → File NOT found
Returning: (nan, nan)

 99%|█████████▊| 1767/1793 [15:15<00:13,  1.95it/s]

Original image path: ./raw_studies/t2_thin/87_3_1668/87_3_1668_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/87_3_1668/87_3_1668_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/87_3_1668/87_3_1668_t2_thin_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/87_3_1668/87_3_1668_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/87_3_1668/87_3_1668_t2_thin_LVS _uvauser2_coregistered.nii.gz)

 99%|█████████▊| 1770/1793 [15:16<00:09,  2.49it/s]

Original image path: ./raw_studies/t1+_thick_ax/87_3_1668/87_3_1668_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/87_3_1668/87_3_1668_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/87_3_1668/87_3_1668_t1+_thick_ax_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/87_3_1668/87_3_1668_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/87_3_1668/87_3_1668_t1+_thick_ax_LVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/87_3_1668/87_3_1668_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/87_3_1668/87_3_1668_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/87_3_1668/87_3_1668_t1+_thick_cor_LVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/87_3_1668/87_3_1668_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/87_3_1668/87_3_1668_t1+_thick_cor_LVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thin/87_4_1793/87_4_1793_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/87_4_1793/87_4_1793_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/87_4_1793/87_4_1793_t1+_thin_image_coregistered.nii.gz, nan)

 99%|█████████▉| 1771/1793 [15:18<00:13,  1.65it/s]

Original image path: ./raw_studies/t2_thin/87_4_1793/87_4_1793_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/87_4_1793/87_4_1793_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/87_4_1793/87_4_1793_t2_thin_image_coregistered.nii.gz, nan)

 99%|█████████▉| 1772/1793 [15:20<00:23,  1.11s/it]

Original image path: ./raw_studies/t2_thin/91_0_0/91_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/91_0_0/91_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/91_0_0/91_0_0_t2_thin_image_coregistered.nii.gz, nan)

 99%|█████████▉| 1774/1793 [15:21<00:13,  1.42it/s]

Original image path: ./raw_studies/t1+_thick_cor/91_0_0/91_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/91_0_0/91_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/91_0_0/91_0_0_t1+_thick_cor_image_coregistered.nii.gz, nan)

Original image path: ./raw_studies/t1+_thick_ax/91_0_0/91_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/91_0_0/91_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/91_0_0/91_0_0_t1+_thick_ax_image_coregistered.nii.gz, nan)

 99%|█████████▉| 1776/1793 [15:21<00:07,  2.34it/s]

Original image path: ./raw_studies/t1+_thick_cor/91_1_318/91_1_318_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/91_1_318/91_1_318_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/91_1_318/91_1_318_t1+_thick_cor_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/91_1_318/91_1_318_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/91_1_318/91_1_318_t1+_thick_cor_AS_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/91_1_318/91_1_318_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/91_1_318/91_1_318_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/91_1_318/91_1_318_t2_thin_AS1_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/91_1_318/91_1_318_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/91_1_318/91_1_318_t2_thin_AS1_uvauser4_coregistered.nii.gz)

 99%|█████████▉| 1778/1793 [15:22<00:05,  2.88it/s]

Original image path: ./raw_studies/t1+_thick_ax/91_1_318/91_1_318_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/91_1_318/91_1_318_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/91_1_318/91_1_318_t1+_thick_ax_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/91_1_318/91_1_318_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/91_1_318/91_1_318_t1+_thick_ax_AS_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/94_0_0/94_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/94_0_0/94_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/94_0_0/94_0_0_t2_thin_AS1_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/94_0_0/94_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/94_0_0/94_0_0_t2_thin_AS1_uvauser4_coregistered.nii.gz)

 99%|█████████▉| 1779/1793 [15:22<00:05,  2.78it/s]

Original image path: ./raw_studies/t1+_thin/94_0_0/94_0_0_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/94_0_0/94_0_0_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/94_0_0/94_0_0_t1+_thin_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/94_0_0/94_0_0_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/94_0_0/94_0_0_t1+_thin_AS_uvauser4_coregistered.nii.gz)

 99%|█████████▉| 1781/1793 [15:23<00:03,  3.31it/s]

Original image path: ./raw_studies/t1+_thick_cor/94_1_221/94_1_221_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/94_1_221/94_1_221_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/94_1_221/94_1_221_t1+_thick_cor_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/94_1_221/94_1_221_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/94_1_221/94_1_221_t1+_thick_cor_AS_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/94_1_221/94_1_221_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/94_1_221/94_1_221_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/94_1_221/94_1_221_t2_thin_AS1_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/94_1_221/94_1_221_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/94_1_221/94_1_221_t2_thin_AS1_uvauser4_coregistered.nii.gz)

 99%|█████████▉| 1782/1793 [15:23<00:03,  2.77it/s]

Original image path: ./raw_studies/t1+_thick_ax/94_1_221/94_1_221_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/94_1_221/94_1_221_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/94_1_221/94_1_221_t1+_thick_ax_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/94_1_221/94_1_221_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/94_1_221/94_1_221_t1+_thick_ax_AS_uvauser4_coregistered.nii.gz)

 99%|█████████▉| 1783/1793 [15:23<00:03,  3.19it/s]

Original image path: ./raw_studies/t2_thin/94_2_590/94_2_590_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/94_2_590/94_2_590_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/94_2_590/94_2_590_t2_thin_AS1_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/94_2_590/94_2_590_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/94_2_590/94_2_590_t2_thin_AS1_uvauser4_coregistered.nii.gz)

 99%|█████████▉| 1784/1793 [15:24<00:04,  1.89it/s]

Original image path: ./raw_studies/t1+_thin/94_2_590/94_2_590_t1+_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/94_2_590/94_2_590_t1+_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thin/94_2_590/94_2_590_t1+_thin_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/94_2_590/94_2_590_t1+_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thin/94_2_590/94_2_590_t1+_thin_AS_uvauser4_coregistered.nii.gz)

100%|█████████▉| 1786/1793 [15:27<00:05,  1.30it/s]

Original image path: ./raw_studies/t1+_thick_ax/95_0_0/95_0_0_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/95_0_0/95_0_0_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/95_0_0/95_0_0_t1+_thick_ax_AS2_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/95_0_0/95_0_0_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/95_0_0/95_0_0_t1+_thick_ax_AS2_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/95_0_0/95_0_0_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/95_0_0/95_0_0_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/95_0_0/95_0_0_t2_thin_AS1_uvauser4-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/95_0_0/95_0_0_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/95_0_0/95_0_0_t2_thin_AS1_uvauser4-copy_coregistered.nii.gz)

100%|█████████▉| 1788/1793 [15:27<00:02,  1.95it/s]

Original image path: ./raw_studies/t1+_thick_cor/95_0_0/95_0_0_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/95_0_0/95_0_0_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/95_0_0/95_0_0_t1+_thick_cor_AS_uvauser4.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/95_0_0/95_0_0_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/95_0_0/95_0_0_t1+_thick_cor_AS_uvauser4_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_cor/95_1_182/95_1_182_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/95_1_182/95_1_182_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/95_1_182/95_1_182_t1+_thick_cor_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/95_1_182/95_1_182_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/95_1_182/95_1_182_t1+_thick_cor_RVS _uvauser2_coregistered.nii.gz)

100%|█████████▉| 1790/1793 [15:28<00:00,  3.12it/s]

Original image path: ./raw_studies/t1+_thick_ax/95_1_182/95_1_182_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/95_1_182/95_1_182_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/95_1_182/95_1_182_t1+_thick_ax_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/95_1_182/95_1_182_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/95_1_182/95_1_182_t1+_thick_ax_RVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t2_thin/95_1_182/95_1_182_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/95_1_182/95_1_182_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/95_1_182/95_1_182_t2_thin_RVS _uvauser2-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/95_1_182/95_1_182_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/95_1_182/95_1_182_t2_thin_RVS _uvauser2-copy_coregistered.nii.gz)

100%|█████████▉| 1791/1793 [15:28<00:00,  2.89it/s]

Original image path: ./raw_studies/t2_thin/95_2_574/95_2_574_t2_thin_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/95_2_574/95_2_574_t2_thin_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t2_thin/95_2_574/95_2_574_t2_thin_RVS _uvauser2-copy.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/95_2_574/95_2_574_t2_thin_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t2_thin/95_2_574/95_2_574_t2_thin_RVS _uvauser2-copy_coregistered.nii.gz)

100%|██████████| 1793/1793 [15:29<00:00,  3.13it/s]

Original image path: ./raw_studies/t1+_thick_cor/95_2_574/95_2_574_t1+_thick_cor_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/95_2_574/95_2_574_t1+_thick_cor_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_cor/95_2_574/95_2_574_t1+_thick_cor_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/95_2_574/95_2_574_t1+_thick_cor_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_cor/95_2_574/95_2_574_t1+_thick_cor_RVS _uvauser2_coregistered.nii.gz)

Original image path: ./raw_studies/t1+_thick_ax/95_2_574/95_2_574_t1+_thick_ax_image.nii.gz
Checking coregistered image path: ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/95_2_574/95_2_574_t1+_thick_ax_image_coregistered.nii.gz
  → File FOUND
Original segmentation path: ./raw_studies/t1+_thick_ax/95_2_574/95_2_574_t1+_thick_ax_RVS _uvauser2.nii.gz
Returning: (./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/95_2_574/95_2_574_t1+_thick_ax_image_coregistered.nii.gz, ./df_coregistered_02_09_2026_V6.6/raw_studies/t1+_thick_ax/95_2_574/95_2_574_t1+_thick_ax_RVS _uvauser2_coregistered.nii.gz)

100%|██████████| 1793/1793 [15:29<00:00,  1.93it/s]

Saved results to meta_df_entropy.csv

In [23]:
# for meta_df find the assicated image in acceptable and see if there is a file that is coregistered or seg_coregistered

In [24]:
meta_df['image path'].iloc[0]

'./raw_studies/t2_thick/126_0_0/126_0_0_t2_thick_image.nii.gz'

In [25]:
# Create boolean columns for each modality (study type)
# First for any scan of that modality
modality_presence = meta_df.groupby('Patient_MRI_Days Tracker')['Study Type'].apply(
    lambda x: pd.Series(True, index=x.unique())
).unstack(fill_value=False).reset_index()

# Add prefix to column names for clarity
modality_presence.columns = ['Patient_MRI_Days Tracker'] + [f'has_{col}' for col in modality_presence.columns[1:]]

# Now for scans with segmentations
modality_with_seg = meta_df[meta_df['original_seg_path'].notna()].groupby('Patient_MRI_Days Tracker')['Study Type'].apply(
    lambda x: pd.Series(True, index=x.unique())
).unstack(fill_value=False).reset_index()

# Add prefix to column names
modality_with_seg.columns = ['Patient_MRI_Days Tracker'] + [f'has_seg_{col}' for col in modality_with_seg.columns[1:]]

# Merge both dataframes
tracker_modality_df = modality_presence.merge(modality_with_seg, on='Patient_MRI_Days Tracker', how='left')

# Fill NaN values with False using infer_objects
tracker_modality_df = tracker_modality_df.fillna(False).infer_objects(copy=False)

print("Patient Timepoints with Modality Presence and Segmentation Status:")
display(tracker_modality_df.head(20))

Patient Timepoints with Modality Presence and Segmentation Status:

/tmp/ipykernel_431655/1039564943.py:22: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  tracker_modality_df = tracker_modality_df.fillna(False).infer_objects(copy=False)

,Patient_MRI_Days Tracker,has_t1+_thick_ax,has_t1+_thick_cor,has_t1+_thin,has_t2_thick,has_t2_thin,has_seg_t1+_thick_ax,has_seg_t1+_thick_cor,has_seg_t1+_thin,has_seg_t2_thick,has_seg_t2_thin
0,126_0_0,True,True,False,True,False,True,True,False,True,False
1,126_1_312,True,True,False,False,True,True,True,False,False,True
2,126_2_582,True,True,False,False,True,True,True,False,False,True
3,126_3_921,True,True,False,False,True,True,True,False,False,True
4,126_4_1231,True,True,False,False,True,True,True,False,False,True
5,126_5_1607,True,True,False,False,True,True,True,False,False,True
6,131_0_0,True,True,False,False,True,True,False,False,False,True
7,131_1_196,False,False,True,False,True,False,False,True,False,True
8,131_2_258,False,False,True,False,True,False,False,True,False,True
9,132_0_0,True,True,False,False,True,False,True,False,False,True
10,132_1_148,False,False,True,False,True,False,False,True,False,False
11,132_2_232,False,False,True,False,True,False,False,True,False,True
12,137_0_0,True,True,False,False,True,True,True,False,False,True
13,137_1_571,True,True,False,False,True,True,True,False,False,True
14,137_2_2111,False,False,True,False,True,False,False,True,False,False
15,140_0_0,True,True,False,False,True,True,True,False,False,True
16,140_1_327,True,True,False,True,False,True,True,False,True,False
17,140_2_780,False,True,True,False,True,False,True,True,False,True
18,146_0_0,True,True,False,False,True,True,True,False,False,True
19,146_1_538,True,True,False,True,False,True,True,False,True,False

In [26]:
# Filter for rows that have BOTH has_seg_t1_thin AND has_seg_t2_thin
trackers_with_both_segs = tracker_modality_df[
    (tracker_modality_df['has_seg_t1+_thin'] == True) & 
    (tracker_modality_df['has_seg_t2_thin'] == True)
]

print(f"Trackers with BOTH t1_thin AND t2_thin segmentations: {len(trackers_with_both_segs)}")
display(trackers_with_both_segs)

Trackers with BOTH t1_thin AND t2_thin segmentations: 82

,Patient_MRI_Days Tracker,has_t1+_thick_ax,has_t1+_thick_cor,has_t1+_thin,has_t2_thick,has_t2_thin,has_seg_t1+_thick_ax,has_seg_t1+_thick_cor,has_seg_t1+_thin,has_seg_t2_thick,has_seg_t2_thin
7,131_1_196,False,False,True,False,True,False,False,True,False,True
8,131_2_258,False,False,True,False,True,False,False,True,False,True
11,132_2_232,False,False,True,False,True,False,False,True,False,True
17,140_2_780,False,True,True,False,True,False,True,True,False,True
21,147_0_0,False,True,True,False,True,False,True,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...
590,745_2_589,True,True,True,True,True,True,True,True,True,True
591,745_3_960,True,True,True,False,True,True,True,True,False,True
592,747_1_6,True,True,True,False,True,True,True,True,False,True
609,94_0_0,False,False,True,False,True,False,False,True,False,True
611,94_2_590,False,False,True,False,True,False,False,True,False,True

In [27]:
#compares T1+_thin and T2_thin of the same time point with dicescore
import pandas as pd
import numpy as np
import nibabel as nib
from scipy.spatial.distance import dice

def calculate_dice_coefficient(seg1_path, seg2_path):
    """
    Calculate Dice coefficient between two segmentation masks.
    
    Parameters:
    seg1_path: path to first segmentation file
    seg2_path: path to second segmentation file
    
    Returns:
    dice_score: Dice coefficient (0-1, where 1 is perfect overlap)
    """
    try:
        # Load segmentation files
        seg1 = nib.load(seg1_path).get_fdata()
        seg2 = nib.load(seg2_path).get_fdata()
        
        # Binarize segmentations (in case they're not already binary)
        seg1_binary = (seg1 > 0).astype(np.uint8)
        seg2_binary = (seg2 > 0).astype(np.uint8)
        
        # Calculate Dice coefficient
        # Dice = 2 * |A ∩ B| / (|A| + |B|)
        intersection = np.sum(seg1_binary * seg2_binary)
        sum_volumes = np.sum(seg1_binary) + np.sum(seg2_binary)
        
        if sum_volumes == 0:
            return np.nan  # Both segmentations are empty
        
        dice_score = 2.0 * intersection / sum_volumes
        return dice_score
        
    except Exception as e:
        print(f"Error calculating Dice for {seg1_path} and {seg2_path}: {e}")
        return np.nan


def create_dice_comparison_dataframe(df):
    """
    Create a dataframe comparing T1 and T2 segmentations with Dice scores.
    
    Parameters:
    df: pandas DataFrame with imaging data
    
    Returns:
    result_df: DataFrame with columns [Patient_MRI_Days Tracker, t1_thin, t2_thin, dice_score]
    """
    results = []
    
    # Group by Patient_MRI_Days Tracker
    grouped = df.groupby('Patient_MRI_Days Tracker')
    
    for tracker_id, group in grouped:
        # Identify T1 and T2 scans based on Series Description or Study Type
        # Adjust the column name and values based on your data
        t1_scans = group[group['Study Type'].str.contains('t1', case=False, na=False)]
        t2_scans = group[group['Study Type'].str.contains('t2', case=False, na=False)]
        
        # If you have multiple T1 or T2 scans per tracker, iterate through combinations
        for _, t1_row in t1_scans.iterrows():
            for _, t2_row in t2_scans.iterrows():
                # Check if both have coregistered segmentations
                if pd.notna(t1_row['coregistered_segmentation']) and \
                   pd.notna(t2_row['coregistered_segmentation']):
                    
                    # Calculate Dice score
                    dice_score = calculate_dice_coefficient(
                        t1_row['coregistered_segmentation'],
                        t2_row['coregistered_segmentation']
                    )
                    
                    # Store results
                    results.append({
                        'Patient_MRI_Days Tracker': tracker_id,
                        't1_thin': t1_row['coregistered_image'],
                        't2_thin': t2_row['coregistered_image'],
                        't1_segmentation': t1_row['coregistered_segmentation'],
                        't2_segmentation': t2_row['coregistered_segmentation'],
                        'dice_score': dice_score
                    })
    
    # Create result dataframe
    result_df = pd.DataFrame(results)
    
    return result_df


# Usage example:
dice_df = create_dice_comparison_dataframe(meta_df)
display(dice_df.head())

# Count how many Patient_MRI_Days Trackers have both T1 and T2 with segmentations
count = dice_df['Patient_MRI_Days Tracker'].nunique()
print(f"Number of patient timepoints with both T1 and T2 segmentations: {count}")

# Or get the total number of comparisons made
total_comparisons = len(dice_df)
print(f"Total T1-T2 comparisons: {total_comparisons}")

# If you want to see which ones they are:
print("\nPatient_MRI_Days Trackers with both T1 and T2:")
print(dice_df['Patient_MRI_Days Tracker'].unique())

,Patient_MRI_Days Tracker,t1_thin,t2_thin,t1_segmentation,t2_segmentation,dice_score
0,126_1_312,./df_coregistered_02_09_2026_V6.6/raw_studies/...,./df_coregistered_02_09_2026_V6.6/raw_studies/...,./df_coregistered_02_09_2026_V6.6/raw_studies/...,./df_coregistered_02_09_2026_V6.6/raw_studies/...,0.083344
1,126_1_312,./df_coregistered_02_09_2026_V6.6/raw_studies/...,./df_coregistered_02_09_2026_V6.6/raw_studies/...,./df_coregistered_02_09_2026_V6.6/raw_studies/...,./df_coregistered_02_09_2026_V6.6/raw_studies/...,0.374806
2,126_1_312,./df_coregistered_02_09_2026_V6.6/raw_studies/...,./df_coregistered_02_09_2026_V6.6/raw_studies/...,./df_coregistered_02_09_2026_V6.6/raw_studies/...,./df_coregistered_02_09_2026_V6.6/raw_studies/...,0.374806
3,126_2_582,./df_coregistered_02_09_2026_V6.6/raw_studies/...,./df_coregistered_02_09_2026_V6.6/raw_studies/...,./df_coregistered_02_09_2026_V6.6/raw_studies/...,./df_coregistered_02_09_2026_V6.6/raw_studies/...,0.776452
4,126_2_582,./df_coregistered_02_09_2026_V6.6/raw_studies/...,./df_coregistered_02_09_2026_V6.6/raw_studies/...,./df_coregistered_02_09_2026_V6.6/raw_studies/...,./df_coregistered_02_09_2026_V6.6/raw_studies/...,0.808989

Number of patient timepoints with both T1 and T2 segmentations: 266
Total T1-T2 comparisons: 487

Patient_MRI_Days Trackers with both T1 and T2:
['126_1_312' '126_2_582' '126_3_921' '126_5_1607' '131_0_0' '131_1_196'
 '131_2_258' '132_0_0' '132_2_232' '137_0_0' '140_0_0' '140_2_780'
 '146_0_0' '146_2_941' '147_1_104' '148_0_0' '148_1_182' '148_2_253'
 '152_1_95' '152_3_905' '152_4_1291' '152_5_1683' '169_0_0' '169_1_184'
 '169_2_722' '169_3_835' '170_1_176' '170_2_382' '170_3_732' '178_0_0'
 '178_5_2486' '185_1_277' '188_0_0' '188_1_263' '188_2_645' '188_3_1033'
 '188_4_1434' '190_1_150' '193_0_0' '193_1_175' '199_0_0' '199_1_183'
 '207_0_0' '207_3_1194' '210_2_231' '215_2_322' '218_0_0' '218_1_199'
 '222_1_11' '222_2_402' '229_1_212' '229_3_938' '235_0_0' '235_3_552'
 '258_2_96' '262_1_497' '267_1_195' '267_2_554' '267_3_916' '267_4_1278'
 '267_5_1693' '270_0_0' '270_1_324' '286_0_0' '301_0_0' '301_1_229'
 '301_2_614' '304_0_0' '304_1_206' '304_2_305' '308_1_189' '308_2_521'
 '309_1_177' '309_3_917' '315_2_2947' '317_1_222' '318_0_0' '318_1_192'
 '320_0_0' '320_1_183' '320_2_225' '333_1_279' '333_2_580' '339_2_430'
 '343_1_167' '343_2_533' '344_0_0' '360_1_211' '374_1_338' '374_3_1258'
 '383_0_0' '383_1_253' '383_2_611' '385_0_0' '398_0_0' '398_1_1237'
 '406_0_0' '406_2_528' '406_3_550' '415_1_211' '415_2_404' '418_1_1056'
 '418_2_1238' '418_3_1428' '421_1_264' '421_2_1633' '423_1_434'
 '423_2_1169' '424_4_2863' '424_5_4003' '427_0_0' '427_1_263' '427_2_315'
 '437_1_52' '439_1_12' '439_3_437' '442_3_702' '442_5_1272' '442_6_1447'
 '454_0_0' '454_1_199' '454_2_556' '461_2_617' '461_3_953' '461_4_1331'
 '467_0_0' '474_1_128' '478_0_0' '478_2_486' '485_1_343' '485_2_734'
 '487_0_0' '487_1_427' '495_0_0' '500_1_346' '500_2_724' '502_1_71'
 '505_1_210' '505_2_342' '508_0_0' '508_1_260' '50_2_108' '514_0_0'
 '514_1_353' '525_0_0' '525_3_465' '527_1_267' '527_3_625' '528_1_488'
 '528_2_838' '532_0_0' '532_1_355' '537_0_0' '540_0_0' '540_2_663'
 '540_3_1126' '546_0_0' '553_0_0' '553_1_194' '556_0_0' '557_0_0'
 '557_1_72' '557_2_488' '558_1_307' '558_2_756' '558_3_1211' '561_0_0'
 '563_0_0' '563_1_204' '563_2_377' '565_0_0' '565_1_90' '568_1_255'
 '569_1_54' '571_0_0' '576_1_172' '577_0_0' '577_3_932' '577_4_1366'
 '578_1_317' '579_0_0' '579_4_1600' '583_0_0' '583_2_278' '583_3_460'
 '584_0_0' '584_1_297' '584_2_507' '585_0_0' '585_1_280' '585_4_1348'
 '589_0_0' '589_1_223' '58_1_214' '590_0_0' '590_1_179' '593_1_403'
 '595_0_0' '600_1_168' '601_1_201' '601_2_616' '603_0_0' '603_1_860'
 '604_1_178' '606_0_0' '606_1_181' '606_2_545' '606_3_914' '609_0_0'
 '609_2_536' '609_3_902' '610_1_210' '610_4_1386' '611_0_0' '611_2_466'
 '616_0_0' '616_1_315' '618_0_0' '618_2_627' '625_1_1139' '629_0_0'
 '629_2_810' '632_0_0' '632_1_246' '636_0_0' '636_1_181' '636_4_978'
 '647_2_176' '649_0_0' '649_2_148' '651_1_1351' '652_1_326' '652_2_869'
 '662_0_0' '662_1_183' '662_2_260' '664_0_0' '676_0_0' '679_1_94'
 '690_0_0' '690_1_188' '696_1_179' '701_0_0' '731_5_4977' '731_6_5458'
 '733_1_53' '734_1_365' '734_2_768' '743_0_0' '743_1_420' '743_3_631'
 '744_0_0' '744_1_295' '745_1_403' '745_2_589' '745_3_960' '747_1_6'
 '74_0_0' '87_3_1668' '91_1_318' '94_0_0' '94_1_221' '94_2_590' '95_0_0'
 '95_1_182' '95_2_574']

In [28]:
from tqdm import tqdm

#compare the pairwise dice with each other in a timepoint
def create_pairwise_dice_comparison(df):
    """
    Create pairwise Dice score comparisons for all studies within each timepoint.
    
    Parameters:
    df: pandas DataFrame with imaging data
    
    Returns:
    result_df: DataFrame with pairwise comparisons and Dice scores
    """
    results = []
    
    # Group by Patient_ID
    grouped = df.groupby('Patient_ID')
    
    # Count total comparisons for progress bar
    total_comparisons = 0
    for _, group in grouped:
        studies_with_seg = group[pd.notna(group['coregistered_segmentation'])]
        n_studies = len(studies_with_seg)
        if n_studies >= 2:
            total_comparisons += n_studies * (n_studies - 1) // 2
    
    print(f"Processing {len(grouped)} patients with {total_comparisons} total pairwise comparisons...")
    
    # Create progress bar
    pbar = tqdm(total=total_comparisons, desc="Calculating Dice scores", unit="comparison")
    
    for tracker_id, group in grouped:
        # Get all studies with segmentations at this timepoint
        studies_with_seg = group[pd.notna(group['coregistered_segmentation'])].copy()
        
        # Create all pairwise combinations
        n_studies = len(studies_with_seg)
        
        if n_studies < 2:
            continue  # Skip if less than 2 studies to compare
        
        # Iterate through all pairs
        for i in range(n_studies):
            for j in range(i + 1, n_studies):
                study1 = studies_with_seg.iloc[i]
                study2 = studies_with_seg.iloc[j]
                
                # Calculate Dice score
                dice_score = calculate_dice_coefficient(
                    study1['coregistered_segmentation'],
                    study2['coregistered_segmentation']
                )
                
                # Store results
                results.append({
                    'Patient_MRI_Days Tracker': tracker_id,
                    'study1_filename': study1['coregistered_image'],
                    'study2_filename': study2['coregistered_image'],
                    'study1_type': study1.get('Study Type', 'Unknown'),
                    'study2_type': study2.get('Study Type', 'Unknown'),
                    'study1_segmentation': study1['coregistered_segmentation'],
                    'study2_segmentation': study2['coregistered_segmentation'],
                    'dice_score': dice_score
                })
                
                # Update progress bar
                pbar.update(1)
    
    # Close progress bar
    pbar.close()
    
    # Create result dataframe
    result_df = pd.DataFrame(results)
    
    return result_df

# Create pairwise comparison dataframe
pairwise_dice_df = create_pairwise_dice_comparison(meta_df)

# Display results
display(pairwise_dice_df.head(10))

# Summary statistics
print(f"\nTotal pairwise comparisons: {len(pairwise_dice_df)}")
print(f"Number of unique timepoints with comparisons: {pairwise_dice_df['Patient_MRI_Days Tracker'].nunique()}")
print(f"\nDice score statistics:")
print(pairwise_dice_df['dice_score'].describe())

# Show distribution of comparisons per timepoint
comparisons_per_timepoint = pairwise_dice_df.groupby('Patient_MRI_Days Tracker').size()
print(f"\nComparisons per timepoint:")
print(f"Mean: {comparisons_per_timepoint.mean():.2f}")
print(f"Max: {comparisons_per_timepoint.max()}")
print(f"Min: {comparisons_per_timepoint.min()}")

Processing 205 patients with 3690 total pairwise comparisons...

Calculating Dice scores: 100%|██████████| 3690/3690 [45:18<00:00,  1.36comparison/s]

,Patient_MRI_Days Tracker,study1_filename,study2_filename,study1_type,study2_type,study1_segmentation,study2_segmentation,dice_score
0,50,./df_coregistered_02_09_2026_V6.6/raw_studies/...,./df_coregistered_02_09_2026_V6.6/raw_studies/...,t1+_thick_cor,t2_thin,./df_coregistered_02_09_2026_V6.6/raw_studies/...,./df_coregistered_02_09_2026_V6.6/raw_studies/...,0.747266
1,50,./df_coregistered_02_09_2026_V6.6/raw_studies/...,./df_coregistered_02_09_2026_V6.6/raw_studies/...,t1+_thick_cor,t1+_thick_ax,./df_coregistered_02_09_2026_V6.6/raw_studies/...,./df_coregistered_02_09_2026_V6.6/raw_studies/...,0.705104
2,50,./df_coregistered_02_09_2026_V6.6/raw_studies/...,./df_coregistered_02_09_2026_V6.6/raw_studies/...,t2_thin,t1+_thick_ax,./df_coregistered_02_09_2026_V6.6/raw_studies/...,./df_coregistered_02_09_2026_V6.6/raw_studies/...,0.831360
3,53,./df_coregistered_02_09_2026_V6.6/raw_studies/...,./df_coregistered_02_09_2026_V6.6/raw_studies/...,t1+_thin,t1+_thin,./df_coregistered_02_09_2026_V6.6/raw_studies/...,./df_coregistered_02_09_2026_V6.6/raw_studies/...,0.000000
4,57,./df_coregistered_02_09_2026_V6.6/raw_studies/...,./df_coregistered_02_09_2026_V6.6/raw_studies/...,t1+_thin,t1+_thin,./df_coregistered_02_09_2026_V6.6/raw_studies/...,./df_coregistered_02_09_2026_V6.6/raw_studies/...,0.680782
5,58,./df_coregistered_02_09_2026_V6.6/raw_studies/...,./df_coregistered_02_09_2026_V6.6/raw_studies/...,t1+_thick_ax,t1+_thick_cor,./df_coregistered_02_09_2026_V6.6/raw_studies/...,./df_coregistered_02_09_2026_V6.6/raw_studies/...,0.483980
6,58,./df_coregistered_02_09_2026_V6.6/raw_studies/...,./df_coregistered_02_09_2026_V6.6/raw_studies/...,t1+_thick_ax,t2_thin,./df_coregistered_02_09_2026_V6.6/raw_studies/...,./df_coregistered_02_09_2026_V6.6/raw_studies/...,0.586031
7,58,./df_coregistered_02_09_2026_V6.6/raw_studies/...,./df_coregistered_02_09_2026_V6.6/raw_studies/...,t1+_thick_ax,t1+_thick_cor,./df_coregistered_02_09_2026_V6.6/raw_studies/...,./df_coregistered_02_09_2026_V6.6/raw_studies/...,0.000000
8,58,./df_coregistered_02_09_2026_V6.6/raw_studies/...,./df_coregistered_02_09_2026_V6.6/raw_studies/...,t1+_thick_ax,t1+_thin,./df_coregistered_02_09_2026_V6.6/raw_studies/...,./df_coregistered_02_09_2026_V6.6/raw_studies/...,0.000000
9,58,./df_coregistered_02_09_2026_V6.6/raw_studies/...,./df_coregistered_02_09_2026_V6.6/raw_studies/...,t1+_thick_ax,t1+_thick_ax,./df_coregistered_02_09_2026_V6.6/raw_studies/...,./df_coregistered_02_09_2026_V6.6/raw_studies/...,0.000000

Total pairwise comparisons: 3690
Number of unique timepoints with comparisons: 175

Dice score statistics:
count    3608.000000
mean        0.455007
std         0.286232
min         0.000000
25%         0.206410
50%         0.512785
75%         0.693599
max         1.000000
Name: dice_score, dtype: float64

Comparisons per timepoint:
Mean: 21.09
Max: 136
Min: 1

In [29]:
pairwise_dice_df.to_csv('pairwise_dice_df.csv')

In [30]:
def create_average_dice_per_study(pairwise_df):
    """
    Calculate average Dice score for each study based on all comparisons it participated in.
    
    Parameters:
    pairwise_df: DataFrame with pairwise comparisons (output from create_pairwise_dice_comparison)
    
    Returns:
    avg_dice_df: DataFrame with average Dice score per study
    """
    results = []
    
    # Get all unique studies from both columns
    all_studies = pd.concat([
        pairwise_df[['Patient_MRI_Days Tracker', 'study1_filename', 'study1_type', 'study1_segmentation']].rename(
            columns={'study1_filename': 'filename', 'study1_type': 'study_type', 'study1_segmentation': 'segmentation'}
        ),
        pairwise_df[['Patient_MRI_Days Tracker', 'study2_filename', 'study2_type', 'study2_segmentation']].rename(
            columns={'study2_filename': 'filename', 'study2_type': 'study_type', 'study2_segmentation': 'segmentation'}
        )
    ]).drop_duplicates()
    
    print(f"Calculating average Dice scores for {len(all_studies)} unique studies...")
    
    # For each unique study, find all comparisons it participated in
    for _, study_row in tqdm(all_studies.iterrows(), total=len(all_studies), desc="Processing studies"):
        tracker_id = study_row['Patient_MRI_Days Tracker']
        filename = study_row['filename']
        study_type = study_row['study_type']
        segmentation = study_row['segmentation']
        
        # Find all comparisons involving this study
        comparisons_as_study1 = pairwise_df[
            (pairwise_df['Patient_MRI_Days Tracker'] == tracker_id) & 
            (pairwise_df['study1_filename'] == filename)
        ]['dice_score']
        
        comparisons_as_study2 = pairwise_df[
            (pairwise_df['Patient_MRI_Days Tracker'] == tracker_id) & 
            (pairwise_df['study2_filename'] == filename)
        ]['dice_score']
        
        # Combine all Dice scores for this study
        all_dice_scores = pd.concat([comparisons_as_study1, comparisons_as_study2])
        
        # Remove NaN values
        all_dice_scores = all_dice_scores.dropna()
        
        if len(all_dice_scores) > 0:
            results.append({
                'Patient_MRI_Days Tracker': tracker_id,
                'study_filename': filename,
                'study_type': study_type,
                'segmentation': segmentation,
                'n_comparisons': len(all_dice_scores),
                'mean_dice': all_dice_scores.mean(),
                'std_dice': all_dice_scores.std(),
                'min_dice': all_dice_scores.min(),
                'max_dice': all_dice_scores.max(),
                'median_dice': all_dice_scores.median()
            })
    
    # Create result dataframe
    avg_dice_df = pd.DataFrame(results)
    
    # Sort by mean_dice descending
    avg_dice_df = avg_dice_df.sort_values('mean_dice', ascending=False).reset_index(drop=True)
    
    return avg_dice_df

# Create average Dice score dataframe
avg_dice_per_study_df = create_average_dice_per_study(pairwise_dice_df)

# Display results
print("\n" + "="*70)
print("Average Dice Scores Per Study")
print("="*70)
display(avg_dice_per_study_df.head(20))

# Summary statistics
print("\n" + "="*70)
print("Overall Statistics:")
print("="*70)
print(f"Total studies analyzed: {len(avg_dice_per_study_df)}")
print(f"\nMean Dice statistics across all studies:")
print(avg_dice_per_study_df['mean_dice'].describe())

print(f"\nNumber of comparisons per study:")
print(avg_dice_per_study_df['n_comparisons'].describe())

# Group by study type
print("\n" + "="*70)
print("Average Dice by Study Type:")
print("="*70)
study_type_summary = avg_dice_per_study_df.groupby('study_type').agg({
    'mean_dice': ['mean', 'std', 'count'],
    'n_comparisons': 'mean'
}).round(4)
print(study_type_summary)

# Show best and worst performing studies
print("\n" + "="*70)
print("Top 10 Studies (Highest Average Dice):")
print("="*70)
display(avg_dice_per_study_df.head(10)[['Patient_MRI_Days Tracker', 'study_filename', 'study_type', 'n_comparisons', 'mean_dice']])

print("\n" + "="*70)
print("Bottom 10 Studies (Lowest Average Dice):")
print("="*70)
display(avg_dice_per_study_df.tail(10)[['Patient_MRI_Days Tracker', 'study_filename', 'study_type', 'n_comparisons', 'mean_dice']])
avg_dice_per_study_df.to_csv('avg_dice_per_study_df.csv', index=False)

Calculating average Dice scores for 1072 unique studies...

Processing studies: 100%|██████████| 1072/1072 [00:01<00:00, 747.37it/s]

======================================================================
Average Dice Scores Per Study
======================================================================

,Patient_MRI_Days Tracker,study_filename,study_type,segmentation,n_comparisons,mean_dice,std_dice,min_dice,max_dice,median_dice
0,315,./df_coregistered_02_09_2026_V6.6/raw_studies/...,t1+_thin,./df_coregistered_02_09_2026_V6.6/raw_studies/...,1,0.898512,NaN,0.898512,0.898512,0.898512
1,315,./df_coregistered_02_09_2026_V6.6/raw_studies/...,t2_thin,./df_coregistered_02_09_2026_V6.6/raw_studies/...,1,0.898512,NaN,0.898512,0.898512,0.898512
2,569,./df_coregistered_02_09_2026_V6.6/raw_studies/...,t1+_thick_ax,./df_coregistered_02_09_2026_V6.6/raw_studies/...,6,0.874854,0.097701,0.798655,1.000000,0.825907
3,525,./df_coregistered_02_09_2026_V6.6/raw_studies/...,t2_thin,./df_coregistered_02_09_2026_V6.6/raw_studies/...,6,0.860297,0.021891,0.832031,0.885778,0.859867
4,185,./df_coregistered_02_09_2026_V6.6/raw_studies/...,t2_thin,./df_coregistered_02_09_2026_V6.6/raw_studies/...,2,0.859517,0.040423,0.830933,0.888100,0.859517
5,553,./df_coregistered_02_09_2026_V6.6/raw_studies/...,t1+_thin,./df_coregistered_02_09_2026_V6.6/raw_studies/...,4,0.859260,0.014307,0.839108,0.872353,0.862790
6,525,./df_coregistered_02_09_2026_V6.6/raw_studies/...,t1+_thin,./df_coregistered_02_09_2026_V6.6/raw_studies/...,6,0.855925,0.032157,0.814766,0.892438,0.863065
7,525,./df_coregistered_02_09_2026_V6.6/raw_studies/...,t1+_thick_cor,./df_coregistered_02_09_2026_V6.6/raw_studies/...,6,0.855726,0.038097,0.801787,0.892438,0.867979
8,553,./df_coregistered_02_09_2026_V6.6/raw_studies/...,t1+_thin,./df_coregistered_02_09_2026_V6.6/raw_studies/...,4,0.852151,0.026173,0.825106,0.876693,0.853403
9,553,./df_coregistered_02_09_2026_V6.6/raw_studies/...,t1+_thick_cor,./df_coregistered_02_09_2026_V6.6/raw_studies/...,4,0.851935,0.022336,0.823908,0.876693,0.853569
10,525,./df_coregistered_02_09_2026_V6.6/raw_studies/...,t1+_thick_cor,./df_coregistered_02_09_2026_V6.6/raw_studies/...,6,0.845254,0.018091,0.820895,0.867609,0.847956
11,553,./df_coregistered_02_09_2026_V6.6/raw_studies/...,t2_thin,./df_coregistered_02_09_2026_V6.6/raw_studies/...,4,0.843442,0.018087,0.823908,0.865197,0.842332
12,569,./df_coregistered_02_09_2026_V6.6/raw_studies/...,t2_thin,./df_coregistered_02_09_2026_V6.6/raw_studies/...,3,0.840680,0.025588,0.825907,0.870226,0.825907
13,553,./df_coregistered_02_09_2026_V6.6/raw_studies/...,t2_thin,./df_coregistered_02_09_2026_V6.6/raw_studies/...,4,0.840295,0.011138,0.825106,0.850210,0.842931
14,437,./df_coregistered_02_09_2026_V6.6/raw_studies/...,t2_thin,./df_coregistered_02_09_2026_V6.6/raw_studies/...,3,0.840070,0.028514,0.808539,0.864045,0.847626
15,437,./df_coregistered_02_09_2026_V6.6/raw_studies/...,t1+_thin,./df_coregistered_02_09_2026_V6.6/raw_studies/...,3,0.838241,0.026640,0.810838,0.864045,0.839841
16,185,./df_coregistered_02_09_2026_V6.6/raw_studies/...,t1+_thin,./df_coregistered_02_09_2026_V6.6/raw_studies/...,2,0.837976,0.009960,0.830933,0.845019,0.837976
17,582,./df_coregistered_02_09_2026_V6.6/raw_studies/...,t2_thin,./df_coregistered_02_09_2026_V6.6/raw_studies/...,3,0.836553,0.009545,0.825652,0.843408,0.840599
18,427,./df_coregistered_02_09_2026_V6.6/raw_studies/...,t2_thin,./df_coregistered_02_09_2026_V6.6/raw_studies/...,6,0.835114,0.042958,0.769766,0.885020,0.832511
19,690,./df_coregistered_02_09_2026_V6.6/raw_studies/...,t2_thin,./df_coregistered_02_09_2026_V6.6/raw_studies/...,5,0.833187,0.010377,0.822121,0.844768,0.830316

======================================================================
Overall Statistics:
======================================================================
Total studies analyzed: 1070

Mean Dice statistics across all studies:
count    1070.000000
mean        0.474142
std         0.225682
min         0.000000
25%         0.339669
50%         0.501707
75%         0.638032
max         0.898512
Name: mean_dice, dtype: float64

Number of comparisons per study:
count    1070.000000
mean        6.981308
std         4.156394
min         1.000000
25%         4.000000
50%         6.000000
75%         9.000000
max        36.000000
Name: n_comparisons, dtype: float64

======================================================================
Average Dice by Study Type:
======================================================================
              mean_dice               n_comparisons
                   mean     std count          mean
study_type
t1+_thick_ax     0.4802  0.2124   282        7.5355
t1+_thick_cor    0.4703  0.2163   292        7.3562
t1+_thin         0.4719  0.2472   200        5.5850
t2_thin          0.4736  0.2328   296        7.0270

======================================================================
Top 10 Studies (Highest Average Dice):
======================================================================

,Patient_MRI_Days Tracker,study_filename,study_type,n_comparisons,mean_dice
0,315,./df_coregistered_02_09_2026_V6.6/raw_studies/...,t1+_thin,1,0.898512
1,315,./df_coregistered_02_09_2026_V6.6/raw_studies/...,t2_thin,1,0.898512
2,569,./df_coregistered_02_09_2026_V6.6/raw_studies/...,t1+_thick_ax,6,0.874854
3,525,./df_coregistered_02_09_2026_V6.6/raw_studies/...,t2_thin,6,0.860297
4,185,./df_coregistered_02_09_2026_V6.6/raw_studies/...,t2_thin,2,0.859517
5,553,./df_coregistered_02_09_2026_V6.6/raw_studies/...,t1+_thin,4,0.859260
6,525,./df_coregistered_02_09_2026_V6.6/raw_studies/...,t1+_thin,6,0.855925
7,525,./df_coregistered_02_09_2026_V6.6/raw_studies/...,t1+_thick_cor,6,0.855726
8,553,./df_coregistered_02_09_2026_V6.6/raw_studies/...,t1+_thin,4,0.852151
9,553,./df_coregistered_02_09_2026_V6.6/raw_studies/...,t1+_thick_cor,4,0.851935

======================================================================
Bottom 10 Studies (Lowest Average Dice):
======================================================================

,Patient_MRI_Days Tracker,study_filename,study_type,n_comparisons,mean_dice
1060,601,./df_coregistered_02_09_2026_V6.6/raw_studies/...,t2_thin,5,0.0
1061,735,./df_coregistered_02_09_2026_V6.6/raw_studies/...,t1+_thin,2,0.0
1062,94,./df_coregistered_02_09_2026_V6.6/raw_studies/...,t2_thin,6,0.0
1063,515,./df_coregistered_02_09_2026_V6.6/raw_studies/...,t1+_thin,2,0.0
1064,495,./df_coregistered_02_09_2026_V6.6/raw_studies/...,t1+_thin,3,0.0
1065,493,./df_coregistered_02_09_2026_V6.6/raw_studies/...,t1+_thin,2,0.0
1066,483,./df_coregistered_02_09_2026_V6.6/raw_studies/...,t1+_thin,2,0.0
1067,439,./df_coregistered_02_09_2026_V6.6/raw_studies/...,t1+_thin,8,0.0
1068,434,./df_coregistered_02_09_2026_V6.6/raw_studies/...,t1+_thin,1,0.0
1069,421,./df_coregistered_02_09_2026_V6.6/raw_studies/...,t1+_thin,8,0.0